### ISSUE TITLE
[BUG] Noteblock texture

### ISSUE THREAD

**Issue by LasurkaXD** [oraxen/oraxen#1002]
### I have checked...

- [x] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [ ] I have checked if any similar bug reports exist

### Description

When you place a custom block on or under another block, and break another block, the custom blocks above or below become a noteblock for a moment, this is very annoying and interferes with the game for normal players

### Steps to reproduce

Idk bruh

### Plugin Version

latest

### ProtocolLib Version

latest

### Server Software & Version

Current: git-Purpur-2004 (MC: 1.20.1)*

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

https://github.com/oraxen/oraxen/assets/129551196/3ada7a15-c194-457a-852c-41dfe93448cd

**Comment by Boy0000** [comment]
Sadly no way to fix this. Its a combination of server trying to update it, oraxen cancelling it and client predicting an update before receiving the cancellation

**Comment by LasurkaXD** [comment]
> Sadly no way to fix this. Its a combination of server trying to update it, oraxen cancelling it and client predicting an update before receiving the cancellation

Have you played Origin Realms? He has a noteblock-block also, but there is no problem with this, but they don't have that problem.

**Comment by Boy0000** [comment]
Origin Realms have a custom server fork which allows them alot more control. Not to mention they have all custom plugins and probably do some magic. If you are on Paper 1.20.1 there is a setting to cancel noteblock uodates which might help but it isnt 100%

**Comment by LasurkaXD** [comment]
Purpur 1.20.1 same?..

**Comment by LasurkaXD** [comment]
> and probably

Purpur 1.20.1 same?

**Comment by LasurkaXD** [comment]
> Origin Realms have a custom server fork which allows them alot more control. Not to mention they have all custom plugins and probably do some magic. If you are on Paper 1.20.1 there is a setting to cancel noteblock uodates which might help but it isnt 100%

purpu 1.20.1 same???

**Comment by Boy0000** [comment]
No clue ive never used purpur as it is just bloated version of paper in my experience. U will have to talk to purpur about that

**Comment by magicelk235** [comment]
Where is it?
