### ISSUE TITLE
[Suggestion] more blocks as barrier in furnitures 

### ISSUE THREAD

**Issue by magicelk235** [oraxen/oraxen#1003]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

This feature will make you able to set the block that used as hitbox to whatever you want
If you want to create a furniture with slab hit box you can
(But hardness will not work, cause it will use the block's hardness)

### Reason

If you want to create a furniture with slab hit box you can

**Comment by Boy0000** [comment]
i dont see purpose in this
slabs arent invisible, and if u retexture it you get x-ray blocks

if you want customizable hitboxes use interaction entity option and ask mojang to add optional collision to them

**Comment by magicelk235** [comment]
The slab will still have a texture, but there will be an item frame or armor stand with an item to cover the slab's texture
