### ISSUE TITLE
[SUGGESTION] Folia support

### ISSUE THREAD

**Issue by TsubakiDev** [oraxen/oraxen#1006]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

When will Oraxen support [Folia](https://github.com/PaperMC/Folia)?

### Reason

A good plugin should match a good core

**Comment by Boy0000** [comment]
Oraxen has an open PR for Folia support, but im not rushing to support it

**Comment by TsubakiDev** [comment]
> Oraxen has an open PR for Folia support, but im not rushing to support it

Thanks Reply!
