### ISSUE TITLE
[BUG] Items lose attributes after they auto update

### ISSUE THREAD

**Issue by antibitcoin** [oraxen/oraxen#1008]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

So my server have lot of oraxen items, but sadly the attributes was added by me to the items using itemedit.
when the converter for 1.20.1 converts armors and weapons to the new system for example on login, or item pickup it will reset attributes.

I suggest it copy over attributes instead of recreating the item everytime, otherwise I am stuck at using oraxen-1.157.1.jar which does not convert items and they got wrong textures.

### Steps to reproduce

add an attribute lets say attack speed to an item using itemedit or itemeditor, drop the sword or armor and pick it up, in case of armor logout and login is enough to update it and lose armor, attack_damage.

### Plugin Version

1.159.0

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-665

### Server Software & Version

paper-1.20.1-106.jar

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
fixed in 1.160.0

**Comment by antibitcoin** [comment]
may I reoped this, items are still losing unbreakable attribute

**Comment by Boy0000** [comment]
unbreakable isnt an AttributeModifier afaik
u can always disable an item from being auto updated if u for some reason need to use another plugin to add xyz property
please open a new issue if it is unbreakable that is the issue
