### ISSUE TITLE
[SUGGESTION] Different Hardness Values per Item

### ISSUE THREAD

**Issue by SebyRo23** [oraxen/oraxen#1016]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

  Mechanics:
    noteblock:
      hardness: 
      -  WOODEN_AXE: 3
      -  PAPER: 8

### Reason

It would make some specific blocks more unique, like a block that can only be broken with a specific tool

**Comment by bkgktp** [comment]
this same request was opened for ItemsAdder, and I think it's pretty ridiculous, but my CustomHardness algorithm can be used instead.
