### ISSUE TITLE
[BUG] <NPC can be attacked>

### ISSUE THREAD

**Issue by sachiko8787** [oraxen/oraxen#1019]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

I updated my server to 1.20.1 and updated oraxes to the latest version since then the problem is that my Citizen NPCs are all vulnerable, please help!!

### Steps to reproduce

oraxen installed - npc can be attacked
oraxen deinstall - npc cant be attacked

### Plugin Version

oraxen-1.160.0.jar

### ProtocolLib Version

ProtocolLib 5.1.0

### Server Software & Version

[?1l>[?1000l[?2004l[?1h=[?2004h> 
[K[20:52:48 INFO]: [97mThis server is running Paper version git-Paper-128 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 47b805f)[0m
[93mYou are 1 version(s) behind
Download the new version at: [33mhttps://papermc.io/downloads/paper[0m
[3m[37mPrevious version: git-Paper-492 (MC: 1.19.4)[0m

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
this seems to be caused by other plugins. Someone else narrowed it down to Graves
