### ISSUE TITLE
Pushing Custom Block With Piston Changes Texture

### ISSUE THREAD

**Issue by test414EFF** [oraxen/Oraxen#102]
Hello,
I recently discovered that pushing a custom block towards another custom block with a piston will change the texture.
This bug does not occur when the block is pushed into a vanilla block.

Video: https://imgur.com/K7V5xH9

**Comment by Th0rgal** [comment]
Hello there!

Can you confirm me this is not just a display bug? Is it fixed if you place a real block next to it?

**Comment by test414EFF** [comment]
I just checked and nothing changes if you place a real block next to it.

**Comment by Th0rgal** [comment]
I'll work on a fix asap, thank you for opening an issue!

**Comment by Th0rgal** [comment]
Hello test414EFF, I tried to reproduce the bug but I couldn't. Are you using other plugins?
