### ISSUE TITLE
[BUG] Custom block issue with custom pickaxe

### ISSUE THREAD

**Issue by NightLife-SG** [oraxen/oraxen#1020]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

custom block wont drop anything with custom pickaxe

### Steps to reproduce

mined custom block with custom pickaxe made in oraxen

### Plugin Version

![image](https://github.com/oraxen/oraxen/assets/84533050/45a96afe-eff8-47df-8ed1-98345c3dae4e)

### ProtocolLib Version

![image](https://github.com/oraxen/oraxen/assets/84533050/b4ec0892-3564-4f0a-8fb5-cead5fcc00bf)

### Server Software & Version

![image](https://github.com/oraxen/oraxen/assets/84533050/fec4864d-8ed9-4eb5-9949-fedd82d57de1)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by NightLife-SG** [comment]
this issue is doesn not persist in version 1.158.2

**Comment by NightLife-SG** [comment]
still no update?

**Comment by Boy0000** [comment]
plan is for this to be in next update. as noted in update due to holiday etc i didnt have time for it last update and took abit longer
devbuilds will be posted in the discord when done

**Comment by Boy0000** [comment]
I am using latest release aka 1.162.0
