### ISSUE TITLE
[BUG] Reload won't apply change to furnitures

### ISSUE THREAD

**Issue by iqtesterr** [oraxen/oraxen#1021]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When doing reload command, the change of furnitures are not applied in game. Need to restart the whole server for it to apply. 
For example hitbox, light level, seat height.

### Steps to reproduce

Change the seat height for any furniture and reload, then place it to test.

### Plugin Version

1.160.0

### ProtocolLib Version

5.1.0

### Server Software & Version

git-Paper-131 (MC: 1.20.1)

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by iqtesterr** [comment]
I not sure how to explain this weird issue.
https://vimeo.com/855757842?share=copy

**Comment by iqtesterr** [comment]
> I not sure how to explain this weird issue. https://vimeo.com/855757842?share=copy

This is only happen when I turn on "experimental_furniture_type_update: true"

**Comment by iqtesterr** [comment]
Yeah, reload not work. 
https://vimeo.com/855767251?share=copy

**Comment by Boy0000** [comment]
Unable to reproduce this on 1.160.0

https://github.com/oraxen/oraxen/assets/62521371/eacc91fa-9034-4664-9744-e6a11f01a855

**Comment by SenPr** [comment]
Getting this issue on 1.161.0 as well, fresh server Paper 1.20.1 Build 191, with only ProtocolLib and Oraxen.

I tried ProtocolLib 5.1.0 release on Spigot and the latest dev builds, problem still persist.
