### ISSUE TITLE
[SUGGESTION] Remove reliance on LightAPI for custom light sources

### ISSUE THREAD

**Issue by iqtesterr** [oraxen/oraxen#1022]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Not relied to LightAPI anymore, and achieve the ability to remove light block when break the furniture or block.

Lonedev Showcase
https://www.youtube.com/watch?v=S0Gc3uhDdqY

### Reason

Currently, the light block won't remove when destroy the furniture or block. In that case it is unusable for player.

**Comment by Boy0000** [comment]
LightAPI has been broken ever since like 1.19
I have no clue atm how lonedev has added light-blocks without it.
Could it be doen? imean yeah sure. Whenever #962 is merged and I can use NMS more it would probably be easier

**Comment by oliviathevampire** [comment]
> Reference in

What about light blocks?

**Comment by Boy0000** [comment]
light blocks are still blocks and if sent as a packet i believe it fails if theres an actual block there
ithink i had a solution in another plugin i did which was packet based, but probably gonna wait until #962 is merged

**Comment by iqtesterr** [comment]
@Boy0000 #962 has been merged is any plan on this topic.

**Comment by Boy0000** [comment]
it has not been done yet no. when it is there will be a linked PR to it

**Comment by samue1ch** [comment]
> LightAPI has been broken ever since like 1.19 I have no clue atm how lonedev has added light-blocks without it. Could it be doen? imean yeah sure. Whenever #962 is merged and I can use NMS more it would probably be easier

pretty sure itemsadder just replace surrounding air blocks with lightblocks
