### ISSUE TITLE
[SUGGESTION] Incorporate feature to prevent NBT data removal 

### ISSUE THREAD

**Issue by relampagorojo93** [oraxen/oraxen#1023]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

I'm a developer of a plugin which is trying to incorporate compatibility with Oraxen, but for customization and optimization, to have a better way to retrieve certain data about an item instead of checking with each registered item to find the one, I use NBT to save at least the identifier of this registered items. I found out that your plugin actually autoupdates the items to keep them with the last settings of their configuration, but this autoupdate seems to remove the previously set NBT tags. As they are removed, the plugin stops detecting them as part of the system, and loses their functionality.

### Reason

I don't exactly know which features offers Oraxen which can be related with NBT, so I can't know actually if there could be issues by trying to incorporate this compatibility, but I think it can help giving compatibility for plugins that work on that way, so they can improve their performance as NBT can help a lot by directly only getting the ID of the respective entry. My idea of a compatibility was about reincorporating this NBT custom data to the new generate item, or include a system which allows to reincorporate data which follows a certain pattern, in case you need to distinct data that can be reincorporated from data that should be restarted.

If there's actually a way to solve this issues without requiring of this implementation, I'ld also love to hear about it, as some of my customers usually likes to use Oraxen for their items.

**Comment by Boy0000** [comment]
If something is in the PDC it shjould be copied over to the updated item
you can also disable it on a per item basis by adding no_auto_update: true to an item tho not recommended

**Comment by relampagorojo93** [comment]
> If something is in the PDC it shjould be copied over to the updated item you can also disable it on a per item basis by adding no_auto_update: true to an item tho not recommended

I didn't hear about PDC before, but cause I'm usually outdated to a certain point, as I usually try to offer compatibility with plugins under 1.13.2, which doesn't have it, basically by NMS and editing the NBTTagCompound that items contains. I don't know if PDC actually works as an interface for this same NBTTagCompound, but being or not the case, I'll test it out to find if it's currently persisting. I imagine that currently Oraxen is not providing support for older versions doesn't it? As I saw that it's tested compatibility seems to start from 1.18.

About this second option, I didn't know about that setting, also my partner which is the one that manages mostly Oraxen on our servers didn't know that this setting was there, and I imagine that it's not recommended, but in case we have more issues or users must have a temporary solution, I'll be telling them to use this meanwhile we work on fixing it. Thank you about the information.
