### ISSUE TITLE
[BUG] OraxenStringBlockPlaceEvent executing twice

### ISSUE THREAD

**Issue by relampagorojo93** [oraxen/oraxen#1024]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

I'm trying to use the API to make a control of some blocks which actually aren't properly detected through the BlockPlaceEvent due its information, so I've been trying to use your events. The OraxenStringBlockPlaceEvent actually is firing twice. I had to check the code, and I found out that the deprecated one is not using the deprecated event class, it's using the new one too, which makes it fire twice the event.

![image](https://github.com/oraxen/oraxen/assets/21053116/ff7eaa7b-6c4d-42e0-a526-ad109e36bbc8)

I'll set this bug as a non-breaking bug, as probably if someone is using this events, would have notice it before, so probably not a lot of people is using it right now, but it's not allowing to use this event properly, as my actions are fired twice, which leads to a cancellation of the event as result.

### Steps to reproduce

- Generate a plugin or make any implementation which has a handler to manage the OraxenStringBlockPlaceEvent.
- Place a StringBlock.
- The event should be firing twice, also, the deprecated one actually shouldn't be executing any more.

### Plugin Version

```
[00:17:38] [Server thread/INFO]: Oraxen | Oraxen version: 1.160.0!
```

### ProtocolLib Version

```
[00:17:54] [Server thread/INFO]: ProtocolLib version 5.0.0
[00:17:54] [Server thread/INFO]: Provides read/write access to the Minecraft protocol.
[00:17:54] [Server thread/INFO]: Authors: dmulloy2 and comphenix
```

### Server Software & Version

```
[00:18:39] [Server thread/INFO]: This server is running CraftBukkit version 3807-Spigot-c62f4bd-676969d (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)
```

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
Guess it is calling the non deprecated yeah, ill just be removing them for next update anyway so
