### ISSUE TITLE
[BUG] entity issues

### ISSUE THREAD

**Issue by PostieMC** [oraxen/oraxen#1025]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Crashclaims > issue with players being able to attack each other and entities while in a disabled claim
essentials > godmod is completely bypassed 
worldguard > pvp blocked areas block pvp but players attack entities is bypassed
civilians > civilians/npcs have become attackable and killable in areas that players shouldn't be allowed to attack in. (i fixed this issue by putting the NPC in creative mode)

### Steps to reproduce

download and install Oraxen onto the server.
the above breaks.

remove Oraxen from server.
the above is fixed

### Plugin Version

1.160.0

### ProtocolLib Version

5.1.0-snapshot- build 654

### Server Software & Version

Paper version git-Paper-17 (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: c287e92)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
Currently unable to reproduce these issues. lmk if i missed something iguess

https://streamable.com/fh9q3i

https://streamable.com/i1k2eg
