### ISSUE TITLE
[SUGGESTION] Split oraxen to two modules

### ISSUE THREAD

**Issue by GliczDev** [oraxen/oraxen#1028]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Oraxen should be split to two modules (api and plugin) and then jitpack should be configured to only compile api module (however it'd require a lot of work to split it correctly with all mechanics etc)

### Reason

Currently, it's possible to download compiled oraxen jar from jitpack's repo and that's bad

**Comment by Boy0000** [comment]
Whilst I probably agree, going to jitpack to get it is probably not the first place people would go
#962 splits it into different modules, so extracting API probably would not be too hard
Not sure if it is gonna be done though but feel free to try
