### ISSUE TITLE
[BUG] GriefPrevention not supported by ProtectionLib

### ISSUE THREAD

**Issue by malusic23354** [oraxen/oraxen#1031]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

i have oraxen-1.160.0.jar and GriefPrevention as well as the latest version and the plugin works perfectly but my problem comes to it bypassing: Claims, Adminclaims, Regions, ect.. like there's no limit, how to fix please.

this is the item file:

stardew_hoe:
  displayname: <#FF55FF>Stardew Hoe
  lore:
  - ''
  material: NETHERITE_HOE
  ItemFlags:
  - HIDE_ATTRIBUTES
  - HIDE_POTION_EFFECTS
  - HIDE_UNBREAKABLE
  unbreakable: true
  Pack:
    generate_model: true
    model: item/handheld
    custom_model_data: 202
  Mechanics:
    harvesting:
      radius: 32
      height: 1
      cooldown: 0
    soulbound:
      lose_chance: 0

### Steps to reproduce

using the hoe and rightclick crops in a claimed land still lets them use the hoe

### Plugin Version

oraxen-1.160.0

### ProtocolLib Version

ProtocolLib-5.1.0

### Server Software & Version

1.20.1/Paper

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
Oraxen does not have support for GriefPRevention rn and they seem to not cancel the events.
Please link to the plugin so I can look into adding compatibility and test it

**Comment by malusic23354** [comment]
> Oraxen does not have support for GriefPRevention rn and they seem to not cancel the events. Please link to the plugin so I can look into adding compatibility and test it

https://www.spigotmc.org/resources/☄%EF%B8%8F-oraxen-add-items-blocks-armors-hats-food-furnitures-plants-and-gui-1-18-1-20-1.72448/
?

**Comment by Boy0000** [comment]
link to the GriefPrevention plugin not Oraxen..

**Comment by malusic23354** [comment]
> link to the GriefPrevention plugin not Oraxen..

https://dev.bukkit.org/projects/grief-prevention/files/4597150/download
