### ISSUE TITLE
[BUG] Item update breaking advanced enchanats

### ISSUE THREAD

**Issue by antibitcoin** [oraxen/oraxen#1034]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When an item updates it will make advanced enchants non functional, they turn from NTB into almost just lores.

### Steps to reproduce

enchant an item with advanced enchants, drop the item and pick it up to update it if it had old textures pre Minecraft 1.20 system, this happened to me in leather helmets and armor

### Plugin Version

1.160.0

### ProtocolLib Version

5.1.1

### Server Software & Version

paper 103, 1.20.1

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
if enchantments are in the PDC then they will be kept
Raw nbt might not be

**Comment by antibitcoin** [comment]
> ```yaml
> myitem:
>   no_auto_update: true
> ```

Yes, but this have never been an issue pre 1.57, please implement a solution that will not affect anything added to the item not from oraxen, as you know people do enchant and use lot of other plugins, its better for the code to respect item original stats.

thanks for your hard work.

regards

**Comment by Boy0000** [comment]
It does keep most stuff but raw NBT not in the items persistentdata container might be skipped. If u got a concrete example with a plugin ill be able to reproduce it then ill see

**Comment by antibitcoin** [comment]
Here is an example of an item I saved using /is save, on itemEdit plugin. of a sword losing enchants and losing attribute modifiers.

  nbt1:
    item:
      ==: org.bukkit.inventory.ItemStack
      v: 3465
      type: DIAMOND_SWORD
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"yellow","text":"∞
          "},{"italic":false,"color":"red","text":"ᴍᴇᴍᴏʀʏ ᴠ2 "},{"italic":false,"obfuscated":true,"color":"yellow","text":"x"}],"text":""}'
        lore:
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Headless
          III"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Insomnia
          VII"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"Featherweight
          III"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"aqua","text":"Execute
          VI"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"aqua","text":"Vampire
          III"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"yellow","text":"Arsonist
          III"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"yellow","text":"Dominate
          IV"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"yellow","text":"Enrage
          III"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gold","text":"Double
          Strike III"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gold","text":"Inversion
          IV"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gold","text":"Rage
          VI"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gold","text":"Silence
          IV"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gold","text":"Stun
          III"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"light_purple","text":"Demonic
          Lifesteal V"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"light_purple","text":"Reflective
          Block III"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Sweeping
          X"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Sharpness
          200"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Mending
          I"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Looting
          20"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Knockback
          X"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Fire
          Aspect X"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"blue","text":"Bound
          to MANVSMEN"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"sᴜᴘᴇʀɪᴏʀ
          ᴠᴀɴɪʟʟᴀ sᴡᴏʀᴅ"}],"text":""}'
        - '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"yellow","text":"*"},{"bold":true,"italic":false,"color":"white","text":"HOLY"},{"bold":true,"italic":false,"color":"yellow","text":"*
          "},{"bold":true,"italic":false,"color":"white","text":"PROTECTED"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_aqua","text":"MobTrak
          Kills: "},{"italic":false,"color":"white","text":"360441"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"50
          Enchantment Slots "},{"italic":false,"color":"gray","text":"(Orb ["},{"italic":false,"color":"green","text":"+40"},{"italic":false,"color":"gray","text":"])"}],"text":""}'
        custom-model-data: 18
        enchants:
          FIRE_ASPECT: 10
          KNOCKBACK: 10
          LOOT_BONUS_MOBS: 20
          MENDING: 1
          DAMAGE_ALL: 200
          SWEEPING_EDGE: 10
        attribute-modifiers:
          GENERIC_ATTACK_DAMAGE:
          - ==: org.bukkit.attribute.AttributeModifier
            amount: 177.0
            name: GENERIC_ATTACK_DAMAGE
            slot: HAND
            uuid: 7c1c855b-d08c-46e6-98c2-a7fff3548957
            operation: 0
          GENERIC_ATTACK_SPEED:
          - ==: org.bukkit.attribute.AttributeModifier
            amount: 7.0
            name: GENERIC_ATTACK_SPEED
            slot: HAND
            uuid: feda6390-527e-49b3-954f-023b4f2468b0
            operation: 0
        internal: H4sIAAAAAAAA/3WQS07EMBBEWzIDEmKH+Egg2M4d5hAcAXWcyqQ1dhu5ncCNOUYwSlZmWNqvqlTV10SOHhjvUD+ylggthxHcB5hRhY7uG2oS6hMVXjh6bKDojGySdMVPDe7T1NXkkuWENf22TS+TruSlIRlDgC8yowvJn1ZRW13UUlThSq/+Vp85fkjGeStnSypWzq/GF/xUfq2Xju5aqJmP/8T2KYpy2e7Vzt18NfNG1GewoX/LXf3aO3ptoxBrQx9kqCcEh6raOXpuVAO4jMifkOO4jdlZSMWWZfmmH9yGWRTxAQAA
        PublicBukkitValues:
          enchantmentnumbers:enchantmentnumbers-len: 6i
          oraxen:id: energy_crystal_sword
          oraxen:original_name: §x§3§6§8§5§E§CE§x§3§9§8§8§E§Cn§x§3§C§8§B§E§Be§x§3§F§8§E§E§Br§x§4§3§9§2§E§Ag§x§4§6§9§5§E§Ay§x§4§9§9§8§E§9
            §x§4§C§9§B§E§9C§x§4§F§9§E§E§9r§x§5§2§A§1§E§8y§x§5§6§A§5§E§8s§x§5§9§A§8§E§7t§x§5§C§A§B§E§7a§x§5§F§A§E§E§7l§x§6§2§B§1§E§6
            §x§6§5§B§4§E§6S§x§6§9§B§8§E§5w§x§6§C§B§B§E§5o§x§6§F§B§E§E§4r§x§7§2§C§1§E§4d
          itemsoulbind:soulbinduuid: 35bcb42e-5038-4e05-b96a-605dc9569790
  nbt2:
    item:
      ==: org.bukkit.inventory.ItemStack
      v: 3465
      type: DIAMOND_SWORD
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"yellow","text":"∞
          "},{"italic":false,"color":"red","text":"ᴍᴇᴍᴏʀʏ ᴠ2 "},{"italic":false,"obfuscated":true,"color":"yellow","text":"x"}],"text":""}'
        lore:
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Headless
          III"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Sweeping
          X"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Sharpness
          200"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Mending
          I"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Looting
          20"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Knockback
          X"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Fire
          Aspect X"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"blue","text":"Bound
          to MANVSMEN"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"sᴜᴘᴇʀɪᴏʀ
          ᴠᴀɴɪʟʟᴀ sᴡᴏʀᴅ"}],"text":""}'
        - '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"yellow","text":"*"},{"bold":true,"italic":false,"color":"white","text":"HOLY"},{"bold":true,"italic":false,"color":"yellow","text":"*
          "},{"bold":true,"italic":false,"color":"white","text":"PROTECTED"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_aqua","text":"MobTrak
          Kills: "},{"italic":false,"color":"white","text":"360441"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"50
          Enchantment Slots "},{"italic":false,"color":"gray","text":"(Orb ["},{"italic":false,"color":"green","text":"+40"},{"italic":false,"color":"gray","text":"])"}],"text":""}'
        custom-model-data: 18
        enchants:
          FIRE_ASPECT: 10
          KNOCKBACK: 10
          LOOT_BONUS_MOBS: 20
          MENDING: 1
          DAMAGE_ALL: 200
          SWEEPING_EDGE: 10
        attribute-modifiers:
          GENERIC_ATTACK_SPEED:
          - ==: org.bukkit.attribute.AttributeModifier
            amount: 1.6
            name: oraxen
            slot: HAND
            uuid: 35f224b1-bd48-4ca1-bd0e-bbb760b2aa0c
            operation: 0
          GENERIC_ATTACK_DAMAGE:
          - ==: org.bukkit.attribute.AttributeModifier
            amount: 10.0
            name: oraxen
            slot: HAND
            uuid: d1fe3908-8aa8-49bb-8c1f-907b765a43ab
            operation: 0
        internal: H4sIAAAAAAAA/+NiYGBmEE9MjU/NS85IzCvJTc0rsc5ITUzJSS0uZgBKMjPwZOYlF6UmFqem+BclAYU0mBlYi3PyS4r///9/kwEA7Ox7m0EAAAA=
        PublicBukkitValues:
          enchantmentnumbers:enchantmentnumbers-len: 6i
          oraxen:id: energy_crystal_sword
          oraxen:original_name: §x§3§6§8§5§E§CE§x§3§9§8§8§E§Cn§x§3§C§8§B§E§Be§x§3§F§8§E§E§Br§x§4§3§9§2§E§Ag§x§4§6§9§5§E§Ay§x§4§9§9§8§E§9
            §x§4§C§9§B§E§9C§x§4§F§9§E§E§9r§x§5§2§A§1§E§8y§x§5§6§A§5§E§8s§x§5§9§A§8§E§7t§x§5§C§A§B§E§7a§x§5§F§A§E§E§7l§x§6§2§B§1§E§6
            §x§6§5§B§4§E§6S§x§6§9§B§8§E§5w§x§6§C§B§B§E§5o§x§6§F§B§E§E§4r§x§7§2§C§1§E§4d
          itemsoulbind:soulbinduuid: 35bcb42e-5038-4e05-b96a-605dc9569790

**Comment by antibitcoin** [comment]
adding new enchants will delete old enchants on oraxen armor, don't know if this is a compatibility issue or should I report this on advanced enchants github.

**Comment by antibitcoin** [comment]
thanks for sharing,  I will share this with advanced enchantment github so they would check from their side, if you don't mind waiting your response.
I am thinking it could be advanced enchants method of adding new enchants to the armor is conflicting with oraxen normal behavior which should work with other plugins normally, because I don't see any other bugs here complaining about enchants, so I do believe for now its something on their side.

**Comment by Toshiii35** [comment]
Can confirm this issue, AE works just fine with normal items, just not with oraxen items here's a clip I added when I made the same issue on AE github

 https://www.xbox.com/en-US/play/media/9JLT76568N

**Comment by Boy0000** [comment]
fixed in this PR, devbuild available in the Discord if anyone wants to test it
