### ISSUE TITLE
[SUGGESTION] oraxen_packstatus placeholder

### ISSUE THREAD

**Issue by antibitcoin** [oraxen/oraxen#1037]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Can you add a placeholder %oraxen_packstatus% it would return 1 or 0 or true or false.

### Reason

I would like to use this placeholder with with my own code to show regular text instead of glyphs when the player does not have the pack loaded, instead of the server full of special chars when people don't load the pack, I would like pretty much not to force the pack on players.

**Comment by Boy0000** [comment]
You can do this via normal Spigot/Paper API by listening to PlayerResourcepackStatusEvent and probably other means aswell
