### ISSUE TITLE
Gesture shader license

### ISSUE THREAD

**Issue by tomalbrc** [oraxen/oraxen#1038]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

The shader Oraxen is using for gestures is blatantly copied from https://github.com/FutureMaximus/Denizen-Player-Models
without retaining the License/Copyright notice

### Steps to reproduce

Lack of copyright notice https://github.com/FutureMaximus/Denizen-Player-Models/blob/main/LICENSE

### Plugin Version

All

### Server Software & Version

All

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by tomalbrc** [comment]
just fyi..

**Comment by Boy0000** [comment]
it is blatanly copied from [https://git.lumine.io/mythiccraft/mccosmetics](MCCosmetics) and they do not have a license with it to my knowledge
