### ISSUE TITLE
[BUG] The texture pack weighs 1.5 Exabytes

### ISSUE THREAD

**Issue by Alexciao** [oraxen/oraxen#1039]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

The pack is a 58KB zip file that cannot be unzipped as it requires 1.5 Exabytes of storage.

**Edit:** Upon further inspection, the pack.mcmeta file weighs 4.285.204,25 Terabytes and the pack.png file weighs 8.677.899,05 Terabytes

**Edit 2:** Upon more inspection, it seems like every ifle weighs between 1 million terabytes and 10 million terabytes. Every single file. Also, the last edited date is the 30th of December 1899 as 1AM.

### Steps to reproduce

- Clone the repo using `gh repo clone oraxen/oraxen`
- Build the JAR using `.\gradlew.bat build`
- Install the JAR alongside ProtocolLib 5.0
- Join the server
- Accept the texturepack

### Plugin Version

1.160.0

### ProtocolLib Version

5.0.0

### Server Software & Version

Paper version git-Paper-110 (MC: 1.20.1)

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
It does not that is simply because of pack encryption

**Comment by Alexciao** [comment]
Yes but my Minecraft cannot unzip it

**Comment by Boy0000** [comment]
i have no issue having oraxen protect the pack and then get it sent and loaded ingame

**Comment by Alexciao** [comment]
client log has no useful info. i cannot ask for support, because i didn't buy the plugin (i wanted to test it on a private server before buying)
