### ISSUE TITLE
Items with hat mechanic enable can be duped

### ISSUE THREAD

**Issue by apatuka** [oraxen/Oraxen#104]
Greetings here is how to reproduce the issue:

1. Get the item with hat mechanic enabled
2. Put the item as offhand
3. Right click while having on your offhand (While having your main hand empty)
4. Now you have two, one on your chest and another on your head

**Comment by Th0rgal** [comment]
Unfortunately I have not been able to reproduce this bug on my test server. Do you have any other plugins installed? Some users told me they fixed the bug by replacing LEATHER_CHESPLATE by another item like DIAMOND. I will do that in the default to ensure no people get those dupe bugs. Thank you very much for reporting the issue.

**Comment by apatuka** [comment]
Dear Th0rgal, i will try that as well. The dupe stopped as soon i removed the hat mechanic. Maybe is caused by another plugins, already have a lot of dupe reports from other plugin (MMOItems) maybe had something to do with that, so i guess it's not a problem from Oraxen.

Thank you very much for the help !

**Comment by Th0rgal** [comment]
You are welcome apatuka!
