### ISSUE TITLE
Multi-language support for Oraxen items  (Translate Component)

### ISSUE THREAD

**Issue by bkgktp** [oraxen/oraxen#1042]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

https://minecraft.fandom.com/wiki/Raw_JSON_text_format#Translated_Text

you can look at this wiki to understand in more detail what needs to be done.

example command: 
```
/tellraw @a [ { "translate" : "commands.op.success" } ] 
``` 

palm_blocks.yml
<img width="373" alt="resim" src="https://github.com/oraxen/oraxen/assets/101702786/56d6f89d-b77e-4e7b-9d93-cb47141b142d">

langueage-1 tr_tr.json
<img width="684" alt="resim" src="https://github.com/oraxen/oraxen/assets/101702786/e1b90b5f-a979-4743-964d-6c940316a1a9">

language-2 en_eu.json
<img width="715" alt="resim" src="https://github.com/oraxen/oraxen/assets/101702786/36c0fd46-8d53-4f2b-8ef8-dc5e0b7f1ffe">

### Reason

Adds multi-language support for users and servers. It will be a more attractive feature than Oraxen's other competitors.
Different messages should be sent according to the player's current language.
It is quite simple to add, only a small change to the ItemBuilder class is required.

I recommend using the MiniMessage API for this.

**Comment by oliviathevampire** [comment]
@Boy0000 this souldn't be too difficult to do? just add a new tag I think?

**Comment by Boy0000** [comment]
this is a part of Adventure and im not gonna just "add a tag"
if someone wants to implement it and open a PR feel free. It isnt a priority atm if the normal MiniMessage lang tag works

**Comment by bkgktp** [comment]
I recently included this in the plugin, the MiniMessage lang tag does not work.

this is a sample configuration 
<img width="516" alt="resim" src="https://github.com/oraxen/oraxen/assets/101702786/2ff85120-7faa-4eae-9fe3-7d1e83703d81">

**Comment by Boy0000** [comment]
depending on your PR @bkgktp i might merge it, but got it working rn with like 1 like of code.
It depends on the 1.162.0 nms glyph system tho, but eventually when reliable enough that will be toggled by default

![Skjermbilde 2023-09-09 020109](https://github.com/oraxen/oraxen/assets/62521371/540cfecc-371f-48ef-a112-f976955aa2c6)

**Comment by bkgktp** [comment]
<img width="508" alt="resim" src="https://github.com/oraxen/oraxen/assets/101702786/979a83b9-15aa-4d88-bd76-7c4f10fdb0c8"> @Boy0000 

<img width="284" alt="resim" src="https://github.com/oraxen/oraxen/assets/101702786/159b9211-3c06-46c0-a957-027fd9bac9fd">

I don't think this is working,

**Comment by bkgktp** [comment]
NMS glyps feature is active

**Comment by bkgktp** [comment]
OK, I understand the problem now! It only shows the original lang data in minecraft, so when I add something new to the lang file, it is invalid because it cannot save it to the server.

<img width="337" alt="resim" src="https://github.com/oraxen/oraxen/assets/101702786/e9b54ab9-4c49-4c5d-ac20-ebeb32821475">
<img width="757" alt="resim" src="https://github.com/oraxen/oraxen/assets/101702786/a052472e-9885-4ea1-82aa-6d0d48286a6b

<img width="619" alt="resim" src="https://github.com/oraxen/oraxen/assets/101702786/4a3a2230-d8c4-499f-b0a9-101945d11428">

The best way to solve this is to change the setDisplayName path in the ItemBuilder class from string to Component so that MiniMessage can set the incoming data completely differently.

**Comment by Boy0000** [comment]
as i said earlier I cannot just make it a Component without breaking Spigot support
Yes it wont inherently know custom keys thats another issue right now
As these are client-side only. Easy enough to fix

**Comment by bkgktp** [comment]
no, only MiniMessage solves the problem
<img width="661" alt="resim" src="https://github.com/oraxen/oraxen/assets/101702786/c62b148a-32a3-4fc3-b141-49191a019b0f">

I made this kind of change without breaking the existing layout of the plugin, I only changed the String data to Component. if this can break spigot compatibility, you can also make it only for paper.
