### ISSUE TITLE
"Resource Reload failed"

### ISSUE THREAD

**Issue by timbo2040** [oraxen/oraxen#1044]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

I've tried google and searching issues and can't find this same problem. Let me know if I missed it. Here's what it is: I just put it on the server and loaded in. I tried getting in a few times, but each time it kicks me out and says "Resource Reload Failed. Not sure if this is something with my computer or the configs messed up, but please help me lol.

### Steps to reproduce

Load plugin into brand new server, 1.20.1, Paper. When loading in, you get an error in the top of the title screen saying "Resource Reload Failed"

### Plugin Version

1.158.0

### ProtocolLib Version

5.1.0

### Server Software & Version

git-Paper-131 (MC: 1.20.1)

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
please use the discord for support. check your client log as nothing server end can tell u why a client failed to download a pack
