### ISSUE TITLE
[enchantment] Optifine blocks

### ISSUE THREAD

**Issue by shmezi** [oraxen/Oraxen#105]
Hey, do you think it could be possible to add custom optifine blocks with oraxen ?

Could be really cool since most people use Optifine and it's possible to create unlimited blocks with it.

**Comment by Th0rgal** [comment]
Hmm do you have a link to a docs about those optifine blocks? :)

**Comment by shmezi** [comment]
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/block.properties

**Comment by Th0rgal** [comment]
Yeah you can add those files within Oraxen/pack/assets :)
