### ISSUE TITLE
[SUGGESTION] Space and offset tags

### ISSUE THREAD

**Issue by oliviathevampire** [oraxen/oraxen#1051]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

A feature inspired by this https://github.com/AmberWat/NegativeSpaceFont which would allow for space and offset tags to change different things, maybe even the newline feature it has.

### Reason

Would allow for more options for text

**Comment by Boy0000** [comment]
shift tags have existed for like 2 years in Oraxen now

**Comment by oliviathevampire** [comment]
Does space and offset work the same?

**Comment by Boy0000** [comment]
a space is a space, a shift/offset is negativespace which most people use

**Comment by oliviathevampire** [comment]
> a space is a space, a shift/offset is negativespace which most people use

ah ok, what about a space tag? does Oraxen have anything like that?

**Comment by Boy0000** [comment]
yes u can find it on the docs
