### ISSUE TITLE
[SUGGESTION] Ability to edit/remove drops when breaking blocks

### ISSUE THREAD

**Issue by WillFP** [oraxen/oraxen#1054]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Similar to how drops can be removed when breaking vanilla blocks, it would be nice to be able to do the same with oraxen via the API

### Reason

So I can prevent blocks dropping items in certain areas

**Comment by Scot-Survivor** [comment]
Can you just do this through bukkit events?

**Comment by WillFP** [comment]
If I could, I wouldn't have opened this PR! Adding an event in `OraxenBlocks.removeNoteBlock(Block, Player)` and `OraxenBlocks.removeStringBlock(Block, Player)` to cancel spawning the drop would help, or it could be merged into `OraxenNoteBlockBreakEvent` and `OraxenStringBlockBreakEvent`. It should be trivially easy to implement
