### ISSUE TITLE
How do I make the allay mechanism work with note_block and redstone?

### ISSUE THREAD

**Issue by maurestor** [oraxen/oraxen#1058]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [x] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When trying to connect the note_block it does not turn on or send a signal for use this block on allays.

### Steps to reproduce

Minecraft run normally, but note_block don't work correctly with redstone for mechanics of Allay.
https://www.youtube.com/watch?v=aeWndL4Wx7U
### Plugin Version

Loading server plugin Oraxen v1.160.0

### ProtocolLib Version

ProtocolLib v5.1.0

### Server Software & Version

Papper version git-Paper-182 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 29d1c7b)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
Noteblock mechanix disables most noteblock vanilla interactions. Probably allays to here. Not much u can do except disable noteblock mechanic and loose custom blocks
