### ISSUE TITLE
[BUG] Rail duplication, bed duplication, sound bugs etc..

### ISSUE THREAD

**Issue by Bruhhhh10** [oraxen/oraxen#1060]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

A video for most of these bugs can be found here (not all):
https://www.youtube.com/watch?v=Swt9o4Lyoso

I've tested all these bugs in
  disable-noteblock-updates: true
  disable-tripwire-updates: true

### Steps to reproduce

First off this issue can really annoy some players, if you hover over an oraxen block and try to eat food or use your bow it just won't let you since it's a noteblock and your player will try to play the noteblock, originrealms finds a way around this though (watch the entire video on youtube)

Flying flowers are still a thing (try placing candles/flowers/cake/pink petals against an oraxen block, and it will get placed anyways on the air)

~~If you get a ominous banner and right click it against an oraxen block it will turn into a white banner~~

If you place an oraxen block against grass or snow, it won't play the hand swing animation

If you place an oraxen block on the ground, place door against the block it will spawn a half door

You can get flying seaweed if you place an oraxen block, place water on side and right click with seaweed where theres water on the side, and if theres water on the sides that aren't full water source blocks of said oraxen block and you try to place seaweed, the water will become a full source block, there's also another bug with seaweed, if you place seaweed against oraxen block and if said oraxen block has lava near it, the lava will turn into cobblestone as if water was placed there:
https://github.com/oraxen/oraxen/assets/134551265/21d766d1-47b0-45d3-bb9f-c886981c9904

If you place a spore blossom on the sides or on top of an oraxen block, it will place the spore blossom in the air even if theres no blocks above

You can dupe power rails, activator rails and detector rails if you right click them against an oraxen block and stand on that oraxen block where you're placing the rail (it also plays rail block place sound everytime), if you try to place a rail it will just place the normal rail in the air (that should also be fixed)

Place oraxen block down then stand on top of it, place bed right below you and it will dupe, (I've reported this before and it still hasn't gotten fixed)

Go to max height (y level 320), place oraxen block the highest you can, try to place oraxen block on top of a vanilla block on max height or a vanilla block like oak plank on top of oraxen block on max height, plays a sound everytime and if you try to place an oak plank on top of an oraxen block thats at y level 320 it will play a stone block place sound

Get your custom armor boots, if you walk on powdered snow you will get Light as a Rabbit achievement because your custom armor boots are leather_boots, also if you open up a grindstone, put a normal leather armor on the top slot of grindstone and your custom armor on the bottom slot of grindstone, it will give you a newly repaired leather armor

~~if you get a cartography table and make a villager get a job from that cartography table, you can trade paper for emeralds, now since oraxen noteblock mechanic and furniture mechanic mainly uses minecraft:paper, you can oraxen blocks for emeralds (the villager will also hold a emerald if you hold a oraxen block with a minecraft:paper id if the villager is offering emeralds for paper), heres a video of that:
https://github.com/oraxen/oraxen/assets/134551265/fa917663-433a-4141-912c-74a71e4f8390~~

Sign placements on top of oraxen blocks are just wrong, if you try to place them diagonally sometimes they will just flip backwards or just not place them diagonally at all if you place them from specific directions

Place tripwire on top of any oraxen block it will play tripwire place sound.

### Plugin Version

1.161.0

### ProtocolLib Version

5.1.0

### Server Software & Version

git-Paper-196 (MC: 1.20.1)

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
for the future, please split unrelated bugs into multiple bugreports
makes it 10x easier to fix these issues

**Comment by bkgktp** [comment]
https://nms.screamingsandals.org/1.20.2/net/minecraft/world/item/UseAnim.html

I think we can update the bow and food interaction in the player's note block by sending UseAnim.NONE, I think Boy should try this with NMS.

**Comment by Boy0000** [comment]
The reason that happens is because NoteBlocks will "play a note" when u right click them
So for bows to work like normal is gonna be alot trickier than it sounds due to it being mostly client side
Might find a fix but not sure
