### ISSUE TITLE
item outputs in recipes are not accurate.

### ISSUE THREAD

**Issue by bkgktp** [oraxen/oraxen#1062]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

I am creating a recipe and I cannot specify the number of inputs/outputs in the recipes I have created.

### Steps to reproduce

<img width="600" alt="resim" src="https://github.com/oraxen/oraxen/assets/101702786/d34b68bd-5c06-4f35-a413-a93cb16c37ac">
<img width="412" alt="resim" src="https://github.com/oraxen/oraxen/assets/101702786/93c01390-c2fc-4c6e-be98-708b7489d5d5">

<img width="321" alt="resim" src="https://github.com/oraxen/oraxen/assets/101702786/c19b9f01-7ace-4eef-b523-344841a9cd35">
The menu created with /oraxen recipe does not write any output quantity data to the configuration.

### Plugin Version

<img width="357" alt="resim" src="https://github.com/oraxen/oraxen/assets/101702786/c23ff521-348c-477a-800b-19962a58e945">

### ProtocolLib Version

<img width="674" alt="resim" src="https://github.com/oraxen/oraxen/assets/101702786/718088c2-9587-4c44-9662-a6c03e711faf">

### Server Software & Version

<img width="471" alt="resim" src="https://github.com/oraxen/oraxen/assets/101702786/d0332b90-2599-4035-a170-0be1ceb625ff">

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
Recipe ingredients cant take amounts. But yes the display menu for recipe here doesnt show amount which is a bug for result

**Comment by bkgktp** [comment]
can you add quantity data? a stable recipes app on the crafting table would be nice.

**Comment by Boy0000** [comment]
If a recipe result item has an amount specified, it will be giving it. For example a log giving 4 planks. Always been like that
