### ISSUE TITLE
[BUG] <name for bug>

### ISSUE THREAD

**Issue by SuperIsSuper** [oraxen/oraxen#1073]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

bushy leaves not working correctly

### Steps to reproduce

spent 5 hours on it

### Plugin Version

latest

### ProtocolLib Version

5.0.0

### Server Software & Version

This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)
You are running the latest version
Previous version: git-Paper-307 (MC: 1.19.2)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
When I said u should open a detailed bugreport with all the info i would need to reproduce this indidnt mean just say "doesnt work"..
