### ISSUE TITLE
[SUGGESTION] Add blast_resistance to Note/String/Furniture mechanics

### ISSUE THREAD

**Issue by liannai569** [oraxen/oraxen#1076]
### I have checked that...

- [X] ... I am using the latest version of Oraxen
- [X] ... I am using the latest version of any dependencies
- [X] ... I am using ProtocolLib 5.0
- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

maybe oraxen can add a setting for customblock to protect it from TNT blast, like that

blast_resistance: 6

I found the ore can be broken by TNT, so maybe add this setting can make customore be better 
and in my create a new block , I found that the block sound is unlike the vanilla sound, and when you place or break the block quickly,it will not play the sound by your actions, maybe we can add a way to use vanilla sound for customblocks like :   

break_sound: BLOCK_STONE_BREAK

to use vanilla minecraft sound

### Reason

add these options for blocks can make the block more like vanilla, enhance the player joy

**Comment by Boy0000** [comment]
1. blast_resistance might work but would prob be a toggle on/off
2. you can already do this. just set the break sound to block.stone.break (and if that doesnt work required.stone.break)

**Comment by liannai569** [comment]
> 1. blast_resistance可能有效，但可能是打开/关闭
> 2. 你已经可以这样做了。只需将中断声音设置为block.stone.break（如果不起作用，则required.stone.break）

And can you add some new options like 

placeable_on_water: true

make the string blocks can place on the water, or add the options:

place_on_ceiling: a_new_model

this all can make the stringblock have some joys

**Comment by Boy0000** [comment]
added in 2.0
