### ISSUE TITLE
[BUG] Stringblock can't place normal in server version 1.20.2

### ISSUE THREAD

**Issue by liannai569** [oraxen/oraxen#1079]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

![L7NP(1A%MSQU1_ 4(4C09(K](https://github.com/oraxen/oraxen/assets/89626087/373292c8-da62-437e-9843-dad08c980add)

you can see the block in /oxn inv, and get it. But you can't place it by yourself.

use "/onx admin place block clover" can place it
![L)S2 @$L {9`@N5Z1O~Z`%E](https://github.com/oraxen/oraxen/assets/89626087/4e1ba7be-3eac-4d80-96ec-fe93bb709cb6)

### Steps to reproduce

only the stringblock has broken

### Plugin Version

name: Oraxen
version: 1.162.0

### ProtocolLib Version

name: ProtocolLib
version: 5.1.1-SNAPSHOT-669

### Server Software & Version

![QQ截图20231026082617](https://github.com/oraxen/oraxen/assets/89626087/d6f3b4b7-9e6c-4c00-8438-311b9e378bf9)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Tomcatchriss** [comment]
Same Problem, but with paperblocks.

**Comment by liannai569** [comment]
paperblocks?what's mean?

**Comment by Boy0000** [comment]
no clue wehat paperblocks is but this should be fixed in 1.163.0

**Comment by liannai569** [comment]
> no clue wehat paperblocks is but this should be fixed in 1.163.0

maybe his mean is the options:

material: PAPER

**Comment by Boy0000** [comment]
material is for the held  item and has nothing to do with the placed block
