### ISSUE TITLE
[BUG] Stringblock can place unlimitly

### ISSUE THREAD

**Issue by liannai569** [oraxen/oraxen#1081]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Now the Stringblock can place but the item will not deduct

### Steps to reproduce

![image](https://github.com/oraxen/oraxen/assets/89626087/8ab6c0b0-e6b0-401b-a94b-ece27417e237)

There have 13 clovers and i right click to place the clover, there also have 13 clovers

![image](https://github.com/oraxen/oraxen/assets/89626087/ff097e8b-785a-4d24-bfa8-fa40ce021cad)

### Plugin Version

![image](https://github.com/oraxen/oraxen/assets/89626087/4b27ff23-aaab-451d-9cd8-608f1048bf30)

### ProtocolLib Version

![image](https://github.com/oraxen/oraxen/assets/89626087/dfcce6a1-68d8-4cbf-bf22-36a51079ab12)

### Server Software & Version

![image](https://github.com/oraxen/oraxen/assets/89626087/38a1edfb-f2a0-4192-bcb6-41b1ae82eba3)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
should not happen if you enable the nms.block_placement option, but otherwise it will be fixed next update

**Comment by liannai569** [comment]
> 如果启用nms.block_placement选项，则不会发生，否则下次更新将修复

My version is 1.20.2,open the nms.block_placement option, the stringblock can't place
