### ISSUE TITLE
[BUG] Block duplication glitch

### ISSUE THREAD

**Issue by MattWillen** [oraxen/oraxen#1082]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When placing an oraxen block (not furnitures) onto a replaceable block (grass, tall grass, ...), the Oraxen block replaces the Vanilla block correctly, but then places another one right next to it (direction depends on the player position).
The duped block can then be broken and drops its items normally, resulting in an effective duplication glitch.

https://github.com/oraxen/oraxen/assets/54420473/81dc7a80-c3dd-46cb-a02e-bb7802bac99c

### Steps to reproduce

- Take any placeable block from Oraxen;
- Place it onto a replaceable block, like grass or tall grass;
- Watch it duplicate
- Break it and enjoy profit!

### Plugin Version

"Oraxen version 1.163.0"

### ProtocolLib Version

"ProtocolLib version 5.1.1-SNAPSHOT-669"

### Server Software & Version

Running Paper version git-Paper-246 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: c1ac983)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
does this happen if you enable the experimental blokc_placement setting in settings.yml?

**Comment by MattWillen** [comment]
> does this happen if you enable the experimental blokc_placement setting in settings.yml?

Nope, as soon as I enabled the experimental block_correction function the issue got fixed!
Thanks for the help

**Comment by MattWillen** [comment]
Update: after some time and after adding a couple more blocks, it started doing it again even with the experimental feature enabled.

I tried out a few things and discovered that restarting the server solves the issue (logging in and out doesn't.
I couldn't figure out the "trigger" that re-activated the bug, as it happened almost randomly while trying to place a block on grass.

**Comment by MattWillen** [comment]
**Update #2**
I found out the issue causing the "re-activation" of the bug is the `/o reload all` command itself.
It seems like after using it, the experimental feature gets disabled or ignored, and as a consequence blocks start duplicating again.
