### ISSUE TITLE
[BUG] Block duplication glitch #2

### ISSUE THREAD

**Issue by MattWillen** [oraxen/oraxen#1083]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

By clicking both mouse buttons with an Oraxen block in hand, so that a block is broken and another one is placed, it gets placed twice, resulting in a successful duplication bug.
This isn't a big issue as normally players have not access to creative gamemode and are unable to instantly break and place a block, but it still exists so I figured reporting it was the best thing anyway.

In the video I'm clicking both the mouse buttons together:

https://github.com/oraxen/oraxen/assets/54420473/6d3b32ef-0ab1-4bc8-b611-52cd15fbd0b4

### Steps to reproduce

- Take any Oraxen placeable block (not furnitures)
- Put it in hand and click both right and left mouse buttons at the same time
- Enjoy the dupe!

### Plugin Version

"Oraxen version 1.163.0"

### ProtocolLib Version

"ProtocolLib version 5.1.1-SNAPSHOT-669"

### Server Software & Version

Running Paper version git-Paper-246 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: c1ac983)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
Well dupes that are only doable in Creative mode arent really dupes?
Blocks arent instabreak with an empty hand in survival so dont think this is an issue

**Comment by MattWillen** [comment]
> Well dupes that are only doable in Creative mode arent really dupes? Blocks arent instabreak with an empty hand in survival so dont think this is an issue

Yes, you are probably right.
The only use-case of this bug I can imagine is if someone uses Oraxen blocks in a Creative plot server or something.
Unlikely to happen, but you know might be something to look into sooner or later :)
