### ISSUE TITLE
[BUG] furniture's options seems have some bug's

### ISSUE THREAD

**Issue by liannai569** [oraxen/oraxen#1087]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

![image](https://github.com/oraxen/oraxen/assets/89626087/17b04bd1-1fe7-47b8-9931-80a992980ad7)

the "limited_placing" options seems dont work, I set it 'roof: false/floor:true/wall:false' but i can also place the furniture in the roof

![image](https://github.com/oraxen/oraxen/assets/89626087/54e3a373-d048-4152-abe8-7cefeb335b3b)

and the 'barrier/barriers/rotatable' three options seems work unnormally. When you 'oxn reload all' the rotatable and barrier 
will not work like you set it, must need restart the server, and the furniture's barriers option don't work normal, it will place the barrier in fixed-location dont follow your placement
![image](https://github.com/oraxen/oraxen/assets/89626087/6b4553bd-b2f1-40d5-96ad-ffa816b4aaf7)

### Steps to reproduce

option seems dont work, not all in descriptions, and the 'seat' also work unnormally when you change it, must need restart the server the option will be corrected

### Plugin Version

![image](https://github.com/oraxen/oraxen/assets/89626087/1c8357bf-f29f-4173-a0ac-e81e0bf282b6)

### ProtocolLib Version

![image](https://github.com/oraxen/oraxen/assets/89626087/aba7d856-cf64-4dd7-9578-7dc535a283ee)

### Server Software & Version

![image](https://github.com/oraxen/oraxen/assets/89626087/2ba394f1-d7cc-4f45-b6c8-7dd5eb4aa51a)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
1. limited placiong was bugged
2. cannot replicate this what so ever
Changing barrier from true -> false + /o reload items works as expected
Same when removing barrier and making multi-barriers

**Comment by liannai569** [comment]
> 1. limited placiong was bugged
> 2. cannot replicate this what so ever
>    Changing barrier from true -> false + /o reload items works as expected
>    Same when removing barrier and making multi-barriers

'/oxn reload all' not work ,and 'rotatable'option when you use '/oxn reload all', it only can rotate 180°. 45° and 90° will lose

**Comment by Boy0000** [comment]
yeah idk, when i reload it applies changes correctly
rotatable also works fine. and yes it only rotates at 45 degree angles
https://github.com/oraxen/oraxen/assets/62521371/14b0373d-fde4-499c-aacd-c22eb5b0d1bc

**Comment by Boy0000** [comment]
no clue, as shown in my clip above this isnt an issue i can replicate
also, your config is `barrier: true/false` which only places 1 or 0 barriers, but yours places two

**Comment by liannai569** [comment]
> 没有线索，如我上面的剪辑所示，这不是我也可以复制的问题，您的配置仅放置 1 或 0 个障碍，但您的配置放置了两个障碍`barrier: true/false`

It what I want to say, '/oxn reload all' not work as expected, but '/oxn reload items' work as expected.

**Comment by liannai569** [comment]
> 没有线索，如我上面的剪辑所示，这不是我也可以复制的问题，您的配置仅放置 1 或 0 个障碍，但您的配置放置了两个障碍`barrier: true/false`

![image](https://github.com/oraxen/oraxen/assets/89626087/4b347bc5-2a72-49f2-a6fb-1170c4fd104f)

'/oxn reload all' also will result the clickActions to repeat actions

![image](https://github.com/oraxen/oraxen/assets/89626087/122051c7-0cb6-44cb-ad34-ea2e0e74dcca)
