### ISSUE TITLE
[BUG] Efficiency doesnt affect custom blocks

### ISSUE THREAD

**Issue by ItzRegen** [oraxen/oraxen#1090]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When I add on pickaxe efficiency 1/2/3/4, then it is mining as without enchant...

### Steps to reproduce

(Nothing)

### Plugin Version

![image](https://github.com/oraxen/oraxen/assets/110901462/7ab7d889-5760-4a8d-8cde-317a0740a4f7)

### Server Software & Version

![image](https://github.com/oraxen/oraxen/assets/110901462/cf3f6343-22b4-48bb-bdcf-9531b7c81663)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by liannai569** [comment]
I test the block hardness, maybe this is a error 


https://github.com/oraxen/oraxen/assets/89626087/7d18763c-ea9e-4acd-b5e9-10e1081f5f6a

**Comment by ItzRegen** [comment]
> I test the block hardness, maybe this is a error
> 
>  bandicam.2023-11-03.20-34-20-424.mp4

Try efficiency I/II/III/IV

**Comment by liannai569** [comment]
> > 我测试了块的硬度，也许这是一个错误
> > Bandicam.2023-11-03.20-34-20-424.mp4
> 
> 尝试效率 I/II/III/IV

yeah, I test efficiency I/II/III/IV, It not work as expected
