### ISSUE TITLE
[BUG] option 'hardness:' have some mistakes

### ISSUE THREAD

**Issue by liannai569** [oraxen/oraxen#1092]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0

### Description

minecraft.wiki the stone hardness is 1.5,
![image](https://github.com/oraxen/oraxen/assets/89626087/5bf55e22-3492-44e4-83ae-2be1eb504194)

I set the 'hardness: 8' for  'Mechanics.noteblock.hardness'
![image](https://github.com/oraxen/oraxen/assets/89626087/0ba42007-b559-4994-bd20-aa35d0587c6b)

When the pickaxe not with enchantment of efficieny 5,the hardness is ok, but when the pickaxe have this enchant , the hardness is not work as expected.

https://github.com/oraxen/oraxen/assets/89626087/4533fde9-2c6e-4be5-92a2-52f5a6b5cccc

### Steps to reproduce

enchant have some mistakes for oraxen's option 'hardness'

### Plugin Version

1.163.0

### ProtocolLib Version

![image](https://github.com/oraxen/oraxen/assets/89626087/3ff072fe-fd3c-477b-bdbc-69fff0d2b73b)

### Server Software & Version

1.20.2

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
so the issue is only with tools with effeciency 5?
i know that i make eff5 instabreak blocks due to a bug with it dropping noteblocks and creating ghost blocks etc

**Comment by liannai569** [comment]
> 所以问题只在于效率为 5 的工具？我知道我制作了 EFF5 InstaBreak 块，因为它有一个错误，它删除了 NoteBlock 并创建了 Ghost 块等

effeciency 1-4 is not work as expected, The tools like have no enchant.
