### ISSUE TITLE
[SUGGESTION] Considering to adding an option to hide Dyed furniture's Attribute labels

### ISSUE THREAD

**Issue by liannai569** [oraxen/oraxen#1094]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

![image](https://github.com/oraxen/oraxen/assets/89626087/1aab13d9-bcfc-4634-a25a-db1ad76b1a3e)

the Dyed furniture will show a 'Dyed' attribute in items, consider to adding a option to hide it?

### Reason

make the item more Simplicity

**Comment by Boy0000** [comment]
this is done via itemflags which is already a thing

**Comment by liannai569** [comment]
> 这是通过 ItemFlags 完成的，这已经是一回事了

sorry, I forget to close it...
