### ISSUE TITLE
[BUG] Issue sending pack on Spigot servers

### ISSUE THREAD

**Issue by DeaDorfd** [oraxen/oraxen#1096]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When you join on the Server the Plugin is not setting the resource pack to the user.
This bug exists in version 1.163.0 and 1.164.0

![Bild_2023-11-07_140728287](https://github.com/oraxen/oraxen/assets/50211952/e74fbcb9-2715-495b-b07a-c5221bcde078)

### Steps to reproduce

1. Plugin selfe Build
2. Install the plugin on Server
3. Starting Server
4. Joining Server or run the command /oraxen pack send <UserName>

And thats the bug.

### Plugin Version

1.163.0 and 1.164.0

### ProtocolLib Version

ProtocolLib v5.1.1-SNAPSHOT-673

### Server Software & Version

1.20.2

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
Seems that the check for paper server fails and the issue atm is that your server is a Spigot server
Suggest using Paper but this will be fixed next release

**Comment by DeaDorfd** [comment]
Okay thanks
