### ISSUE TITLE
[BUG] Spigot NoSuchMethod for toCenterLocation()

### ISSUE THREAD

**Issue by DeaDorfd** [oraxen/oraxen#1099]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When opening the Oraxen Inventory, some Textures are null (All Config Items/Blocks with Entity_Display as Mechanic type)
If you are trying to place some of the blocks, they are sending an error in the console.
![Bild_2023-11-08_104018394](https://github.com/oraxen/oraxen/assets/50211952/86d5f549-147f-42ea-a1fa-98ba4eec53cf)

### Steps to reproduce

1. Start Server 
2. Add an Item/Block to config with Entity_Display as Mechanic type
3. Place a block with this type

### Plugin Version

Latest develop build (1.164.0)

### ProtocolLib Version

ProtocolLib v5.1.1-SNAPSHOT-673

### Server Software & Version

Spigot 1.20.2

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
issue is because ur on a Spigot server. I highly suggest that you use Paper over spigot like 50+% of server owners
the issue will be fixed next update though
