### ISSUE TITLE
[BUG] .Git directory missing when building

### ISSUE THREAD

**Issue by TheWeirdCoder** [oraxen/oraxen#1100]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

So, as i'm a bit broke i saw that oraxen offered source code, i tried to build it using intelljidea but i'm getting the error "No .git directory found!". I checked my source code and saw that it came with a .github directory but not .git

I'm not sure what to do to make sure i can build this without that error. Any help is appreciated.

### Steps to reproduce

Download Source Code

Try and compile using intelljidea

no .git directory found!

### Plugin Version

3.163.0 source code version

### ProtocolLib Version

?

### Server Software & Version

?

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by DeaDorfd** [comment]
You must clone the project, and then you have a .git directory

**Comment by TheWeirdCoder** [comment]
Oh okay! <3
