### ISSUE TITLE
[BUG] Bigmining Mechanic handels like normal Pickaxe

### ISSUE THREAD

**Issue by JamesBach93** [oraxen/oraxen#1103]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

The Bigmining Mechanic is actually not working.
It handels like an normal Pickaxe. (With the Config on Reproduce) 

### Steps to reproduce

`dragonsoul_hammer:
  Pack:
    generate_model: false
    model: dragonsoulset/hammer
    custom_model_data: 22
  displayname: Dragonsoul Hammer
  material: NETHERITE_PICKAXE
  lore:
  - <#6f737d>» <#D5D6D8> 5x5x5
  Mechanics:
    bigmining:
      radius: 2
      depth: 3
  unbreakable: true`

### Plugin Version

1.164.0 (Latest from Discord)

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### Server Software & Version

git-Purpur-2086 (MC:1.20.2)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by JamesBach93** [comment]
Edit:
I have shortly installed the Version on my main Servers.
And Update it back on 1.163.0

But now it even works not on 1.163.0 ... :/

**Comment by Boy0000** [comment]
enable call_events in mechanics.yml and itll work
