### ISSUE TITLE
[BUG] Entity_Display is broken

### ISSUE THREAD

**Issue by DeaDorfd** [oraxen/oraxen#1105]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Entity_Display items has a null texture and won't load.
![Bild_2023-11-15_142922244](https://github.com/oraxen/oraxen/assets/50211952/c263b9e3-554f-4a8b-b680-3073c62cef3b)

### Steps to reproduce

Add an Item to Config with Entity_Display and using a Spigot Server on 1.20.2

### Plugin Version

1.164.0

### ProtocolLib Version

5.1.1

### Server Software & Version

Spigot 1.20.2

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
No clue at all what you mean Entity_Display here
Furniture mechanic is the only thing making use of display entities and thats totally irrelevant to rthe item

Im sure this is just a malformed item config. check your console and use the support discord
