### ISSUE TITLE
Please

### ISSUE THREAD

**Issue by Splinmem** [oraxen/oraxen#1106]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Hello, tell me how can I buy this plugin without pay pal?

### Reason

Hello, tell me how can I buy this plugin without pay pal?

**Comment by Boy0000** [comment]
better to ask in the [discord](https://discord.gg/4Qk5kBT9UX) for help
polymart accepts paypal & stripe
