### ISSUE TITLE
[BUG] Some blocks disappear upon placing against an Oraxen block

### ISSUE THREAD

**Issue by Bruhhhh10** [oraxen/oraxen#1109]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Some blocks disappear upon placing against an Oraxen block

### Steps to reproduce

Glass pane disappears when placing on top of Oraxen block
Dead coral fan disappears when placing below Oraxen block
Fence disappears when placing on top of Oraxen block
Banner disappears when placing below Oraxen block
Tripwire hook disappears when placing on top of Oraxen block
Redstone torch disappears when placing below Oraxen block
Seagrass disappears when placing on any side of Oraxen block

Pitcher plant and rose bush (Blocks that have 2 blocks long hitbox) disappear when placing between Oraxen block that dont have enough space

https://github.com/oraxen/oraxen/assets/134551265/34f0b2b3-daab-41b3-9636-135e54c503d5

### Plugin Version

1.164.0

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### Server Software & Version

git-Paper-291 (MC: 1.20.2)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
is this with or without the `Plugin.experimental.nms.block_correction`setting enabled

**Comment by Boy0000** [comment]
fixed in #1128
@Bruhhhh10 if you want to test that PR and double check all the issues.
think most should be fixed now with block correction 👍
