### ISSUE TITLE
[BUG] Breaking oraxen block doesn't show particles

### ISSUE THREAD

**Issue by Bruhhhh10** [oraxen/oraxen#1110]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Title

### Steps to reproduce

Place Oraxen block

Break it in gamemode survival, it shows no particles upon breaking but if you break it while you're on gamemode creative it will show particles.

https://github.com/oraxen/oraxen/assets/134551265/699af7e2-5172-49b9-948d-3148eee8b69e

### Plugin Version

1.164.0

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### Server Software & Version

git-Paper-291 (MC: 1.20.2)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
is this with or without the `Plugin.experimental.nms.block_correction`setting enabled

**Comment by Bruhhhh10** [comment]
Fixed in https://github.com/oraxen/oraxen/pull/1261
