### ISSUE TITLE
[BUG] Break Oraxen block instantly with efficiency 5

### ISSUE THREAD

**Issue by Bruhhhh10** [oraxen/oraxen#1111]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Break Oraxen block instantly with any tool that has efficiency 5

### Steps to reproduce

Get a netherite hoe/shovel/axe/pickaxe anything you can apply efficiency 5 to

Break Oraxen block with said tool, and it will break instantly, even if it's a shovel with efficiency 5 or a netherite hoe with efficiency 5, However let's say that if a netherite pickaxe has any efficiency level that is less than 5, it will not increase the speed at all.

### Plugin Version

1.164.0

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### Server Software & Version

git-Paper-291 (MC: 1.20.2)

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
this has been a repeated issue and isnt inherently solvable
1.164.0 adds a new setting in mechanics.yml which might fix it
