### ISSUE TITLE
[BUG] Breaking an oraxen block holding flint & steel loses durability

### ISSUE THREAD

**Issue by Bruhhhh10** [oraxen/oraxen#1113]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Title

### Steps to reproduce

Get a flint & steel or shield or elytra or any armor piece
Break Oraxen block while holding any of those and it will lose 1 durability, that doesn't happen with regular blocks

Also if you hold a trident and break an Oraxen block, it will get rid of 1 durability instead of 2 (You lose one extra durability if you mine the wrong block with the wrong tool, example if you break a grass block holding a sword it will lose 2 durability, mine it with a shovel and it will lose 1 durability

https://github.com/oraxen/oraxen/assets/134551265/186c213e-b750-45cf-9847-d5757839bd7a

### Plugin Version

1.164.0

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### Server Software & Version

git-Paper-291 (MC: 1.20.2)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
is this with or without the `Plugin.experimental.nms.block_correction`setting enabled

**Comment by Boy0000** [comment]
fixed in #1128 with fixes for other mentioned things with double durab damage on incorrect tool
