### ISSUE TITLE
[BUG] Sound plays only if block destroy stage increases

### ISSUE THREAD

**Issue by Bruhhhh10** [oraxen/oraxen#1114]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Everytime a block destroy stage increases it plays the sound, that doesn't happen for vanilla blocks

### Steps to reproduce

Break an Oraxen block with a decent amount of hardness

Video showcasing this:
https://github.com/oraxen/oraxen/assets/134551265/1f3d108d-25b5-4303-ae96-8fbae8b2858e

Video showcasing this but for a vanilla minecraft block where this doesn't happen:

https://github.com/oraxen/oraxen/assets/134551265/366527b8-5900-4061-bd49-a468feb46c8b

pretty big sound difference

### Plugin Version

1.164.0

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### Server Software & Version

git-Paper-291 (MC: 1.20.2)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
fixed in #1128
