### ISSUE TITLE
[BUG] Sound pitch is different when a block is placed against oraxen block

### ISSUE THREAD

**Issue by Bruhhhh10** [oraxen/oraxen#1115]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Sound pitch is different when a block is placed against oraxen block, but when placed against a regular minecraft block it's normal.

### Steps to reproduce

Place sand/gravel/anvil against an Oraxen block where there's some air in the surface

https://github.com/oraxen/oraxen/assets/134551265/0e75c609-082b-4a17-9d10-75e4e179bedb

### Plugin Version

1.164.0

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### Server Software & Version

git-Paper-291 (MC: 1.20.2)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
is this with or without the `Plugin.experimental.nms.block_correction`setting enabled

**Comment by Bruhhhh10** [comment]
> is this with or without the `Plugin.experimental.nms.block_correction`setting enabled

All of the issues I've made are with nms block correction setting disabled, I didn't even know that was a thing, I've tested every single issue I've made recently with nms block correction enabled, it seems that most of them are fixed and some are not.

With NMS block correction enabled these issues are still occurring:
Can place oraxen block even if inside that block: https://github.com/oraxen/oraxen/issues/1116
Breaking an oraxen block holding flint & steel loses durability: https://github.com/oraxen/oraxen/issues/1113
Sound plays only if block destroy stage increases: https://github.com/oraxen/oraxen/issues/1114
Hand doesn't swing when placing Oraxen block: https://github.com/oraxen/oraxen/issues/1112
Breaking oraxen block doesn't show particles: https://github.com/oraxen/oraxen/issues/1110
Placing block against oraxen block makes a stone place sound: https://github.com/oraxen/oraxen/issues/1107

And these are the issues not occurring with NMS block correction setting enabled:
Rotatable blocks rotations are switched: https://github.com/oraxen/oraxen/issues/1117 (Only for hanging signs, hanging signs can only place on north or south)
Placing wheat on top of Oraxen block turns into seed: https://github.com/oraxen/oraxen/issues/1121
Sound pitch is different when a block is placed against oraxen block: https://github.com/oraxen/oraxen/issues/1115 (It's still broken tho, when you place a gravity block like sand against an Oraxen block, it will instead play a stone place sound instead of a high pitch sand place noise)
