### ISSUE TITLE
[BUG] Rotatable blocks rotations are switched

### ISSUE THREAD

**Issue by Bruhhhh10** [oraxen/oraxen#1117]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Rotatable blocks such as Heads banners signs and hanging signs are switched when placing on Oraxen blocks which can be a little confusing

### Steps to reproduce

I'm facing west and placing all these blocks and they are facing diagonally but when I place it on a normal minecraft block it doesn't, and when I place diagonally it doesn't place it diagonally as expected

https://github.com/oraxen/oraxen/assets/134551265/2b4ec368-eec6-4573-b259-a92ab25d8e9f

### Plugin Version

1.164.0

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### Server Software & Version

git-Paper-291 (MC: 1.20.2)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
nms block correction setting should fix this

**Comment by Bruhhhh10** [comment]
> nms block correction setting should fix this

yeah and also trying to get a banner rotation blockstate to odd numbers like rotation: 3, 5, 7, seems impossible when placing on top of oraxen blocks

**Comment by Boy0000** [comment]
should also be fixed by nms block correction setting
