### ISSUE TITLE
[BUG] Can't place buckets on noteblock

### ISSUE THREAD

**Issue by samue1ch** [oraxen/oraxen#1118]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Unable to place buckets of any type on custom noteblocks

https://github.com/oraxen/oraxen/assets/142220298/6bc4b38c-10f3-49cf-b2f4-e1045b816bad

### Steps to reproduce

Place custom noteblock
Place buckets of any type on the noteblock

### Plugin Version

<img width="213" alt="image" src="https://github.com/oraxen/oraxen/assets/142220298/6726ed47-d3e4-4295-b938-4d6cfa913c53">

### ProtocolLib Version

<img width="371" alt="image" src="https://github.com/oraxen/oraxen/assets/142220298/3e6e58a2-24a2-4823-9b71-c36d4f91f6cc">

### Server Software & Version

<img width="272" alt="image" src="https://github.com/oraxen/oraxen/assets/142220298/048403e2-41e6-4702-98f6-5de346b5868f">

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
is this with or without the `Plugin.experimental.nms.block_correction`setting enabled

**Comment by Bruhhhh10** [comment]
> is this with or without the `Plugin.experimental.nms.block_correction`setting enabled

I tried this with NMS block correction enabled, it works except if you place water/lava bucket while shifting on oraxen block it will prevent you from doing that and same thing happens for trying to pick up the water/lava while sneaking
If you pick up water/lava against an Oraxen block it won't make any sound, and also if you put water/lava against Oraxen block without sneaking it will place it but make a stone place sound
