### ISSUE TITLE
[BUG] Vanilla block drop disappears if a string block is on top

### ISSUE THREAD

**Issue by samue1ch** [oraxen/oraxen#1119]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Vanilla block drop disappears if a string block is on top

https://github.com/oraxen/oraxen/assets/142220298/6fcb55b4-77da-4565-8010-bf1248313a66

### Steps to reproduce

Place a vanilla block
Place a custom string block on top
Break the vanilla block

### Plugin Version

![image](https://github.com/oraxen/oraxen/assets/142220298/253f0057-054e-44d5-959c-e42eb682fd2d)

### ProtocolLib Version

![image](https://github.com/oraxen/oraxen/assets/142220298/a2bb1730-fcc0-4568-9f05-ccca6a231d79)

### Server Software & Version

![image](https://github.com/oraxen/oraxen/assets/142220298/b22c0035-4f25-4b38-96f8-9f25ca3e439f)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
fixed in #1128
