### ISSUE TITLE
[BUG] Placing water on a stringblock, drops string

### ISSUE THREAD

**Issue by samue1ch** [oraxen/oraxen#1120]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Water turns string blocks into regular string item

https://github.com/oraxen/oraxen/assets/142220298/d4149871-d7b1-44ee-9667-cdead37eb5c6

### Steps to reproduce

Place custom string block
Place water on top

### Plugin Version

![image](https://github.com/oraxen/oraxen/assets/142220298/a1917bd7-fd4a-402c-aef1-8c7d8f0382b0)

### ProtocolLib Version

![image](https://github.com/oraxen/oraxen/assets/142220298/abe15a0d-095e-41ef-8fc0-ea71a9767d41)

### Server Software & Version

![image](https://github.com/oraxen/oraxen/assets/142220298/44102a99-70f0-4d52-95dd-086d5eb84ce8)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Bruhhhh10** [comment]
@Boy0000 This no longer happens in the latest version, you can close this.
