### ISSUE TITLE
[BUG] Placing wheat on top of Oraxen block turns into seed

### ISSUE THREAD

**Issue by Bruhhhh10** [oraxen/oraxen#1121]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Placing wheat on Oraxen block turns into wheat seed and it can also grow just fine

### Steps to reproduce

Place Oraxen block
Get wheat, right click on Oraxen block

https://github.com/oraxen/oraxen/assets/134551265/4439ef47-c78f-4000-b286-c58be9737f65

### Plugin Version

1.164.0

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### Server Software & Version

 git-Paper-291 (MC: 1.20.2)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
is this with or without the `Plugin.experimental.nms.block_correction`setting enabled
