### ISSUE TITLE
[BUG] Shapeless recipes ingredients amount not taken in account

### ISSUE THREAD

**Issue by ajeanselme** [oraxen/oraxen#1122]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

The itemstack amount of an ingredient in shapeless recipes can be set to whatever, as long as every ingredient is present in the crafting matrix, the result item is given. 
I don't know if it is intended design or not, but it is pretty inconvenient.

### Steps to reproduce

- Create a shapeless recipe
- Add different ingredients with different amounts
- Observe that the result item is given when at least one of each ingredient is in the matrix, independant of its amount set in config

### Plugin Version

1.164.0

### Server Software & Version

Pufferfish 1.20.2

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
not sure what you mean here? if every item is present in the recipe then yes it will allow you to craft it
if you have 2 in one slot it doesnt matter, recipe ingredients, afaik, always ignore amount

**Comment by ajeanselme** [comment]
Ah yes my bad, I was expecting the recipe to be dependant of the ingredients itemstacks amount.
I didn't know it follows vanilla crafting.
