### ISSUE TITLE
[BUG] Enabling block_correction setting make stringblock can't place

### ISSUE THREAD

**Issue by liannai569** [oraxen/oraxen#1125]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Enabling Block_Correction setting make stringblock can't place ,when set it to false you can place it normally

### Steps to reproduce

https://github.com/oraxen/oraxen/assets/89626087/21a18653-78fe-491d-bc31-c3e44bd50e43

### Plugin Version

1.164.1

### ProtocolLib Version

5.11

### Server Software & Version

1.20.2-Purpur

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
fixed in #1128
