### ISSUE TITLE
[BUG] суслик, твой плагин не компилится, чо за кал, кучу ошибок нассало

### ISSUE THREAD

**Issue by Splinmem** [oraxen/oraxen#1129]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

[BUG] суслик, твой плагин не компилится, чо за кал, кучу ошибок нассало

### Steps to reproduce

ываываыва

### Plugin Version

ывадоьлтывдроаровлдаролываролывапорлд

### ProtocolLib Version

5.10

### Server Software & Version

ывавыаыва

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
bugreports must be in english, I do not speak other languages
