### ISSUE TITLE
[BUG] remove method which doesn't spawn drops

### ISSUE THREAD

**Issue by ThomasWega** [oraxen/oraxen#1134]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Hey! Would it PLEASE be possible to have a method which removes a block but doesn't produce any drops? https://github.com/oraxen/oraxen/blob/master/core/src/main/java/io/th0rgal/oraxen/api/OraxenBlocks.java#L234

It seems kind of stupid to spawn the drops automatically...

### Steps to reproduce

https://github.com/oraxen/oraxen/blob/master/core/src/main/java/io/th0rgal/oraxen/api/OraxenBlocks.java#L234

### Plugin Version

1.160.0

### Server Software & Version

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version
Previous version: git-Paper-246 (MC: 1.20.2)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
`OraxenBlocks.remove(Location, null)` should do just that

**Comment by ThomasWega** [comment]
Thank you. My bad, missed the if check for player completely :D
