### ISSUE TITLE
[BUG] different nbt name in getLoots method than on actual drop

### ISSUE THREAD

**Issue by ThomasWega** [oraxen/oraxen#1135]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

This is what I've found out. The actual item from getDrop#getLoots#getItemStack is producing item with different NBT name then when the item is dropped naturally. I'd need this fixed if possible to allow stacking of these items

This is how naturally dropped item is named
![image](https://github.com/oraxen/oraxen/assets/82312488/759b4807-6bf0-4b5e-aa25-32c27dfd01d8)

This is how item from getDrop#getLoots#getItemStack is named
![image](https://github.com/oraxen/oraxen/assets/82312488/2ff2d0a7-778f-474e-a3df-4ecb67612d88)

You can see that some of the letters are uppercase in the natural version

### Steps to reproduce

compare naturally dropped Item NBT with getDrop#getLoots#getItemStack item NBT

### Plugin Version

1.160.0

### Server Software & Version

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version
Previous version: git-Paper-246 (MC: 1.20.2)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
I'll take a look at this, though the issue should be that it is not "updated".
See you say version is 1.160.0. I believe this is not an issue in 1.164.0 aka latest
Could you try that and see? thanks

**Comment by ThomasWega** [comment]
You'd be right. Completely my bad and very sorry. Thank you, solved
