### ISSUE TITLE
[BUG] Oraxen does not prevent OraxenItems used in base-mc brewing recipes

### ISSUE THREAD

**Issue by Bruhhhh10** [oraxen/oraxen#1136]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

If you make an oraxen item with lets say ID sugar or gold_ingot, you can use the custom item with gold ingot id for piglin trades, or sugar for brewing.

I have Experimental NMS block correction on

### Steps to reproduce

power brewing stand with blaze powder, put water bottles inside put your custom oraxen item that has the id sugar

https://github.com/oraxen/oraxen/assets/134551265/b01bb7c6-2f8a-4f22-9188-6960332a4c92

### Plugin Version

1.165.0

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### Server Software & Version

git-Paper-307 (MC: 1.20.2)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
1. the ID is not gold_ingot, that is the material
2. Block_Correction is irrelevant here
3. yes by default it would not exclude them from brewing recipes

**Comment by Boy0000** [comment]
this should be fixed in 1.168.0 with `Mechanics.misc.allow_in_vanilla_recipes`
