### ISSUE TITLE
[BUG] Quickly swap between tool and it wont have the mining effect

### ISSUE THREAD

**Issue by Bruhhhh10** [oraxen/oraxen#1137]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Quickly swapping between tool the second you start mining the oraxen block, it wont have the mining speed effect but it will still drop the item

NMS Block correction is on
remove mineable tag is set to true

### Steps to reproduce

You can see in this video I start mining the block with fist and then I quickly swap to the netherite pickaxe

https://github.com/oraxen/oraxen/assets/134551265/0b71cf07-6731-409f-9cc1-1be23e034ce4

### Plugin Version

1.165.0

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### Server Software & Version

git-Paper-307 (MC: 1.20.2)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
as this really isnt a big issue and so infrequent it probably will not be fixed
The packet is sent with empty hand so thats all oraxen knows. Since the solution here is to stop and start breaking again
im gonna close this
