### ISSUE TITLE
[BUG] Custom block disappear when placing below/above height limit

### ISSUE THREAD

**Issue by Bruhhhh10** [oraxen/oraxen#1139]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

placing custom block at height limit will do nothing except play a block play sound and get rid of the block

NMS Block correction is on
This also works in 1.164.0

### Steps to reproduce

https://github.com/oraxen/oraxen/assets/134551265/34296847-4696-4b3e-a395-9654cec60acc

Place oraxen block on height limit against a vanilla minecraft block or a custom oraxen block, it will get rid of it

### Plugin Version

1.165.0

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### Server Software & Version

git-Paper-307 (MC: 1.20.2)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
fixed in #1128
