### ISSUE TITLE
[BUG] Block placement on glow lichen/sculk vein is different

### ISSUE THREAD

**Issue by Bruhhhh10** [oraxen/oraxen#1140]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Placing an oraxen block against a glow lichen or sculk vein doesn't replace the sculk vein/glow lichen, it just places the oraxen block beside it

NMS Block correction is on
Same thing happens on 1.164.0

### Steps to reproduce

placing vanilla minecraft block and placing oraxen block on glow lichen and sculk vein

https://github.com/oraxen/oraxen/assets/134551265/6a5f00f4-266d-4231-928e-cc859ccbd802

### Plugin Version

1.165.0

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### Server Software & Version

git-Paper-307 (MC: 1.20.2)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
fixed in #1128
