### ISSUE TITLE
[BUG] Can place blocks in air with custom blocks

### ISSUE THREAD

**Issue by Bruhhhh10** [oraxen/oraxen#1141]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

This bug requires very precise movement but it works, you gotta right click at a timing against an oraxen block so that it places it in the air

NMS Block correction is on

Seems to only happen on 1.165.0 and not 1.164.0

### Steps to reproduce

https://github.com/oraxen/oraxen/assets/134551265/411188c8-6237-408f-96c0-b92e2dea116d

### Plugin Version

1.165.0

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### Server Software & Version

git-Paper-307 (MC: 1.20.2)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
should be fixed in #1153
