### ISSUE TITLE
[BUG] Weird/Wrong pulling animation with bow

### ISSUE THREAD

**Issue by KlausTrophobie** [oraxen/oraxen#1142]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

It seems Oraxen is using one frame of normal bow.json as pulling animation for some reason.
Only if you setting your reference model "charged bow" (POV) in blockbench the same as the _0 one https://i.imgur.com/QT2zA1v.png + https://i.imgur.com/zzSn3YX.png you have a normal pulling animation

p.e. this bow have a very weird pulling animation due to this: https://i.imgur.com/VXmMLA7.png + https://i.imgur.com/lfLFkrN.png

example video: https://www.youtube.com/watch?v=QNRYEZAIIp8

### Steps to reproduce

Use the bow from this pack: https://mcmodels.net/model/ruby-weapons-volume-1/ (weird animation)

The bow from this free set is working well: https://mcmodels.net/model/carnivoret-weapon-set-volume-1/ (bow.json an bow_0.json have the same "charged bow" reference model adjustment.

### Plugin Version

1.164.1

### ProtocolLib Version

5.1.0-SNAPSHOT-653

### Server Software & Version

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version
Previous version: git-Paper-297 (MC: 1.20.2)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
fixed in #1128
