### ISSUE TITLE
[SUGGESTION] Maybe you can add an option 'hand_break' to note_block

### ISSUE THREAD

**Issue by liannai569** [oraxen/oraxen#1143]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

![image](https://github.com/oraxen/oraxen/assets/89626087/609bd570-70db-4e56-b33f-1b7c1ee52ec1)

I created a Custom_Sand, but I found that if I use hand to destroy it, it will not drop anything. I have to use a shovel to drop it.
So I was wondering if we could add an option so that players can break custom_blocks using their hand and get the drops normally.like that:

![image](https://github.com/oraxen/oraxen/assets/89626087/401dbb65-84d4-467b-8d2d-b30fdc6a3412)

Or you can just add a parameter to 'best_tools' to make player use hand to destroy the custom_blocks and drop the items normally.

### Reason

Adding some woods and dirts needed this feature to make the custom block even more perfect

**Comment by Boy0000** [comment]
Remove minimal_type and this should do it

**Comment by liannai569** [comment]
> 删除minimal_type，这应该可以做到

I just tested it and it doesn't work

**Comment by liannai569** [comment]
> a better hardness algorithm would be good instead.

It's true. The current hardness is basically useless. It's so strange.
