### ISSUE TITLE
[SUGGESTION] Add different volume and pitch controls to each sound effect

### ISSUE THREAD

**Issue by liannai569** [oraxen/oraxen#1144]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

![image](https://github.com/oraxen/oraxen/assets/89626087/3190e7dd-75d1-4ad9-976e-658afa96f212)

I discovered a problem today when I was testing a custom block.If all the volume and pitch were the same, that would result in the destruction and placement sounds being probably the same as vanilla, but once you walk up on them you'll notice that the volume is so much higher than in vanilla, and that bothers me.

So my suggestion is to be able to adjust the volume and pitch of different sound effects to better adjust the pitch and volume of custom blocks.

### Reason

Add more customization of volume and pitch, improve custom blocks, and provide better custom sound adjustment methods

**Comment by Boy0000** [comment]
Should be doable rn aswell. Docs should show you an example for it. Iirc it is
break:
  sound:
  volume: 
  pitch:

**Comment by liannai569** [comment]
> Should be doable rn aswell. Docs should show you an example for it. Iirc it is break: sound: volume: pitch:

Where is the documentation? All I saw was the documentation on GitHub. It was too brief.

**Comment by liannai569** [comment]
> Should be doable rn aswell. Docs should show you an example for it. Iirc it is break: sound: volume: pitch:

thx, please close this issue
