### ISSUE TITLE
[SUGGESTION] Option on API to generate texture and apply to any item.

### ISSUE THREAD

**Issue by InterlopersDev** [oraxen/oraxen#1148]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

This would allow server owners and developers to essentially just generate a skin on an item.

### Reason

There are server owners and developers out there who want everything hardcoded rather than configured. Adding this option to Oraxen to just generate any items skin models and render them would be a lifesaver.

**Comment by Boy0000** [comment]
you can manually do this by adding needed files to the pack
you dont "generate textures" you specify a texture or model for a specific material & cmd
