### ISSUE TITLE
[BUG] New MMOItems API changes broke the support

### ISSUE THREAD

**Issue by Taiyou06** [oraxen/oraxen#1151]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

MMOItems had breaking changes recently, the supported format doesnt work in oraxen at the moment.

### Steps to reproduce

1. Create an item in MMOItems
2. Try to apply MMOItem config

### Plugin Version

1.164.1

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### Server Software & Version

Current: git-Purpur-2094 (MC: 1.20.2)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
fixed in #1128
