### ISSUE TITLE
[BUG] AtlasHandler automatically including sprites from PackSlicer in blocks.png

### ISSUE THREAD

**Issue by KlausTrophobie** [oraxen/oraxen#1155]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Bossbar sprites dropping mip level from 4 to zero with gui slicer enabled

`[00:05:30] [Worker-Main-83/WARN]: Texture minecraft:gui/sprites/boss_bar/purple_progress with size 182x5 limits mip level from 4 to 0
[00:05:30] [Worker-Main-83/WARN]: minecraft:textures/atlas/blocks.png: dropping miplevel from 4 to 0, because of minimum power of two: 1`

### Steps to reproduce

Enable gui slicer

### Plugin Version

1.166.0

### ProtocolLib Version

5.1.0-SNAPSHOT-653

### Server Software & Version

This server is running Cheetah version git-Cheetah-"9ccddfd" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 9ccddfd)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by szarkans** [comment]
This is not fixed - gui's added to assets folder directly are still in `blocks.json` atlas, decreasing mip level
