### ISSUE TITLE
[BUG] Cannot place block unless I'm 2 blocks away from it from certain direction

### ISSUE THREAD

**Issue by Bruhhhh10** [oraxen/oraxen#1158]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

title

### Steps to reproduce

Place oraxen block, try placing a minecraft block against oraxen block, if you're placing it from the right direction it wont let u place it, can also try placing oraxen block against minecraft block, it wont place if u in the correct direction and not 2 blocks away

https://github.com/oraxen/oraxen/assets/134551265/7ab46224-6d59-4641-8bf0-2da2e2365c08

Also, offtopic but right clicking while holding anything in ur hand against oraxen block still makes a placement sound

### Plugin Version

1.165.0

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### Server Software & Version

git-Paper-318 (MC: 1.20.2)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
not able to reproduce this

**Comment by Bruhhhh10** [comment]
> not able to reproduce this

@Boy0000 I still can't place blocks in certain directions in 1.167.0 and 1.168.0 in a freshly installed 1.20.4 Paper server
