### ISSUE TITLE
[BUG] Cant place oraxen block on the bottom of the world

### ISSUE THREAD

**Issue by Bruhhhh10** [oraxen/oraxen#1159]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Cant place oraxen block on the bottom of the world, doesn't happen at world height

### Steps to reproduce

place oraxen block on bottom of the world

https://github.com/oraxen/oraxen/assets/134551265/dceb40ee-040f-4602-8de8-351a9147477f

### Plugin Version

1.165.0

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### Server Software & Version

git-Paper-318 (MC: 1.20.2)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
fixed in #1153
