### ISSUE TITLE
[BUG] Breaking oraxen block then disconnecting, oraxen will still think you're mining the block

### ISSUE THREAD

**Issue by minustenchan** [oraxen/oraxen#1161]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

title

### Steps to reproduce

start breaking oraxen block, disconnect the server instantly, join back and u will see it will disappear or show the block destroy stage depending on the hardness

https://github.com/oraxen/oraxen/assets/134551265/bac7d6e6-12cf-4121-a559-bc2a1199c1c0

### Plugin Version

1.165.0

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### Server Software & Version

 git-Paper-318 (MC: 1.20.2)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by bkgktp** [comment]
Dude, why is your name ItemsAdder? You're using Oraxen.
