### ISSUE TITLE
[BUG] ITEM_TOOLS Tag called in ItemUtils on unsupported servers

### ISSUE THREAD

**Issue by Ariouz** [oraxen/oraxen#1163]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Error spamming in console, with block break sound spaming alsowhen breaking custom ore with tool

### Steps to reproduce

- Create custom ore with minimal_type + best tool
- Break the blocks with a tool, any type
- Console spam

### Plugin Version

1.165.1

### ProtocolLib Version

5.1.0

### Server Software & Version

Paper 1.18.2-R0.1-SNAPSHOT

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Ariouz** [comment]
![image](https://github.com/oraxen/oraxen/assets/55002955/eec41062-0040-4312-9d22-8a7ca123606f)

**Comment by Ariouz** [comment]
My ore config:
`angelium_ore:
  displayname: Angelium Ore
  material: PAPER
  Pack:
    generate_model: true
    parent_model: block/cube_all
    textures:
    - angelsky/items/angelium/angelium_ore
    custom_model_data: 1058
  Mechanics:
    noteblock:
      block_sounds:
        place_sound: block.stone.place
        break_sound: block.stone.break
        hit_sound: my.custom.hitsound # Custom sound as defined in Oraxen/sound.yml
        step_sound: my.custom.stepsound # Requires a sound-file in the Oraxen/pack-folder aswell
        fall_sound: my.custom.fallsound
        volume: 0.8 # Default: 0.8
        pitch: 0.8 # Default: 0.8
      custom_variation: 5
      model: angelium_ore
      hardness: 6
      drop:
        silktouch: true
        fortune: true
        minimal_type: DIAMOND
        best_tools:
          - PICKAXE
        loots:
          - oraxen_item: angelium_nugget
            probability: 1.0`

**Comment by Boy0000** [comment]
fixed in #1153 thanks. devbuild is available on discord aswell
