### ISSUE TITLE
[BUG]  If "minimal_type" is missing, the block won't drop the specified loot 

### ISSUE THREAD

**Issue by SebyRo23** [oraxen/oraxen#1165]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

If the "minimal_type" is missing from the noteblock/stringblock configuration, The block won't drop the specified loot

### Steps to reproduce

Remove the "minimal_type" or change the value to null from the configuration

### Plugin Version

1.165.1

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### Server Software & Version

Paper version git-Paper-318 (MC: 1.20.2)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
the block will drop fine without minimal_tool as long as the tool is still correct with best_tools
