### ISSUE TITLE
[BUG] <Multiple resource pack uploads>

### ISSUE THREAD

**Issue by iRama7** [oraxen/oraxen#1168]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

By constantly editing the Oraxen configuration and doing "/o reload all" from time to time, sometimes it is as if the plugin sent one more pack to the client, causing it to sometimes get bugged and an error appears or the client loads more than one pack at a time.
I made a plugin listening to the PlayerResourcePackStatusEvent event with a console output with each of these events, and when reproducing the bug in the console you can see the number of packs that the plugin sends after making several rerloads. I have seen up to 10 packs for a single reload.

![image](https://github.com/oraxen/oraxen/assets/67761349/b6dd3e77-d897-41ea-83c5-f9153c47dbf8)

### Steps to reproduce

Reload the plugin many times with an edit of the texture pack each time.

### Plugin Version

Oraxen version 1.166.0
Authors: th0rgal and boy0000

### ProtocolLib Version

[22:21:43 INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679
[22:21:43 INFO]: Provides read/write access to the Minecraft protocol.
[22:21:43 INFO]: Authors: dmulloy2 and comphenix

### Server Software & Version

[22:21:56 INFO]: Checking version, please wait...
[22:21:56 INFO]: This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
You are running the latest version
Previous version: git-Paper-196 (MC: 1.20.1)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
already fixed in #1166
devbuilds are available on discord
