### ISSUE TITLE
[BUG] Cactus doesn't break when placing oraxen block next to it

### ISSUE THREAD

**Issue by Bruhhhh10** [oraxen/oraxen#1178]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Cactus doesn't break when placing oraxen block next to it
cactus doesn't break when breaking oraxen block next to it aswell, but if you break an oraxen block next to a cactus and theres more oraxen blocks around the cactus it will break

### Steps to reproduce

https://github.com/oraxen/oraxen/assets/134551265/7add67a6-23a6-4312-b3d6-edae5cb22043

https://github.com/oraxen/oraxen/assets/134551265/a15596dd-05e1-487e-8f86-d14d54655851

### Plugin Version

1.166.0

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### Server Software & Version

git-Paper-370 (MC: 1.20.4)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
Not reproducable on 1.168 devbuild so either fixed in 1.167.0 or 1.168.0

https://github.com/oraxen/oraxen/assets/62521371/52ee2b05-8a45-4eda-8a29-073ceeafc7ee
