### ISSUE TITLE
[BUG] Pitch & Volume modifiers don't work properly

### ISSUE THREAD

**Issue by Bruhhhh10** [oraxen/oraxen#1180]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Issue with volume modifier is that it doesn't change the volume of when you place and break the block, but it does change the volume when you place the oraxen block on a block that has #minecraft:replacable block tag

Issue with pitch modifier is that it just doesn't work at all; theres no difference in sound when changing the value to really high or really low

### Steps to reproduce

      block_sounds:
        place_sound: block.stone.place
        break_sound: block.stone.break
        fall_sound: block.stone.fall
        hit_sound: block.stone.hit
        step_sound: block.stone.step
        volume: 0.05
        pitch: 0.1
        
Have this in your oraxen block config for example

https://github.com/oraxen/oraxen/assets/134551265/08118d76-3fc0-433f-a5b8-0ad9b95caf50

(Also I have no idea why it wasn't swinging my hand no matter how I placed the block after placing the block on short grass, I had to /kill myself to fix it)

### Plugin Version

1.166.0

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### Server Software & Version

git-Paper-370 (MC: 1.20.4)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
fixed in 1.167.0
