### ISSUE TITLE
[SUGGESTION] Folia Support

### ISSUE THREAD

**Issue by Euphillya** [oraxen/oraxen#1182]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Is it possible to make Oraxen work with Folia?

### Reason

I helped develop it at one time, and we're still on Oraxen. Currently, no custom item plugin allows this. This would be one of the first plugins to do so, which would add value to the plugin.

**Comment by LoJoSho** [comment]
It's coming in Oraxen 2.0, https://github.com/oraxen/oraxen/tree/2.0/master

**Comment by RootingInLoad** [comment]
Hello ! Any update on this ? I see that 2.0 hasn't been released yet, could I still build a version of Oraxen that'd support Folia ?
Thanks.

**Comment by LoJoSho** [comment]
> Hello ! Any update on this ? I see that 2.0 hasn't been released yet, could I still build a version of Oraxen that'd support Folia ? Thanks.

Oraxen 2.0 looks dead, the developer that has been maintaining the plugin for the past few years (and who was working on 2.0) was kicked off by the original dev (who abandoned it years ago), so I doubt Folia support is on the horizon. There is https://github.com/Stabrinai/oraxen-folia, but that's out of date. Your best bet might be waiting for Nexo todo a full release and add Folia later down the road.

**Comment by RootingInLoad** [comment]
> > Hello ! Any update on this ? I see that 2.0 hasn't been released yet, could I still build a version of Oraxen that'd support Folia ? Thanks.
> 
> Oraxen 2.0 looks dead, the developer that has been maintaining the plugin for the past few years (and who was working on 2.0) was kicked off by the original dev (who abandoned it years ago), so I doubt Folia support is on the horizon. There is https://github.com/Stabrinai/oraxen-folia, but that's out of date. Your best bet might be waiting for Nexo todo a full release and add Folia later down the road.

On the Nexo Discord server, Boy0000 hints at a 1.0 release for Folia support, and considering how fast he's shipping the point releases, we might get it soon 🤷🏻‍♂️ ?

Also, I tried yesterday to utilize the 2.0-SNAPSHOT version of the Oraxen API as it's supposed to support Folia, though I couldn't build my plugin... Have you tried that already ?
