### ISSUE TITLE
Breaking custom block fail

### ISSUE THREAD

**Issue by AllayRPG** [oraxen/oraxen#1189]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

It is not possible to strike ore. The process of breaking will begin when he is at the end, he starts again and then knocks him out. (Block is not knocked out, so the ore is not specified)

### Steps to reproduce

It is not possible to strike ore. The process of breaking will begin when he is at the end, he starts again and then knocks him out. (Block is not knocked out, so the ore is not specified)

### Plugin Version

Oraxen version: 1.165.1!

### ProtocolLib Version

ProtocolLib version: 5.1.0-SNAPSHOT-652

### Server Software & Version

Velocity 1.19.4 version 

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
please ensure you use latest oraxen
also this just sounds like something is preventing the blocks from being broken
for example worldguard or another protection plugin

**Comment by AllayRPG** [comment]
![image](https://github.com/oraxen/oraxen/assets/132414911/96825774-7405-43cc-aa9d-deb10cbd01ec)
https://i.imgur.com/3JPTkh5.mp4

**Comment by AllayRPG** [comment]
They can break blocks like plain ore, but not oraxen custom blocks.

**Comment by Boy0000** [comment]
unable to reproduce this sadly, some other plugin is probably intefering
