### ISSUE TITLE
[BUG] Vanilla noteblocks no longer trigger observers when interacted with

### ISSUE THREAD

**Issue by Grafnus** [oraxen/oraxen#1191]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When an observer is observing a normal/vanilla noteblock, it only detects any change when the noteblock is mined. Not when I right-click it.

### Steps to reproduce

Let an observer observe a noteblock and power a redstonelamp.

The Lamp only lights up when the noteblock is mined, not when right-clicked.

### Plugin Version

Oraxen version 1.167.0
Authors: th0rgal and boy0000

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-665
Provides read/write access to the Minecraft protocol.
Authors: dmulloy2 and comphenix

### Server Software & Version

Current: git-Purpur-2032 (MC: 1.20.1)*

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
When Oraxens NoteBlock mechanic is enabled, no vanilla behaviour should be expected to fully work
Oraxen cancels everything to properly allow for custom blocks
In most cases you have to choose between custom blocks and vanilla noteblock functionality
Can be disabled like most mechanics, in mechanics.yml

**Comment by Grafnus** [comment]
Thanks for the swift answer, although I am sad to hear that. There isn't a way to make it possible in the future?

**Comment by Boy0000** [comment]
Might be but manually handling redstone is not performant or optimal at all
For now there are no plans to attempt to fully restore its behaviour
