### ISSUE TITLE
[BUG] sound bug is back

### ISSUE THREAD

**Issue by Castiella** [oraxen/oraxen#1192]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

oraxen-1.167.0.jar

bug report as requested

### Steps to reproduce

Sound bug is back, annoying sound loop when breaking blocks

### Plugin Version

oraxen-1.167.0.jar

### ProtocolLib Version

[16:48:47 INFO]: ProtocolLib version 5.1.1-SNAPSHOT-669

### Server Software & Version

This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

config example

```board_2:
  displayname: <white>Board
  material: PAPER
  Mechanics:
    furniture:
      type: DISPLAY_ENTITY
      hitbox:
        width: 1
        height: 2
      display_entity_properties:
        display_transform: FIXED
      drop:
        silktouch: false
        loots:
        - oraxen_item: board_2
          probability: 1.0
  Pack:
    generate_model: false
    model: med_gain/board_2
    custom_model_data: 3010```

**Comment by Dreig-Michihi** [comment]
1.173.0, looping break sound bug still happens. I have no any idea how it can be reproduced, it just happens on our pvp and duel arenas after some time. May be it could be some cancelled by other plugins events?
The looping break block sound stops, when you hit the bugged block again.
[https://youtu.be/YUV4i84tupA](url)
