### ISSUE TITLE
[BUG] Mythic Mobs Drops

### ISSUE THREAD

**Issue by THEzenith1** [oraxen/oraxen#1194]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

On the latest version of Oraxen and Mythic mobs, in MC 1.20.2, drops with custom items in Mythic mobs do not work. I have reverted my Oraxen version to 1.166.0, and the bug was resolved, leading me to conclude that it is a bug with Oraxen 1.167.0. The bug did not appear until I upgraded. 

### Steps to reproduce

1. Use the latest version of Mythic Mobs, Oraxen, and MC 1.20.2 
2.  Try and add a drop with an oraxen item to a mythic mob

### Plugin Version

1.167.0

### ProtocolLib Version

5.1.0

### Server Software & Version

1.20.2

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
Tested this on latest dev-release of MythicMobs and drops just fine
