### ISSUE TITLE
[BUG] Can't upload resourcepack with 100mb+ filesize

### ISSUE THREAD

**Issue by DaddyRobLIVE** [oraxen/oraxen#1199]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

My pack contains ton of .ogg files mostly songs converted to .ogg to be played with music discs that's why my resourcepack is quite big. I keep getting the error below no matter how much I try.

![image](https://github.com/oraxen/oraxen/assets/109517972/ebd782f8-5f33-4966-9941-106286b82903)
tons

### Steps to reproduce

1. Compile a resource pack that's around 100mb+
2. Do /o reload all
3. Wait for the error to appear

### Plugin Version

Oraxen version: 1.167.0

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-669

### Server Software & Version

This server is running Pufferfish version git-Pufferfish-34 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: bc89152 on HEAD)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
Polymath limit was set to 100MB, should be increasing shortly 👍
