### ISSUE TITLE
[SUGGESTION] support FabledSkyBlock

### ISSUE THREAD

**Issue by MrDzharik** [oraxen/oraxen#1200]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

I use the plugin FabledSkyBlock + Oraxen for my SkyBlock server, recently I have a problem that furniture can be placed on other people's islands, I would like to fix this problem.

### Reason

This greatly improved the gaming experience for players, as it would be impossible for other players to put furniture on their own islands

**Comment by Boy0000** [comment]
as far as i can see, this plugin does not have any public API oraxen can use
Oraxen will check the generic events for placing blocks normally
If they are cancelled properly this should not be an issue
