### ISSUE TITLE
[BUG] <name for bug>

### ISSUE THREAD

**Issue by Aness6040** [oraxen/oraxen#1202]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

I got this error
> [13:34:23 INFO]: §xO§xr§xa§xx§xe§xn§x | §xThe resource pack has not been uploaded to the server. Usually this is due to an excessive size.
> [13:34:23 WARN]: org.apache.http.conn.HttpHostConnectException: Connect to atlas.oraxen.com:443 [atlas.oraxen.com/5.135.152.216] failed: Connection refused: connect
> [13:34:23 WARN]:        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
> [13:34:23 WARN]:        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
> [13:34:23 WARN]:        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
> [13:34:23 WARN]:        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
> [13:34:23 WARN]:        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
> [13:34:23 WARN]:        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
> [13:34:23 WARN]:        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
> [13:34:23 WARN]:        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
> [13:34:23 WARN]:        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
> [13:34:23 WARN]:        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
> [13:34:23 WARN]:        at io.th0rgal.oraxen.pack.upload.hosts.Polymath.uploadPack(Polymath.java:42)
> [13:34:23 WARN]:        at io.th0rgal.oraxen.pack.upload.UploadManager.lambda$uploadAsyncAndSendToPlayers$1(UploadManager.java:66)
> [13:34:23 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:78)
> [13:34:23 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:55)
> [13:34:23 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> [13:34:23 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> [13:34:23 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
> [13:34:23 WARN]: Caused by: java.net.ConnectException: Connection refused: connect
> [13:34:23 WARN]:        at java.base/sun.nio.ch.Net.connect0(Native Method)
> [13:34:23 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:579)
> [13:34:23 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:568)
> [13:34:23 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
> [13:34:23 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
> [13:34:23 WARN]:        at java.base/java.net.Socket.connect(Socket.java:633)
> [13:34:23 WARN]:        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
> [13:34:23 WARN]:        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
> [13:34:23 WARN]:        ... 16 more
> [13:34:23 INFO]: §xO§xr§xa§xx§xe§xn§x | §xResourcepack not uploaded

The Rescource Pack is not uploaded and i didn't added anything i tried to delete all things and re-install it too

### Steps to reproduce

idk

### Plugin Version

# Oraxen [1.167.0](https://gleaks.pro/redirect?to=aHR0cHM6Ly9naXRodWIuY29tL29yYXhlbi9vcmF4ZW4vcmVsZWFzZXMvdGFnLzEuMTY3LjA=)

### ProtocolLib Version

5.1.0

### Server Software & Version

This server is running Mohist version 1.20.1-550 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT, Forge version 47.2.20, NeoForge version 47.2.20)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
Resourcepack server is down, see https://discord.com/channels/480068531132563476/613672597699297291/1199689297381556244
for info
