### ISSUE TITLE
[BUG] Pack loading multiple times

### ISSUE THREAD

**Issue by Emibergo02** [oraxen/oraxen#1204]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When reloading the pack, the player receives the new one but also the previous pack
[More info](https://discord.com/channels/480068531132563476/613680450761785344/1199741866795597914)

### Steps to reproduce

Steps To Reproduce:
1. install a new velocity+paper with oraxen
2. remove random item & reload
3. logout
4. rejoin and it sends you the first default pack and the modified one

### Plugin Version

1.167.0

### Server Software & Version

Paper 1.20.4

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
There really isnt anything i can do about this
Oraxen always just sends 1 pack
When the hash changes, a new pack is uploaded and sent

But velocity is caching the first pack and sending it aswell apparently due to new 1.20.4 api
Oraxen itself would not prevent this sadly

**Comment by Boy0000** [comment]
should be fixed in latest push to #1186 
someone made me aware of reloading re-registering stuff 👍
