### ISSUE TITLE
[BUG] WorldEdit furniture support not working

### ISSUE THREAD

**Issue by KlausTrophobie** [oraxen/oraxen#1205]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

copy/paste just pastes some barrier blocks and //cut leaves display entities without barriers

https://www.youtube.com/watch?v=nBHF7cTulVY

### Steps to reproduce

just use //copy, //paste and/or //cut

### Plugin Version

1.168.0 latest Dev-Build

### ProtocolLib Version

5.0.0

### Server Software & Version

paper 1.20.1-196

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
Works fine, u have to ensure ur copying the entity aswell

https://github.com/oraxen/oraxen/assets/62521371/612adb28-e248-4690-b733-aafd0dc9676b
