### ISSUE TITLE
[BUG] A SUPER easy hardness bypass.

### ISSUE THREAD

**Issue by pernydev** [oraxen/oraxen#1209]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

You can easily bypass hardness by pressing down left click while looking at the block, then moving your mouse so you are just looking at air and then moving it back to the block. All this while holding down left click.

### Steps to reproduce

By pressing down left click while looking at the block, then moving your mouse so you are just looking at air and then moving it back to the block. All this while holding down left click.

### Plugin Version

1.167.0

### ProtocolLib Version

5.2.0

### Server Software & Version

Purpur 2127 (1.20.4)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
fixed in 2.0
