### ISSUE TITLE
[BUG] Dyed furniture does not keep its color upon placing

### ISSUE THREAD

**Issue by lucian929** [oraxen/oraxen#1214]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When you dye a furniture item (via /o dye or other methods), and then place it, the furniture will place as the normal color defined in its item config. Additionally, when you break the furniture, it will also be the base color.

### Steps to reproduce

1) make a dyeable furniture item
2) dye it with /o dye
3) place the item - bug
4) break the item - bug

### Plugin Version

1.168.0

### Server Software & Version

1.20.2

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by jackboi03** [comment]
Can reproduce this
