### ISSUE TITLE
[BUG] Cannot reference dependency for oraxen 1.168.0 version

### ISSUE THREAD

**Issue by Uni0305** [oraxen/oraxen#1216]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

There appears to be no problem with the dependency reference in version 1.167.0, so it appears that the dependency was not deployed properly in the last update.

![2024-01-29 17 38 41](https://github.com/oraxen/oraxen/assets/71868623/b10eaf10-773e-45c6-af64-cb346c73666c)
![2024-01-29 17 38 46](https://github.com/oraxen/oraxen/assets/71868623/6c15164a-7830-4bfd-be0f-2d46afa8b616)

### Steps to reproduce

1. In the Gradle Kotlin DSL environment, configure the repository and dependencies in the project as shown below in the `build.gradle.kts` file.

```kts
repositories {
    maven("https://repo.oraxen.com/releases")
}

dependencies {
    compileOnly("io.th0rgal:oraxen:1.168.0")
}
```

2. Reload gradle to apply changes

### Plugin Version

```
[17:11:27 INFO]: Oraxen version 1.168.0
[17:11:27 INFO]: Authors: th0rgal and boy0000
```

### ProtocolLib Version

This issue is not related to ProtocolLib version

### Server Software & Version

This issue is not related to server software version

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
this should be fixed now @Uni0305 if u could confirm

**Comment by Uni0305** [comment]
The class reference issue seems to have been resolved. thank you!
