### ISSUE TITLE
[SUGGESTION] Add furniture rotation snap limit (90 degrees)

### ISSUE THREAD

**Issue by quillincn** [oraxen/oraxen#1219]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Add parameters to the furniture mechanics to prevent diagonal placement, so they only snap at 90 degrees, like vanilla blocks.

### Reason

A lot of possible furniture had ~block shape, so when you try to put it straight, it can rotate diagonally, which is really annoying. And in general, it's going to be really useful to decide how your furniture spouse to be placed, depending on what exactly you're trying to create.

https://streamable.com/20kjid

**Comment by liannai569** [comment]
yes,we need this option to make furnitures only place like a real block,Boy!!!!! must add this option thx!!!!
