### ISSUE TITLE
[SUGGESTION] Adding the 'falling_block: true' option for custom_block(note and string) 

### ISSUE THREAD

**Issue by liannai569** [oraxen/oraxen#1223]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

I make a yellow_sand block of oraxen's custom_block but It can't falling down, not like a real block,Maybe we can add this machiance for custom_block for user to create a falling_block

### Reason

![image](https://github.com/oraxen/oraxen/assets/89626087/4bc13621-b3ca-4147-8868-2f528cd36ae2)

Really need this funtion,Thx boy!!!!!!

**Comment by Boy0000** [comment]
![image](https://github.com/oraxen/oraxen/assets/62521371/e0931bc2-922c-4e95-9733-eff6518e37c8)

it is a thing already

**Comment by liannai569** [comment]
> ![image](https://private-user-images.githubusercontent.com/62521371/302398606-e0931bc2-922c-4e95-9733-eff6518e37c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNTk2NDQsIm5iZiI6MTcwNzE1OTM0NCwicGF0aCI6Ii82MjUyMTM3MS8zMDIzOTg2MDYtZTA5MzFiYzItOTIyYy00ZTk1LTk3MzMtZWZmNjUxOGUzN2M4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDE4NTU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5NDFiZmI4NGJiYjEwMWY2NDA4OTE4MTE2MjllZjM4ZTQ3MGZhYTRjM2FmOTZhNTA0ZDc2NzI0NjQ0ZjM1OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MCawQMPIXTFuotMOIErhFDVLdGmLT2vpC3C4LzM9nJM)
> 
> 这已经是一回事了

![image](https://github.com/oraxen/oraxen/assets/89626087/3d206752-8446-4c46-bf08-991c0989587f)
this is a bug right?
