### ISSUE TITLE
[SUGGESTION] add the option 'is_falling' for string_block

### ISSUE THREAD

**Issue by liannai569** [oraxen/oraxen#1224]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

the string_block can not use 'is_falling' option , please add this option for it

### Reason

we can make a block like falling_leave in the grass_block,and player break the grass_block the string_block also falling down into the next block

**Comment by Boy0000** [comment]
not planning on adding this sorry
no vanilla "plant" type block has this feature so
