### ISSUE TITLE
[BUG] the option of 'is_falling' seems has some bugs

### ISSUE THREAD

**Issue by liannai569** [oraxen/oraxen#1225]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

the option 'is_falling' seems has some bugs,like this
![image](https://github.com/oraxen/oraxen/assets/89626087/26c3bbee-716e-4e73-9819-be6d914c58eb)
It didnt like sand,maybe we can make it more like vanllia sand

### Steps to reproduce

is only a small bug

### Plugin Version

![image](https://github.com/oraxen/oraxen/assets/89626087/24c9f73c-0b8a-4920-a765-d2400959fda2)

### ProtocolLib Version

5.1

### Server Software & Version

1.20.2

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
please do include the config of custom blocks when making a bugreport
the more info you provide, the faster i can fix stuff

**Comment by liannai569** [comment]
> 在制作错误报告时，请务必包含自定义块的配置，您提供的信息越多，我修复东西的速度就越快

![image](https://github.com/oraxen/oraxen/assets/89626087/6c7d0769-719e-4af6-886b-c048c8feb4f9)
Sorry,I post it in discord , forget post in here
