### ISSUE TITLE
[BUG] StringBlocks able to be placed ontop of eachother

### ISSUE THREAD

**Issue by liannai569** [oraxen/oraxen#1227]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

When you place a string_block on top of a string_block, it will place another one on top. Hopefully an option will be added so that it cannot be placed on top of a string_block.
![image](https://github.com/oraxen/oraxen/assets/89626087/5f33608b-0eba-4878-889f-1166c40632f8)

If possible, it is recommended to add a stacking function so that one string_block can be stacked into other string_blocks to facilitate the creation of some interesting things, such as stone piles. Small stones can be stacked into large stones.
![image](https://github.com/oraxen/oraxen/assets/89626087/fdbb3859-220c-4ffb-a63f-238ce560ab39)

### Reason

make the string_block better than now

**Comment by Boy0000** [comment]
fixed in 2.0

**Comment by liannai569** [comment]
> 已在 2.0 中修复

maybe can fix 1.X
