### ISSUE TITLE
[SUGGESTION] Beacons & Custom Blocks

### ISSUE THREAD

**Issue by Person0z** [oraxen/oraxen#1228]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

A way to allow custom blocks to activate beacons, for example how diamond blocks can activate beacons and give effects from the beacon with the levels too!

### Reason

Because I'm adding custom blocks in my server that are very hard to get, so its gonna give players something to grind for and do to show that they are better than everyone else.

**Comment by Boy0000** [comment]
This seems to only really be feasable by:
1. Making a datapack that adds NOTEBLOCK to the BEACON_BASE_BLOCKS tag
2. This means the beacon will "activate" for all noteblocks
3. cancel the beacon giving the players effects unless the base-pyramid are either vanilla or valid custom blocks
