### ISSUE TITLE
[SUGGESTION] Rename items with a rainbow Wobble/Jump effect 

### ISSUE THREAD

**Issue by Yurkhun** [oraxen/oraxen#1229]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

would be nice to have a `/o rename` command to rename items with special effects like _itemsadder_ have
![rj](https://github.com/oraxen/oraxen/assets/95500637/0d1eb1e4-a87b-4562-b51b-cfb177e92d5b)
![assets_-M28TcKgSDvuFN510qye_-MlL8i6c68MqtctzLv80_-MlLAOKvRe4aT8SHOW9u_rw_chat-ezgif com-webp-to-gif-converter](https://github.com/oraxen/oraxen/assets/95500637/e662c27b-33cb-4848-870f-324bc2be0cd9)

### Reason

would be a nice feature for oraxen to have

**Comment by Boy0000** [comment]
Due to compativility with other plugins like happyhud i do not plan to add this
