### ISSUE TITLE
[BUG] PackSlicer overwriting recipe_book.png leading to incomplete texture on >1.20.2

### ISSUE THREAD

**Issue by BiallyDEV** [oraxen/oraxen#1230]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Custom GUI textures not work properly, probably because of sliced textures replace the one that I put in the pack. Even when in setting.yml slicing of gui textures is on false "texture_slicer: false"
![2024-02-08_14 30 47](https://github.com/oraxen/oraxen/assets/107373572/efc741db-195d-49c5-84f3-508ae7c7da28)

### Steps to reproduce

I can provide you in dm on discord a pack that I bought so you can put it on your test server and test by urself

### Plugin Version

1.168.0

### ProtocolLib Version

5.1.0

### Server Software & Version

Paper 1.20.1 Build #196

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by BiallyDEV** [comment]
Found a fix, after disabling slicing in setting.yml, needs to delete all the textures and restart server, then drop back new textures and it's working

**Comment by Boy0000** [comment]
This is still a bug with the splitter and ahould be fixed. Issue is only with the recipe book as it still uses the old filepath unlike modt other things
