### ISSUE TITLE
[BUG] Blocks, NoteBlock, Mining, BUGS

### ISSUE THREAD

**Issue by TuhkanenS** [oraxen/oraxen#1231]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

?

https://github.com/oraxen/oraxen/assets/109818371/b388146c-865f-4770-b0a1-fab007a0225f

### Steps to reproduce

If you quickly break the blocks, it happens that they simply disappear and become invisible and do not appear, only when you click on the block with the right button of Misha, it appears, This happens very often.
It happens that when you mine blocks that are vertically placed, they can become note blocks

### Plugin Version

ORAXEN 1.168.0

### ProtocolLib Version

5.2.0-SNAPSHOT-678

### Server Software & Version

This server is running Paper version git-Paper-416 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 581fb30)

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
fixed in 2.0
