### ISSUE TITLE
[BUG] string

### ISSUE THREAD

**Issue by TuhkanenS** [oraxen/oraxen#1232]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When you destroy a block of threads, it has barrier particles, when you put a thread it is invisible, but when you put a thread next to another thread, they become visible for a second and become invisible again

https://github.com/oraxen/oraxen/assets/109818371/53b3c2ec-f1e5-4ac0-9042-78ab66426082

### Steps to reproduce

Is this my problem in the texture pack or a plugin error?

### Plugin Version

1.168.0

### ProtocolLib Version

5.2.0-SNAPSHOT

### Server Software & Version

This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
this is just client side issues, nothing oraxen can 100% fix
the client predicts a block update, and a tick later is told the real blockdata and changes back
this is sadly afaik just a limitation of custom blocks

**Comment by TuhkanenS** [comment]
Can I write here about all the errors that I found?

**Comment by Boy0000** [comment]
i closed this because as i said tghis is client side flicker that i cant really fix
if there is some other bug thats with oraxen, open a separate bugreport for it

**Comment by TuhkanenS** [comment]
okay
