### ISSUE TITLE
[BUG] Custom blocks have the bugs about sound and  place

### ISSUE THREAD

**Issue by liannai569** [oraxen/oraxen#1234]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

https://github.com/oraxen/oraxen/assets/89626087/7a06abc3-4ad7-49b7-a17d-6206037a8e2e

When you place the custom_block when you sneak,the hand will have no action of place

https://github.com/oraxen/oraxen/assets/89626087/32a31094-a702-434f-a15c-20165b8b8fee
When you place a vanllia block in the custom_block,the place sound will disappear

### Steps to reproduce

some bug of the custom_block, pls fix it ~ boy~

### Plugin Version

![image](https://github.com/oraxen/oraxen/assets/89626087/599a7b7b-382a-4331-8dd0-e0a202975280)

### ProtocolLib Version

5.11

### Server Software & Version

1.20.2

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Bruhhhh10** [comment]
"When you place a vanilla block in the custom block, the place sound will disappear" has been fixed in https://github.com/oraxen/oraxen/pull/1261
