### ISSUE TITLE
[BUG] Spigot broke EntityDamageByEntityEvent

### ISSUE THREAD

**Issue by Euphillya** [oraxen/oraxen#1235]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Spigot broke EntityDamageByEntityEvent by changing its implementation.

Link: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/be72314ca31c7628c9a4cf0cba695b2d7c1cee47#src/main/java/org/bukkit/event/entity/EntityDamageByEntityEvent.java

```md
java.lang.NoSuchMethodError: 'void org.bukkit.event.entity.EntityDamageByEntityEvent.<init>(org.bukkit.entity.Entity, org.bukkit.entity.Entity, org.bukkit.event.entity.EntityDamageEvent$DamageCause, double)
```

### Steps to reproduce

Use latest version Spigot

### Plugin Version

all version impacted

### Server Software & Version

Spigot latest build (2 days)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
Yeah noticed this in another project of mine. Very annoying change but it will be sorted in the next update
