### ISSUE TITLE
[BUG] Formatting color codes in a translation file

### ISSUE THREAD

**Issue by Nalurione** [oraxen/oraxen#1236]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

I have encountered a problem, probably related to the generation of the language file. For some strange reason, the formatting color changes only in the first line with the color code, all other lines are ignored by the color code. I've tried different versions of both HTML and § and <gold>. The translation changes, but the color only changes once.
![изображение_2024-02-13_221506928](https://github.com/oraxen/oraxen/assets/101350325/7f03bd27-dc2d-40cc-9ccb-0017daaa90d8)
![изображение_2024-02-13_221516808](https://github.com/oraxen/oraxen/assets/101350325/83db0de8-96a8-438d-9ca0-0919e868e108)

### Steps to reproduce

Just create a translation file or make a translation in a global file and specify the color codes

### Plugin Version

1.168.0

### ProtocolLib Version

5.1.0

### Server Software & Version

Paper version git-Paper-100 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by NekrosBurek** [comment]
Just confirming this is happening on latest versions as well, bumping this in hope this will be fixed soon

**Comment by Boy0000** [comment]
fixed next update, sorry for the wait 👍
