### ISSUE TITLE
[BUG] Strings don't work correctly

### ISSUE THREAD

**Issue by NatBiscoito** [oraxen/oraxen#1238]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

I cannot use normal Strings In my server, I already enabled blockupdates in paper-global.yml and showed the error to the developer

https://imgur.com/a/8Dgk6yz

### Steps to reproduce

The strings seem to just face only one side when I put them on the ground, and they don't work with TripWire Hook

### Plugin Version

Oraxen version 1.169.0

### ProtocolLib Version

ProtocolLib version 5.1.0

### Server Software & Version

Current: git-Purpur-2062 (MC: 1.20.1)*
Previous: git-Purpur-2044 (MC: 1.20.1)
* You are running the latest version

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by haha44444** [comment]
me too
:(

**Comment by Boy0000** [comment]
this is not a bug, stringblock mechanic causes this, use discord for further support
