### ISSUE TITLE
[BUG] Issues with option "brightness" 

### ISSUE THREAD

**Issue by Ergail** [oraxen/oraxen#1241]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Hi, very happy with the latest version of Oraxen with the light functionality on furnitures I'm however coming to share a problem I've encountered with DISPLAY_ENTITY and the "brightness" options which don't seem to work at all for me. From the moment I add the variable to a furniture, it always appears very dark. Whether the variable is set to 0-15 on "block" or "sky" makes no difference at all.

### Steps to reproduce

By simply adding the following configuration to a furniture, it will appear completely dark. As if the emissive light value were set to 0, regardless of the value given to "block" or "sky".

      display_entity_properties:
        brightness:
          block: 15
          sky: 0

I tried, for example, with the following configuration:

https://pastebin.com/NawXGwij

### Plugin Version

Oraxen - 1.169.0

### ProtocolLib Version

ProtocolLib - 5.1.1-SNAPSHOT-673

### Server Software & Version

Paper version git-Paper-318 (MC: 1.20.2)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
works just fine for me
you have block not block_light as your option here so yes will not set it

https://github.com/oraxen/oraxen/assets/62521371/7189ac7d-6049-4108-9cb3-e7ce6bc30ad6
