### ISSUE TITLE
[BUG] After server resource pack load, player can't walk

### ISSUE THREAD

**Issue by akiakyo** [oraxen/oraxen#1244]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

After resouce pack load, I can't walk

### Steps to reproduce

I think to reproduce this was /flyspeed 10 pr /walkspeed 10

### Plugin Version

1.168.0

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### Server Software & Version

This server is running Paper version git-Paper-409 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 9e171ef)
You are 15 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-196 (MC: 1.20.1)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
unable to reproduce this, likely to be another plugin
