### ISSUE TITLE
[SUGGESTION] Misc-Mechanic disable-vanilla-recipes count towards furnaces etc

### ISSUE THREAD

**Issue by lelegore** [oraxen/oraxen#1245]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

A flag for item so that the item cannot be smelted, or be put into a container (furnace, grindstone, etc) would be really useful

### Reason

If user want to make custom item without resourcepack, for example cobblestone.
the flag would be useful so that the item cannot be smelted or just cannot be put in a furnace.

why not just use paper, bamboo, (unsmeltable item)? because i dont want it just to be the same item base, i need the item to have variety even if the player cannot see it

**Comment by Boy0000** [comment]
Cannot make an itemflag for something like this, it would need to be in the misc mechanic
