### ISSUE TITLE
[BUG] Pack Merging Error

### ISSUE THREAD

**Issue by goldenkuky209** [oraxen/oraxen#1246]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Tried merging my texturepack with Oraxen's. Documentation says to just "copy your packs assets-folder and paste it into Oraxen/pack/assets." but I did that and now the texturepack doesn't even load, saying there's been an unexpected error. The files in the pack.zip are also corrupted if I try to open them.

https://pastebin.com/TY6ZrTDh

### Steps to reproduce

Add in texturepack to Oraxen/pack/assets and reload.

### Plugin Version

1.169.0

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### Server Software & Version

git-Paper-379 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
Suggest stopping by the discord to get support as this is most likely just a bad merge and not an inherent bug 👍

**Comment by goldenkuky209** [comment]
Yea I did stop by the discord, I just opened a ticket on here just in case the help chat isn't that active.

**Comment by Boy0000** [comment]
If you have access to the proper support channel it is very active. The "unverified" non-buyer support isnt very active no

**Comment by goldenkuky209** [comment]
Do I need to verify my purchase for that one?
