### ISSUE TITLE
[SUGGESTION] Dye should work with FireworkStars

### ISSUE THREAD

**Issue by itsMarkiS** [oraxen/oraxen#1252]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

firework stars has support for custom hex colors so why not???
the system used in the NBT is decimal

/give @p firework_star{Explosion:{Colors:[I;2437522],Type:0b}}

### Reason

would allow new furnitures and a new type of dyable item to avoid conflicts and other stuff

**Comment by Boy0000** [comment]
There is already plenty of choices to where conflicts should never happen
Compared to others, firework star is alot morew annoying to deal with due to color being in the effect
Not planning on adding this
