### ISSUE TITLE
[BUG] Oraxen loads texture pack onto user's client but client instantly crashes with "Can't Load Default Font"

### ISSUE THREAD

**Issue by 01maxzie** [oraxen/oraxen#1258]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

I'm having issues with Oraxen. Every time I run it, it works but as soon as the texture pack finishes loading, everything gets replaced by [], and the game crashes.

I'm using this plugin so I can put furniture in my server for my cousins who really want them, so please respond ASAP.

### Steps to reproduce

1. Install Oraxen
2. Use it on a minecraft server, or in my case Falix
3. Start the server
4. Join the server and accept the pack

### Plugin Version

Oraxen version 1.168.0

### ProtocolLib Version

ProtocolLib version 5.1.0

### Server Software & Version

This server is running Mohist version 1.20.1-580 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT, Forge version 47.2.20, NeoForge version 47.1.79)

### How breaking is the bug?

Breaking Bug - Plugin unusable

### Details
I was going to originally use the latest one, but it kept disabling itself so I used 1.168.0

**Comment by Boy0000** [comment]
you have a malformed resourcepack, go to the discord for proper support 👍
