### ISSUE TITLE
[BUG] Oraxen Load first then mmoitems

### ISSUE THREAD

**Issue by JickJacks** [oraxen/oraxen#1266]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Oraxen load first mmoitems i think and the oraxen item connected with MMoitems breaks 

### Steps to reproduce

create an item with mmoitems like this 
mythril:
  displayname: '<white>ꐱ 뀇 ꐱLingotto di Mythril'
  mmoitem:
    type: MATERIAL

    id: MYTHRIL_INGOT
    
    Then  load the server 

### Plugin Version

Oraxen | Oraxen version: 1.170.1!

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### Server Software & Version

Current: git-Purpur-2136 (MC: 1.20.4)*

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
as of 1.170.0 oraxen loads before the world loads
Oraxen has a dependency on MMOITems but if MMOITEMS loads POSTWORLD then this would be the issue

**Comment by MRX580** [comment]
I have also this problem, here is my logs
[latest.log](https://github.com/oraxen/oraxen/files/14579802/latest.log)

**Comment by lucian929** [comment]
Similarly, this issue happens with MythicCrucible item support. Confirmed same oraxen version, crucible 2.0 (stable)

**Comment by Boy0000** [comment]
fixed in #1291
