### ISSUE TITLE
[SUGGESTION] Auto-Generation of custom_variation

### ISSUE THREAD

**Issue by oliviathevampire** [oraxen/oraxen#1267]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

An option to auto-generate and maybe update custom_variation for blocks, similar to custom_model_data.

### Reason

When adding a lot of blocks, keeping check of your custom_variation number might be a bit difficult, so this would allow it to be easier.

**Comment by oliviathevampire** [comment]
@Boy0000 What do you think?

**Comment by Boy0000** [comment]
Answered no to this before and still say no. It has more implications than cmd so

**Comment by oliviathevampire** [comment]
> Answered no to this before and still say no. It has more implications than cmd so

What about atleast a way to easier keep track of what values are used and like that? it's a bit difficult when having lots of blocks and have to try and keep track of them all.

**Comment by oliviathevampire** [comment]
> > > Answered no to this before and still say no. It has more implications than cmd so
> > 
> > 
> > What about atleast a way to easier keep track of what values are used and like that? it's a bit difficult when having lots of blocks and have to try and keep track of them all.
> 
> Why do you need to keep track of them? you start at 0 and keep incrementing that number every time you create a new custom block, it's honestly not difficult.

When you have blocks from different packs you have to go a lot back and forward to keep track of what values is used and not
