### ISSUE TITLE
Texture pack wont load

### ISSUE THREAD

**Issue by Itsuki-Ph** [oraxen/oraxen#1272]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Hey, i have a server running with oraxen and for some ppl the pack wont load , we get about 50 ppl and the problem show only for 5/6 ppl

Im using the self hosted option for the pack and ive 0 error in the console when the problem appear

If u have any idea for helping me with that im taking it :)) 

Thx

### Steps to reproduce

Running a server 1.20.1 with oraxen i guess ? x)

### Plugin Version

1.170.1

### ProtocolLib Version

ProtocolLib version 5.0.0

### Server Software & Version

This server is running Paper version git-Paper-100 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: f402f89)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
This is an issue best helped in the support discord as it is heavily unlikeøy to be a plugin pug if 5/6 work fine, sounds like a client related problem. Support discord will get problem resolved faster 👍
