### ISSUE TITLE
[BUG] Food effects Mechanics not work

### ISSUE THREAD

**Issue by liannai569** [oraxen/oraxen#1276]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

![image](https://github.com/oraxen/oraxen/assets/89626087/86e62349-456d-4630-a472-fd805bbb5b7b)

this can not work 

### Steps to reproduce

when I eat the chilli , the effect will not apply

### Plugin Version

![image](https://github.com/oraxen/oraxen/assets/89626087/8ddcaaa7-f7e0-469d-8706-3edbf96d01cc)

### ProtocolLib Version

![image](https://github.com/oraxen/oraxen/assets/89626087/69fc3fea-ea1a-44b2-a3e2-9e4f3b4029ee)

### Server Software & Version

![image](https://github.com/oraxen/oraxen/assets/89626087/573565a9-6d50-42cf-9299-5c963ef14aa1)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Bruhhhh10** [comment]
```yml
  Mechanics:
    food:
      effects:
        WITHER:
          amplifier: 1
          duration: 20
          is_ambient: true
          has_particles: true
          has_icon: true```

@liannai569 This works completely fine, from your screenshot it seems that "effects:" is under mechanics sub-path, not food sub-path
It has to be under food sub-path to work.

@Boy0000 I think you can probably close this issue
