### ISSUE TITLE
[BUG] Furniture with seat mechanic leaves old armorstand behind after moving wie WE

### ISSUE THREAD

**Issue by KlausTrophobie** [oraxen/oraxen#1277]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

I have just noticed that when moving furniture with seat mechanic using WorldEdit, the (invisible) Armorstands remain in the old position and you can no longer place anything there. However, a new armor stand is created at the target location so that the seat mechanics can still be used. Only the old armor stand should be removed after the move (//cut).

### Steps to reproduce

- place furniture with seat mechanic and move via worldedit

### Plugin Version

1.170.1

### ProtocolLib Version

5.1.0-SNAPSHOT-653

### Server Software & Version

Paper-196 (MC: 1.20.1)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
seems like a worldedit issue to me
the entity is there, so adding -e should include it, unless WE filters out specific entities
Oraxen doesnt have much to do with that, only the final clipboard paste
