### ISSUE TITLE
[BUG] Ground Items

### ISSUE THREAD

**Issue by xMystik** [oraxen/oraxen#1281]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When oraxen items are on the ground they have different NBT tags than the ones that are already on the player's inventory, so if player has full inventory he cannot pick them up unless he frees a slot.

### Steps to reproduce

Have full inventory with one oraxen item on your inventory, then drop the same oraxen item and try to pick it up.

### Plugin Version

1.171.0

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### Server Software & Version

This server is running Paper version git-Paper-450 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 62b220a)
You are running the latest version
Previous version: git-Paper-381 (MC: 1.20.4)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Bruhhhh10** [comment]
@xMystik this has been fixed already, update your 1.171.0 build

**Comment by Bruhhhh10** [comment]
@Boy0000 you can close this btw
