### ISSUE TITLE
[BUG] Removing furniture with command removes all furniture instead of specified furniture in radius

### ISSUE THREAD

**Issue by jaydenmcil** [oraxen/oraxen#1283]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When typing '/oraxen admin furniture rock_small1 remove ~ ~ ~ 50 false' it removes all furniture items in a radius of 50 instead of the specified furniture 'rock_small1'

Idk if it matters or not but all the furniture around me is made of paper

### Steps to reproduce

Place down lots of different furniture items, type '/oraxen admin furniture <name> remove ~ ~ ~ <radius> false'

### Plugin Version

1.170.1 (latest)

### ProtocolLib Version

5.0.0

### Server Software & Version

1.20.1

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
fixed in #1261
