### ISSUE TITLE
[BUG] Could not pass event BlockBreakEvent to Oraxen in 1.18.2

### ISSUE THREAD

**Issue by liannai569** [oraxen/oraxen#1284]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

![image](https://github.com/oraxen/oraxen/assets/89626087/73c4151c-9410-4aaf-ad4c-bd89f8372a3c)

break a oraxen block , it will report that

### Steps to reproduce

break a oraxen block , it will report that

### Plugin Version

1.171.0

### ProtocolLib Version

![image](https://github.com/oraxen/oraxen/assets/89626087/1df5bd38-6c1d-4029-9317-9ce7c9fb578c)

### Server Software & Version

![image](https://github.com/oraxen/oraxen/assets/89626087/49180fec-5a98-431f-a71b-520dcafe8e86)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
Fixed in #1261
