### ISSUE TITLE
[BUG] Bed Explosions drop Noteblocks

### ISSUE THREAD

**Issue by ClumsyIsNotReal** [oraxen/oraxen#1294]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Bed explosions drop Note blocks when an explosion is near to a custom block in the nether / end etc

### Steps to reproduce

place a few custom blocks and a bed in the end or nether and right click the bed

### Plugin Version

Latest

### ProtocolLib Version

Latest

### Server Software & Version

Pufferfish - 1.20.4 Latest

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
fixed in #1291
