### ISSUE TITLE
[SUGGESTION] Blast Resistance for Custom Blocks

### ISSUE THREAD

**Issue by ClumsyIsNotReal** [oraxen/oraxen#1295]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Add a "blast_resistance" option for custom blocks

### Reason

Helps when making custom ores or blocks that require the same level of strength as blocks like obsidian etc

**Comment by ClumsyIsNotReal** [comment]
Completely missed this post of basically the same suggestion: https://github.com/oraxen/oraxen/issues/1076#issue-1958560120

The suggestion was made months ago and is a great feature for making custom blocks work the same as real blocks within the game. Even just a toggle option of "explodable" or "blast_resistance" with true/false would be good enough as a temporary option

**Comment by Boy0000** [comment]
added in 2.0
