### ISSUE TITLE
[BUG] double particles on block break

### ISSUE THREAD

**Issue by aquatic-86** [oraxen/oraxen#1296]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

when breaking a custom block, created with oraxen, the block displays twice as much particles when being broken

### Steps to reproduce

create any custom block and break it

### Plugin Version

1.171.0/1.172.0 latest dev build

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### Server Software & Version

paper-1.20.4.jar

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by minustenchan** [comment]
this only happens in gamemode creative*
would have to use packets to fix this issue i think
