### ISSUE TITLE
[BUG] Custom falling block dropping noteblock

### ISSUE THREAD

**Issue by minustenchan** [oraxen/oraxen#1299]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Custom falling block drops noteblock if two falling blocks land at the same block at the same time

### Steps to reproduce

Place custom falling block and then place another falling block right below it, it will drop a noteblock if they both drop on the same block at the same time

https://github.com/oraxen/oraxen/assets/134551265/bcddb620-2524-4440-9c4a-ea85bb7a5755

### Plugin Version

1.172.0

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### Server Software & Version

git-Paper-448 (1.20.4)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
fixed in #1291
