### ISSUE TITLE
[BUG] Custom Food

### ISSUE THREAD

**Issue by al3xm15** [oraxen/oraxen#1303]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

I have a custom food made with Oraxen and i found a bug that deletes items while eatingi t

### Steps to reproduce

So having the Custom Food from Oraxen being in secondhand/shield slot and having another item in main hand while eating it i get the hunger but it deletes the item in main hand and not the secondhand/shield slot where the custom food is in

### Plugin Version

![image](https://github.com/oraxen/oraxen/assets/159070228/4a26cad1-9ab3-47cd-b4a2-7df241ef348d)

### ProtocolLib Version

![image](https://github.com/oraxen/oraxen/assets/159070228/6eeeb36c-45ae-4387-9f42-32d840c40ed1)

### Server Software & Version

![image](https://github.com/oraxen/oraxen/assets/159070228/be83f9c9-ce52-4452-b6b4-f0b592862b80)

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
fixed in #1291
