### ISSUE TITLE
[BUG] Hand doesn't swing when placing custom noteblock on replaceable type

### ISSUE THREAD

**Issue by minustenchan** [oraxen/oraxen#1304]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

this only happens for custom noteblocks, swings the hand perfectly fine for custom stringblocks or furniture

### Steps to reproduce

Place oraxen custom noteblock on a replaceable block like short_grass seagrass etc

### Plugin Version

1.172.0

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### Server Software & Version

git-Paper-459 (MC: 1.20.4)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
Fixed in 2.0 :)
