### ISSUE TITLE
[BUG] When you place the water in the Stringblok near blok, there will make a bug

### ISSUE THREAD

**Issue by liannai569** [oraxen/oraxen#1305]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

when you place a water in the location of stringblcok , It will make the stringblock to string

### Steps to reproduce

https://github.com/oraxen/oraxen/assets/89626087/419361b0-1781-489f-aa83-8e0b2d44bd32

that is a bug

### Plugin Version

![image](https://github.com/oraxen/oraxen/assets/89626087/69b0f28e-cfd9-490a-9fbc-348dec18ab0c)

### ProtocolLib Version

5.1.1

### Server Software & Version

1.20.4

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
Fixed in 2.0
