### ISSUE TITLE
[BUG] I found bug from Lasted Oraxen when player destroy above barrier in furniture under barrier not destroy with above barrie

### ISSUE THREAD

**Issue by rise2477** [oraxen/oraxen#1306]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

I found bug from Lasted Oraxen when player destroy above barrier in furniture under barrier not destroy with above barrie

### Steps to reproduce

I just place and break furniture

### Plugin Version

Lasted

### ProtocolLib Version

Lasted

### Server Software & Version

1.20.2

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
fixed with 2.0
