### ISSUE TITLE
[BUG] Can't import items into config files

### ISSUE THREAD

**Issue by LunarStudiosDEV** [oraxen/oraxen#1307]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

tried migrating some items. on ver 1.171.0, but for some reason, it doesn't migrate the namespace properly:
https://gyazo.com/5f865f84e11fa755b2a2529d923ebbba

### Steps to reproduce

import items, and use the duplication config option

### Plugin Version

1.171.0

### Server Software & Version

Paper-318 (MC: 1.20.2)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by LunarStudiosDEV** [comment]
instead of mcicons:auto_gen... it's mcicons_auto_gen...
not utilizing any /s or :s

**Comment by Boy0000** [comment]
fixed in #1291
