### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by G4mingJ4ck** [oraxen/oraxen#1309]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

![2024-03-23_20 30 34](https://github.com/oraxen/oraxen/assets/164562182/750068be-451d-4972-aa33-72360a43d665)

Oraxen models doesn't work without optifine

Did I Need a Plugin for this?

### Steps to reproduce

Pls Help

### Plugin Version

latest

### ProtocolLib Version

latest

### Server Software & Version

Paper 1.20.4 

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by G4mingJ4ck** [comment]
![Uploading help.png…]()

**Comment by G4mingJ4ck** [comment]
![help](https://github.com/oraxen/oraxen/assets/164562182/7bd1615c-ac14-4e45-b522-02f6cb3ca386)

Its worked with optifine
But the most of my Player hasn't optifine installed

**Comment by Boy0000** [comment]
Your pack is using optifine only formatting then. This isnt an oraxen bug. Please use the support discord for further help resolving thsi

**Comment by G4mingJ4ck** [comment]
How can I change this?

**Comment by G4mingJ4ck** [comment]
I saw this
It is no longer possible to use upper case in textures or model names with vanilla since minecraft 1.11, however optifine still supports it. Please never use upper case to avoid problems.

But i doesn't use upper case

**Comment by G4mingJ4ck** [comment]
> Your pack is using optifine only formatting then. This isnt an oraxen bug. Please use the support discord for further help resolving thsi

Can you answer fast pl

**Comment by G4mingJ4ck** [comment]
Can you send me the discord

**Comment by G4mingJ4ck** [comment]
There was one problem, I need to verify the email of the purchase but i buyed it over my father, can you help me other way?
