### ISSUE TITLE
[BUG] Trying to place button against CB when there's already a button plays place sound

### ISSUE THREAD

**Issue by minustenchan** [oraxen/oraxen#1328]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

This bug only started happening from my most recent commit for reference

could fix it with a canPlace() check then cancelling the blockPlaceEvent but since the newData variable is set to the default blockstate of the material that wouldn't work properly

could also make the correctBlockStates return a InteractionHand enum and check if it's failed, if so cancel the blockPlaceEvent maybe?

Block place system still needs some work

### Steps to reproduce

Place button against custom block
Once it's placed, try placing a button again on the same side against custom block, it will play a wood place sound

### Plugin Version

1.173.0

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### Server Software & Version

git-Paper-550 (MC: 1.19.4)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
fixed in 2.0
