### ISSUE TITLE
[BUG] Trying to place passable/non-solid block against custom block if player is inside block won't work

### ISSUE THREAD

**Issue by minustenchan** [oraxen/oraxen#1329]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Place a passable/non-solid block like short grass for example, it wont let you if you're on the block location

### Steps to reproduce

Place a passable/non-solid block against custom block (Example: Short grass, Iron Bars) while standing on the block

### Plugin Version

1.173.0

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### Server Software & Version

 git-Paper-550 (MC: 1.19.4)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
Pretty sure this is vanilla behaviour?

https://github.com/oraxen/oraxen/assets/62521371/fd452e62-31de-41db-829b-1f63df334699

**Comment by Boy0000** [comment]
fixed in 2.0
