### ISSUE TITLE
[SUGGESTION] Option to automatically create local Polymath server

### ISSUE THREAD

**Issue by Browsit** [oraxen/oraxen#1332]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Only mention we could find of this suggestion before is https://discord.com/channels/480068531132563476/1219031695647445162/1219031695647445162

[Polymath](https://github.com/oraxen/polymath) seems like a fine resource pack hosting option, but while it's obviously possible to create your own instance, we feel it is being underutilized in that Oraxen should be able to create a local instance automatically if configured. 

### Reason

This would be particularly useful for paid resource packs—or projects which contain them—where uploading/distributing the packs to other machines is against their terms of service.

Since we've read that parity is important to Oraxen, it should be noted that ItemsAdder has offered a comparable option for some time now (see https://www.youtube.com/watch?v=iiYRCsT1NlE&t=3m28s).

**Comment by Kaidenleaf** [comment]
Self-host will be in 2.0. https://github.com/oraxen/oraxen/pull/1313
