### ISSUE TITLE
[BUG] Command /o take <custom item> does not work.

### ISSUE THREAD

**Issue by sorrrix** [oraxen/oraxen#1335]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Whenver i use the command /o take  (custom item) it gives me an unexpected error. https://mcpaste.io/dc4c90e225c321c6
I just want to use the command to simply remove custom oraxen items from the inventory of players without having to use the unnecessary minecraft command using custommodel datas and stuff.

### Steps to reproduce

Just simply try to use the /o take <custom item> command. Using an oraxen custom item.

### Plugin Version

Oraxen 1.170.1

### ProtocolLib Version

5.2.0

### Server Software & Version

Paper 1.20.4

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
fixed next update
