### ISSUE TITLE
[BUG] OraxenFurnitureInteractEvent never called

### ISSUE THREAD

**Issue by Hokiib** [oraxen/oraxen#1336]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

the furniture interact event isn't called when right clicking 

### Steps to reproduce

Interact with the furniture

### Plugin Version

1.172.0

### ProtocolLib Version

5.2.0-SNAPSHOT

### Server Software & Version

 This server is running Folia version git-Folia-"a5ddd94" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by liannai569** [comment]
![image](https://github.com/oraxen/oraxen/assets/89626087/d3964ea8-708a-4927-ac33-2ccc5bc10336)

![image](https://github.com/oraxen/oraxen/assets/89626087/a29719c5-92fc-4048-996e-9b92522fddc7)

my version is 1.173.0

**Comment by liannai569** [comment]
> ![image](https://private-user-images.githubusercontent.com/89626087/321510695-d3964ea8-708a-4927-ac33-2ccc5bc10336.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MTI5MTUsIm5iZiI6MTcxMjgxMjYxNSwicGF0aCI6Ii84OTYyNjA4Ny8zMjE1MTA2OTUtZDM5NjRlYTgtNzA4YS00OTI3LWFjMzMtMmNjYzViYzEwMzM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA1MTY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmOTMyN2Y0MDk3OTRjYjBjODdlOTliNDNlM2YyZTc4M2ExYjM3NmQ5MmQwOWE3NjQyZmM2NjdlNWUzZGU5YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9GFL_BVmv7K3kp6pUj6RGaiFTDeQ8sVOHuepx3FayCY)
> 
> ![image](https://private-user-images.githubusercontent.com/89626087/321510727-a29719c5-92fc-4048-996e-9b92522fddc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MTI5MTUsIm5iZiI6MTcxMjgxMjYxNSwicGF0aCI6Ii84OTYyNjA4Ny8zMjE1MTA3MjctYTI5NzE5YzUtOTJmYy00MDQ4LTk5NmUtOWI5MjUyMmZkZGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA1MTY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwOTIxYjgwZGVlMDc4MDAzZDRjNDMxMGQ3ZmM3NTY2MDljZGEwODUyMDVkNjcyNzkxZDdlODcyMWJkMmFiMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ypTK6KrExTNTZCXzhvCmcZ_qMgpTh-wjE7aWG30iPgE)
> 
> 我的版本是 1.173.0

sorry,My server is purpur not folia

**Comment by Euphillya** [comment]
If it only comes from Folia, put the error in the Pull Request: https://github.com/oraxen/oraxen/pull/1271

**Comment by Boy0000** [comment]
folia isnt supported, test this on a non-folia as here you would be using the experimental folia patch not standard oraxen
