### ISSUE TITLE
add support for minecraft 1.20.4

### ISSUE THREAD

**Issue by stormkiller0** [oraxen/oraxen#1344]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

add support for minecraft 1.20.4

### Reason

add support for minecraft 1.20.4

**Comment by Boy0000** [comment]
1.20.4 has been supported for months as spigot/polymart says 👍 
if there is an issue with the plugin please use the support discord and im sure itll be resolved in minutes
