### ISSUE TITLE
[BUG] NoSuchMethod error for 1.19.4 server on 2.0-SNAPSHOT

### ISSUE THREAD

**Issue by minustenchan** [oraxen/oraxen#1345]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

full stacktrace: https://mclo.gs/mMby4Wu

### Steps to reproduce

Launch server with oraxen 2.0-snapshot

### Plugin Version

2.0-SNAPSHOT

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### Server Software & Version

git-Paper-550 (MC: 1.19.4)

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
fixed
