### ISSUE TITLE
[BUG] NullPointerException on EfficiencyMechanicListener

### ISSUE THREAD

**Issue by minustenchan** [oraxen/oraxen#1346]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

stacktrace: https://mclo.gs/xyxZK3j

### Steps to reproduce

mine custom block

### Plugin Version

2.0-SNAPSHOT

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### Server Software & Version

git-Paper-459 (MC: 1.20.4)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
fixed in 2.0
