### ISSUE TITLE
[BUG] Lore not supporting font-tag

### ISSUE THREAD

**Issue by ALMikey** [oraxen/oraxen#1348]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Unable to use custom fonts in lore

### Steps to reproduce

![image](https://github.com/oraxen/oraxen/assets/121159477/27ef0691-702e-42d2-92ef-93f8c36c00f7)
![image](https://github.com/oraxen/oraxen/assets/121159477/e77a29b0-50b5-4e4a-9a1c-008b37edf47a)

### Plugin Version

Oraxen-1.170.1

### ProtocolLib Version

ProtocolLib-v5.2.0

### Server Software & Version

paper-1.18.2

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
fixed in 2.0
