### ISSUE TITLE
[BUG] Drop probability is not taken into account

### ISSUE THREAD

**Issue by liannai569** [oraxen/oraxen#1352]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

loots:
        - oraxen_item: clover
          probability: 0.3
        - oraxen_item: clover2
          probability: 0
         Probability option does not take effect

![image](https://github.com/oraxen/oraxen/assets/89626087/2c23e637-ff1f-4f7f-8761-13b2c6144305)

### Steps to reproduce

No matter how much you fill in the probability, it will fall 100%

### Plugin Version

1.173.0

### ProtocolLib Version

5.2.0

### Server Software & Version

1.20.4

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
fixed in 1.174.0
