### ISSUE TITLE
[BUG] Can't have a glyph & item use the same texture file

### ISSUE THREAD

**Issue by lukemango** [oraxen/oraxen#1362]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

can't have a glyph & item use the same texture file

### Steps to reproduce

have a glyph and item use the same texture file

### Plugin Version

1.173.0

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### Server Software & Version

git-Paper-484 (MC: 1.20.4)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
Seems fine on my end i suspect the issue is elsewhere @lukemango 

![image](https://github.com/oraxen/oraxen/assets/62521371/facd4f5b-d083-4b56-9f3e-9ddf77647172)

**Comment by lukemango** [comment]
> Seems fine on my end i suspect the issue is elsewhere @lukemango
> 
> ![image](https://private-user-images.githubusercontent.com/62521371/325532730-facd4f5b-d083-4b56-9f3e-9ddf77647172.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzQ5OTAsIm5iZiI6MTcxNDAzNDY5MCwicGF0aCI6Ii82MjUyMTM3MS8zMjU1MzI3MzAtZmFjZDRmNWItZDA4My00YjU2LTlmM2UtOWRkZjc3NjQ3MTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA4NDQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhYjBmOTViYjZkNzJjYjRkYzk1NjllZWQxNDFkYjhiYjZkYmU3NzhiMDM2YTEwNGFiMWJmMTViMzAzMzczOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.di8Q6GRqBMx2XcmWC1MbRFegGriPmKYp_mSIzBB8zd0)

odd, I just tested this on a server with only oraxen, plib & papi and it wasn't working

**Comment by lukemango** [comment]
```owner:
  texture: cyt/chat_ranks/owner
  ascent: 7
  height: 7
  char: ```
  
  tested by making an item in the paper.json file, not using Oraxen's item creator
