### ISSUE TITLE
[BUG] oraxen plugin error

### ISSUE THREAD

**Issue by loeskeee** [oraxen/oraxen#1370]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Короче, поступило сообщение спустя где-то через 2 недели, скачиваю новое обновление на сайте Spigot. Скачал новое обновление, перекидываю файл png. в pack/ui и хочу установить картинку в DeluxeMenus, выскакивает ошибка в виде непонятного иероглифа, чуть позже смотрю в консоль и вижу ряд ошибок, которые пишут про версию 1.20.4 (лог скину, ссылка будет снизу) Спустя где-то 1-2 дня и вижу, что появилось новое обновление 1.20.5, скачиваю, а потом у меня полностью пропал текстурпак на сервере, не знаю что делать.

https://mclo.gs/GYJ8Cmw - Log

### Steps to reproduce

Скачать новое обновление 1.20.5 и у вас полностью пропадет текстурпак 

### Plugin Version

Oraxen version 1.173.0

### ProtocolLib Version

ProtocolLib version 5.2.0

### Server Software & Version

Version: it-Purpur-1985 (MC: 1.19.4)

![2024-04-29_00-27-15](https://github.com/oraxen/oraxen/assets/164649467/05a9f5ef-8838-44f3-bd1a-2f6daa720ff0)
![2024-04-29_00-06-16](https://github.com/oraxen/oraxen/assets/164649467/119a8a5d-94a4-4e90-b026-cf6dac85f926)

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
fixed in 1.174.0
