### ISSUE TITLE
[BUG] Custom Blocks can place in non-solid blocks

### ISSUE THREAD

**Issue by VinPlays1234** [oraxen/oraxen#1374]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Custom Blocks can place in non-solid blocks like lantern, chain, chest, torch 
anything that isn't a full block.I think this bug is very dangerous.

### Steps to reproduce

1.place a block in non-solid block.
2.block will replace in that location

### Plugin Version

1.173.0

### ProtocolLib Version

5.2.0

### Server Software & Version

purpur 1.20.44 2176

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
fixed in 1.174.0 👍
