### ISSUE TITLE
[BUG] inv cmd not working

### ISSUE THREAD

**Issue by BKStreemze** [oraxen/oraxen#1375]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When I try to do "/o inv" I am getting the error listed at the bottom of the log listed below and have also reached out via discord but no luck and told to make a report here.

https://mcpaste.io/098616d97e886072

### Steps to reproduce

I dont know how to reproduce the issue as it has been happening since i installed this premade server pack i purchased sorry ik this isnt any help.

### Plugin Version

Oraxen version: 1.173.0!

### ProtocolLib Version

ProtocolLib version 5.2.0

### Server Software & Version

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
fixed in 1.174.0 👍
