### ISSUE TITLE
[SUGGESTION] interactionBoxes possible to place into Exists block

### ISSUE THREAD

**Issue by hyein6790** [oraxen/oraxen#1376]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

I conducted a test and encountered an issue. The CCrops check fails if the entity is null, returning the message ‘Oraxen config is incorrect.’ However, Oraxen is unable to place the item when the interactionBoxes offset is less than zero because the offset is already positioned on the floor block.
![image](https://github.com/oraxen/oraxen/assets/15249360/8b0d96a4-537c-4cb5-a8dc-6714d33a2abc)

Is it possible to position a furniture’s interactionBoxes within a block?

interactionBoxes are different from barrierBoxes in that I think there is no need to check if there is a valid space in Furniture Place. barrierBoxes need to check if space is required for Place, but for interactionBoxes, even if the space is occupied when placing, can’t we just make it possible to Place?

There is a workaround to place it: First, remove the floor block and place a roof block. Then, place the floor furniture against the ceiling. Now, you can place the floor block again, and you’ll be able to see the furniture positioned as intended.
![2024-05-03_20 01 38](https://github.com/oraxen/oraxen/assets/15249360/902e3512-01d1-48c7-99ee-4e96d96adcdd)

### Reason

interactionBoxes are different from barrierBoxes in that I think there is no need to check if there is a valid space in Furniture Place. barrierBoxes need to check if space is required for Place, but for interactionBoxes, even if the space is occupied when placing, can’t we just make it possible to Place?

**Comment by Boy0000** [comment]
this is intended behaviour, preventing u from placing furniture inside others and such when the hitbox collides with something
might add an option to bypass this but not sure
