### ISSUE TITLE
[SUGGESTION] adjustable language files that are automatically included in the RP

### ISSUE THREAD

**Issue by jan-kir-wwu** [oraxen/oraxen#1378]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

It seems like it is not possible to include language files that are automatically inserted in the resulting RP. Doing the step manually is much more difficult together with the automated RP generation. 

This was discussed on discord in the support channel https://discord.com/channels/480068531132563476/613680450761785344

### Reason

Adding own language files to the generated RP needs a lot of manual effort. 

For professional servers with multilanguage support this would be a good reason to get the plugin and its (most likely) not hard to implement.

**Comment by Boy0000** [comment]
the issue here doesnt really make sense as there is nothing to automate in this process
there is a global.json lang-file and otherwise u must indeed include said lang files
nothing to automate
