### ISSUE TITLE
[BUG] piston bug

### ISSUE THREAD

**Issue by VinPlays1234** [oraxen/oraxen#1380]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Update oraxen and piston making bug.

### Steps to reproduce

1.Push block with piston. It will start bugging

### Plugin Version

1.174.0

### ProtocolLib Version

5.4.0 rc2

### Server Software & Version

1.20.4

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
A more detailed bugreport would be helpful, this says very little. Record the bug and show it, or explain it better.
Oraxen doesnt do anything with pistons unless ur on pre 1.19 or not on a Paper server
