### ISSUE TITLE
[BUG] Placement wall furniture with display entity type

### ISSUE THREAD

**Issue by KlausTrophobie** [oraxen/oraxen#1383]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

If you place wall furniture with type DISPLAY_ENTITY and transformation FIXED, it can also be placed on block edges in the air although VERY_STRICT is noted in the rotation. If you use the ITEM_FRAME type, this is not the case.

Atm you have to stay with item_frame type if you want wall furniture to be only "straight" on the block.

![air_placement](https://github.com/oraxen/oraxen/assets/25036374/b43dcfbd-bb25-45ad-9026-69b160b50a2e)

### Steps to reproduce

use furniture with this config:

```  Mechanics:
    furniture:
      barrier: false
      restricted_rotation: VERY_STRICT
      type: DISPLAY_ENTITY
      display_entity_properties:
        display_transform: FIXED
      limited_placing:
        roof: false
        floor: false
        wall: true```

### Plugin Version

1.174.0

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### Server Software & Version

Paper-196 (MC: 1.20.1)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
fixed in 2.0
