### ISSUE TITLE
[BUG] Custom Armor not keeping texture when crafted with custom crafting recipe

### ISSUE THREAD

**Issue by koinkk** [oraxen/oraxen#1391]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

We have a custom recipe, made out of custom items that makes custom armor, it keeps all of the icons and everything in the inventory, but it doesn't show up on our person with the correct textures, it just looks like white leather. If we grab the item from /o inv, it looks just fine. 

### Steps to reproduce

Make a custom Armor, Make another custom item, Make a recipe that creates the custom armor with that custom item, put armor on.

### Plugin Version

Oraxen version 1.173.0

### ProtocolLib Version

[12.05 04:23:15] [Server] [INFO] ProtocolLib version 5.2.0-SNAPSHOT-679

### Server Software & Version

[12.05 04:21:50] [Server] [INFO] This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
[12.05 04:21:50] [Server] You are running the latest version
[12.05 04:21:50] [Server] Previous versiongit-Paper-241 (MC: 1.20.2)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by koinkk** [comment]
Also downloaded version 174 and wasn't able to even open the /o inv anymore

**Comment by DiabolusCorporation** [comment]
I have the same problem. /o inv dosnt want to opet and armor texture dosnt want to show after reload (sometimes it shows some times it dosnt)
