### ISSUE TITLE
[BUG] Smelting Mechanic doesnt work on

### ISSUE THREAD

**Issue by 4two0** [oraxen/oraxen#1393]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

I switched to [oraxen-1.175.0.jar] cause there was a fix for the /o inventory
then i created a 3x3 Pickaxe of the already created "Hammers"
i just switched the Material Type and the Item Texture

Bigmining works, Durability also works but Smelting doesnt work

### Steps to reproduce

3x3_picke:
  displayname: <gradient:#3685EC:#72C1E4>3x3 Pickaxe
  material: NETHERITE_PICKAXE
  lore:
  - <#6f737d>» <#D5D6D8>3x3 Pickaxe
  - <#6f737d>» <#D5D6D8>schmelzt Erze sofort
  Pack:
    generate_model: true
    parent_model: item/handheld
    textures:
    - default/3x3_pickaxe.png
    custom_model_data: 1000
  Mechanics:
    smelting:
      enabled: true
      play_sound: true
    durability:
      value: 4683  
    bigmining:
      radius: 1
      depth: 1

### Plugin Version

Oraxen version 1.175.0

### ProtocolLib Version

ProtocolLib version 5.2.1-SNAPSHOT-685

### Server Software & Version

This server is running Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
unable to reproduce this bug at all with the default example item oraxen provides
please record this bug happening and please properly format your config example using codeblocks as the above is unreadable @4two0 

https://github.com/oraxen/oraxen/assets/62521371/da7ba84f-60a0-45f1-96ed-fbbccc8c942e
