### ISSUE TITLE
[BUG] MiniMessage of oxn cannot be edited and used in lore

### ISSUE THREAD

**Issue by ALMikey** [oraxen/oraxen#1398]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

![image](https://github.com/oraxen/oraxen/assets/121159477/1b5c2004-d802-469f-a86b-295bdd25d062)
![image](https://github.com/oraxen/oraxen/assets/121159477/7f17d801-2c82-49a7-958b-82ddaf4576bf)

### Steps to reproduce

The editing is invalid. I have previously provided feedback that it has been fixed. It is possible that you forgot to add it

### Plugin Version

1.175.0

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### Server Software & Version

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
minimessage works just fine
the font one might not be supported however

![image](https://github.com/oraxen/oraxen/assets/62521371/33790c6b-07cf-4eb9-8d55-a5da74ddf796)

**Comment by Boy0000** [comment]
fixed next update
