### ISSUE TITLE
[BUG] clickAction Mechanic

### ISSUE THREAD

**Issue by Kingmaix** [oraxen/oraxen#1402]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

if you use the clickAction mechanic and want to place the "furniture" you gave the clickAction, than it opens the action you have set for the furniture. Every time you take the block in you'r inv and place it new it opens again but it should just open if you click on the "furniture" that is still placed to the ground and not if you place the "furniture" to the ground.

![Settings](https://github.com/oraxen/oraxen/assets/134948267/fb4f6837-8c36-4df0-9fad-527632794357)

### Steps to reproduce

take the furniture with the clickAction and place it to the ground it triggers the action you set but it should't trigger by placing it.

### Plugin Version

26.05 14:36:04 [Server] INFO Authors: th0rgal and boy0000
26.05 14:36:04 [Server] INFO Oraxen version 1.174.0

### ProtocolLib Version

26.05 14:36:25 [Server] INFO Authors: dmulloy2 and comphenix
26.05 14:36:25 [Server] INFO Provides read/write access to the Minecraft protocol.
26.05 14:36:25 [Server] INFO ProtocolLib version 5.2.0-SNAPSHOT-679

### Server Software & Version

26.05 14:36:43 [Server] INFO This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
unable to reproduce this bug @Kingmaix 

https://github.com/oraxen/oraxen/assets/62521371/d1cae7e5-55a9-4949-948f-559476789530
