### ISSUE TITLE
[SUGGESTION] Order in Emoji List

### ISSUE THREAD

**Issue by KlausTrophobie** [oraxen/oraxen#1403]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

The emojis should have a sort order in the list which you can influence. For example, you could use the order within the respective .yml. 

### Reason

If you have emojis with different themes and other styles, these should also be sorted accordingly. In the current random arrangement, it looks very "untidy".

**Comment by Boy0000** [comment]
fixed in 1.176.0 thanks
