### ISSUE TITLE
[BUG] the pack does not load beacuse the pack.zip is 4.29EB size

### ISSUE THREAD

**Issue by TutorialMan7727** [oraxen/oraxen#1407]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Hello. I installed the plugin today however the plugins resource pack will not load. I looked at the pack and it seemed fine until I attempted to extract it. I got presented with a windows error saying that I didn't have enough room and that it is "4.29EB". It had been left at the default config. This wont allow me to enable the pack.

### Steps to reproduce

Install the plugin and start it

### Plugin Version

1.175.0

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### Server Software & Version

This server is running Paper version 1.20.6-130-master@5d8e53d (2024-06-01T14:32:53Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
the pack.zip is by default "encyrpted" it is not 4.2b EB
the pack loads just fine independent of this

you might not be able to unzip pack.zip unless you disable protection in settings yes
