### ISSUE TITLE
[BUG] Cannot load the resource pack

### ISSUE THREAD

**Issue by TutorialMan7727** [oraxen/oraxen#1408]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

I started the plugin and joined the server and it told me the resource pack failed. I have not changed any config (except the protection but that doesn't make a difference).

### Steps to reproduce

Install the plugin and join the server

### Plugin Version

1.175.0

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### Server Software & Version

This server is running Paper version 1.20.6-130-master@5d8e53d (2024-06-01T14:32:53Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by TutorialMan7727** [comment]
Sorry to open this issue in the logs it show that the protocol lib isn't enabled as shown here `[17:52:46 INFO]: Oraxen | ProtocolLib is not on your server, some features will not work`

**Comment by Boy0000** [comment]
use the discord for support
compiled versions lack default assets that configs try to use
thats likely why

protocollib is irrelevant to the resourcepack

**Comment by TutorialMan7727** [comment]
can you please tell me where I can get the default assets from please. I believed that protocol lib was used for the compiling of the texture pack

**Comment by Boy0000** [comment]
buy the plugin and u have the default assets
protocollib is irrelevant to the bug ur having here in all ways shapes and forms

**Comment by TutorialMan7727** [comment]
ok thank you for the information 👍
