### ISSUE TITLE
[SUGGESTION] the <state> in debug.toggle should be translatable

### ISSUE THREAD

**Issue by Clexus** [oraxen/oraxen#1410]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

debug.toggle: "调试模式已enabled!"
debug.toggle: "调试模式已disabled!"

### Reason

It's weird that there's English state in Chinese sentence or other languages

**Comment by Boy0000** [comment]
you can simply add this to said languages, the togfgle translation can be added to any language yml
