### ISSUE TITLE
[BUG] Invisible shopkeeper plugin trade result preview

### ISSUE THREAD

**Issue by b01w** [oraxen/oraxen#1411]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When using an oraxen item as the result of a trade with the shopkeeper plugin it does not display the preview item at all when the trade knows it is correct. Instead it is invisible but is still clickable and does still work, just that the player will not know if they have the correct item to trade which is the bug.

### Steps to reproduce

Setup shopkeeper (https://www.spigotmc.org/resources/shopkeepers.80756/) with an npc. Use an oraxen item (ideally tool with model on it) as a trade in which you'll get this oraxen item, then when you have fulfilled requirements for a successful trade it won't show the item in the slot to get the item. VIDEO LISTED ON DISCORD AND SEEN BY BOY

### Plugin Version

Latest Version

### ProtocolLib Version

Latest version

### Server Software & Version

1.20.4 Purpura latest

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
unable to reproduce this, ensure that ur oraxen items are fetched from oraxens give or inv command @b01w 

https://github.com/oraxen/oraxen/assets/62521371/3ba96586-d397-43f8-80d4-0a883aa0c0c4
