### ISSUE TITLE
[SUGGESTION] Introducing a bespoke NBT configuration option for items.

### ISSUE THREAD

**Issue by MrLaoGe** [oraxen/oraxen#1415]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

It is hoped that the functionality to append custom NBT attributes to items could be facilitated.

### Reason

The rationale behind this proposition lies in the compatibility enhancement with other plugins, particularly those reliant on NBT parsing. By enabling customization of NBT attributes within the OX item repository, seamless integration with said plugins could be achieved.

**Comment by Boy0000** [comment]
Already a thing though might not be documented
https://github.com/oraxen/oraxen/blob/master/core/src/main/java/io/th0rgal/oraxen/items/ItemParser.java#L227-L242
here is the code, should be able to see how to use it 👍

**Comment by MrLaoGe** [comment]
> Already a thing though might not be documented https://github.com/oraxen/oraxen/blob/master/core/src/main/java/io/th0rgal/oraxen/items/ItemParser.java#L227-L242 here is the code, should be able to see how to use it 👍

May I inquire about the structure used for YAML in PersistentData? I couldn't find any relevant examples in the wiki.

**Comment by MrLaoGe** [comment]
> > Already a thing though might not be documented https://github.com/oraxen/oraxen/blob/master/core/src/main/java/io/th0rgal/oraxen/items/ItemParser.java#L227-L242 here is the code, should be able to see how to use it 👍
> 
> May I inquire about the structure used for YAML in PersistentData? I couldn't find any relevant examples in the wiki.

my_item:
  PersistentData:
      - key: example_key:subkey
        type: STRING
        value: example_value
I attempted to employ this method, but it proved ineffective

**Comment by MilkFoam-L** [comment]
This is the configuration I wrote according to the code, but I use the command cmi itemnbt will not display the nbt I configured here


jewel_fish_5333:
  displayname: <white>宝石鱼
  material: APPLE
  Mechanics:
    food:
      hunger: 2
      saturation: 0.4
  Pack:
    generate_model: true
    parent_model: item/generated
    textures:
    - custom/misc_items/fishs/jewel_fish.png
    - custom/misc_items/star/5.png
    custom_model_data: 1004
  PersistentData:
    - fishing:
      key: "oraxen:fishing"
      type: "STRING"
      value: "234"
