### ISSUE TITLE
[BUG] amount: not working for drops.

### ISSUE THREAD

**Issue by goldenkuky209** [oraxen/oraxen#1416]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

min_amount: , max_amount: and amount: do not work. (The only situation where I got these to work is max_amount when using fortune).

I am trying to make a crate that when broken drops random amounts of some items but It only drops 1, even when min or max or normal amount is specified.

### Steps to reproduce

Have a block drop items. Ex:

wooden_crate:
  displayname: <gradient:#ffffff:#ffffff>Wooden Crate
  material: PAPER
  Pack:
    generate_model: true
    parent_model: block/cube_all
    textures:
    - default/wooden_crate
    custom_model_data: 111
  Mechanics:
    noteblock:
      block_sounds:
        break_sound: block.wood.break
        place_sound: block.wood.place
      custom_variation: 12
      model: wooden_crate
      hardness: 1
      drop:
        silktouch: false 
        loots:
        - { oraxen_item: amethyst, max_amount: 2, probability: 0.75 }
        - { oraxen_item: weed_seed, max_amount: 5, probability: 0.55 }
        - { mmoitems_id: RADIANT_COIN, mmoitems_type: MATERIAL, min_amount: 5, probability: 1 }
        - { minecraft_type: DIAMOND, amount: 1..10, probability: 1 }

### Plugin Version

Oraxen version 1.175.0

### Server Software & Version

This server is running Paper version git-Paper-431 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 3ea95ef)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
fixed in 1.176.0 thanks
