### ISSUE TITLE
[BUG] Oraxen not parsing item data correctly on latest version

### ISSUE THREAD

**Issue by b01w** [oraxen/oraxen#1418]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Some features of the item data is not working on 1.20.4 on the latest version of oraxen for me. Its making all item names italic in the GUI, making all lore and item names italic in the GUI, then when giving items in inventory its messing up some of the colours, underlining and other things making it look ugly and also affecting other plugins using ingame items from oraxen as theyre now not matching

### Steps to reproduce

Take any item out from a gui in oraxen with rgb colours in lore and name aswell as underlining start and end

https://github.com/oraxen/oraxen/assets/70667899/4b4cefe4-9e67-4e8e-94d6-f3610f719657

### Plugin Version

1.176.0

### ProtocolLib Version

5.2.0 Snapshot

### Server Software & Version

1.20.4 Purpur latest vers

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
fixed next update
