### ISSUE TITLE
[SUGGESTION] Placeholders change depending on if player has pack downloaded

### ISSUE THREAD

**Issue by SubGplayz** [oraxen/oraxen#1419]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

I believe it would be a good feature for glyph placeholders to have an optional alternative that shows when a player does not have the resource pack loaded. This could be a good feature for if a server has an optional resource pack, and want it so they can enhance things in chat without it looking bad for players without the resource pack.

### Reason

I like using custom textured ranks, but my server's resource pack is optional as it has geyser as well. I want bedrock players to be able to see a fallback rank without having to compromise by java players having to use a vanilla rank as well.

**Comment by Boy0000** [comment]
Bedrock is in no way supported or expected to be compatible in any way
There is also no way to really know if a player has  a specific pack or not, u can just check if they have a server sent pack
