### ISSUE TITLE
[BUG] unstackable: true

### ISSUE THREAD

**Issue by Welly23** [oraxen/oraxen#1422]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

'unstackable: true' dont work
![Screenshot 2024-06-11 234402](https://github.com/oraxen/oraxen/assets/57121205/fd226ad4-a06a-4f79-ad60-dfac0a49798d)

### Steps to reproduce

.

### Plugin Version

oraxen-1.176.0.jar

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### Server Software & Version

This server is running Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
fixed next update and in latest devbuild 👍
