### ISSUE TITLE
[BUG] Tab complete glyphs does not color the glpyph to be white

### ISSUE THREAD

**Issue by enesop** [oraxen/oraxen#1425]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When you use the `tabcomplete` feature for a emoji, the emoji does not get turned into white. If you use a placeholder, the emoji will print white

Normal
![image](https://github.com/oraxen/oraxen/assets/60015283/6911a756-0a24-40c3-8287-c0902cc0d2d0)
![image](https://github.com/oraxen/oraxen/assets/60015283/93609431-067a-4854-80a7-3d34ce932cdc)
Unnormal
![image](https://github.com/oraxen/oraxen/assets/60015283/05fe9a23-87c3-4730-8e8f-be15a37dbb81)
![image](https://github.com/oraxen/oraxen/assets/60015283/8a85f1b7-85e6-4086-bc07-bfa22e0e1d4d)

### Steps to reproduce

Add `tabcomplete` to one of your glpyhs and send a chat message, make sure your message format is not white.

### Plugin Version

1.176.0

### ProtocolLib Version

5.2.1-SNAPSHOT-685

### Server Software & Version

git-Leaves-"e7c14b8" (MC: 1.20.4)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
it will use the earlier formatting if u have tabcomplete set to show the unicode instead of the placeholder
nothing i can do about that sadly
