### ISSUE TITLE
[BUG] 2D icon to place a 3D object

### ISSUE THREAD

**Issue by Snozbear** [oraxen/oraxen#1429]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

I'm trying to create an item that has a 2D icon when held, but when placed changes to another, 3D, item of furniture

### Steps to reproduce

I'm using these two objects to try and get the desired effect. Trying to place the item just results in a big version of the 2D icon.

2D Icon: 

![image](https://github.com/oraxen/oraxen/assets/47871610/03b26401-b9d1-41da-a569-affdeaca7af7)
          
 3D item:
 
![image](https://github.com/oraxen/oraxen/assets/47871610/87ec18a8-37ff-43a6-b62a-29c9d8e7873b)

Outcomes:
![image](https://github.com/oraxen/oraxen/assets/47871610/a2e7a987-d72b-4bf9-9730-f8ef82f903e1)

### Plugin Version

Oraxen version 1.177.0

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### Server Software & Version

Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
fixed next update
