### ISSUE TITLE
[BUG] shade of commandapi does not loads with paper remapping disabled

### ISSUE THREAD

**Issue by justlofe** [oraxen/oraxen#1430]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

I'm disabled paper plugin remapper with JVM arg ("-Dpaper.disable-plugin-rewriting=true"), and commandapi shade stopped loading. CommandAPI with mojang mappings loading successfully, but shade still using spigot mappings.
But, if you convert a jar via paper remapper, then disable remapper and run the converted jar file as a normal plugin, everything will run with a warning.

### Steps to reproduce

Disable paper plugin remapper with JVM arguments: -Dpaper.disable-plugin-rewriting=true
Start server and wait a few seconds

### Plugin Version

Works from 1.174.0, but i'm using 1.176.0

### ProtocolLib Version

5.3.0

### Server Software & Version

Purpur Version: 1.20.6-2227-79d199c (MC: 1.20.6)*

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
yes currently oraxen uses spigot mappings and shades in commandapi
sadly just dont plan on supporting disabling papers remapper as i see no real benefit here
feel free to open a PR if there is a fix that doesnt break it or cause extra steps for spigot / paper servers by default

**Comment by justlofe** [comment]
i turned off paper remmaper because most of the old plugins dont work with it, and sometimes the server won't even turn on. but thanks for answer, maybe i will find some time to fix this
