### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Popthecat206** [oraxen/oraxen#1436]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

new 1.21 "Jukebox playable" not functioning correctly.  Item cannot be placed into a juke box as well as music title not displaying on item.

### Steps to reproduce

Here is the paste of my code for the item that did not funciton correctly. 
<img width="392" alt="jukeboxissue" src="https://github.com/oraxen/oraxen/assets/89034917/9d8f0d58-1f35-4943-9adf-c28421def48b">

### Plugin Version

 Oraxen version 1.177.0

### ProtocolLib Version

5.3.0-SNAPSHOT-721

### Server Software & Version

1.21-28-812701d (MC:1.21)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
as the docs say, unless you have a datapack to register this sound as a "music disc sound" yes it will not work
