### ISSUE TITLE
[BUG] placing a furniture block down consumes the entire held stack regardless of how many you're holding

### ISSUE THREAD

**Issue by asheden** [oraxen/oraxen#1440]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

placing a furniture block down consumes the entire held stack regardless of how many you're holding

### Steps to reproduce

placing a furniture block down
watching as it consumes the entire held stack regardless of how many you're holding

### Plugin Version

1.777.0

### ProtocolLib Version

5.3.0-SNAPSHOT-709

### Server Software & Version

Paper 1.21-37-master@dd49fba (2024-06-24T02:08:49Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
fixed in 1.178 thanks
