### ISSUE TITLE
Resource pack Excalibur doesn’t work

### ISSUE THREAD

**Issue by capubara** [oraxen/oraxen#1441]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When i place Excalibur(1.20.1) assets to assets of oraxen, i see lots of errors with that when i start the server 
logs : https://mclo.gs/VoBxCwT#L571

### Steps to reproduce

1 Download 1.20.1 Excalibur resource pack
2 Place assets(pack) to assets(oraxen)
3 See lots of errors 

### Plugin Version

Oraxen version 1.177.0

### ProtocolLib Version

Protocollib version 5.2.0-SNAPSHOT-679

### Server Software & Version

Spigot 1.20.1-R0.1-SNAPSHOT+

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
this doesnt sound like a bug moreso just not properly merging a resourcepack
use the discord for further support
