### ISSUE TITLE
[BUG] <name for bug>

### ISSUE THREAD

**Issue by MonG3n** [oraxen/oraxen#1444]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

I eat this item and it doesn't disappear, I can eat it infinitely.

### Steps to reproduce

eat something custom oraxen food

### Plugin Version

1.177.0

### ProtocolLib Version

5.2.0

### Server Software & Version

1.20.4

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
fixed next update 👍
