### ISSUE TITLE
[BUG] Music Discs Require two discs to play unless in creative

### ISSUE THREAD

**Issue by jtwebhomer** [oraxen/oraxen#1450]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

 Music Discs Require two discs in inventory to play properly unless in creative....they will sometimes play with just one but when they play they will pop out of the jukebox right away and it will play as a sound that sometimes needs to be stopped through /stopsound record.......sometimes popping the same disc into the jukebox will actually stop it from playing, but if you have two discs it will work as it should

### Steps to reproduce

Add this to a new .yml file in items folder
`treasure:
  displayname: <#55FFFF>Music Disc
  material: PAPER
  lore:
  - "<#AAAAAA>astral - Treasures"
  Mechanics:
    music_disc:
      song: minecraft:treasure.mysong
  Pack:
    generate_model: true
    parent_model: "item/generated"
    textures:
    - lyra/music_disc_treasure
    custom_model_data: 1548`
  
  add this section to the appropriate section to sounds.yml
 `  treasure.mysong:
    category: record
    sound: treasure.ogg`
    
  add treasure.ogg to pack/sounds
  
  restart server or reload plugin (in this case i restarted server completly)
  
  rejoin
  
  do /o give yournamehere treasure
  make sure your in survival 
  put the disc in a jukebox (bug will only happen if you have one of that exact disc)
  
  

### Plugin Version

![image](https://github.com/oraxen/oraxen/assets/94643886/3d4bdf5e-7e18-4ea5-b9f7-65878dd1f30a)

### ProtocolLib Version

![image](https://github.com/oraxen/oraxen/assets/94643886/12d9eee7-6623-48d1-b493-0d7850ee4079)

### Server Software & Version

![image](https://github.com/oraxen/oraxen/assets/94643886/5a8bb3fa-a862-4ef3-afec-d43899a56e86)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by jtwebhomer** [comment]
update, it might be a bug with protocol lib but i will leave it here, i downgraded to protocollib SNAPSHOT 721 from 723 and it no longer is buggy

**Comment by jtwebhomer** [comment]
so it plays with the disc inside but it doesnt follow proximity like vanilla discs......doesnt matter how far i go i can still hear the music

**Comment by jtwebhomer** [comment]
not sure if players who are far from jukebox when it starts if they can hear music need to wait for a player to get on to ask

**Comment by Boy0000** [comment]
as your console probably tells you, for 1.21 you **should** use the new jukebow_playable property, not this mechanic
