### ISSUE TITLE
[BUG] I don't find any way to deny the resource pack without kicking me from server

### ISSUE THREAD

**Issue by SimonMage** [oraxen/oraxen#1452]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Hi, I'm new I have checked everywhere, I have tested everything but the send pack of oraxen makes no chance to refuse the prompt of resource pack. I would like to simply offer the possibility to users to accept it (and downloading) or simply refuse and play with te client resource pack

### Steps to reproduce

Simply use default settings or enable the deny option with chat or something else "not kick" and the plugin doesn't permit to refuse the prompt

### Plugin Version

1.178.0

### ProtocolLib Version

5.3.0 - 723

### Server Software & Version

Spigot 1.20.1 - R0.1

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
pack is only mandatory if set to it in settings.yml, which it is by default 👍

**Comment by SimonMage** [comment]
> pack is only mandatory if set to it in settings.yml, which it is by default 👍

Yes it's off for me but if I send the resource pack I have the same issue, I can't refuse it

**Comment by Boy0000** [comment]
Please use the discord for further support, if it is not mandatory, the server will not kick you if denied

**Comment by SimonMage** [comment]
> Please use the discord for further support, if it is not mandatory, the server will not kick you if denied

I don't find the link, could you please pass me it?

**Comment by Boy0000** [comment]
https://discord.com/invite/4Qk5kBT9UX
![image](https://github.com/oraxen/oraxen/assets/62521371/0befdef7-1312-4708-aec8-15e1beddf1e9)
