### ISSUE TITLE
[BUG] <Hud not working>

### ISSUE THREAD

**Issue by CoatedMedusa906** [oraxen/oraxen#1457]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

if I try "/oraxen hud toggle balance" it won't work it only spits out an error
![Bild_2024-07-16_225151210](https://github.com/user-attachments/assets/40819914-116e-47b3-8eee-0531c7cbef27)
even if I uncommented it in hud.yml.
![Bild_2024-07-16_225238351](https://github.com/user-attachments/assets/ce80aa49-3276-41b9-892d-5efbcc2dd45d)

### Steps to reproduce

Uncomment the hud example in hud.yml install Vault and then type "/oraxen hud toggle balance"

### Plugin Version

Oraxen: 1.178.0
Vault: v1.7.3-b131

### ProtocolLib Version

Protocolib: v5.2.0-SNAPSHOT-679

### Server Software & Version

My server is running Paper version git-Paper-497 (MC:1.20.4) (Implementing API version 1.20.4-R0.1_SNAPSHOT) (Git:d8d54d9 on ver/1.20.4)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

I tried a few thing and this was the outcome 
![image](https://github.com/user-attachments/assets/0fe99460-371f-476a-ba1b-e9c67dfcecf5)

If I type "/o hud toggle balance" it toggles it on/off but if I change gamemode or rejoin its toggled on everytime

And even if I enabled "disabled_whilst_in_water: true" or "enable_for_spectator_mode: false" it will show up
![image](https://github.com/user-attachments/assets/85a0e2c7-fe6b-4622-a453-ebf56d7c2586)
![image](https://github.com/user-attachments/assets/b6e3970e-cd79-4b95-8e1c-79bc50923062)

**Comment by Boy0000** [comment]
this shows fully working hud - underwater
u are using a glyph that doesnt exist and thus the exit icon
and you dont have the placeholderapi expansion, that is the issues here
