### ISSUE TITLE
[BUG] Not working on 1.20.6

### ISSUE THREAD

**Issue by Dungjava** [oraxen/oraxen#1458]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Plugin not working on 1.20.6
In console it say "Version not supported" but i see on spigotmc you say that it support in 1.20.6
Full logs: https://mclo.gs/xVcw96j

### Steps to reproduce

Run server on 1.20.6 version and java 21

### Plugin Version

Not working so it didn't say anything but i download 1.178.0 version so

### ProtocolLib Version

![image](https://github.com/user-attachments/assets/96959f0c-0d73-4061-97cb-7f2a84062cea)

### Server Software & Version

![image](https://github.com/user-attachments/assets/a5dff65d-eaa1-4e61-ab8e-493178b4b62b)

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
You have gestures enabled, oraxens gesture feature does not work on modern versions
