### ISSUE TITLE
[BUG] Incompatibility Between ProtocolLib and Oraxen Plugins Causing Warnings and Exceptions

### ISSUE THREAD

**Issue by var1nthon** [oraxen/oraxen#1461]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When running a Minecraft server with ProtocolLib and Oraxen plugins, several warning messages appear in the server logs.
The errors indicate an inability to set a value of a field in the ClientboundSetObjectivePacket, causing an IllegalStateException.
Additionally, there is a ClassCastException where the server attempts to cast io.papermc.paper.scoreboard.numbers.BlankFormatImpl to java.util.Optional, which fails.

### Steps to reproduce

1. Start a Minecraft server with ProtocolLib and Oraxen plugins installed.
2. Observe the server logs during startup or when specific scoreboard-related packets are sent.

### Plugin Version

1.178.0

### ProtocolLib Version

5.3.0-SNAPSHOT-723

### Server Software & Version

This server is running Paper version 1.21-54-master@f250ec0 (2024-07-11T16:05:17Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are 38 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21-55-7bd22b1 (MC: 1.21)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
unable to reproduce this on latest paper and latest decvuild
maybe if you have hide_scoreboard_numbers on
