### ISSUE TITLE
[SUGGESTION] Support CrazyEnchantements

### ISSUE THREAD

**Issue by Euphillya** [oraxen/oraxen#1463]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Add compatibility to apply CrazyEnchantments on Oraxen items.

### Reason

Oraxen allows you to add multiple features to items, but adding compatibility with CrazyEnchantments will enable servers to add even more customization.

**Comment by Boy0000** [comment]
This is something better suited for this plugin to add most likely
I dont want to add random compatibilities for every plugin out there

Can be added by these other plugins fairly simply by listening to OraxenItemsLoadedEvent and altering the ItemBuilder as needed

Example of a plugin that alters displayname of all oraxen items
![image](https://github.com/user-attachments/assets/163b9951-738d-480a-834b-d17ab2e58b84)
