### ISSUE TITLE
[BUG] Players unable to swim if using a protocol higher than the server.

### ISSUE THREAD

**Issue by Valorless** [oraxen/oraxen#1466]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [x] I have checked if any similar bug reports exist

### Description

I'm running Paper 1.20.4 with ViaVersion, but players 1.20.5 and above are unable to swim in water or lava, and boats sink to the floor.
They don't take fall damage, and are still able to drown.

I've tried removing all plugins, and the issue only exists when Oraxen is enabled.
Tried fiddling with settings, but I can't seem to fix it..
I have a [ViaVersion dump](https://dump.viaversion.com/0a89b484eb6e5bd3c09aa7e2b9493411435fd820cf26a8d0b34c6a5c2af9fabf) with server information for debugging.

_Some players have reported that on 1.21 Lava looks like water, but I've been unable to reproduce that bug._

### Steps to reproduce

Unsure how to explain it, and unsure exactly when the issue happened, because I originally thought it was ViaVersion.
But I just restart the server with Oraxen, and now 1.20.5+ cant swim.

### Plugin Version

Oraxen version 1.179.0
Authors: th0rgal and boy0000

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679
Provides read/write access to the Minecraft protocol.
Authors: dmulloy2 and comphenix

### Server Software & Version

This server is running Paper version git-Paper-497 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: d8d54d9 on ver/1.20.4)
You are running the latest version
Previous version: git-Paper-496 (MC: 1.20.4)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
please use the discord for support
issues brought by viaversion is not something i can really fix either without any more info
