### ISSUE TITLE
[BUG] SHADER based custom armors allows repair when disabled

### ISSUE THREAD

**Issue by BurningCoolDude** [oraxen/oraxen#1469]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Using shader method and the configuration enabled disabling leather repairing, custom armors are still repairable with leather.

### Steps to reproduce

Disable leather repairing in config
Use shader method
Fix armor with leather

### Plugin Version

1.178.0

### ProtocolLib Version

5.3.0-SNAPSHOT-721

### Server Software & Version

This server is running Paper version 1.21-100-master@681c013 (2024-07-20T16:42:56Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by BurningCoolDude** [comment]
Shoot, I forgot a name I apologize!
"Leather repairs custom armors even while disabled"

**Comment by Boy0000** [comment]
Unable to reproduce this on latest devbuild

![image](https://github.com/user-attachments/assets/314076ad-09d5-4156-8f6b-48f2bf74db07)

![image](https://github.com/user-attachments/assets/33344b0e-5a87-44cd-9ad2-18f853a571c4)
