### ISSUE TITLE
[BUILD 2.0] Please give instructions on how to build 2.0

### ISSUE THREAD

**Issue by KeiBoogie** [oraxen/oraxen#1470]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Explained in the title.

### Reason

So I may add it to my server.

**Comment by Boy0000** [comment]
You wont get help compiling Oraxen. Buy the plugin if you cant compile it and want to test it as there are devbuilds in the Discord
