### ISSUE TITLE
[BUG] Display Names with no color

### ISSUE THREAD

**Issue by TheGh0st3rS** [oraxen/oraxen#1471]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

No color in items names and oraxen inventory.
![image](https://github.com/user-attachments/assets/de03170c-a485-4edc-8611-8ca28829ef1a)
![image](https://github.com/user-attachments/assets/41a9e508-6039-4d90-9a7f-3b363681f6e2)

### Steps to reproduce

Only open oraxen inventory and this displays <green>armors.yml in white and cursive.
This ocurrs with all of the items and categories

### Plugin Version

1.179.0

### ProtocolLib Version

5.2.0

### Server Software & Version

Spigot 1.20.4 (Java 21)

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
issue is your on spigot and not paper, this will happen in that case

**Comment by TheGh0st3rS** [comment]
Oh, thanks friend
