### ISSUE TITLE
[BUG] Cannot rotate furniture based on surface placement

### ISSUE THREAD

**Issue by DragonsAscent** [oraxen/oraxen#1473]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Essentially trying to make a new "amethyst cluster" block. Trying to mimic the fact that it snaps to all surfaces and rotates appropriately. unfortunately doesn't seem possible.

### Steps to reproduce

Make a simple 1x1x1 furniture block with a model
Try using `limited_placement` with all values allowed
Block still does not rotate based on if it's on ceiling or walls. Only rotates 45 degrees horizontally

### Plugin Version

1.180

### ProtocolLib Version

5.0

### Server Software & Version

Paper 1.21 Stable

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
try using display-transform FIXED and see, it should mimic itemframe logic which is what u seemingly want here

**Comment by Boy0000** [comment]
fixed next update
