### ISSUE TITLE
[SUGGESTION]Cake creator

### ISSUE THREAD

**Issue by TheGh0st3rS** [oraxen/oraxen#1474]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

I´m exploring in to spigot "player values" and I can´t modify or read the "player food".
Like plants, I want to make custom cakes, when you do right click, it set another model and increase your food level

### Reason

I want to add this feature because I want to add custom cakes into my server and I don´t have any idea of how can I do it...
I read the documentation 5 times, and I can´t do nothing.

**Comment by Boy0000** [comment]
not something oraxen does
