### ISSUE TITLE
[BUG] No replacement of items

### ISSUE THREAD

**Issue by TheGh0st3rS** [oraxen/oraxen#1475]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When I consume a item, the first that I configured works fine.
But when I use again the replacement, it doesnt works
![image](https://github.com/user-attachments/assets/b509b9ae-b8e1-4844-b3ab-fbc0fd3525dd)

https://github.com/user-attachments/assets/10e82c21-355b-4af3-84e2-86d36ad41912

### Steps to reproduce

You need to configure two or more replacement items and only works the first one

### Plugin Version

1.179.0

### ProtocolLib Version

5.2.0

### Server Software & Version

Paper 1.20.4 (Java 21)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
not able to reproduce this issue on the latest devbuilds, feel free to try those

https://github.com/user-attachments/assets/e17704d7-c578-48cf-9a6f-ce9979c9db8a

**Comment by TheGh0st3rS** [comment]
I don't know how I do it, but when I restart the server, 3 times, it works sucessfully

**Comment by TheGh0st3rS** [comment]
I don't know what happend, but when I restart my server 3 times, it works sucessfully
