### ISSUE TITLE
[BUG] Error Breaking Furnitures

### ISSUE THREAD

**Issue by TheGh0st3rS** [oraxen/oraxen#1478]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

 Could not pass event EntityDamageByEntityEvent to Oraxen v1.179.0
java.lang.NullPointerException: Cannot invoke "io.th0rgal.oraxen.items.ItemBuilder.build()" because the return value of "io.th0rgal.oraxen.api.OraxenItems.getItemById(String)" is null

### Steps to reproduce

When I put a furniture with a Hitbox, it doesn´t break (in survival) and the console display this error:

![image](https://github.com/user-attachments/assets/15559d17-f6e0-4a3b-a433-ee2994866fae)

I don´t know why this ocurrs exactly

### Plugin Version

1.179.0

### ProtocolLib Version

5.2.0

### Server Software & Version

Paper 1.20.4 (Java 21)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
you defined an invalid drop by the looks of it
