### ISSUE TITLE
[SUGGESTION] Custom work box

### ISSUE THREAD

**Issue by TheGh0st3rS** [oraxen/oraxen#1482]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

I propose being able to create your own crafting table, using the "slot" mechanics, "custom inventory" and recipes.
For example, I create a custom menu.
If in that custom menu, I put the materials in the following order:
slot: 0 ---> wood
slot: 1 ---> wood
slot: 9 ---> wood
slot: 10 ---> wood

In the slot: 27 will be apear a crafting table
(This is only an example)

If we can make custom gui, custom menu, and If you implement this, we could create our own crafting tables, anvils, ovens, etc...

### Reason

I think it would be something quite original and that it would help the plugin grow and become more popular... Whenever it is possible to do it, of course

**Comment by Boy0000** [comment]
not planning on this sorry
