### ISSUE TITLE
[SUGGESTION] denying oraxen item not in an recipe to craft in crafting table

### ISSUE THREAD

**Issue by RUYSUE** [oraxen/oraxen#1483]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Block oraxen items not in specfic recipe from crafting in crafting table or somewhere else.

### Reason

I helped to check a server, finding though oraxen items won't appear in recipe book, putting an oraxen item into slots manually will result in another recipe, like this
![a453cd22d748361e35e09966549bff8b](https://github.com/user-attachments/assets/b0d4b2a8-2f74-4e38-a515-158bab84a4f6)

player can put them all and get this result (not adding this recipe in oraxen/CMI or other plugin) :
![44f093b4801ddbdfe439e1380a1c87f5](https://github.com/user-attachments/assets/8ddf99f3-6510-4671-a1bd-883582983963)

i dont know if there will be anyone do like this. no one knows what players will out of our expectation, but finally there will be one do this

i wonder if you can add a feature that deny crafting with oraxen items not in this recipe. (maybe just like Slimefun?)

**Comment by Boy0000** [comment]
this is implemented under Misc-mechanic, refer to docs for example or support discord
