### ISSUE TITLE
[BUG] Wind charges breaks the custom blocks

### ISSUE THREAD

**Issue by Taiyou06** [oraxen/oraxen#1486]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

like the title suggest, custom blocks take wind charges as any other explosion.

### Steps to reproduce

1 - get a custom block
2 - throw a wind charge next to it
3- profit

### Plugin Version

1.179.0

### ProtocolLib Version

5.3.0-SNAPSHOT-722

### Server Software & Version

Current Purpur Version: 1.21-2280-930003b (MC: 1.21)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
fixed next update
