### ISSUE TITLE
[BUG] @BOY ORAXEN ARMOR FIX 

### ISSUE THREAD

**Issue by Minegoats** [oraxen/oraxen#1487]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

custom_chestplate:
  displayname: <gradient:#3685EC:#72C1E4>Custom Chestplate
  material: LEATHER_CHESTPLATE
  color: 223,224,216
  disable_enchanting: true
  unstackable: true
  Mechanics:
    durability:
      value: 555
  AttributeModifiers:
  - attribute: GENERIC_KNOCKBACK_RESISTANCE
    amount: 0.1
    operation: 0
    slot: CHEST
    uuid: 56813a77-8ad3-4100-bf10-fe3735ef7651
    name: oraxen:modifier1
  - attribute: GENERIC_ARMOR
    amount: 8
    operation: 0
    slot: CHEST
    uuid: 4675ea32-f5dc-4cf8-9fd5-3ed51e860a61
    name: oraxen:modifier1
  - attribute: GENERIC_ARMOR_TOUGHNESS
    amount: 3
    operation: 0
    slot: CHEST
    uuid: bfff6cb2-8803-4c9c-8d28-53cc1ef46de1
    name: oraxen:modifier1
  Pack:
    generate_model: true
    parent_model: item/generated
    textures:
    - default/armors/custom_chestplate
    - default/armors/custom_chestplate
    custom_model_data: 1000

I understand most reports you receive players most often times are correct about the occurrence of the problem, but most times they are incorrect about the reason why it happens, so I'm glad you're trying to find out more. But I don't think you should so easily dismiss my proposal.
The `PlayerItemDamageEvent` gets fired properly as it should whenever the item receives durability damage, but as you set its event damage to 0 without manually firing the `PlayerItemBreakEvent` once that durability reaches 0, that event does not get fired. Like you said, it should be fired, but it doesn't, so it's a bug; I explained why it happens and how to fix it, I've basically done all your work. Instead of replacing your plugin with a custom of our own or by doing some half-fix we're here sending you a bug report in hopes that it might help others as well. I doubt we're only ones using Oraxen, and it's true that many plugins doesn't use the `PlayerItemBreakEvent` but for those that does use it fixing this will be of great help. I've also mentioned it is expected of you to follow the bukkit's documentation to uphold plugin compatibility. Your code is very well made so I don't understand why you're being so hesitant. When you start up a small test, here, today, does it work for you?

All you have to do to reproduce this issue is set up a basic event listener such as this:

@EventHandler
public void onItemBreak(PlayerItemBreakEvent event) {
  System.out.println("break event");
}

You'll find out that it gets called for vanilla items, but not Oraxen ones. The test doesn't have to take more than that. Note that I do not check if the event is cancelled, so the issue isn't regarding other plugins, unless of course they set the PlayerItemDamageEvent's damage to 0 like Oraxen does. For this purpose, I uninstalled everything other than the testplugin and Oraxen. Issue persists. Then I uninstalled Oraxen, it works proving the issue is with Oraxen.

### Steps to reproduce

in description

### Plugin Version

1.18 is what we use native

### Server Software & Version

1.18

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by supercoolspy** [comment]
Could you upload your config to https://pastes.dev so it is easier to read along w/ the code (in different pastes)

**Comment by Boy0000** [comment]
fixed next update
