### ISSUE TITLE
[SUGGESTION] The model of the telescope cannot be changed using normal methods

### ISSUE THREAD

**Issue by W-IBARI** [oraxen/oraxen#1489]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

I hope to add support for custom models of telescope items. If there is already a similar feature, I hope to explain it in detail in the wiki

### Reason

I plan to use the telescope as a base to make a sniper rifle. However, when I import the items as usual, I find that the model rendering method of general items does not work properly on the telescope. My configuration is shown below. I am sure that there is no problem with my model, as long as the telescope is replaced with other items, it will display normally.
![图片](https://github.com/user-attachments/assets/61e3aef1-624c-4160-8fb4-d7ae2bf646e7)
After digging a little deeper, I discovered that the spyglass in the vanilla version of minecraft has a unique rendering method, you can look at the file "spyglass_in_hand" which seems to declare the unique rendering method of the spyglass. This would also explain why it is the only one with a unique 3d item model in the game.

**Comment by Boy0000** [comment]
this is one of the items you should manually handle the model for, as the gui and the held are separate
then simply specify the model-path in your config and set it to not generate a model
