### ISSUE TITLE
[Bug] Recovery Compass model malformed when OraxenItem uses it as material

### ISSUE THREAD

**Issue by 0x484** [oraxen/oraxen#1490]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When setting the material of any item to "RECOVERY_COMPASS" the Recipe for the actual Recovery Compass is bugged and displays the "error item" ![bug](https://github.com/user-attachments/assets/f8884adc-2910-4e79-bf7b-6e10172ad5ae)

### Steps to reproduce

1. Set the material of any item to "RECOVERY_COMPASS"
2. Check Recipe Book for Recovery Compass

### Plugin Version

1.180.0

### ProtocolLib Version

5.2.0

### Server Software & Version

git-Purpur-2062 (MC: 1.20.1)*

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
the issue would be the recovery compass model is bugged if one or more OraxenITems uses Recovery Compass
not the recipe being bugged

**Comment by Boy0000** [comment]
fixed next update
