### ISSUE TITLE
DUPE / Craft Bug with EcoItems

### ISSUE THREAD

**Issue by 0x484** [oraxen/oraxen#1491]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When using Oraxen Custom Items in EcoItems as Material, certain Recipes that consist of the same vanilla Item will always default to the same if you use SHIFT to mass craft that Item. If you're only clicking and not using shift, it will craft the correct Item. 

I Have provided 3 Test Items and 3 Test Recipes using the Oraxen default Configs. 

Note that the Bug only happens in Oraxen 1.176.0+ (Not 1.175.0 or below, in those versions you can't use SHIFT to mass craft at all)

Made with "enforce-preparing-recipes: true" in eco.yml 
(Without this, the recipe output display is bugged, the crafting stays the same, just the display is different)
[Items&Recipes.zip](https://github.com/user-attachments/files/16593670/Items.Recipes.zip)

### Steps to reproduce

I Have provided 3 Test Items and 3 Test Recipes using the Oraxen default Configs. 
1. Use Oraxen, Eco and EcoItems. (Default Configs, set "enforce-preparing-recipes: true" in eco.yml to see the item that should be craftet)
2. Place the 3 test Items in the Items folder in EcoItems
3. Place the 3 test Recipes in the Recipe folder in EcoItems
4. Give yourself the test2 item with ``/ecoitems give <NAME> test2 64``
5. Try to uncraft it (Put it in the top left slot in a crafting bench), press shift to mass craft the whole stack
6. As set in the Recipe you should get 5 test1 Items for every test2 item, instead you get once 5x test1 and 4 stacks of test2, effectively duping it

### Plugin Version

Oraxen: 1.180.0
Eco: 6.73.4
EcoItems: 5.58.0

### ProtocolLib Version

5.2.0

### Server Software & Version

git-Purpur-2062 (MC: 1.20.1)*

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
a video or anything showcasing this would be helpful as all this tells me is eco-stuff and nothing specific to pinpoint anything to oraxen

**Comment by Boy0000** [comment]
Imean this just seems like an eco issue. Every detail provided specifies eco-something
Where does oraxen come into play here? are these oraxen items? or eco items? does disabling that setting fix it? if so thats prob the issue then

**Comment by Boy0000** [comment]
Oraxen has support for eco in the sense that an OraxenItem can import any EcoItem and build ontop of it
if all your doing is using oraxen to generate a resourcepack, ur better of just making the ecoitem and importing it to oraxen and adding file info for RP generation, then still use the ecoitem only

The issue is likely a conflicting issue with your recipe not being an oraxen recipe but using oraxen item and oraxen doing some logic to fix issues for oraxen recipes
so should be solved by not relying on the oraxenitem here if you even need to import the item at all from eco to handle this
