### ISSUE TITLE
[SUGGESTION] Durability in 1.20.4 servers and before

### ISSUE THREAD

**Issue by TheGh0st3rS** [oraxen/oraxen#1492]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

add again the durability for 1.20.4 servers and before

### Reason

I can´t make custom durability; and I need them for this version (1.20.4)

**Comment by Boy0000** [comment]
durability mechanic is there for 1.20.4 still unchanged
