### ISSUE TITLE
[BUG] Furnitures goes 0.5 blocks down

### ISSUE THREAD

**Issue by TheGh0st3rS** [oraxen/oraxen#1493]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

In 1.20.4 server (paper) the furniture issue doesnt work correctly (in the Oraxen 1.179.0 works fine)

### Steps to reproduce

I dont know, make a furniture

### Plugin Version

1.180.0

### ProtocolLib Version

5.2.0

### Server Software & Version

Paper 1.20.4

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
gonna need a more detailed bugreport this tells me nothing
please provide screenshots, configs and anything else relevant

**Comment by TheGh0st3rS** [comment]
Ok, sorry for no send anything. There is some screenshots:

Code:
![image](https://github.com/user-attachments/assets/63f933c1-fa64-436d-89ae-bc0c6699c2bb)

With Oraxen 1.179.0 (and Paper 1.20.4):
![image](https://github.com/user-attachments/assets/c0359767-0b91-42ec-9627-f37c6deb7539)

With Oraxen 1.180.0 (and Paper 1.20.4):
![image](https://github.com/user-attachments/assets/1a0e6515-8394-4555-bea6-de08921517f6)

In the server´s console doesnt appear anything

**Comment by b01w** [comment]
Experiencing this too, only since updating to the same version aswell, 1.21 here

**Comment by Boy0000** [comment]
should be fixed in latest devbuild / next release 👍

**Comment by TheGh0st3rS** [comment]
Ok, thanks bro
