### ISSUE TITLE
[BUG] java.lang.IllegalArgumentException: empty RecipeChoice isn't allowed here

### ISSUE THREAD

**Issue by tomasalias** [oraxen/oraxen#1498]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When using Oraxen with certain datapack, it makes the server unplayable. Player cannot join, motd and commands doesn't work, etc.
[latest.log](https://github.com/user-attachments/files/16645770/latest.log.log)

### Steps to reproduce

1. Install this datapack: https://github.com/atomic-junky/tasty-supplies
2. Install latest Oraxen plugin
3. Start the server

### Plugin Version

Oraxen version 1.180.0

### Server Software & Version

This server is running Paper version 1.21-130-master@b1b5d4c (2024-08-10T10:02:42Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-13-7c9240f (MC: 1.21.1)

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
issue would be in your datapack most likely
issue is that the server doesnt properly load your recipe or somehting like that
looking at the error there doesnt seem to be anything i can do on my end
