### ISSUE TITLE
discord

### ISSUE THREAD

**Issue by dinobossytnew** [oraxen/oraxen#1500]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Hello, it won't let me join your Discord; it says the invitation is not valid!
discord: dinobossyt

### Steps to reproduce

Hello, it won't let me join your Discord; it says the invitation is not valid!

### Plugin Version

Hello, it won't let me join your Discord; it says the invitation is not valid!

### ProtocolLib Version

Hello, it won't let me join your Discord; it says the invitation is not valid!

### Server Software & Version

Hello, it won't let me join your Discord; it says the invitation is not valid!

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by dinobossytnew** [comment]
what ban :u

**Comment by dinobossytnew** [comment]
why am i banned i just found out wtf?

**Comment by Boy0000** [comment]
you are not banned

![image](https://github.com/user-attachments/assets/805c3aeb-f309-4c7e-ad5b-85c9bdc82d39)
