### ISSUE TITLE
[BUG] Console spam on InventoryClickEvent

### ISSUE THREAD

**Issue by NekrosBurek** [oraxen/oraxen#1503]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

This issue happens from time to time there is no specific case when it happens

### Steps to reproduce

This issue happens from time to time there is no specific case when it happens

### Plugin Version

Oraxen v1.181.0

### ProtocolLib Version

v5.2.1-SNAPSHOT-689

### Server Software & Version

git-Paper-496 (MC: 1.20.4)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
fixed next upodate
