### ISSUE TITLE
[BUG] Item Mechanics not working properly

### ISSUE THREAD

**Issue by lelegore** [oraxen/oraxen#1504]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

My item still can be crafted even tho i already put "allow_in_vanilla_recipes: false" and "disable_vanilla_interactions: true" mechanics on the item config

### Steps to reproduce

this is my item config:

racs:
  itemname: <#27AE60>Racs
  material: PAPER
  Mechanics:
    misc:
      disable_vanilla_interactions: true
      allow_in_vanilla_recipes: false
  lore:
  - <#6f737d>↳ <#D5D6D8>Currency, used to trade for items
  Pack:
    generate_model: true
    parent_model: item/generated
    textures:
    - default/currency/racs.png
    custom_model_data: 2001

### Plugin Version

1.180.0

### ProtocolLib Version

5.3.0-SNAPSHOT-726

### Server Software & Version

paper-1.21-119

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
fixed next update
