### ISSUE TITLE
[SUGGESTION] The model configuration of the telescope still cannot be solved

### ISSUE THREAD

**Issue by W-IBARI** [oraxen/oraxen#1506]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Two weeks ago, I raised the same question and your response was to configure it to not generate models and specify its model path. So I configured it in the following format:
![图片](https://github.com/user-attachments/assets/93317e9c-ddf2-4486-a3a2-0fd8f16e224b)
In the game, it still cannot function properly, as shown below:
![图片](https://github.com/user-attachments/assets/22dc170b-93ce-46f0-9549-6221326d5993)
However, if I configure it as another item, it can appear normally in the model I configured:
![图片](https://github.com/user-attachments/assets/61a3c039-0313-4096-adfd-94d8c096b492)
![图片](https://github.com/user-attachments/assets/287ff831-f971-42fd-8caf-d1720bbd28b5)

### Reason

I am a beginner and still in the exploratory stage for this plugin. The problem with this telescope model has been bothering me for a month. I spent about 7-8 hours trying to solve it, but it was not successful. If possible, could you provide me with an example of modifying a telescope model? So I can refer to the correct configuration for modification.

**Comment by Boy0000** [comment]
this would be a support question in the discord, and as mentioned u will need to manaully handle these model files
the item held in the hand and the gui are 2 different models
