### ISSUE TITLE
[BUG] Oraxen Emojis doesn't work

### ISSUE THREAD

**Issue by Cionnaa** [oraxen/oraxen#1509]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

The command /oraxen emojis doesn't work for me
I'm opped but do I need another permission?
I run /oraxen emojis and there's no error in console - I get no book and nothing happens

### Steps to reproduce

I run /oraxen emojis
Nothing happens

I am opped
I have also given myself the permission oraxen.emojis.list
Nothing happens

### Plugin Version

1.181.0

### ProtocolLib Version

5.3.0-SNAPSHOT-726

### Server Software & Version

Purpur 1.21

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by FaultyFunctions** [comment]
I'm also having this issue.

**Comment by Boy0000** [comment]
fixed next update
