### ISSUE TITLE
/o emojis not showing the book in 1.21.1

### ISSUE THREAD

**Issue by neweraproduction** [oraxen/oraxen#1510]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

/o emojis not popping up the book, it did nothing when the glyphs has "is_emoji: true".

### Steps to reproduce

I did a fresh config to reproduce this bug, which Oraxen auto generate all the files

1. Fresh Oraxen generated file.
2. Test in minecraft to check if /o emojis works. (Yes it work to show "No Emojis Found" message)
3. Stop server, and add "is_emoji: true" into emoji.yml in glyphs folder
4. Start server and try /o emojis
5. This time, when type /o emojis, nothing come up.

### Plugin Version

Oraxen version 1.180.0

Also tried version 1.181.0

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-726

### Server Software & Version

This server is running Paper version 1.21.1-40-master@2fdb2e9 (2024-08-21T01:35:33Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
fixed next update
