### ISSUE TITLE
[BUG] /o take doesn't work properly

### ISSUE THREAD

**Issue by Clawsssme** [oraxen/oraxen#1511]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

It takes not exact amount of items, but all your slots where you have the exact amount

### Steps to reproduce

1. Make a custom item (example - crystal)
2. Use /o take crystal 64 - it will take all the stacks, if you have 3 stacks and 48 of crystals, it will take all you 3 stacks, but will keep the 48. So basically it takes all your slots where you have a stack of this item. Same for every other number of item, not just 64

### Plugin Version

1.180.0

### ProtocolLib Version

5.3.0 Snapshot 726

### Server Software & Version

1.20.6-2233-0d6766e (MC: 1.20.6)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
fixed next update
