### ISSUE TITLE
[BUG]  Dyed model turns to its default color when break

### ISSUE THREAD

**Issue by JavisRit** [oraxen/oraxen#1514]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

In my server, when any dyed model breaks, its color turns brown, are there anything I can do to fix this? For example, the surfboard in the picture is red, I'm using itemedit command to dye its color, and when it breaks, it turns brown
![image](https://github.com/user-attachments/assets/d38d39a9-0d88-4394-8efe-cc5eadd2e914)
![image1](https://github.com/user-attachments/assets/31e586e8-79ff-4d47-921d-3bcf8d667224)

### Steps to reproduce

1.Obtain a dyeable furniture by using /o inv and pick any dyeable furniture

2.Dye the furniture by using /ie dye or /oraxen dye

3.Place the furniture down

4.Break the furniture

5.Resulting a default color furniture

### Plugin Version

Oraxen version 1.181.0
Authors: th0rgal and boy0000
![image](https://github.com/user-attachments/assets/70e9ed6a-4ec6-4109-b3f7-862c2f254e99)

### ProtocolLib Version

ProtocolLib v5.3.0-SNAPHOT-726
Authors: dmulloy2 and Comphenix
Issuess: https://github.com/dmulloy2/ProtocolLib/issues
![image](https://github.com/user-attachments/assets/590b937d-c66c-4b36-84e1-0dc440c4d99f)

### Server Software & Version

Server Software: Window 11 hosting private
This server is running Paper version
1.21.1-52-master@e08e667 (2024-08-26T18:02:06Z)
(Implementing API version 1.21.1-R0.1-SNAPSHOT)
![image](https://github.com/user-attachments/assets/ba5b864b-e126-4118-86a6-3a6b5674d070)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
fixed next update thanks
