### ISSUE TITLE
[BUG] Furniture placement issues

### ISSUE THREAD

**Issue by killertuling** [oraxen/oraxen#1517]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When I place this furniture against the wall corner, it will be placed horizontally on the wall

`forest_archery_target:
  itemname: 掠夺者训练用的靶子
  lore:
  - <#a5acb8>Dungeon Furniture
  material: LEATHER_HORSE_ARMOR
  Pack:
    generate_model: false
    model: custom/furnitures/dungeon/forest_archery_target
    custom_model_data: 1087
  Mechanics:
    furniture:
      type: DISPLAY_ENTITY
      hitbox:
        width: 1
        height: 2
      limited_placing:
        roof: false
        floor: true
        wall: false
      display_entity_properties:
        display_transform: FIXED
      drop:
        silktouch: false
        loots:
        - oraxen_item: forest_archery_target
          probability: 1.0`

### Steps to reproduce

![image](https://github.com/user-attachments/assets/5ebcd1fb-56a2-45c5-81c1-a99c5f954eb5)

### Plugin Version

1.181.0

### Server Software & Version

![image](https://github.com/user-attachments/assets/d1fb7852-5f37-4344-8fcb-85e3f88493ab)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
fixed next update
