### ISSUE TITLE
[BUG] PersistentData and injectID not work.

### ISSUE THREAD

**Issue by killertuling** [oraxen/oraxen#1518]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

PersistentData and injectID is not work.

![image](https://github.com/user-attachments/assets/7581cc3a-2273-4e3f-b938-90f5f852ba6b)

### Steps to reproduce

`jade:
  itemname: 翡翠
  material: PAPER
  Pack:
    generate_model: true
    parent_model: item/generated
    textures:
    - custom/minerals/jade/jade
    custom_model_data: 100000
  injectID: false
  PersistentData:
  - key: test:hello
    type: STRING
    value: Here is a value`

### Plugin Version

1.181.0

### ProtocolLib Version

5.2.0

### Server Software & Version

![image](https://github.com/user-attachments/assets/616f1061-680b-4a2c-bd39-639f6dc7cfdb)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by killertuling** [comment]
![image](https://github.com/user-attachments/assets/861b1854-4863-45a9-b46d-2cfc70897b5d)

**Comment by Boy0000** [comment]
fixed next update
