### ISSUE TITLE
[BUG] <name for bug>entity 'ITEM_DISPLAY' does not support modification of max step height

### ISSUE THREAD

**Issue by CIKI3** [oraxen/oraxen#1519]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

An error occurs when placing modelengine furniture

https://github.com/user-attachments/assets/00ef7429-2e16-459f-9a5f-a6d66071a199

### Steps to reproduce

As the video shows

### Plugin Version

Oraxen version 1.181.0

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-726

### Server Software & Version

This server is running Paper version 1.21.1-57-master@b483da4 (2024-09-01T18:09:05Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by CIKI3** [comment]
ceiling_fan:
  itemname: 电风扇
  material: PAPER
  Mechanics:
    furniture:
      modelengine_id: ceiling_fan
      display_entity_properties:
        display_transform: NONE
      rotatable: true
      barriers:
      - x: 0
        y: 0
        z: 0
      limited_placing:
        roof: true
        floor: false
        wall: false
      drop:
        silktouch: false
        loots:
        - oraxen_item: ceiling_fan
          probability: 1.0
  Pack:
    generate_model: false
    model: custom/decorations/ceiling_fan
    custom_model_data: 1414

**Comment by kveion** [comment]
stolen asstes :skull: :death:

**Comment by Boy0000** [comment]
yeah stealing all of Origin Realms aint gonna get you help
Your issue here is also not logical, use discord for support thanks
