### ISSUE TITLE
[BUG] OraxenBlocks.place method always place last block of blocks.yml

### ISSUE THREAD

**Issue by zqodev** [oraxen/oraxen#1520]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

I'm using the Oraxen API to place Oraxen Blocks but i cant place a block by his id because it always return the same block. Maybe its my bad, sorry by advance.

### Steps to reproduce

OraxenBlocks.place(id, loc); 

### Plugin Version

1.181.0

### ProtocolLib Version

5.3.0

### Server Software & Version

Paper 1.20.2

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
unable to reproduce this, please show your relevant code and use discord for support 👍 

![image](https://github.com/user-attachments/assets/2f9b968e-54ef-4fba-92e3-103e857dd911)
