### ISSUE TITLE
[BUG] Circular Load Order

### ISSUE THREAD

**Issue by knepyt** [oraxen/oraxen#1526]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [x] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description
[crash-2024-09-22_01.35.07-server.txt](https://github.com/user-attachments/files/17087902/crash-2024-09-22_01.35.07-server.txt)

![image](https://github.com/user-attachments/assets/af9df933-502c-4a72-83ac-4bc91f214ffc)

### Steps to reproduce

Starting Server 

### Plugin Version

1.181.0

### ProtocolLib Version

Latest dev build

### Server Software & Version

purpur 1.21.1

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
Nothing Oraxen can do here
Oraxen supports Lands to prevent custom block and furniture issues
just aknowledge it like it says
