### ISSUE TITLE
[BUG] Excelent Enchants not able to apply enchantments while Oraxen is loaded

### ISSUE THREAD

**Issue by LadyHaley** [oraxen/oraxen#1528]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [x] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Whille the plugins EnchantGui, ExcellentEnchants, LibsDisguises, nightcore, Oraxen, packetevents, ProtocolLib are installed, Excellent Enchants cannot apply enchantment to items outside of using commands. Removing Oraxen is the only thing that fixes this bug
I booted a fresh server with new configs and got the same result as my testing and live servers

EnchantGui - 3.9.1
ExcellentEnchants- 4.2.2
LibsDisguises - v10.0.44-SNAPSHOT-b1450
nightcore - v2.6.3-updated 29th July
packetevents - 2.5.0+738d429-SNAPSHOT

### Steps to reproduce

install plugins onto server
result

### Plugin Version

1.181.0

### ProtocolLib Version

5.3.0-SNAPSHOT-726

### Server Software & Version

This server is running Paper version 1.21.1-97-master@acdd6d3 (2024-09-23T22:14:51Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)\nYou are running the latest version

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by LadyHaley** [comment]
I realised on the test server I used the last version of oraxen, not latest, redid the test, same result

**Comment by LadyHaley** [comment]
![image](https://github.com/user-attachments/assets/a56643c1-c92f-480b-9ebd-8b6b6f03f253)
This error shows up only when oraxen is installed

**Comment by LadyHaley** [comment]
Any insight as to why this is occurring? it only happens with Oraxen installed :c

**Comment by thatpris** [comment]
After some testing, only when **Oraxen, Protocolib, PacketEvents and ExcellentEnchants** are all present together would the error occur. My bet is that the anvil-changing behaviour codes of the two plugins are clashing together. Oraxen dev if you can look into this ASAP I would be glad.

**Comment by thatpris** [comment]
Removing either packetevents or protocolib seems to fix the error, this may shine some light?

**Comment by Boy0000** [comment]
unable to reproduce this with oraxen and Excellent enchants, if protlib or packetevents fixes it its a clash there
Oraxen relies on protocollib and might cause issues if you have both plugins
If someone can consistently reproduce this with only the relevant plugins lmk, if this is an issue of packetevents + protocollib, i cant fix it

https://github.com/user-attachments/assets/e57601d6-064c-42e9-a91f-fc71721bf379

**Comment by Boy0000** [comment]
Tracked it down to [CommandAPI](https://github.com/JorelAli/CommandAPI), so it is not Oraxen
I'll try and find a solution but yeah, seems to be something there

![image](https://github.com/user-attachments/assets/1efcf763-8430-4b2c-a2c7-52c8316c7503)
![image](https://github.com/user-attachments/assets/6a4113aa-4e57-458a-ba0c-16e2a3ae1bca)

**Comment by Boy0000** [comment]
Has been tracked down to how this plugin works and registers enchantments in a Spigot way not Paper way / datapack
Not CommandAPI, ProtocolLib or anything like that here, would be on ExcellentEnchants to fix @thatpris @LadyHaley 

![image](https://github.com/user-attachments/assets/ea7e01d6-bb76-4cf7-8792-0fda6070cab7)

**Comment by Boy0000** [comment]
> great! how soon can I expect the workaround/fix?
next update and devbuilds soon if ur compiling / in the discord
