### ISSUE TITLE
[BUG] Bedrock_pickaxe on first_layer

### ISSUE THREAD

**Issue by DarkLionQc** [oraxen/oraxen#1531]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Layer 1 of bedrock can be destroy with the bedrock pickaxe

### Steps to reproduce

Step 1 : go on the mechanics.yml
Step 2 : put "disable_on_first_layer" on true
(like that): 

  bedrockbreak:
  enabled: true
  disable_on_first_layer: true # Set it on true to avoid player breaking the ground ...completely
  durability_cost: 500 

Step 3 : go to the bedrock layer
Step 4 : Mine bedrock layer 1 (Y: -64)
Finally : you can see the Void 

### Plugin Version

[INFO] Oraxen version 1.182.0
[INFO] Authors: th0rgal and boy0000

### ProtocolLib Version

[INFO] ProtocolLib version 5.3.0-SNAPSHOT-732
[INFO] Provides read/write access to the Minecraft protocol.
[INFO] Authors: dmulloy2 and comphenix

### Server Software & Version

[INFO] This server is running Paper version 1.21.1-99-master@1bc02e6 (2024-09-25T02:41:02Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
fixed next update
