### ISSUE TITLE
Add the ability to make new armor for horses

### ISSUE THREAD

**Issue by Internativ** [oraxen/oraxen#1532]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

I want Oraxen to add the ability to make horse armor and an article about it in the wiki. We want to make netherite horse armor on our server

### Reason

Because it will broaden the horizons of the plugin.

**Comment by fxkveion** [comment]
you cant custom horse armor yet, but you will be able to do custom horse armor in minecraft 1.21.2 version

**Comment by fxkveion** [comment]
I assume this feature will be added after 1.21.2 is released

**Comment by Boy0000** [comment]
custom armor will be remade to take advantage of 1.21.2 features for 1.21.2 features when time comes yes
same for wolf armor and most new possibilites
