### ISSUE TITLE
[BUG] join bug. Error codes

### ISSUE THREAD

**Issue by TurretedAsh** [oraxen/oraxen#1535]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Player join bug.

Here is the log.
[error.txt](https://github.com/user-attachments/files/17189217/error.txt)

### Steps to reproduce

Not sure just joined server and a error game up. Was told to report it for boy to look into it later

### Plugin Version

 Oraxen version 1.182.0

### ProtocolLib Version

5.3.0-SNAPSHOT-726

### Server Software & Version

This server is running Paper version 1.21.1-110-master@6d7a438 (2024-09-28T22:14:12Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
fixed next update
