### ISSUE TITLE
[BUG] XP-Trasnfer From XP to bottled xp

### ISSUE THREAD

**Issue by SaltyAlpaca** [oraxen/oraxen#1540]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

It says that in the console, maybe adding just a player message if he has less then 1 Expierience that he needs more to perform this action same error as the one in "Steps to reproduce"
[log (3).txt](https://github.com/user-attachments/files/17344314/log.3.txt)

### Steps to reproduce

I have 0 XP and used the Axe of expirience and it gave me this error
[log (3).txt](https://github.com/user-attachments/files/17344301/log.3.txt)

### Plugin Version

1.182.0

### ProtocolLib Version

5.3.0-SNAPSHOT-726

### Server Software & Version

This server is running Paper version 1.21.1-118-master@fb76840 (2024-10-02T12:49:56Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads/paper

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
unable to reproduce this
please show the config of your item and a full error log if ur still able to reproduce this
