### ISSUE TITLE
[BUG] The description don't load into the player interface

### ISSUE THREAD

**Issue by WaxenSs** [oraxen/oraxen#1543]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

The description does load into the Oraxen interface: 
![image](https://github.com/user-attachments/assets/c8416649-3f03-488a-9e4f-756626bd78c1) 

but when it gives to a player, the description resumes id:
![image](https://github.com/user-attachments/assets/538fab98-40ef-4d74-bf95-183394262168) 

### Steps to reproduce

- In `plugins\Oraxen\items\hammers.yml`
```
  lore:
  - <#6f737d>» <#D5D6D8><lang:items.excavators_hammers.desc>
```
- In `plugins\Oraxen\pack\lang\en_us.json`
```
{
"items.excavators_hammers.desc": "Dig a 3x3 blocks area"
}
```

### Plugin Version

oraxen-1.182.0

### ProtocolLib Version

ProtocolLib v5.3.0-SNAPSHOT-732

### Server Software & Version

paper-1.21.1-119

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
fixed next update
