### ISSUE TITLE
[BUG]  Fatal error trying to convert Oraxen v1.183.0:io/th0rgal/oraxen/api/events/stringblock/OraxenStringBlockPlaceEvent.class

### ISSUE THREAD

**Issue by yueerfeifei123** [oraxen/oraxen#1556]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

[latest.log](https://github.com/user-attachments/files/17540597/latest.log)

### Steps to reproduce

After the server starts, an error message will appear.
﻿

### Plugin Version

[17:53:41 INFO]: Oraxen version 1.183.0
[17:53:41 INFO]: Authors: th0rgal and boy0000

### ProtocolLib Version

[17:53:27 INFO]: ProtocolLib version 5.4.0-SNAPSHOT-735
[17:53:27 INFO]: Provides read/write access to the Minecraft protocol.
[17:53:27 INFO]: Authors: dmulloy2 and comphenix

### Server Software & Version

This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)
You are running the latest version

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
for 1.19.4 u might need to use 1.176.0
everything after requires java21, so if your server is using that it is purely because 1.19.4 doesnt support java21 at all
