### ISSUE TITLE
Duplication with Backpacks and minecraft:decorated_pots

### ISSUE THREAD

**Issue by ListerWorks** [oraxen/oraxen#1579]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

If you put a backpack in your hand and look at a Minecraft:decorated_pot then right click to open the backpack, you can remove an item then close the backpack. Break the pot to get your backpack back to you with the original item still in the backpack.

A quick fix might be to require players look at air when opening a backpack.

### Steps to reproduce

If you put a backpack in your hand and look at a Minecraft:decorated_pot then right click to open the backpack, you can remove an item then close the backpack. Break the pot to get your backpack back to you with the original item still in the backpack.

### Plugin Version

Oraxen 1.184.0

### ProtocolLib Version

ProtocolLib 5.3.0-SNAPSHOT-732

### Server Software & Version

Purpur Version: 1.21.1-2324-e12a4de (MC: 1.21.1)*

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Th0rgal** [comment]
Hey @ListerWorks , can you reproduce with 1.184.1?
