### ISSUE TITLE
[BUG] chair facing north

### ISSUE THREAD

**Issue by Th0rgal** [oraxen/oraxen#1592]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

https://www.youtube.com/watch?v=-nbcwtBmc6M

### Steps to reproduce

place a chair not north

### Plugin Version

1.185.0

### ProtocolLib Version

n.a.

### Server Software & Version

n.a.

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Th0rgal** [comment]
Unable to reproduce

https://github.com/user-attachments/assets/7a54a441-b090-48c4-942e-d635968c0605

**Comment by redh0t** [comment]
Hi, I'm redhot from discord
try to add my forniture that I sent to you

But I think is not about the json model
Look, I replaced my model with your forniture 

(left) my forniture item & model
(right) my forniture replaced oraxen chair item

![image](https://github.com/user-attachments/assets/42ff3bc2-6540-4cda-ad4f-26741d3c131f)

**Comment by Th0rgal** [comment]
Uploading unable_to_reproduce_480p.mov…

**Comment by Th0rgal** [comment]
I tried to reproduce it again, but it seems to work as expected if I don't specify the yaw
https://github.com/user-attachments/assets/0fcba73f-2346-414c-b430-d7df14377fcf

**Comment by redh0t** [comment]
> I tried to reproduce it again, but it seems to work as expected if I don't specify the yaw https://github.com/user-attachments/assets/0fcba73f-2346-414c-b430-d7df14377fcf

can you see the armorStand in spectator mode?
I can't see you sit down in the forniture
