### ISSUE TITLE
[SUGGESTION] <Add wings/capes/body_cosmetics>

### ISSUE THREAD

**Issue by GNBijke** [oraxen/oraxen#1604]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

A mechanic that allows you to equip paper in a chestplate slot, comparable to the hat feature.

This would allow you to equip balloon, quivers, wings, capes or any body cosmetic in chest slot.

### Reason

- More usable cosmetics
- Not forced to use armor for a cosmetic.

**Comment by Th0rgal** [comment]
Hey, thank you for the suggestion. Unfortunately it is not supporte by minecraft yet as far as I know. Feel free to reopen the issue if you wind a way to do it, I would be happy to add it to Oraxen.
