### ISSUE TITLE
[BUG] Broken items for versions under 1.21.4

### ISSUE THREAD

**Issue by oliviathevampire** [oraxen/oraxen#1606]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0+
- [X] I have checked if any similar bug reports exist

### Description

With newest version of Oraxen every single item is bugged and somehow also dirt and certain deepslate rotations is broken for me on 1.20.4

### Steps to reproduce

Create items in any version under 1.21.4

### System Report
**Plugin Versions:**
- Oraxen: 1.186.0
- ProtocolLib: 5.3.0
**Server Information:**
- Software: Paper
- Version: git-Paper-497 (MC: 1.20.4)
**System Information:**
- OS: Windows 11
- OS Version: 10
- Architecture: amd64

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Th0rgal** [comment]
Thank you, looking into it
