### ISSUE TITLE
[Enhancement] Make use of 1.17's force resource pack settings.

### ISSUE THREAD

**Issue by untuned** [oraxen/oraxen#192]
In 1.17, the server-sided resource pack settings have received an update, allowing verification of the SHA1 hash, sending a message with the prompt, and **forcing acceptance of the resource pack to play**.

It would be great if Oraxen could make use of these settings natively.

**Comment by Th0rgal** [comment]
Hey!

I'm sorry I didn't see your issue earlier. It was introduced two days ago: https://www.spigotmc.org/resources/%E2%98%84%EF%B8%8F-oraxen-custom-items-blocks-plants-emojis-guis-and-more.72448/update?update=417009
