### ISSUE TITLE
resource pack suggestion

### ISSUE THREAD

**Issue by BookWyrm114** [oraxen/oraxen#198]
I noticed that the oraxen pack automatically puts all the files into the /assets/minecraft folder, but my servers resource pack has a lot of the files in separate folders, like /assets/modelengine and a few others, would it be possible to adjust the files to show the "assets" folder so it would be possible to use oraxen's auto-compression instead of having to update dropbox constantly for resource packs like these?

**Comment by Th0rgal** [comment]
Hey there!

You can already create an assets folder within Oraxen/pack, it will be moved to the root assets folder of the pack when oraxen will zip your pack.

I hope this will help you!

**Comment by BookWyrm114** [comment]
Thank you, this helps a lot!
