### ISSUE TITLE
Some ideas I had

### ISSUE THREAD

**Issue by BookWyrm114** [oraxen/oraxen#200]
1: would it be possible to add vehicles to oraxen? I don't know how viable that would be, but I think it would be a fun addition.

2: compatibility with the customcrafting plugin (https://www.spigotmc.org/resources/customcrafting-advanced-custom-recipe-plugin-1-15-1-17-free.55883/) would be nice, I personally prefer it to the oraxen recipe system, as it provides much more options, and I think it would be nice if it would be able to recognize oraxen furniture and blocks in the custom item maker, to make custom 4x4+ crafting table with custom textures and more

3: compatibility with the plugin "PlayerParticles" (https://www.spigotmc.org/resources/playerparticles.40261/) which adds a ton of different types for particles, like "wings", "sphere", etc.

4: worldedit/fastasyncwordedit compatibility would be a nice addition, it's not as important, but would be useful for building with custom blocks

**Comment by Th0rgal** [comment]
1) I'm waiting for a cool thing with new core shaders
2) This plugin is already compatible with Oraxen
3) Okay, but we can also add some to the Aura mechanic
4) great idea

**Comment by BookWyrm114** [comment]
1:That sounds amazing! I can't wait!

2: I know the custom crafting mechanics are, but when attempting to make a custom crafting table using an oraxen block, the custom crafting plugin does not recognize the blocks as actually being blocks, most likely because they're actually paper. i just think it would be awesome to be able to use an oraxen block as a custom crafting table

3: yeah, this wasn't as good of an idea, but I thought it would be a quick way to implement a ton of aura mechanics at once

4: thanks!
