### ISSUE TITLE
Texture pack cannot be used

### ISSUE THREAD

**Issue by wykwey** [oraxen/oraxen#210]
[latest.log](https://github.com/oraxen/oraxen/files/7046890/latest.log)
I built the plugin myself, but I can’t use the official texture pack
The same is true for the version shared by other people (I know this is not good)
![@7{4)$B WF WXLQYJSFEEP3](https://user-images.githubusercontent.com/73051894/130790112-f5ceb34a-d107-4f3e-ad4f-c300a148d469.png)

**Comment by Th0rgal** [comment]
Hello there,

Please disable the advanced pack sending option in your oraxen settings. This option doesn't work with 1.16.5, it requires 1.17+.
