### ISSUE TITLE
Feature Request - MMOITEM Support

### ISSUE THREAD

**Issue by Uinajo** [oraxen/oraxen#212]
Please add MMoItem support where we can add our MMoItem into Oraxen. Also an ability to add Oraxen Items into MMoItem crafting system

Thanks in advance.

**Comment by Mrdeeznut** [comment]
UPDATE

I just found Th0rgal's old message about working together with mmoitem dev and here's their reply

> We will not be using the persistent data containers unfortunately, they’re an awful implementation. If that’s what the hold up is, I don’t think whatever the plan is is gonna come through.

**Comment by Th0rgal** [comment]
Hello!

After discussing with indyuce, we've found a way to bring MMoItem compatibility. It should soon be added to the docs.

Thomas

**Comment by Uinajo** [comment]
Thanks for the reply Thomas, I really appreciate it.
