### ISSUE TITLE
Cannot change best tool type of block

### ISSUE THREAD

**Issue by lucian929** [oraxen/oraxen#214]
I have a block that defaulted to using `AXE` for `best_tools:`. I now need to change the type to `PICKAXE`, but noticed even after reloading the plugin, or restarting the server, the tag still stays as `#minecraft:mineable/axe`.

**Comment by flagz404** [comment]
the reason that it's stuck at #minecraft:mineable/axe is because it's a retextured noteblock....
you can't do much with it though.... (but i might be wrong.)

**Comment by lucian929** [comment]
@flagz404 You should be able to, there is a `best_tools:` option in the config for a reason

**Comment by flagz404** [comment]
oof, my bad 😅

**Comment by Th0rgal** [comment]
> @flagz404 You should be able to, there is a `best_tools:` option in the config for a reason

yes but it should not replace what is displayed on F3
