### ISSUE TITLE
Feature Request - Custom models with inventories

### ISSUE THREAD

**Issue by xIRoXaSx** [oraxen/oraxen#217]
### Description
Hi,  
I'd like to request a feature which enables users to set inventories (like chests, barrels, ...) for custom models (with a defined size).  
That would be a great improvement for customization (cupboards, bedside tables, crates, ...), letting players store items inside those models (persistently).  

### Potential target group for this feature?
Anyone who has custom models.  
Even more for people who are uisng Iris!  

### References
I saw the PR #202 which describes the feature as well.  

***

Thanks in advance for the consideration!

**Comment by Boy0000** [comment]
This was added with the introduction of [Storage Mechanic](https://docs.oraxen.com/mechanics/furniture-mechanic#storage)
