### ISSUE TITLE
Any plan to support Geyser/Bedrock clients?

### ISSUE THREAD

**Issue by Leonardo-Fiori** [oraxen/oraxen#218]
For obvious reasons, bedrock clients connecting through GeyserMC aren't supported by Oraxen.
Are you planning to add some kind of support? Geyser supports custom resource packs

It would be cool for example to just have custom chat ranks or emojis

**Comment by Uinajo** [comment]
The answer is probably no since the bedrock client doesn't have custom model data to begin with...

**Comment by Th0rgal** [comment]
Hello!

Here is a project started by @Auth-Xero to bring oraxen support to geyser users: https://github.com/oraxen/oraxen_geyser

**Comment by Leonardo-Fiori** [comment]
> Hello!
> 
> Here is a project started by @Auth-Xero to bring oraxen support to geyser users: https://github.com/oraxen/oraxen_geyser

Amazing! Will follow the progress there. So far I can see only a Geyser-Spigot fork. Can't wait to see the standalone version to test it out.

**Comment by Th0rgal** [comment]
Great!
