### ISSUE TITLE
Feature Request - Aurelium Skills compatibility 

### ISSUE THREAD

**Issue by Esronn** [oraxen/oraxen#221]
Hello, I've been looking into and discussing making a 3rd party integration between these.
But it would be amazing to have it as an official integration.

Aurelium Skills is the best Skills and Stats plugin out there as far as I am aware, roughly 3000 servers use it with bstats enabled:
https://bstats.org/plugin/bukkit/AureliumSkills/8629

+ it has over 70 000 downloads on Spigot.

https://github.com/Archy-X/AureliumSkills

They have decent APIs and good documentation.

Wishes:
 - Add increased stats (health, strength, Regenaration, Luck, Wisdow, Toughness) to items.
 - Add skill level (like mining or archery) requirement to items.
 
 Currently when adding these using ASkills to an item ingame it looks like this:
![image](https://user-images.githubusercontent.com/69452994/132949479-227c60e7-29e6-4c99-8b6c-1fb9056b7746.png)

**Comment by Passeo** [comment]
Yes Please I need this, I used aureliumskills too. It will be very good feature to have

**Comment by dbmage** [comment]
Yes please, definitely need this!

**Comment by skulltraill** [comment]
+1. Not everyone can be bothered with mmoCore and this is the best alternative. Would love to see AS support.

**Comment by BookWyrm114** [comment]
I also use AS, this would be an amazing addition!

**Comment by DoctaEnkoda** [comment]
Contact the developer first to see if they can do it.

**Comment by Th0rgal** [comment]
That's a good idea. Any idea how I could get more informations about how to implement it?

**Comment by robertosu** [comment]
We need this
