### ISSUE TITLE
[Bug Report] Commands mechanic not functioning

### ISSUE THREAD

**Issue by entertheusername** [oraxen/oraxen#230]
When following the guide, commands mechanic is not functioning when right or left clicking.
Oraxen version : 8cd9e81cf4c92997c95c7477a22f569da6fbcdf6
Server version : Airplane 1.17.1

![image](https://user-images.githubusercontent.com/86881467/133915796-13de7d4e-9c6c-4bbb-9a3e-29b38d061b16.png)

![image](https://user-images.githubusercontent.com/86881467/133915797-bc0b486d-084b-44b1-870c-e0308d9d2c0d.png)

**Comment by Boy0000** [comment]
fixed in #446
