### ISSUE TITLE
Small issue with the Energy Crystal Sword and the Menu Items texture

### ISSUE THREAD

**Issue by starwarsfreak219** [oraxen/oraxen#237]
I have been messing around with Oraxen for the past few weeks, and have noticed some small (not major) issues with some of the default things that are loaded.

The Energy Crystal Sword is too low to the ground when you throw it, along with it having a strange issue with you switch it to your off hand (it's backwards). I did update it on a test server with this new display configuration in the energy_crystal_sword.json:
`	"display": {
		"thirdperson_righthand": {
			"rotation": [0, -90, 55],
			"translation": [0, 4, 0.5],
			"scale": [0.85, 0.85, 0.85]
		},
		"thirdperson_lefthand": {
			"rotation": [90, -90, 55],
			"translation": [0, 4, 0.5],
			"scale": [0.85, 0.85, 0.85]
		},
		"firstperson_righthand": {
			"rotation": [0, 96, 31],
			"translation": [0.2086, 4.8695, 1.13],
			"scale": [0.52, 0.6452, 0.55]
		},
		"firstperson_lefthand": {
			"rotation": [0, -85, -31],
			"translation": [0.2086, 4.8695, 1.13],
			"scale": [0.52, 0.6452, 0.55]
		},
		"ground": {
			"translation": [0, 6, 0]
		}
	}
}`

Using this data appears to have completely fixed the weird small issues with the Energy Crystal Sword.

Something else I noticed is with the menu items texture, the player inventory section is off by one pixel (it is one pixel too low, causing items to look strange, I noticed this with the swords in the game.
![Screenshot 2021-09-28 095908_LI](https://user-images.githubusercontent.com/20121232/135103277-eb0b7469-3ff0-4c26-8014-64bef1c0f1a2.jpg)

I did update the texture on my test server, though the divider is much closer to the inventory (but this does resolve the items being off by a pixel). Here is that updated image that I used on my test server to resolve this:
![menu_items](https://user-images.githubusercontent.com/20121232/135103830-74a1ca3e-bf31-40d2-a5b4-dbe3f1730f5a.png)

**Comment by Th0rgal** [comment]
hey there!

Thanks for your help! What do you mean by "divider is much closer to the inventory"? :)

Thomas

**Comment by starwarsfreak219** [comment]
The chains (which divides the inventory and the menu) when I was mentioning the second issue become relatively close to the inventory, and can be noticeable in game (from my updated image for it). Sorry I didn't clarify it.
