### ISSUE TITLE
Config param automatically_set_glyph_code does not attribut the correct id when enable

### ISSUE THREAD

**Issue by StevenDouillet** [oraxen/oraxen#241]
I have set automatically_set_glyph_code to true in order to put my pack on a production server but when i had new file in glyph directory, the generated code overide other glyph files codes.

Example : 
I got two files in /glyphs : 
- chat_tags.yml
- ranks_tags.yml

Then int first one, codes are 3000 to 3005
And then in the second one, code are 3006 to 3015 

And when i add a new line to the first file, the new generated code for the new glyph is 3006 so conflict with the second file

Maybe you should map all existing codes and then only after attribute a new one that is not used

**Comment by MinMaxxx** [comment]
This happens with custom_model_data too. Sometimes it overwrites existing ones or duplicated them. This is a big issue for the production server.

**Comment by Boy0000** [comment]
Gonna keep track of this in #395
