### ISSUE TITLE
Server crashing incompatibility with the advancedenchants plugin

### ISSUE THREAD

**Issue by BookWyrm114** [oraxen/oraxen#245]
When using the "Trench" (And possibly other mining enchants) on a Hammer, and attempting to mine a block, the server spits out a ton of errors, disconnects all players, and the TPS drops to 1, forcing the owner to forcibly close the server. There might also be other enchantment bugs with AdvancedEnchants, but I have not found any others as of yet

Here's my server log:
[2021-11-03-2.log.gz](https://github.com/oraxen/oraxen/files/7470113/2021-11-03-2.log.gz)

Edit: wrong server log

**Comment by BookWyrm114** [comment]
One possible solution would be to prevent Oraxen hammers from being able to get the trench enchantment, or add some sort of integration so that it's possible to manually add a tag to an Oraxen item to prevent it from having the trench enchantment if that item would conflict with it

**Comment by Th0rgal** [comment]
Hey there!

What tag should be added to prevent an oraxen item from having the trench enchantment?

Thanks for the report,
Thomas

**Comment by BookWyrm114** [comment]
you could use
disable-trench: true/false

or, you could add an option that would allow you to disable any vanilla or AE enchantment, which would allow people to use that to fix any enchantment incompatibilities.

I believe AE uses lore to check if an item has an enchantment, so you could check an items lore when it is enchanted via anvils or enchantment tables. and remove the line of the disabled enchantment for that item, though I'm not 100% sure about that.

disable-enchant: [enchantment name] (for vanilla enchants)
or
disable-enchant: ae:[enchantment name] (for AE enchants)
