### ISSUE TITLE
items that use retextured Hoes can hoe grass blocks

### ISSUE THREAD

**Issue by BookWyrm114** [oraxen/oraxen#246]
The title says it all

**Comment by Th0rgal** [comment]
Hello,

Should I add a mechanic to disable right click event?

Thomas

**Comment by BookWyrm114** [comment]
I think that would be really useful, though if you do, would Oraxen still be able to run actions upon right-clicking that item?

**Comment by Boy0000** [comment]
@BookWyrm114 idk if ur still even present, but this has been fixed in 1.155.2 via Misc Mechanic 👍
