### ISSUE TITLE
A weird issue with making custom blocks

### ISSUE THREAD

**Issue by BookWyrm114** [oraxen/oraxen#249]
For some reason, when trying to make some custom blocks, the entire group of the non-default blocks becomes draconium_ore_end (one of the ores I'm adding) when placed, even though they shouldn't. this only happened after I added the aforementioned block.

Server version: pupur build #1385

Here's my Oraxen folder:
[Oraxen.zip](https://github.com/oraxen/oraxen/files/7491496/Oraxen.zip)

Edit: Upon a tiny bit of further testing, the custom blocks always seem to become the last block in the blocks.yml file when placed, this also only applies to the non-default blocks for some reason

**Comment by BookWyrm114** [comment]
Upon a tiny bit of further testing, the custom blocks always seem to become the last block in the blocks.yml file when placed

**Comment by Th0rgal** [comment]
Hello, did you use a different block id per custom block?

**Comment by matyasvane** [comment]
Some problem with this

**Comment by BookWyrm114** [comment]
> Hello, did you use a different block id per custom block?

Thanks! Sorry about that, I just looked through the docs, I didn’t realize what custom_variation was for, thank you!
