### ISSUE TITLE
New type of block: TRIPWIRE

### ISSUE THREAD

**Issue by TeiBri2** [oraxen/oraxen#259]
Hello, I have a big request regarding a new type of block. The most famous type of block is NOTE_BLOCK and it is very great and you did a good job. But I have a proposal with another type of block and it is TRIPWIRE (block states up to 100+) This block would be used mainly for decorations (Stones, plants, etc.) (See on originrealms.com) I know it would be necessary to disable tripwire on servers but I have an idea. What can be enabled or disabled in yml? I know it would be difficult to implement, but also very great.

(Plus content for this function)
If you go to originRealms and you notice a plant that is TRIPWIRE and is 2 blocks high, then its TRIPWIRE is moved a block higher to avoid bad shade. That would also be great to implement! What do you think?
Now I'm not sure, but I think your plugin has the ability to have a 2D texture in the inventory, but when I put the block, it can have its own model, which would be very great for TRIPWIRE type decorations (Also see OriginRealms)
Thank you for your attention. :-)

**Comment by Boy0000** [comment]
This is now implemented, and the additional feature request will be tracked on #277 👍
