### ISSUE TITLE
Texture doesn' t display

### ISSUE THREAD

**Issue by EMB11D** [oraxen/oraxen#261]
![164c556e7d576209af1b916b464f26d](https://user-images.githubusercontent.com/90746189/142885684-d1f24aa0-0bbb-4c28-84e4-8628f062e9e9.png)

Hey, I built this plugin myself and successfully loaded it into my server, but the textures of the items are not loaded correctly in game.

I'm using Paper1.17.1 and there isn't any error on the console.

**Comment by kacperleague9** [comment]
compiled jars dont include textures
