### ISSUE TITLE
[null] [Oraxen] The resource pack has not been uploaded to the server. Usually this is due to an excessive size.

### ISSUE THREAD

**Issue by bliksemgiel** [oraxen/oraxen#262]
help i get this error

**Comment by qrawless** [comment]
i have the same problem +

**Comment by bliksemgiel** [comment]
nevermind it fixed it self today

**Comment by bliksemgiel** [comment]
> i have the same problem +

i think you need to wait a day or so probbably an error that just happens

**Comment by qrawless** [comment]
atlas.oraxen may be corrupting because it crashed. resource pack is stored there

**Comment by ExagonoIZI** [comment]
Same problem here. I can't fix it!

**Comment by ziayzu** [comment]
SAME PROBLEM I FACE NOW SAME PROBLEM HELP SIR
Oraxen] The resource pack has not been uploaded to the server. Usually this is due to an excessive size.
