### ISSUE TITLE
AT

### ISSUE THREAD

**Issue by cian1203099189** [oraxen/oraxen#265]
>.... [11:29:12 INFO]: Touch issued server command: /o pack send Touch
>.... [11:29:12 INFO]: FieldAccessException: No field with type boolean exists in class PacketPlayOutResourcePackSend.
>.... [11:29:12 INFO]: at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:365)
>.... [11:29:12 INFO]: at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345)
>.... [11:29:12 INFO]: at io.th0rgal.oraxen.pack.dispatch.AdvancedPackSender.sendPack(AdvancedPackSender.java:51)
>.... [11:29:12 INFO]: at io.th0rgal.oraxen.commands.CommandsManager.lambda$getPackCommand$3(CommandsManager.java:96)
>.... [11:29:12 INFO]: at io.th0rgal.oraxen.shaded.commandapi.executors.IExecutorNormal.executeWith(IExecutorNormal.java:43)
>.... [11:29:12 INFO]: at io.th0rgal.oraxen.shaded.commandapi.CustomCommandExecutor.execute(CustomCommandExecutor.java:114)
>.... [11:29:12 INFO]: at io.th0rgal.oraxen.shaded.commandapi.CustomCommandExecutor.execute(CustomCommandExecutor.java:102)
>.... [11:29:12 INFO]: at io.th0rgal.oraxen.shaded.commandapi.CustomCommandExecutor.execute(CustomCommandExecutor.java:78)
>.... [11:29:12 INFO]: at io.th0rgal.oraxen.shaded.commandapi.CommandAPIHandler.lambda$generateCommand$0(CommandAPIHandler.java:307)
>.... [11:29:12 INFO]: at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
>.... [11:29:12 INFO]: at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176)
>.... [11:29:12 INFO]: at net.minecraft.server.v1_16_R3.CommandDispatcher.a(CommandDispatcher.java:267)
>.... [11:29:12 INFO]: at org.bukkit.craftbukkit.v1_16_R3.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45)
>.... [11:29:12 INFO]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
>.... [11:29:12 INFO]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810)
>.... [11:29:12 INFO]: at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2168)
>.... [11:29:12 INFO]: at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1983)
>.... [11:29:12 INFO]: at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1936)
>.... [11:29:12 INFO]: at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49)
>.... [11:29:12 INFO]: at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7)
>.... [11:29:12 INFO]: at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
>.... [11:29:12 INFO]: at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
>.... [11:29:12 INFO]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
>.... [11:29:12 INFO]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
>.... [11:29:12 INFO]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
>.... [11:29:12 INFO]: at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252)
>.... [11:29:12 INFO]: at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245)
>.... [11:29:12 INFO]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
>.... [11:29:12 INFO]: at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1206)
>.... [11:29:12 INFO]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120)
>.... [11:29:12 INFO]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
>.... [11:29:12 INFO]: at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by Boy0000** [comment]
closing because 1.16
