### ISSUE TITLE
BlockMechanicFactory#setBlockModel throws NullPointerException

### ISSUE THREAD

**Issue by NichtStudioCode** [oraxen/oraxen#279]
When calling ``BlockMechanicFactory.setBlockModel`` in order to place a block, a NullPointerException is thrown.

```
java.lang.NullPointerException: Cannot invoke "io.th0rgal.oraxen.mechanics.MechanicFactory.getMechanic(String)" because "mechanicFactory" is null
        at io.th0rgal.oraxen.mechanics.provided.gameplay.block.BlockMechanicFactory.setBlockModel(BlockMechanicFactory.java:84) ~[?:?]
        at xyz.xenondevs.nova.integration.customitems.plugin.Oraxen.placeBlock(Oraxen.kt:23) ~[?:?]
```

It is caused by ``MechanicsManager.getMechanicFactory("block");`` not finding a ``MechanicFactory``, as a factory under that name does not exist. I did a little debugging, and it seems like this should be ``MechanicsManager.getMechanicFactory("noteblock");``?

**Comment by Boy0000** [comment]
Closing due to API rework and deprecating BlockMechanic
