### ISSUE TITLE
Missing API method to remove Oraxen blocks

### ISSUE THREAD

**Issue by NichtStudioCode** [oraxen/oraxen#280]
There doesn't seem to be an API method to destroy blocks and retrieve a list of drops from Oraxen without calling the BlockBreakEvent.

**Comment by Boy0000** [comment]
#337 should resolve this if im correct

**Comment by NichtStudioCode** [comment]
> #337 should resolve this if im correct

No, #337 just seems to add events, I was talking about an API method to remove Oraxen blocks from the world and get their drops

**Comment by Boy0000** [comment]
Added in #538 but probably wont be done for a bit longer as it entirely reworks the API
