### ISSUE TITLE
BUG REPORT!!! String Custom Blocks

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#282]
Stepping on custom blocks with strings turns them into string again, but when you get out it turn back
![image](https://user-images.githubusercontent.com/47507632/150072933-2c7b1222-7888-43d2-aab2-6aef4501a6c7.png)

![image](https://user-images.githubusercontent.com/47507632/150072953-59d4a8e7-e439-49e0-856c-f90c487623ce.png)

![image](https://user-images.githubusercontent.com/47507632/150072968-a9fe1142-8e54-44c3-8281-c945fc0041f0.png)

**Comment by PatoTheBest** [comment]
Also placing blocks next to them updates them and changes it's state and you cannot place normal string on the ground

**Comment by Boy0000** [comment]
This should be fixed in #303 so can be closed
