### ISSUE TITLE
Pack is loading twice even tho I'm using Bungee Pack Layer

### ISSUE THREAD

**Issue by LuluxClient** [oraxen/oraxen#289]
Hey after copy pasting the config of oraxen on the hubs and the main server I started the bungee, the hub and the main server (hub and main server have the SAME config of oraxen everything is the same) and after a restart I now need to load the pack twice for some reason. I had a similar issue with itemsadder when using auto external host so it might be because of the polymath host thing from oraxen since i'm using the public one.

I'm on 1.18
Java: 17
plugin list: 
![image](https://user-images.githubusercontent.com/62576432/152375328-d7867544-ea98-44dc-8398-9f6baa655b47.png)
no error logs

**Comment by DanyGreaver** [comment]
Bungee layer doesn't work for now. 
The dev will update it. 
check out an alternative on the discord.
