### ISSUE TITLE
Pack considered invalid when it is generated with either a "blockstates" or "fonts" folder

### ISSUE THREAD

**Issue by IoIxD** [oraxen/oraxen#294]
This is a bug that perplexes me. I compiled Oraxen using `gradle shadowJar` and the only line I changed was one that allowed me to use a custom Polymath server over http (because for some reason the plugin tries to access an http server over https...I don't think it's possible to route https requests to http so I have no idea what you've done with your setup). It works just fine, except for the part where the packs it generates get deleted by Minecraft instantly with a really weird error (and thus, does not actually get applied to the user's game).

`Deleting /home/gavin/.minecraft/server-resource-packs/28e2f456949892db95f6cbbecd70dbf9ba157be4 as it does not match what we currently have (63598337 vs our 209960).`

Even stranger, that second number is always different. This would imply a weird issue in which I've managed to screw with the code, but I only changed ONE line.

`this.serverAddress = "https://" + serverAddress + "/";` > `this.serverAddress = "http://" + serverAddress + "/";`

Furthermore, I switched to the default Polymath server, and I'm still getting the same error.

Attached to this post is the pack in question (which becomes valid after you unzip and rezip it), my config file (the zipbomb protection thing is disabled), and the modified Polymath.java. I am at a loss for what I've done wrong here.

https://ioi-xd.net/files/pack.zip
https://ioi-xd.net/files/settings.yml
https://ioi-xd.net/files/Polymath.java

**Comment by IoIxD** [comment]
The `blocks/mushroom_stem.json` file also doesn't get generated, suggesting there may be a problem with the blocks.yml file.

https://ioi-xd.net/files/blocks.yml

**Comment by Th0rgal** [comment]
Hey there!

Unfortunately Minecraft had some bugs with ssl certificates on some client versions. We needed to use HTTP to be supported by a maximum of players.

**Comment by IoIxD** [comment]
Hi, which versions are you referring to? That said, I don't think this is relevant as the pack downloads just fine, it's just that what gets generated cannot get applied to the game for some reason.

**Comment by IoIxD** [comment]
Ok, I found out what the problem actually is by spinning up a test server. When the pack is generated with either the `font` or `blockstates` folder, the pack is suddenly invalid.
Both are available in this zip:
[huh.zip](https://github.com/oraxen/oraxen/files/8312597/huh.zip)

**Comment by Boy0000** [comment]
i will assume this is a duplication error, aka ur importing default.json but oraxen also generates one
same if ur importing blockstatefiles oraxen generates. If not reopen this i suppose
