### ISSUE TITLE
Certain texture sizes fail to load with optifine installed

### ISSUE THREAD

**Issue by Cboxhero** [oraxen/oraxen#305]
Migrating from IA to oraxen and ran into an issue when transferring over my sign models. These are simple planes with a large texture applied for crate holograms, shop signs or otherwise. Some of these textures fail to load (only with optifine installed) when implemented through oraxen, however. Itemsadder pack has no issues with the same texture. Single player with the model loaded through optifine CIT also works, so it has been narrowed down to only being an oraxen issue. There are also 0 console or client errors.

Original texture size is 480x130. Scaling it to 240x65 allows it to show in game. Also extending the crop to 480x480 allows it to load. 

What it should look like in game inside of an armorstand: 
![image](https://user-images.githubusercontent.com/9125502/160518228-c33acc85-3bbb-40c9-855d-5e2fa2182645.png)

what it looks like when implemented through oraxen:
![image](https://user-images.githubusercontent.com/9125502/160518352-e84c6445-9c08-4e21-9cdc-7937569c618a.png)

Texture in question:
![heroic_armor](https://user-images.githubusercontent.com/9125502/160519217-7e8279c7-b7e5-4185-955a-9a576f409f73.png)

I have worked with several people to troubleshoot this issue and absolutely everything is in it's right place and named correctly.

**Comment by Boy0000** [comment]
if this is still an issue, please stop by the discord for support. Hard to go back and forth in a github issue when this most likely is just a misconfigured somehting
