### ISSUE TITLE
Oraxen & Towny Incompatibility 

### ISSUE THREAD

**Issue by ItsSynchro** [oraxen/oraxen#309]
Hello,

I've gone ahead and tested this on multiple Oraxen and Towny instances however it has yielding the same results. 
Using the Block mechanic from Oraxen does not protect those blocks from being broken from Bedrock players. Whilst it does protect it against Java players. This is only Towny that the incompatibility occurs as it doesn't occur on WorldEdit.

Oraxen Version: 1.131.0
Towny Version: 0.98.1.0

Server Version: 1.18.2

Evidence:
https://www.youtube.com/watch?v=Kuuezy-tjdw

**Comment by Boy0000** [comment]
@ItsSynchro Please confirm this is still an issue with 1.136.2
Towny got updated compatibility recently.

Keep in mind Oraxen has no intent to support bedrock players.
Cross-version is a rabbit hole that we prob dont wanna dig into just yet

Geyser is apparently making a more expensive API so might happen after that but yeah
Just too many factors atm
