### ISSUE TITLE
Custom shaders incompatibility

### ISSUE THREAD

**Issue by TheLaoming** [oraxen/oraxen#317]
Hello,
As you probably know, oraxen does not support custom shaders when you decide to use custom armors.
Armor mechanic is way good, but unfortunatelly it's 2022 and a lot of my players using shaders and reporting this to me as a bug.

Is there a way to add shaders support? Even manual via files. It's really important for me.
Thanks!

**Comment by EspartaProJunior** [comment]
> 

https://docs.oraxen.com/configuration/custom-armors/shader-armors
