### ISSUE TITLE
Shapeless and furnace recipes support

### ISSUE THREAD

**Issue by Th0rgal** [oraxen/Oraxen#32]
Hey @yzl210,

I just tried your pr and ran into a few problems:
- This is the error that I get when I try to load a shapeless recipe I just generated:
https://hasteb.in/ififuqex.lua
- I can't put an item in the result slot of the furnace builder inventory
- When I already opened a builder, I can't replace it by another one (this is my fault but we could not see it before because we had only shaped recipes).
I will work on the result slot issue by tomorrow, I'ld love if you could check the first one tho.

Thomas!

**Comment by yzl210** [comment]
So, when I try it, the first two didn't happen, so can you send me the config it generated, thanks.

**Comment by yzl210** [comment]
I can't reproduce the first issue, did you change anything in the config?

**Comment by yzl210** [comment]
The second issue should be fix in [this](https://github.com/oraxen/Oraxen/pull/31/commits/7783ad9b279f8a4e376d99debeb7638c48f5eaa9#diff-eb6dd3a952420f0b4ee4b2fadb397375)

**Comment by Th0rgal** [comment]
The first problem comes from the fact that the generated config does not include the material of the itemstack (if this is a simple itemstack) but its amount instead, for example:
glass_sword:
  result:
    oraxen_item: glass_sword
  ingredients:
    A:
      amount: 1
    B:
      amount: 1

As you can see the ingredients cannot work

The second problem comes from the inventory name. I'm working on it (I don't understand why but the inventory created from a furnace builder doesn't have the same name than what we gave it)

**Comment by yzl210** [comment]
I find the cause of the first problem, in the `setSerializedItem` function, if you have more than 1 Oraxen item in an ItemStack the statement `OraxenItems.getItemById(itemID).build().equals(itemStack)` will be false so it doesn't think it's an Oraxen item.

**Comment by Th0rgal** [comment]
> I find the cause of the first problem, in the `setSerializedItem` function, if you have more than 1 Oraxen item in an ItemStack the statement `OraxenItems.getItemById(itemID).build().equals(itemStack)` will be false so it doesn't think it's an Oraxen item.

Alright, I fixed the bug with the watermark thing, now the furnace recipes are working great. I noticed that you added some default recipes for ores, great work!

**Comment by Th0rgal** [comment]
Btw if you have discord, don't hesitate to join the official discord (https://discord.gg/ceX5Zv8) or add me (th0rgal#8470)

**Comment by yzl210** [comment]
joined!

**Comment by yzl210** [comment]
fixed!

**Comment by Th0rgal** [comment]
Nice!

**Comment by yzl210** [comment]
Is it working?

**Comment by Th0rgal** [comment]
> Is it working?

yep, I just need to fix a few errors and I'll release it ! Thank you very much!
