### ISSUE TITLE
[Suggestion] Support for doing an action when given redstone power

### ISSUE THREAD

**Issue by oliviathevampire** [oraxen/oraxen#320]

**Comment by Boy0000** [comment]
Ideas on the top of my head of this.

* Check adjacent blocks to a block wiht redstone mechanic
* Lamps (Determines the lightblock created depending on the redstones power
  - If given multiple sources, prioritizes the strongers signal
* If block is powered, swap to new block. This is rather simple and similar to farmblocks in #316  
  - This kinda ties into lamps as u would probably swap the displayed texture
