### ISSUE TITLE
[BUG] Glyph and Oraxen loading bug

### ISSUE THREAD

**Issue by Ozander16** [oraxen/oraxen#346]
### I have checked...

- [x] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

When I add any new glyph (just copy change name etc.) I get this bug: https://mclo.gs/f18HIKB

### Steps to reproduce

When I add new glyph, do `/oraxen reload all`, I get bug. If i remove it from config and restart server I still get bug.
[Click to get bug](https://mclo.gs/f18HIKB)

### Plugin Version

Oraxen v1.135.0

### ProtocolLib Version

ProtocolLib v4.8.0

### Server Version

Paper 1.18.2

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
Can you provide the glyph config aswell?
Also there is a support discord thats probably better for getting a reply faster but
