### ISSUE TITLE
[BUG] Plants don't work in latest versions

### ISSUE THREAD

**Issue by skvipers** [oraxen/oraxen#352]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

In the latest versions, plants do not work, or rather their last stage. They just disappear. In version 1.30.1 it still works, in version 1.33.0 it no longer works. In intermediate between them did not check.

There have already been written about the impossibility of wearing hats with models. I also faced this problem and the same in new versions. In 0.130.1 they work.

### Steps to reproduce

Install Oraxen 1.33.0 +
Plant a plant and wait for the last stage

### Plugin Version

1.33.0 +

### ProtocolLib Version

4.7.1

### Server Version

1.18.2

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
This is because of the default config being incorrect.
Next release will have them fixed, in the meantime you can check out #348 to see how to correct it
