### ISSUE TITLE
[SUGGESTION] Common api with itemsadder

### ISSUE THREAD

**Issue by NeumimTo** [oraxen/oraxen#353]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Would it be possible to agree on some common patterns/apis with itemsadder devs?

For example to get a glyph/image from resourcepack with oraxen you can use papi %oraxen_xxx% but with itemsadder you have to use %img_xxx%

This makes things kind of hard if you, as a plugin developer, want to keep compatibility with both itemsadder and oraxen. 
If you rely on papi you need to manage duplicate configurations. 
If you need to create ox/ia managed itemstack you have to create two different implementations to lookup item by its id.

Plugins should not really care what resourcepack manager is the server using. Its similar to how plugins handle economy, theres vault and other economy plugins can use vault apis, then plugin developers can use vault as a single dependency if they need to manipulate player balances.

Mimic works in similar way as provides api layer for rpg plugins and their class and level systems.

### Reason

To make developers life easier

**Comment by Boy0000** [comment]
Due to the way papi works and the fact that itemsadder is closed source, i would be suprised if this happens
Essentially papi needs an identifier so having it be oraxen and itemsadder etc makes sense
