### ISSUE TITLE
Issues & Suggestions on Block Mechanic

### ISSUE THREAD

**Issue by ijerrychan** [oraxen/Oraxen#36]
1. Netherite pickaxe in 1.16 doesn’t work with “minimal tool”.It seems that it isn’t being considered as a “tool” at all.
2. Could you make custom blocks “unbreakable ” when not using a tool that reaches minimal requirement? Just to prevent players from breaking the block by accident and getting nothing.
3. Ore generating for vanilla perhaps?

**Comment by Th0rgal** [comment]
> 1. Netherite pickaxe in 1.16 doesn’t work with “minimal tool”.It seems that it isn’t being considered as a “tool” at all.
> 2. Could you make custom blocks “unbreakable ” when not using a tool that reaches minimal requirement? Just to prevent players from breaking the block by accident and getting nothing.
> 3. Ore generating for vanilla perhaps?

1) Thanks I'll work on a fix
2) Well I could an option to cancel the block breaking but it wouldn't look reallly realistic.
3) I believe this is already possible with some simple world generators (and free), you should ask on the discord.

**Comment by Th0rgal** [comment]
Netherite support introduced in the last update!
