### ISSUE TITLE
[SUGGESTION] Allow for vanilla item overwriting

### ISSUE THREAD

**Issue by Cboxhero** [oraxen/oraxen#360]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Allow vanilla models to be overwritten then add custom model data overrides THAT file rather than always generating a new one.

### Reason

Allows you to replace models/textures of vanilla items.

**Comment by Boy0000** [comment]
Not entirely sure what this issue is about.
If you mean like importing paper.jsons into the pack, then you just wanna either:
1. Delete all oraxen default items that use paper so that oraxen doesnt generate one
2. Recreate all your items inside oraxen so that it creates one for you wil everything in it

**Comment by Cboxhero** [comment]
> Not entirely sure what this issue is about. If you mean like importing paper.jsons into the pack, then you just wanna either:
> 
>     1. Delete all oraxen default items that use paper so that oraxen doesnt generate one
> 
>     2. Recreate all your items inside oraxen so that it creates one for you wil everything in it

With the current version of the plugin, it is not possible to overwrite/re-texture an existing minecraft item if you are ALSO using that item as a material within an item config.

For instance, if I wanted to have custom models for all the vanilla swords, I could then no longer have custom swords beyond that, as Oraxen creates a new file on pack generation instead of checking for an existing one within the minecraft namespace and appending it.

**Comment by Boy0000** [comment]
it will only check for the diamond_sword.json etc yes
iirc setting an item to CMD 0 makes it the default but not entirely sure.
if not i  suppose yes you cant remodel a vanilla item and then use it for custom stuff after

**Comment by Cboxhero** [comment]
It looks like setting CMD to 0 works, so thank you! It would be beneficial to add this to the documentation.
