### ISSUE TITLE
[BUG] Swing speed issue.

### ISSUE THREAD

**Issue by gamergeek1213** [oraxen/oraxen#372]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [x] I have checked if any similar bug reports exist

### Description

When using Oraxen to create a weapon its swig speed by default is set to 1.6 which is the speed of Minecraft's swords, But it does not appear to be the same swing speed as a sword instead it has the swing speed of your hand. When testing the Diamond sword vs the Glass sword the swing speed of the glass sword was almost double the default Diamond sword which the Glass sword is based off of.

### Steps to reproduce

Using /o inv to pull out a glass sword you'll see swinging it has a higher speed then a normal sword.

### Plugin Version

Version 1.135.4

### ProtocolLib Version

4.8.0

### Server Version

This server is running Paper version git-Paper-267 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
After testing this is a vanilla thing.
The TLDR is this:
a sword by default has 1.6
if you then add a modifier of 2.6 you are doing (4.0 +2.6)
the 4.0 is the default of a player, so to properly calculate the speed you want you need to do:
4.0 - x = intended speed
Example:
want 2.0 speed
add a modifier of -2.0

There is also no way to have the lore entry not be -2 sadly.
This is a vanilla thing and not oraxens sadly
Hope that made sense
