### ISSUE TITLE
[BUG] one_usage

### ISSUE THREAD

**Issue by Domzzo** [oraxen/oraxen#388]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

Adding one_usage to mechanic doesn't work. I tried with default oraxen config.

example_custom_mechanic:
  displayname: "<gradient:#FA7CBB:#F14658><bold>My Item With A Custom Mechanic"
  material: DIAMOND_SWORD
  Mechanics:
    custom:
      test:
        one_usage: true
        cooldown: 200 # in ticks
        event: "CLICK:right:all"
        conditions:
          - "#player.hasPermission('example.permission')"
        actions:
          - '[console] give <player> cooked_beef 1'

### Steps to reproduce

Use the example sword from /o inv, and click for it to give you cooked beef. One usage will not work.

### Plugin Version

Oraxen version 1.135.4
Author: Th0rgal

### ProtocolLib Version

ProtocolLib version 4.8.0
Provides read/write access to the Minecraft protocol.
Authors: dmulloy2 and comphenix

### Server Version

Current: git-Purpur-1632 (MC: 1.18.2)*
* You are running the latest version

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
@Domzzo please update to the latest release of [1.135.7](https://www.spigotmc.org/resources/%E2%98%84%EF%B8%8F-oraxen-add-items-blocks-armors-hats-food-furnitures-plants-and-gui.72448/update?update=460070) and try

**Comment by Domzzo** [comment]
@Boy0000 That solved the issue, seems like I didn't notice the latest version, my bad.
