### ISSUE TITLE
[BUG] 0 block update

### ISSUE THREAD

**Issue by Mitsu13Ion** [oraxen/oraxen#392]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

no block update, impossible to rotate the stairs, dispenser, observer
no blocks are updated automatically

the redstone doesn't work anymore

### Steps to reproduce

1.18.1 Paper - and just 1 redstone block and 1 piston

### Plugin Version

>....=>.... [20:36:51 INFO]: Oraxen version 1.136.0
>.... [20:36:51 INFO]: Author: Th0rgal

### ProtocolLib Version

>....=>.... [20:36:35 INFO]: ProtocolLib version 4.8.0
>.... [20:36:35 INFO]: Provides read/write access to the Minecraft protocol.
>.... [20:36:35 INFO]: Authors: dmulloy2 and comphenix

### Server Version

 This server is running Paper version git-Paper-341 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc1752f)
You are 45 version(s) behind

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
please try with 1.136.1 @Mitsu13Ion
