### ISSUE TITLE
Items get assigned custom_model_data overlapping with pre-assigned custom_model_data

### ISSUE THREAD

**Issue by VergilPrime** [oraxen/oraxen#395]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

 - Some items configured have custom_model_data set to a value
 - Some items configured do not have a custom_model_data
 - These items share a material

What can happen is that the items with configured cmd can overlap with generated cmd.

This is likely because items are loaded (and cmds assigned) as they are read, to fix this you would need to store the cmd-unassigned items in a list and wait for all the cmd-assigned items to be loaded before attempting to assign cmd values and load those items.

### Steps to reproduce

Create a bunch of items that use paper as a material, starting at the custom_model_data of 1. These items may need to be in another file besides gui for this test.

gui items have paper as a material and may load first, assigning 1, 2, and 3 to these items on pack creation.

Check inside the resulting pack.zip at assets\minecraft\models\item\paper.json and see that some items have overlapping custom_model_data values.

### Plugin Version

1.136.0

### ProtocolLib Version

5.0.0 snapshot b568

### Server Version

purpur 1.19 1663

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Emibergo02** [comment]
i had the same problem. it seems that oraxen checks one file at a time for duplicates. so if you have duplicates in different files this can happen

**Comment by Emibergo02** [comment]
are you sure that the items in question do not have the same name/oraxenId?

**Comment by VergilPrime** [comment]
Very sure, initial items that had this issue were the default gui items "arrow_next_icon" and my custom "red_heart".

**Comment by Emibergo02** [comment]
i think the only solution is to queue non-generated custommodeldata to the end of the config load and then generate ids starting from highest model data (like /o highest_modeldata)

**Comment by Emibergo02** [comment]
@Boy0000 do you think you can queue custom-model-id generation to the end of item files reading?

**Comment by Boy0000** [comment]
if someone could supply me with config examples that would make me able to reproduce it.
Dont quite get the issue, cant reproduce it and from my minor overlook the code makes it "impossible" aswell but

**Comment by Emibergo02** [comment]
You have 3 files in items directory: bbb.yml ccc.yml zzz.yml with all items with PAPER as material
Step to reproduce:
1- set automatically_set_model_data: true in settings.yml
2- generate all model ids
3- add a new file to items directory called aaa.yml
4- add an item to aaaa.yml with PAPER as material without specifying the modelid
5- reload Oraxen.
it would generate a modelid equal to another item.
this happens because Oraxen loads items sequentially based on the file without checking subsequent files for duplicates

**Comment by Emibergo02** [comment]
solved in the new version

**Comment by Boy0000** [comment]
Weird cant say anything was done to fix it

**Comment by VergilPrime** [comment]
I triggered the issue again a couple days ago. I think if I change all my items from using paper cmd 1-10 to a higher number like 200-210 it won't happen. It always happens with the smallest cmd values, so it always happens to the same items. Why it happens sometimes but doesn't happen other times I have no idea.
