### ISSUE TITLE
[BUG] Custom Enchant disappear everytime i logout and login | CLOSED / SOLVED

### ISSUE THREAD

**Issue by Dvaelin121** [oraxen/oraxen#397]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [x] I have checked if any similar bug reports exist

### Description

Custom Enchant used: EcoEnchants (Auxilor)

Detail:
So i have an enchantment on my oraxen weapon but when i logout of the game and login after 5 hours, the enchantments is gone just like it never enchanted with the custom enchantments.

I don't know if this is oraxen bug or bug from the custom enchants. but i hope you can help me solve this.

### Steps to reproduce

So i tried to make an experiment, i use 1 netherite weapon and 1 weapon from oraxen inventory, i enchant those two with unbreaking 3 and sharpness 5. After that i logout from the game and comeback 1 hour later and the enchantment on oraxen weapon is disappear like i think.

### Plugin Version

Oraxen 1.136.1 (Latest)

### ProtocolLib Version

ProtocolLib (DevBuilds #569)

### Server Version

Paper 1.19

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Dvaelin121** [comment]
New Experiment (28/06/2022): 

I change from custom enchant to vanilla enchantments, i enhcant the weapon from oraxen inventory with sharpness 5 and unbreaking 3. After that i leave my server again and go to sleep. 

Today (29/06/2022) i open my minecraft and login into my server again and the enchantments disappear.

I conclude that this happen whenever the server restart or the enchantments disappear for a certain hours.

**Comment by Dvaelin121** [comment]
Experiment #3 (Same day as Experiment 2)

I use storm sword, anubis head, and bedrock pickaxe as the subject.

Vanilla and Custom Enchantmenst on each of these. Then i save the game by /save-all.

I logout, and restart the server, login again and all the enchantments disappear.


New Conclusion: Enchantments disappear when the server restarting and not disappear when i left it for a certain hours.

**Comment by Boy0000** [comment]
It would probably be because it resets the oraxen item to the base copy of it
Tho it should store itemmeta on it and not remove it, might be because of how this plugin handles enchantments
hard to say completely but its probably a combination of an issue on oraxen and the other plugins end

**Comment by Dvaelin121** [comment]
I see, is there a way to fix this?

**Comment by Boy0000** [comment]
not sure, imean if the plugin registers the enchantments as normal enchantments there should be no issue
but custom enchantments arent really easy to support compatibility for ithink.
would have to look more into it so ill see

**Comment by Dvaelin121** [comment]
that may be the case, but i have tested vanilla enchantment too and not using the custom enchantments, it disappear as well.

I'll try to do some experiment later since im still at my college.

**Comment by Boy0000** [comment]
you can check `auto-update-items` inside settings.yml. If thats enabled it might be why it resets it
its disabled by default afaik so not sure if you enabled it but

**Comment by Dvaelin121** [comment]
You're right, i make auto_update_item to true.

The enchantments doesn't disappear anymore. Thanks man

My bad xD
