### ISSUE TITLE
[BUG] Emoji

### ISSUE THREAD

**Issue by baranshn** [oraxen/oraxen#401]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

There is a bug with emojis.

Let me explain this with an example.

I named the emoji as look. And
I created a 2nd emoji which is lookeyes

When I type lookeyes in chat, it says eyes next to the look emoji.

### Steps to reproduce

lookeyes:
  texture: emoji/lookeyes
  ascent: 7
  height: 8
  chat:
    placeholders:
      - ".lookeyes"

look:
  texture: emoji/look
  ascent: 7
  height: 8
  chat:
    placeholders:
      - ".look"

### Plugin Version

1.136.0

### ProtocolLib Version

4.8.0

### Server Version

This server is running Paper version git-Paper-299 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 76ed156)
You are 87 version(s) behind
Download the new version at: https://papermc.io/downloads

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
this isnt a bug, its just a bad placeholder youve set
make it `:look:` and `:lookeyes:` or something so it knows when it is done
