### ISSUE TITLE
[BUG] RECIPES NOT WORKING WITH AMOUNT

### ISSUE THREAD

**Issue by vithov1120** [oraxen/oraxen#406]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

 All items with amount not working (you can craft it with 1 item of the type)
  ingredients:
    A:
      minecraft_item:
        ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: DEEPSLATE
        amount: 16
  shape:
  - AAA
  - _A_
  - AAA

  i created it with /o recipes builder ...
  
 next thing: that not possible to craft... it show in recipes...

medium_filament_blue:
  result:
    minecraft_item:
      ==: org.bukkit.inventory.ItemStack
      v: 3105
      type: PAPER
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#F933FF","text":"M"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#F933FB","text":"e"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FA33F6","text":"d"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FA33F2","text":"i"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FA33ED","text":"u"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FB33E9","text":"m"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FB33E4","text":"
          "},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FB33E0","text":"f"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FB33DB","text":"i"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FC33D7","text":"l"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FC33D2","text":"a"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FC33CE","text":"m"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FD33C9","text":"e"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FD33C5","text":"n"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FD33C0","text":"t"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FE33BC","text":"
          "},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FE33B7","text":"b"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FE33B3","text":"l"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FE33AE","text":"u"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FF33AA","text":"e"}],"text":""}'
        custom-model-data: 108
        PublicBukkitValues:
          oraxen:id: medium_filament_blue
          oraxen:furniture: 1b
          oraxen:if-uuid: '[B;22B,-32B,106B,-45B,-2B,-92B,68B,-52B,-96B,127B,-66B,-104B,-87B,77B,-99B,18B]'
  ingredients:
    B:
      minecraft_item:
        ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: PAPER
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#F933FF","text":"M"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#F933FB","text":"e"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FA33F6","text":"d"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FA33F2","text":"i"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FA33EE","text":"u"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FA33EA","text":"m"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FB33E5","text":"
            "},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FB33E1","text":"f"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FB33DD","text":"i"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FC33D8","text":"l"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FC33D4","text":"a"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FC33D0","text":"m"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FC33CC","text":"e"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FD33C7","text":"n"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FD33C3","text":"t"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FD33BF","text":"
            "},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FE33BA","text":"e"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FE33B6","text":"m"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FE33B2","text":"p"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FE33AE","text":"t"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FF33A9","text":"y"}],"text":""}'
          custom-model-data: 89
          PublicBukkitValues:
            oraxen:id: medium_filament_empty
            oraxen:furniture: 1b
            oraxen:if-uuid: '[B;-59B,36B,-28B,4B,96B,67B,72B,-80B,-105B,-94B,-17B,117B,-54B,37B,-26B,-83B]'
    A:
      minecraft_item:
        ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: STRING
        amount: 32
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"text":"Filament string blue"}],"text":""}'
          custom-model-data: 2
          PublicBukkitValues:
            oraxen:id: string_blue
            oraxen:if-uuid: '[B;25B,-101B,-17B,3B,100B,-92B,76B,38B,-83B,-24B,-55B,74B,-20B,39B,-79B,-93B]'
  shape:
  - AAA
  - ABA
  - AAA

### Steps to reproduce

create more recipes

### Plugin Version

1.19

### ProtocolLib Version

newest

### Server Version

1.19

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
I think adding amount in the recipe doesnt work. Only the result lets you specify a amount the item should have.
Closing this for now
