### ISSUE TITLE
[BUG] Harvesting and Lifeleech ability bug.

### ISSUE THREAD

**Issue by NotSharwan** [oraxen/oraxen#419]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

Two of these mechanism namely Harvesting and Lifeleech are having issues in our server right now, loosing extra crops from the harvesting ability and non-targetable mobs becoming ghost whened killed using the Lifeleech ability.

### Steps to reproduce

Harvesting - when used in large radius (64blocks) the extra crops which dosnt able to fit in the inv drops on ground and after just couple of second despawns
Lifeleech - When killed mobs something they turning in a ghost non-targetable mobs, close to being brain dead mobs.

### Plugin Version

21.07 12:01:42 [Server] INFO Oraxen version 1.137.0
21.07 12:01:42 [Server] INFO Author: Th0rgal

### ProtocolLib Version

21.07 12:05:35 [Server] INFO ProtocolLib version 5.0.0-SNAPSHOT

### Server Version

This server is running Paper version git-Paper-"a76a1ab" (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: a76a1ab)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
I've fixed the issue with Harvesting but cant really replicate the one mentioned for Lifeleech @NotSharwan ?
Is it just killing a mob as you steal life from it? nothing in the code really touches the mob so not sure thats the reason.
Could it be caused by another plugin you have enabled?

**Comment by NotSharwan** [comment]
It occurs whenever I kill a mob, whether spawner or naturally spawned. They will die if I hit them with a tool that has that ability (Lifeleech), but they will still attack me. I won't be able to kill it because it's technically dead. 
I'm not sure if any of my server plugins could be causing this.

Here's a list of all my server plugins:
https://i.imgur.com/BXSaZMe.jpg
Also included is a video demonstrating the lifeleech bug:
https://i.imgur.com/LTzBpKb.mp4

**Comment by Boy0000** [comment]
Can you try it on a server with no other plugins than Oraxen and Protocollib?
I cant see why this would happen and its the easiest way ithink to find out if its Oraxen or something else @NotSharwan
