### ISSUE TITLE
[BUG] Players in survival can't break furniture and probably custom blocks.

### ISSUE THREAD

**Issue by rafael5gr2** [oraxen/oraxen#420]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

As the title says players in survival can't break furniture and probably custom blocks. This is caused by the change I made that added the code block below in OraxenPlugin.
```
CustomBlockData.registerListener(this);
```
This is related to the breaker system that calls a block break event, checks if it's canceled and if it's not then tries to break the block. The problem is that CustomBlockData removes any data that the block had and when the plugin tries to check if it is a custom block, it thinks it isn't because the block has no data anymore. 

This can be found here https://github.com/oraxen/oraxen/blob/master/src/main/java/io/th0rgal/oraxen/utils/breaker/BreakerSystem.java#L116

### Steps to reproduce

Go into survival mode and try to break a furniture block.

### Plugin Version

1.137.1

### ProtocolLib Version

5.0.0-SNAPSHOT-b577

### Server Version

1.19 Paper build 66

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
fixed in #422
