### ISSUE TITLE
[BUG] NullPointerException when trying to port from mmoitems to oraxen

### ISSUE THREAD

**Issue by Bookie28** [oraxen/oraxen#429]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [x] I have checked if any similar bug reports exist

### Description

i dont know i bought this program and i tried to follow the website tutorial but it doesnt give enough info for what im trying to do. unless it is and im dumb

### Steps to reproduce

what does reproduce mean lol i have never coded

### Plugin Version

1.137.2

### ProtocolLib Version

5.0.0-SNAPSHOT-b585

### Server Version

git-Purpur-1735 (MC: 1.19)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
Reproduce means what steps do we follow to recreate your situation.
In this case what does your config look like.

Also when ur making a report regarding an error please include the logfile uploaded to https://mclo.gs @Bookie28
