### ISSUE TITLE
[BUG] FactionsUUID break/placement bug

### ISSUE THREAD

**Issue by Bralien** [oraxen/oraxen#442]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

When using the latest version of FactionsUUID, there seems to be a problem when trying to break/ place blocks, depending on whether you are in a faction or not. 

When a player is in a faction, they can only break/ place Oraxen blocks inside their own claimed territory. When players are not in a faction, they are able to break/ place Oraxen blocks in the wilderness. Vanilla blocks are not affected.

Nothing is shown in the server logs when unsuccessfully trying to place/ break blocks. Problem has occurred with the most recent paper server version and previous ones.

### Steps to reproduce

1. Use the latest version of FactionsUUID (https://www.spigotmc.org/resources/factionsuuid.1035/)
2. Before joining/creating a faction, try placing and breaking Oraxen blocks in the Wilderness, this should be possible.
3. Join/create a faction, try placing and breaking Oraxen blocks in the Wilderness, this is where you encounter the problem, this is not possible.

### Plugin Version

Oraxen version 1.139.1

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b597

### Server Version

This server is running Paper version git-Paper-130 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 4ba43fe)

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by mbax** [comment]
Fixed in above referenced pull request
