### ISSUE TITLE
[BUG]  Drop of custom crops

### ISSUE THREAD

**Issue by Niko302** [oraxen/oraxen#445]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

The custom crops do not drop they just drop an item of themselves

### Steps to reproduce

Break a custom crop/plant

### Plugin Version

1.139.1

### ProtocolLib Version

Build #598

### Server Version

1.19.2

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
Duplicate of #443
