### ISSUE TITLE
Bigmining Mechanic ignores WorldGuard regions.

### ISSUE THREAD

**Issue by apatuka** [oraxen/Oraxen#45]
Hello !

Using those hammers / Bigming mechanic, it breaks as expected, but if an adjacent blocks to be breaked inside the radius is inside a worldguard Region, it ignores totally causing damage to protected regions.

Here is the version info: 

Oraxen version 1.33.0
Worldguard 7.0.3 Snapshot
PaperMC 1.16.1

**Comment by Th0rgal** [comment]
Hello,

This error is pretty new (I know we didn't have this a few months ago). @DoctaEnkoda is going to work on it soon. Thanks for the report!
