### ISSUE TITLE
[BUG] Clicking on barrier or noteblock oraxen block (or any button that is attached to this block) on gamemode adventure triggers PlayerInteractEvent twice with different action

### ISSUE THREAD

**Issue by GliczDev** [oraxen/oraxen#459]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

By clicking on barrier or noteblock oraxen block (or any button that is attached to this block) with right click on gamemode adventure, PlayerInteractEvent is triggered twice with `RIGHT_CLICK_BLOCK` and `LEFT_CLICK_AIR` action

### Steps to reproduce

Right click on barrier or noteblock oraxen block (or any button that is attached to this block) on gamemode adventure and debug what PlayerInteractEvent action says

### Plugin Version

[11:47:16 INFO]: Oraxen version 1.139.0
[11:47:16 INFO]: Author: Th0rgal

### ProtocolLib Version

[11:44:36 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b600
[11:44:36 INFO]: Provides read/write access to the Minecraft protocol.
[11:44:36 INFO]: Authors: dmulloy2 and comphenix

### Server Version

[11:44:47 INFO]: Checking version, please wait...
[11:44:47 INFO]: Current: git-Purpur-1751 (MC: 1.19.1)*
Previous: git-Purpur-1682 (MC: 1.19)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Emibergo02** [comment]
are you right clicking or left clicking?
