### ISSUE TITLE
Repairing Oraxen items with anvil doesn't work

### ISSUE THREAD

**Issue by apatuka** [oraxen/Oraxen#46]
I have an custom item with 1521 durability, when i use it, it reduces its durability as expected.

But when i repair from 823 to 1521 again, and use it it brings back to 821 minus the durability loss during item use.

**Comment by Th0rgal** [comment]
Hey there,

You need to use cogs to repair the items. You can also use the api to create another way of repairing!

**Comment by apatuka** [comment]
All right, will see a workaround with the API. Thank you so much !
