### ISSUE TITLE
No documentation for Rotation or Facing on furniture mechanic

### ISSUE THREAD

**Issue by VergilPrime** [oraxen/oraxen#461]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

![image](https://user-images.githubusercontent.com/1651211/187319184-cae22b11-ecdc-47b1-ab73-970340b2cd65.png)
The docs show "Rotation" and "Facing" but have no mention of these settings and no examples of any possible settings beyond "NONE" and "UP".

### Steps to reproduce

N/A

### Plugin Version

N/A

### Server Version

N/A

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Emibergo02** [comment]
open an issue on https://github.com/oraxen/documentation

**Comment by Boy0000** [comment]
indeed open this on docs is probably better
