### ISSUE TITLE
[BUG] Breaking Noteblock duplication glitch

### ISSUE THREAD

**Issue by zek2468** [oraxen/oraxen#479]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

If you break a notebook or a custom oraxen noteblock with an Efficiency 5 Netherite Axe, it will duplicate that block as shown in the video

https://user-images.githubusercontent.com/25335568/189771466-bc1b37ef-4fb8-47b2-924b-51b1bf856714.mp4

### Steps to reproduce

- Make an Efficiency 5 Netherite Axe
- Place down a noteblock or any oraxen block that uses the note block
- break that block with the Efficiency 5 Netherite Axe

### Plugin Version

1.141.0

### ProtocolLib Version

5.0.0-SNAPSHOT-b600

### Server Version

![image](https://user-images.githubusercontent.com/25335568/189771785-e441f22b-812c-4ddb-b005-663b348e8096.png)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
Is this only for noteblocks or for the custom blocks using noteblock mechanic aswell @zek2468 ?
Thought I fixed it but might have only fixed custom noteblocks

**Comment by zek2468** [comment]
It is happening for both.

**Comment by zek2468** [comment]
@Boy0000 So it looks like it happens to both but only if you don't hard the hardness set on the custom note blocks in the ymal file.


https://user-images.githubusercontent.com/25335568/189877550-e46c4d49-8422-4d5c-9b72-98f42d4092c2.mp4

**Comment by blek-id** [comment]
Happened on my end as well
![3](https://user-images.githubusercontent.com/26654664/191415556-763f3509-bebf-4a6b-81cb-c2d3c94e81f4.gif)

**Comment by Niko302** [comment]
Can confirm. Happens on my end aswell
