### ISSUE TITLE
[BUG] Joining server with pack disabled (in client server settings) doesn't kick player

### ISSUE THREAD

**Issue by MichixYT** [oraxen/oraxen#484]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

Joining server with pack disabled (in client server settings) doesn't kick player

### Steps to reproduce

Joining server with pack disabled (in client server settings)

### Plugin Version

Oraxen version 1.141.0

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b600

### Server Version

Current: git-Purpur-1773 (MC: 1.19.2)*

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
Is it set to be mandatory in settings.yml?
Otherwise yes they dont need to accept and bypass the prompt
Prompt is only shown to players who have it set to Prompt in the server settings, and if pack is mandatory @MichixYT 

```yml
dispatch:
    send_pack: true
    delay: -1
    # this option requires ProtocolLib and will make the pack loading more fluid
    send_pack_advanced:
      enabled: true
      mandatory: true```

**Comment by MichixYT** [comment]
> Is it set to be mandatory in settings.yml?

yes
> Prompt is only shown to players who have it set to Prompt in the server settings

but to people that have pack disabled in the server settings oraxen don't even kick them
