### ISSUE TITLE
[BUG] Basic leather armor Items not registering

### ISSUE THREAD

**Issue by doitliketyler** [oraxen/oraxen#488]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

I've ran into an issue while creating a basic item that uses leather helmet/chestplate/leggings/boots (with or without enchantments).  The item doesn't actually register and I get this error in console:

https://pastebin.com/raw/vat4RtEu

Example item: https://pastebin.com/raw/20QDtsdF

I can also make the exact same item but with an IRON_HELMET and it will work just fine.

### Steps to reproduce

1. Create item
2. Reload

### Plugin Version

1.142.1

### ProtocolLib Version

5.0.0-SNAPSHOT-b597

### Server Version

Paper 1.19.2

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
thanks for spotting this! should be fixed in the next update @doitliketyler
