### ISSUE TITLE
[BUG] Plugin not loading on startup

### ISSUE THREAD

**Issue by doitliketyler** [oraxen/oraxen#493]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

Updated to latest version that was just released and the plugin will not load. This is the error I'm getting on startup:

https://pastebin.com/raw/UMB2Bb7y

Any idea why this is happening and if I can fix on my end?

### Steps to reproduce

1. Upload latest update
2. Restart server

### Plugin Version

1.143.0

### ProtocolLib Version

5.0.0-SNAPSHOT-b597

### Server Version

Purpur 1.19.2

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
This is because you deleted some glyphs which oraxen uses by default.
For example the glyphs for inventory menus etc in interface.yml
Until next update, solution is to not delete these files, just leave the default assets as is
@doitliketyler

**Comment by doitliketyler** [comment]
I didn't delete any glyphs. I use the default glyphs so I wouldn't do that. I'll regenerate the file nonetheless but it was definitely the latest update that didn't replace the old glyphs with the new ones since it changed them all for the new hud stuff.

**Comment by Boy0000** [comment]
this will be fixed anyway in the next release to hinder the error.
But this is the only way i could replicate it. I know it didnt happen before but nothing should have changed which is why im confuseled. Anyway its fixed next release now 👍
