### ISSUE TITLE
does backpack work?

### ISSUE THREAD

**Issue by DJamMix** [oraxen/oraxen#513]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

I created a backpack, and when I pick it up and try to open it, I press the right mouse button or the left mouse button, nothing happens. There are no errors. If you need to install an additional plugin, then tell me. Here is my backpack config:

leather_backpack:
  displayname: "<#ff8e4c>Backpack"
  material: PAPER
  Pack:
    generate_model: false
    model: "item/backpack/leather_backpack"
    custom_model_data: 189
  Mechanics:
    backpack:
      rows: 4
      title: "<red>Backpack"                      #Optional, Default: "Backpack"
      open_sound: "entity.shulker.open"       #Optional, Default: "entity.shulker.open"
      close_sound: "entity.shulker.close"     #Optional, Default: "entity.shulker.close"
      
  If I wrote the wrong way, then forgive me :)

### Steps to reproduce

I created a backpack, and when I pick it up and try to open it, I press the right mouse button or the left mouse button, nothing happens. There are no errors. If you need to install an additional plugin, then tell me. Here is my backpack config. If I wrote the wrong way, then forgive me :)

### Plugin Version

1.143.

### ProtocolLib Version

4.8.0

### Server Version

1.18.2

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
It was fixed today and should be fully fixed in the coming 1.144.0
Just a minor issue which is nice as we got to fix a dupe aswell
