### ISSUE TITLE
[BUG] forced ids breaks shifts and required glyphs from commit 801025b0

### ISSUE THREAD

**Issue by Emibergo02** [oraxen/oraxen#516]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

[20:10:24 WARN]: [null] [Oraxen] glyphs/shifts.yml was incorrect, renamed to .old and regenerated the default one
[20:10:24 WARN]: [null] [Oraxen] glyphs/required.yml was incorrect, renamed to .old and regenerated the default one
automatically_set_glyph_code: true makes oraxen overwrite file everytime now that file contents are forced 

### Steps to reproduce

automatically_set_glyph_code: true set this in settings.yml

### Plugin Version

latest

### Server Version

1.19.2

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
this should be fixed in 1.143.2, please verify
