### ISSUE TITLE
[BUG] Resourcepack generator breaking when having overly excessive amount of files read

### ISSUE THREAD

**Issue by Imobaing** [oraxen/oraxen#524]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

Once the maximum RP size is met Oraxen will not send the RP to players.

Complete Log File:

https://mclo.gs/c2FlpCM

### Steps to reproduce

Restart server

### Plugin Version

1.143.3

### ProtocolLib Version

ProtocolLib 4.8.0

### Server Version

1.19.2

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Imobaing** [comment]
https://mclo.gs/c2FlpCM

**Comment by Boy0000** [comment]
no clue what this is a bugreport for, please edit the title and description to actually explain the bug @Imobaing

**Comment by Imobaing** [comment]
@Boy0000 Done 👍

**Comment by Boy0000** [comment]
The issue isnt size. Size as in file size is only limited by Minecraft. If this is about RPs with incredibly high filecounts thats different

**Comment by Imobaing** [comment]
Will do!

**Comment by Imobaing** [comment]
Hi there, any news on this issue?

**Comment by Boy0000** [comment]
no theres not sorry, you can try it on 1.150.0 and see if it is fixed though

**Comment by Th0rgal** [comment]
@Imobaing are you able to identify what files cause the issue? This could be because a binary file is read by the plugin looking for placehodlers to replace.

**Comment by Imobaing** [comment]
@Th0rgal No clue, the only thing I know is that the resource pack was too big.

**Comment by Imobaing** [comment]
@Boy0000 I updated to 1.153.1 and the issue seems to be fixed.
