### ISSUE TITLE
[BUG] Compatibility error

### ISSUE THREAD

**Issue by mapacheee** [oraxen/oraxen#525]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

When Oraxen is installed some plugins like TrMenu or ProtectionStones gives error.

https://hastebin.com/zoxuliqixi.sql
https://hastebin.com/peyezetemo.kotlin

### Steps to reproduce

1.- Install TrMenu or ProtectionStones and their dependencies.
2.- Install Oraxen.
3.- Check console for error.

### Plugin Version

[18:19:31 INFO]: Oraxen version 1.143.3
[18:19:31 INFO]: Author: Th0rgal

### ProtocolLib Version

[18:20:00 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b602
[18:20:00 INFO]: Provides read/write access to the Minecraft protocol.
[18:20:00 INFO]: Authors: dmulloy2 and comphenix

### Server Version

[18:20:11 INFO]: Current: git-petal-"3efc156" (MC: 1.19.2)*
* You are running the latest version

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by mapacheee** [comment]
PD: Also I tested ProtectionStones and TrMenu in their last version

**Comment by Boy0000** [comment]
the errors uve set there doesnt tell me really anything
neither does oraxen, afaik, even use Trmenu or anything
I doubt this issue is with oraxen but if it is please provide a full startup log and not just parts of it

**Comment by mapacheee** [comment]
I just know when I install Oraxen that plugins gives error, idk if there is a solution for that 😔

Full log: https://mclo.gs/QVvBkXa

**Comment by Boy0000** [comment]
no clue but this doesnt seem like something oraxen would fix, moreso the plugins getting errors but
cant really see what breaks as oraxen doesnt use TrMenu or ProtectionStones

**Comment by mapacheee** [comment]
I see, thanks sir
