### ISSUE TITLE
Smelting Mechanic can dupe a lot of ingots

### ISSUE THREAD

**Issue by apatuka** [oraxen/Oraxen#53]
When someone picks with a item with the Smelting Mechanic inside a protected region, he can duplicate endlessly any kind of ingot.

Attaching the proof

[2020-07-29 19-09-14.zip](https://github.com/oraxen/Oraxen/files/4998579/2020-07-29.19-09-14.zip)

**Comment by yzl210** [comment]
What region protect plugin are you using?

**Comment by apatuka** [comment]
WorldGuard for region protection
And LandLord as a WorldGuard Wrapper.

**Comment by yzl210** [comment]
I've tested with WorldGuard, it's working fine

**Comment by yzl210** [comment]
What version are you using?

**Comment by apatuka** [comment]
Oraxen version 1.33.0
Worldguard 7.0.3 Snapshot

**Comment by yzl210** [comment]
You can join our discord https://discord.gg/ceX5Zv8

**Comment by yzl210** [comment]
you should update to the latest Oraxen. 1.39.0 fixed some problems with Smelting Mechanic

**Comment by apatuka** [comment]
No problems so far. Will reopen the issue if happens again.
Thanks
