### ISSUE TITLE
Weird noteblock issue

### ISSUE THREAD

**Issue by CryptoXB** [oraxen/oraxen#536]
Noteblocks show up when blocks are updated and no longer contain the original block data

https://cdn.discordapp.com/attachments/613680450761785344/1034231044704051282/unknown.png

**Comment by Boy0000** [comment]
@CryptoXB Please verify that this happens on a server with **only** Oraxen and ProtocolLib 5.0 enabled
You havent included much for me to go of here, so no clue what plugins could do it, but this issue was fixed in Oraxen right after 1.19 came out

**Comment by Boy0000** [comment]
Closing this as i am fully unable to replicate it. Feel free to reopen if you can reproduce it and provide more info
