### ISSUE TITLE
[SUGGESTION] Functionality between Stringblocks and Directional blocks mechanic

### ISSUE THREAD

**Issue by SebyRo23** [oraxen/oraxen#554]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Adds functionality between stringblocks and directional blocks

### Reason

This can be usefull to recreate some vanilla block behavoiurs like lanterns or dripstone

**Comment by NinjagoKristian** [comment]
Yeah, this is a great idea
