### ISSUE TITLE
[BUG] modelengine crash build

### ISSUE THREAD

**Issue by Nardann** [oraxen/oraxen#569]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

Hi 
When I try to build the project, I have an error about the resolve of modelengine : 
`oraxen:main: Could not resolve com.ticxo.modelengine:api:R3.0.1.`
I use jdk 17.0.5

### Steps to reproduce

Launch intelij idea and wait some seconds, the build start automatically. When it is finish there is 1 error 
`oraxen:main: Could not resolve com.ticxo.modelengine:api:R3.0.1.`

### Github Plugin Version

the last update 

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
This is an issue with Mythic's Repo not Oraxen. The issue will only prevent you from compiling the Jar if you do not have the repo cached locally. Closing this as it has been reported to ModelEngine Discord and I cannot fix it in any other way
