### ISSUE TITLE
[BUG] BACKPACK

### ISSUE THREAD

**Issue by leonarmeneses** [oraxen/oraxen#577]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

no puedo usar la mecanica de backpak en ningun item me pueden ayudar por favor 

### Steps to reproduce

pongo este codigo en el item hago reload y no hace nada no funciona 

Mechanics:
  backpack:
    rows: 4
    title: "<red>Backpack"                      #Optional, Default: "Backpack"
    open_sound: "entity.shulker.open"       #Optional, Default: "entity.shulker.open"
    close_sound: "entity.shulker.close"     #Optional, Default: "entity.shulker.close"

### Plugin Version

la ultima lo acabo de comprar

### ProtocolLib Version

ultima version recien descargada

### Server Version

1.18.2

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
Do not speak spanish, bugreports must be in english. Closing this for now, reopen in english and I can fix this @leonarmeneses
