### ISSUE TITLE
[Problem] blocks customs placement

### ISSUE THREAD

**Issue by Yukylyu** [oraxen/oraxen#596]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Hi,
Concern the custom blocks, I have noticed a problem when I put a custom oraxen block on a staircase, for example, it turns into stone. (I use note blocks and the rendering of the item when I hold it is a "stone" item). And conversely I can't put lanterns, fences etc. on custom blocks.
Thanking you in advance for your help.

picture: https://www.zupimages.net/up/22/46/jz65.png

### Steps to reproduce

- take a  custom block.
- place it on or against a stairs (half slab too).

and

- take a  custom block and place it.
- place a fence, lantern, entities... on it.

- it can't ...

### Plugin Version

oraxen-1.148.2

### ProtocolLib Version

ProtocolLib v5.0.0-SNAPSHOT-b600

### Server Software & Version

paper-1.19.2-138

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
cannot replicate this
