### ISSUE TITLE
[Problem] custom model data cannot be modified (furnitures)

### ISSUE THREAD

**Issue by Yukylyu** [oraxen/oraxen#597]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Hi, I have a problem in relation to "furniture",
I have tried to integrate an existing one into my pack before creating new ones:
table:
displayname: "<gray>Table"
material: PAPER
Pack:
generate_model: false
model: default/table

The problem I have is that it sets it to the custom_model_data: 1 by default (but in my pack this custom_model_data is already occupied by another item). I have tried to add as for the blocks the line "custom_model_data: 200000" above "generate_model: false
  "(and also generate_model: true) but it stays on the custom_model_data 1.
Would there exist a method or another writing to be able to define itself the number of customs model data of the items for the furnitures. Thanking you in advance for your response.

### Steps to reproduce

- Place a furniture with the config custom.

### Plugin Version

oraxen-1.148.2

### ProtocolLib Version

ProtocolLib v5.0.0-SNAPSHOT-b600

### Server Software & Version

paper-1.19.2-138

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
this seems more like a support question than a bugreport, ask in discord if this still applies
