### ISSUE TITLE
[problem] Permissions

### ISSUE THREAD

**Issue by Yukylyu** [oraxen/oraxen#600]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Hi I would like to create a profession on my server related to furniture. 
Is it possible to add permissions to place furniture please?

### Reason

I would like to create a profession on my server related to furniture.

**Comment by Boy0000** [comment]
@Yukylyu You can use plugins like WorldGuard and only allow x-group to place blocks in a region
This should extend to oraxen furniture as well. I might add an extra option in mechanics.yml to make it so permission can be checked
