### ISSUE TITLE
[BUG] Break and place sounds are switched

### ISSUE THREAD

**Issue by oliviathevampire** [oraxen/oraxen#602]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Looked at the code and I saw place and break sounds are switched

### Steps to reproduce

Set different sounds for place and break, and you'll hear they are switched (I saw in code, but should happen when doing this)

### Plugin Version

1.149.0

### ProtocolLib Version

Newest

### Server Software & Version

1.19.2 Paper

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
Please actually mention where this is in the code or whatever

**Comment by oliviathevampire** [comment]
> Please actually mention where this is in the code or whatever

Here https://github.com/oraxen/oraxen/blob/e5f27c8d790ecca665e0b9a3db91188eab359410/src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/block/BlockSoundListener.java#L57-L72

**Comment by Boy0000** [comment]
thanks
