### ISSUE TITLE
[SUGGESTION] API method to retrieve block item model files

### ISSUE THREAD

**Issue by NichtStudioCode** [oraxen/oraxen#604]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

An API method to retrieve a ``Map<NamespacedKey, String>`` (or similar) representing block ids and a path to their item model in Oraxen's resource pack.

### Reason

I'm currently working on a WAILA-like overlay for Spigot. In order for it to be compatible with Oraxen, I would need to render Oraxen's blocks.

The WAILA-like overlay I've been working on:
![](https://i.imgur.com/NNiSCbZ.gif)

**Comment by Boy0000** [comment]
@NichtStudioCode could do this but feels pretty niche
You could do this relatively easy though via OraxenItems

```java
Mechanic mechanic = OraxenBlocks.getOraxenBlock(location);
if (mechanic == null) return;
String id = mechanic.getItemID();

String modelPath = OraxenItems.getItemById(id).getOraxenMeta().getModelName();
```
Stop by the discord in the development channel if you want any further help, easier than back and forth here 👍
