### ISSUE TITLE
Sample server

### ISSUE THREAD

**Issue by PortableGames** [oraxen/oraxen#605]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Is there any sample server where I could view and test the plugin capabilities before purchasing?

I am most interested in the preload of the resourcepack before connecting to the world and the speed of the load. Also the structure of the resourcepack because of the new atlases in version 1.19.3

### Reason

I plan to purchase the plugin but would like to try it out first

**Comment by Boy0000** [comment]
@PortableGames there is no demo server no, very hard to have one aswell as oraxen without config access doesnt show much
You can compile the plugin if you feel unsure about just buying it but means no default assets and no support from our end. Of course when you buy it you will get those 👍
