### ISSUE TITLE
[BUG] Pack not converting to 1.19.3 logs included

### ISSUE THREAD

**Issue by antibitcoin** [oraxen/oraxen#613]
### I have checked...

- [x] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When I enable convert to 1.19.3 on a 1.19.2 server it will not convert the pack.
here is the full log:
https://mclo.gs/H88E7yN

summery:

[19:49:29] [Server thread/ERROR]: Error occurred while enabling Oraxen v1.149.1 (Is it up to date?)
--
195 | java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonArray.size()" because "<local7>" is null
196 | at io.th0rgal.oraxen.pack.generation.PackConvertor.convertItemsPack_1_19_3(PackConvertor.java:61) ~[oraxen-1.149.1.jar:?]
197 | at io.th0rgal.oraxen.pack.generation.PackConvertor.handlePackConversionFor_1_19_3(PackConvertor.java:23) ~[oraxen-1.149.1.jar:?]
198 | at io.th0rgal.oraxen.pack.generation.ResourcePack.generate(ResourcePack.java:134) ~[oraxen-1.149.1.jar:?]
199 | at io.th0rgal.oraxen.OraxenPlugin.onEnable(OraxenPlugin.java:86) ~[oraxen-1.149.1.jar:?]
200 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
201 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
202 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
203 | at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-307]
204 | at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-307]
205 | at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-307]
206 | at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-307]
207 | at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-307]
208 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-307]
209 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
210 | at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Steps to reproduce

just use oraxen and my configs and try to start the server.

### Plugin Version

1.149.1

### ProtocolLib Version

[20:13:36 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b608
[20:13:36 INFO]: Provides read/write access to the Minecraft protocol.
[20:13:36 INFO]: Authors: dmulloy2 and comphenix

### Server Software & Version

[20:12:08 INFO]: This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version
Previous version: git-Paper-263 (MC: 1.19.2)

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
This is already fixed in 1.150.0 coming next weekend
