### ISSUE TITLE
[BUG] Oraxen messes with WorldGaurd ItemFrameRotation flag

### ISSUE THREAD

**Issue by SynapseZen** [oraxen/oraxen#618]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Oraxen interferes with the WorldGaurd flag "item-frame-rotation" allowing players to rotate item frames, even if it's disabled. 

https://user-images.githubusercontent.com/94088569/210039929-c313f23e-44d0-49cb-b39d-83afe23f387e.mp4

https://user-images.githubusercontent.com/94088569/210040145-e446dbd8-f2cc-463d-adaf-841e5f1943f6.mp4

### Steps to reproduce

With Oraxen and WorldGaurd installed, create a WorldGaurd region and deny the flag "item-frame-rotation". You'll still be able to rotate item frames in that region.

### Plugin Version

1.148.2

### ProtocolLib Version

5.00-SNAPSHOT-b602

### Server Software & Version

This server is running Paper version git-Paper-172 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 6d63005)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
Unable to replicate this seemingly. You sure this is an oraxen issue and not another plugin @SynapseZen ?
I cant see in the code either why this would happen
https://streamable.com/bu9gdq
