### ISSUE TITLE
[Request] Prevent certain ItemMeta from being updated with ItemUpdater

### ISSUE THREAD

**Issue by lacin59** [oraxen/oraxen#622]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

So i would like to add a new setting (for example ignore_enchants, which would fully work with the setting enable_configs_updater). We need to have on our server turned enable config updater but if we enchant an item then log off and back on, it dissapears.(the enchants)so the new setting would mainly ignore all the enchants.
Thanks

### Reason

It would help many servers. With this issue

**Comment by Boy0000** [comment]
This is moreso about making it so it can not update itemmeta but it is very tricky, hence not done
Might come back to this but yeah

**Comment by lacin59** [comment]
So are you going to do it?

**Comment by Boy0000** [comment]
> Might come back to this but yeah

i might but it is not as easy as your original request makes it sound
ItemMeta is a pain to deal with when you need to take so many things into account
I definetly do want to do it but it isn't priority 1 at the very moment 👍

**Comment by Boy0000** [comment]
Working on this in the linked branch
Currently it will re-add all enchantments to the new item
It will keep displayname changed as long as it was renamed in an anvil, this way the config name can be changed and updated
cmd, lore etc will be forcefully updated

not sure if im missing anything here but lmk @lacin59
