### ISSUE TITLE
cave vines and saplings for custom blocks

### ISSUE THREAD

**Issue by magicelk235** [oraxen/oraxen#625]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

I suggest adding saplings and cave vines(glow berries as blocks) to the automatic generator of blocks

### Reason

because more custom blocks or maybe new cave plants that can grow food or something or maybe custom sapling

**Comment by Boy0000** [comment]
Cave Vines would require us to handle World Generation as they would otherwise be random custom blocks throughout the world
Saplings have very limited blockstates and just like #607 saplings would really be only a few blockstates and only good for hitbox purposes over StringBlockMechanic
