### ISSUE TITLE
[BUG] Worldguard bypass with Eff 5 Axe

### ISSUE THREAD

**Issue by blek-id** [oraxen/oraxen#630]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When using efficiency 5 axe, users with no permission to break anything in a region could break oraxen blocks

### Steps to reproduce

1. get eff 5 axe
2. set a region with block-break and block-place false
3. place an oraxen block
4. break oraxen block with eff 5 axe

Expected result:
block break is blocked, with message from worldguard saying you can't break that here

Actual result:
block is broken, no block is dropped however, with worldguard still saying you can't break that here

![repair3](https://user-images.githubusercontent.com/26654664/211180581-558af0a6-5423-42d0-8244-39c8cc31ce5b.gif)

### Plugin Version

1.150.1

### ProtocolLib Version

5.0.0-SNAPSHOT-b608

### Server Software & Version

1.19.2 Paper 307

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
You sure this isnt just a visual glitch either @blek-id ?
Axe isnt damaged so i assume it is a ghost block
Try right clicking thhe spot again, sorry for late reply
