### ISSUE TITLE
[BUG] HappyHUD Incompatibility

### ISSUE THREAD

**Issue by Boy0000** [oraxen/oraxen#631]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Seems some of HappyHUDs font files are translated incorrectly thus leading to breaking changes

### Steps to reproduce

.

### Plugin Version

.

### ProtocolLib Version

.

### Server Software & Version

.

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by JustKira** [comment]
same i tested it same settings and that what i found in log

[log.txt](https://github.com/oraxen/oraxen/files/10369254/log.txt)
