### ISSUE TITLE
[BUG] PlotSquared Delete Takes to Long / Doesn't Delete if Oraxen Block on it

### ISSUE THREAD

**Issue by RedstoneZockt** [oraxen/oraxen#632]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

The Plot Deletion Process takes up to 60000ms (if no oraxen block on it) -> In SparkProfiler the WorldEditIntegration shows up at the top

The Plot doesn't delete if oraxen block on it (Error: https://pastebin.com/444rg4GC)

### Plot Doesn't Delete

1. Download latest version from PlotSquared + Fawe + Oraxen
2. Add the Oraxen Handler to Fawe Config
3. Generate PlotWorld
4. Claim a Plot
5. Place an Oraxen Block on the Plot
6. Try to Delete the Plot

### Plot Deletion Takes 50000ms
- Same Steps above (1-4)
-  Try to Delete the Plot

### Plugin Version

Oraxen version 1.150.1
Author: Th0rgal

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b605
Provides read/write access to the Minecraft protocol.
Authors: dmulloy2 and comphenix

### Server Software & Version

This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
@RedstoneZockt unsure if this still happens as of 1.158.0
Please confirm if it does as I am currently not able to replicate it
