### ISSUE TITLE
make kelp, sugar cane custom blocks and way to disable regular string

### ISSUE THREAD

**Issue by magicelk235** [oraxen/oraxen#633]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

kelp and sugar cane: just like any other custom block
disable regular string: in the settings make something like this "disable regular strings: true/false"

### Reason

kelp and sugar cane: kelp can be used as an underwater plant and sugar cane can be used as an on-ground plant
disable regular string: if the regular string doesn't have texture and it just makes lags and bugs so why not

**Comment by Boy0000** [comment]
Kelp and SugarCane depend on worldgen so no
disable string will be tracked at #663 if added
