### ISSUE TITLE
/o update

### ISSUE THREAD

**Issue by magicelk235** [oraxen/oraxen#643]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

"/o update" is a new command that allows you to convert from the old Oraxen folder to the current folder
example:
/o update (path of the old folder)
another method:
new folder in Oraxen that calls "update" that will be the place to pot the old folder, Oraxen will convert the old ones to new ones
### Reason

it will be so much essayer to update if you are working with lots of files and folders

**Comment by Boy0000** [comment]
no clue what you mean with current oraxen folder?
if you mean restore default stuff, simply delete the folder and it should regen from the default?
no need for a command for this
