### ISSUE TITLE
Multiple bugs in latest version of Oraxen

### ISSUE THREAD

**Issue by TheLaoming** [oraxen/oraxen#646]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Hey, so I decided to write there few bugs that I already know about.

1. **Critical one**, when you spam click + ESC on any furniture using **storage** mechanic, tps value is falling extremelly fast and what's even worse, you increasing your and other's people ping. This is even worse if you use external applications such as autoclicker.

2. For some reason, two latest versions of Oraxen (up to 1.150.2) messing up with color codes on signs. When you type for example "&a&lTest" it will use "< bold >< green >Test", uncolored ofc.

3. When you place any barrier furniture on snow with Creative gamemode, it place up 2 of them. This doesn't work for carpets etc., only snow.

### Steps to reproduce

Already wrote these above

### Plugin Version

1.150.2

### ProtocolLib Version

5.0.0-SNAPSHOT-b612

### Server Software & Version

1.19.2-R0.1-SNAPSHOT git-Paper-307

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
@TheLaoming for future split every bug into multiple bugreports
becomes infinitly easier to keep track off

**Comment by Boy0000** [comment]
1. unable to replicate but i will try more
2. this is cuz ur probably using a spigot server? if not its just because oraxen primarily uses spigot api. Fix it bydisabling formatting in settings.yml for signs for now
3. havent looked at yet @TheLaoming

**Comment by TheLaoming** [comment]
1. I forgot to mention one important detail here, you need to fill that storage block with some items. The problem is that storage mechanic loading these itemsa and if you put here a lot of items with many nbt tags. The worst part is skuler boxes filled with these items. Try it like that, maybe you'll replicate it.
2. I'm using paper, tried also forks like purpur etc. Thanks for letting me know, will disable it.
3. Okay @Boy0000
