### ISSUE TITLE
debug log last version 1.150.3

### ISSUE THREAD

**Issue by Yukylyu** [oraxen/oraxen#652]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Hi, I have a problem with the latest version, it puts "-1" in the chat for each custom block placement.

### Steps to reproduce

-place a custom block.

### Plugin Version

1.150.3

### ProtocolLib Version

v5.0.0

### Server Software & Version

paper 1.19.2

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
fixed in 1.150.4
