### ISSUE TITLE
[BUG] worldedit custom block problem

### ISSUE THREAD

**Issue by Yukylyu** [oraxen/oraxen#653]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Hi, there is a problem with oraxen and worldedit, if a worldedit brush is used near the custom blocks the custom blocks disappear completely, while they are not concerned by the brush…
Example with a custom tree (I have a mix of custom block and oak_leaves):
-    I want to replace the oak_leaves by spruce_leaves with worldedit.
-    I use /mask oak_leaves then /br sphere spruce_leaves 15
Result: My oak leaves are transformed into spruce but the custom blocks have disappeared completely…
And on another test with world edit the use of //replace oak_leaves spruce_leaves transforms part of the custom blocks into a note block.
I have tried to set in setting file on true:
worldedit: 
noteblock_mechanic: true
But whether on this on true or that on false, the result is the same.
Thank you for your help.

### Steps to reproduce

Example with a custom tree (I have a mix of custom block and oak_leaves):
-    I want to replace the oak_leaves by spruce_leaves with worldedit.
-    I use /mask oak_leaves then /br sphere spruce_leaves 15
Result: My oak leaves are transformed into spruce but the custom blocks have disappeared completely…
And on another test with world edit the use of //replace oak_leaves spruce_leaves transforms part of the custom blocks into a note block.
I have tried to set in setting file on true:
worldedit: 
noteblock_mechanic: true
But whether on this on true or that on false, the result is the same.

### Plugin Version

1.150.3

### ProtocolLib Version

v5.0.0

### Server Software & Version

paper 1.19.2

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
WorldEdit support is rather tricky to do fully
It is basically a bare-bones version of WorldEdit support intended for use with basic commands like //set and //replace etc
Someday maybe full support but it isnt the simplest so
