### ISSUE TITLE
[SUGGESTION] Dont Break Tags

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#656]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

new features/mechanics for items not being affected by lava (like netherite stuff) or also cactus
for example

cactus-breaks: false
lava-burns: false

### Reason

idk this would be great, also for creating "fake" netherite stuff like netherite bricks block

**Comment by magicelk235** [comment]
it actually really good idea
