### ISSUE TITLE
[BUG] ORAXEN CANT DROP VANILLA ITEMS // No Info in the DOCS

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#657]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

the docs does not show/teach how you can use vanilla drops for oraxen items, for example, ive tried a lot of stuff and none of it worked

 - {minecraft_type: DIRT, probability: 1.0}
 - {minecraft_item: DIRT, probability:1.0}
 - {item: DIRT, probability: 1.0}

### Steps to reproduce

search for "loots" in the docs, there will be no examples about how to use vanilla drops

### Plugin Version

1.150.2 i think its the last one

### ProtocolLib Version

one of the latests, i cant see rn but ive updated it 2 days aog, i dont remember exactly the number

### Server Software & Version

purpur 1.19.2 latest release

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
to drop vanilla items u do indeed just say `minecraft_type: MATERIAL`
This is identical to everywhere else where you define an oraxenitem/mmoitem/vanilla item etc
