### ISSUE TITLE
[BUG] <name for bug>

### ISSUE THREAD

**Issue by Zitronekuchen** [oraxen/oraxen#662]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Its the break, break1 bug again

### Steps to reproduce

Break and Place a block

### Plugin Version

1.150.4

### ProtocolLib Version

5.0 the one from the discord command

### Server Software & Version

Minecraft 1.18.2

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
when opening a bugreport, if you want your bug fixed
1. actually name the bugreport
2. write a description that would explain the issue and not just 2 words
3. "break and place block" what blocks? custom blocks? and config examples? any plugins that might be the issue? logfile?
4. a debug message i would say isnt gonna make the plugin unusable. yes it is very annoying but no not unusable
