### ISSUE TITLE
[SUGGESTION] Emissive textures for other items, not only armors

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#668]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

the same way as armor, but for any other items
with the alpha treated as the amount of emissivity.

but, blocking the alpha/emissivines when using the same amount of emissivity/alpha in settings for "texture/model in hand or in gui" as i suggested in #667

### Reason

cause emissives textures are awesome

**Comment by Boy0000** [comment]
armor is only emissive because of FancyPants custom armor shader
have no plans to learn GLSL to add this to all textures
