### ISSUE TITLE
[SUGGESTION] adding item models option for blocks

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#669]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

one example is the flowers using cross generated, the item model is the same as the block model, different from how it looks in vanilla...

heres one example

How it is NOW
blue_poppy:
  displayname: Blue Poppy
  material: PAPER
  Pack:
    generate_model: true
    parent_model: item/cross
    textures:
    - custom/block/blue_poppy.png
    custom_model_data: 1
  Mechanics:
    stringblock:
      custom_variation: 0
      model: custom/block/blue_poppy

how it could be
blue_poppy:
  displayname: Blue Poppy
  material: PAPER
  Pack:
    generate_block_model: true
    parent_block_model: item/cross
    block-textures:
    - custom/block/blue_poppy.png
    generate_item_model: true
    parent_item_model: item/generated
    item-textures:
    - custom/item/blue_poppy.png   
     custom_model_data: 1 #for the item, model we generated in "generate_item_model"
  Mechanics:
    stringblock:
      custom_variation: 0
      model: custom/block/blue_poppy #the block model we have generated with "generate_block_model"

### Reason

i mean... i know this is possible, so why not?

**Comment by magicelk235** [comment]
It's actually a very good idea boy have to add this

**Comment by Boy0000** [comment]
You can already do this though it is abit more unclear
Either you provide your own model file, or simply make another basic oraxenitem that paths to whatever you need
Then in the mechanic you specify said model as said model and Pack has the GUI one

Even if abit odd, I think it is alot less confusing than a second option here
