### ISSUE TITLE
[BUG] <i made an custom recipes but cant craft>

### ISSUE THREAD

**Issue by vincyxiroff** [oraxen/oraxen#674]
proof:
https://prnt.sc/VKtVLEAsS9zH
https://prnt.sc/JHEEoHjKriUO

### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

i made the crafting i go to the crafting table but cant craft 

### Steps to reproduce

idk

### Plugin Version

oraxen-1.150.4

### ProtocolLib Version

latest

### Server Software & Version

log: https://mclo.gs/oSi3Qws 1.19.3 paper

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
should be fixed in latest releases
