### ISSUE TITLE
[BUG] Mushroom block texture problem

### ISSUE THREAD

**Issue by harmanprecious** [oraxen/oraxen#676]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Even though I'm using note block mechanics, only one side of the mushroom blocks have texture.

### Steps to reproduce

as i said i'm not using any mushroom block mechanic but still seems like on this video; https://gyazo.com/a68f038f0fdf21ca6f1e69580c7fa66f

### Plugin Version

1.151.0

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b608

### Server Software & Version

[18:49:49 INFO]: This server is running Paper version git-Paper-386 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 4da844f)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
@harmanprecious please show me your settings.yml

**Comment by Boy0000** [comment]
Okey this happens if you have the "block" mechanic enabled. This should never really be used anyway
Set it to disabled. NoteBlock mechanic is irrelevant
