### ISSUE TITLE
[BUG] NOTE BLOCK SOUNDS (STONE AND WOOD)

### ISSUE THREAD

**Issue by HonzasikCZ** [oraxen/oraxen#678]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Hello,

I have a problem with note block sounds
The player reported a bug that the correct sounds are not heard when using wood and note block
The same with stone
I have no idea if it's like that for every block but when I tried emerald block it worked fine

Piano sounds instead of the sounds that should be heard

Do you know what it could be?

I will be very happy for the answer :)

### Steps to reproduce

I can't think of anything to write here

### Plugin Version

1.151.0

### ProtocolLib Version

5.0.0-SNAPSHOT-b612

### Server Software & Version

Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
fully depends on if u disabled noteblock mechanic and if u did if u also disabled the customsound stuff right above it in mechanics.yml

use discord for further support if needed

**Comment by Boy0000** [comment]
@HonzasikCZ
