### ISSUE TITLE
[BUG] INFINITELY LOADING RESOURCE PACK

### ISSUE THREAD

**Issue by HonzasikCZ** [oraxen/oraxen#679]
### I have checked...

- [x] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Hi,

I recently found out when someone joins with version 1.18.1 and the lower resource pack loads endlessly...

I would be very happy for an answer :)

### Steps to reproduce

I can't think of anything to write here

### Plugin Version

1.151.0

### ProtocolLib Version

5.0.0-SNAPSHOT-b612

### Server Software & Version

Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
@HonzasikCZ are you using the "hide_scoreboard_numbers" option in settings.yml?
Is this ALWAYS on every single player joining on 1.18.1 or lower or just some specific players?
if it is specific players does it not happen on 1.19.3 for example?

**Comment by HonzasikCZ** [comment]
Yes I use "hide_scoreboard_numbers"

And it happens with every player, I've tried it too

**Comment by Boy0000** [comment]
then try disabling said option and see

**Comment by HonzasikCZ** [comment]
Unfortunately it doesn't work..

**Comment by Boy0000** [comment]
Closing this for now as it should either have been fixed by an update or by a user error being found
If not use the discord for further support
