### ISSUE TITLE
No Sound on Wood

### ISSUE THREAD

**Issue by C00kiemax** [oraxen/oraxen#680]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When im Walking on Wood theres no sound. I already deleted the sound.yml and restarted the server like Boy told me. And you are forced to use the oraxen texture pack on the server.
heres a link to the latest log for that. 
https://mclo.gs/qbtZnqC

### Steps to reproduce

I dont know how i should reproduce that. Sound on wood is just not working. thats all, if you want you can come to the server and check it by urself

### Plugin Version

1.150.2

### ProtocolLib Version

5.0.0-SNAPSHOT-b610

### Server Software & Version

MC 1.19.3 paper build 381

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
@C00kiemax update to 1.151.0, might not fix it but always good to be up to date
Please also show me your mechanics.yml and settings.yml and sound.yml

**Comment by C00kiemax** [comment]
> @C00kiemax update to 1.151.0, might not fix it but always good to be up to date Please also show me your mechanics.yml and settings.yml and sound.yml

Okay, i'll send you all theses files, and btw i found out, that if i break wood with an axe, the stone sound is played.

mechanics.yml
https://mclo.gs/rUDu87P
settings.yml
https://mclo.gs/cxZU6Ov
sound.yml
https://mclo.gs/uYwg3KA

**Comment by Boy0000** [comment]
right sorry for the delay forgot about this
@C00kiemax so you have disabled noteblock mechanic but not disabled the custom sound fields
Thus it gets abit wacky here. If you dont want custom blocks also disable the custom sound settings right above

**Comment by C00kiemax** [comment]
Okay @Boy0000, thank you for your answer first. To get sure, i will disable the right setting i will ask you now, before i destroy something where im to stupid to fix it haha. 
# GAMEPLAY

# Specify if custom block sounds should be enabled for the below mechanics
# If both mechanics are disabled, this will force the sound system for those off
custom_block_sounds:
  noteblock_and_block: true
  stringblock_and_furniture: true

Do i have to set noteblock_and_block to false? in mechanics.yml. or must i search for something in the settings.yml file? :o

**Comment by Boy0000** [comment]
imean it should be pretty clear that to disable custom blocksounds you disable those options yes @C00kiemax
