### ISSUE TITLE
[SUGGESTION] Prevent damage while texture is loading

### ISSUE THREAD

**Issue by Nolex01** [oraxen/oraxen#684]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

While the texture pack is loading prevent all damage to players.

### Reason

You can easily got killed by a mob or anything while loading the pack especially on low-end pcs.

**Comment by magicelk235** [comment]
use this plugin 
https://www.spigotmc.org/resources/%E2%AC%9B-gizmo-%E2%AC%9B-custom-welcome-screen-more.106024/
