### ISSUE TITLE
[BUG] Stringblock blockstate changed if tall plant placed next to it. Vanilla tall plants are broken too.

### ISSUE THREAD

**Issue by camelovaty** [oraxen/oraxen#687]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Placing any tall plants (tall rose / tall grass / peony) next to the stringblock
-breaks the blockstate of stringblock
-breaks tall plant mechanic of tall rose / tall grass / peony)

**Paper & Purpur 1.19.2 tested**

It makes usage riskful and unusable, with ease of obtaining items in non-authorized way.

### Steps to reproduce

Just place the tall plant next to stringblock.
Blocsktate changes.

Try to break vanilla tall plant. Mechanic is broken.

Like tall grass, tall rose, peony.

### Plugin Version

![image](https://user-images.githubusercontent.com/102817128/216299587-99bf22f2-ed3a-4707-b968-e7b5e61c5c85.png)

This doesn't matter at all, all versions had this issue.
You surely have own  30 seconds to test the issue on the latest version.
Reproduction is very simple.

### ProtocolLib Version

![image](https://user-images.githubusercontent.com/102817128/216299848-35ca6c92-cf3f-479e-a1d9-16c087f41289.png)

### Server Software & Version

![image](https://user-images.githubusercontent.com/102817128/216299938-afbc5915-e148-4e15-9660-3c332ee9d9d3.png)

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by magicelk235** [comment]
the same happens when you bone meal near a string block

**Comment by Boy0000** [comment]
Partially fixed in #744
