### ISSUE TITLE
[SUGGESTION] redstone support

### ISSUE THREAD

**Issue by magicelk235** [oraxen/oraxen#692]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Redstone tags like that will work for any custom block type
Redstone: true/false (works like regular Redstone)
Recharge_Redstone: 1-15/false (works like a repeater, the numbers represent the amount of power)
Predoser_Redstone: 1-15/false (as the name says that will predose Redstone power, the numbers represent the amount of power)
Redstone_auction:
  actions:
     - '[console] say Redstone'  (this will detect  Redstone power and dose actions) 

### Reason

you will be able to make a lot of custom Redstone block

**Comment by Boy0000** [comment]
redstone is the main cause of issues with custom blocks, i doubt this will be done
