### ISSUE TITLE
[BUG] BetonQuest does not recognize BlockBreak from Oraxen

### ISSUE THREAD

**Issue by MisterCookie1234** [oraxen/oraxen#693]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Hi,
We are utilizing BetonQuest and attempting to utilize the Quest Objective "Block-Break". This Objective is intended to detect broken blocks. However, it appears to be detecting custom blocks placed from Oraxen, but not blocks that have been broken. The reason for this is that BetonQuest looks for the Vanilla BlockBreakEvent and disregards it if it is cancelled.

BetonQuest is a Open-Source Resource: 
https://github.com/BetonQuest/BetonQuest

BetonQuest just reads the BlockBreakEvent and does nothing else with it.

### Steps to reproduce

---

### Plugin Version

1.151.0

### ProtocolLib Version

ProtocolLib (5.0.0-SNAPSHOT-b608)

### Server Software & Version

Purpur-1907 (MC: 1.19.3)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by MisterCookie1234** [comment]
@EventHandler(ignoreCancelled = true, priority = EventPriority.HIGHEST)
    public void onBlockBreak(final BlockBreakEvent event) {
    
    (From the BQ Dev)

**Comment by Boy0000** [comment]
https://github.com/oraxen/oraxen/blob/master/src/main/java/io/th0rgal/oraxen/utils/breaker/BreakerSystem.java#L151-L153
Oraxen does call this event but it is cancelled as we manually handle breaking it @MisterCookie1234

**Comment by MisterCookie1234** [comment]
I see @Boy0000, this is probably why BetonQuest won't be able to work with it, as it ignores it if its cancelled :/

**Comment by Boy0000** [comment]
Nvm im wrong here. So what oraxen does is call the event, then if event isnt cancelled it will set the block to air later. So afaik BetonQuest should be able to pick it up?

**Comment by MisterCookie1234** [comment]
The Devs from BQ tested around and they say its probably oraxen related.

CyberOtter — heute um 22:05 Uhr
We tested it: Oraxen does not broadcast the events correctly
Or something cancels it inbetween
CyberOtter — heute um 22:16 Uhr
So for now it's just not compatible. It could be a bug on Oraxen's side 🤷‍♂️

**Comment by Boy0000** [comment]
this might be fixed in 1.158.0. Did some internal API changes which should have fixed this
Sorry for the wait
