### ISSUE TITLE
[BUG] Tabcomplete in glyph generates error when a player joins

### ISSUE THREAD

**Issue by jackboi03** [oraxen/oraxen#696]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When a glyph has tabcomplete: true in its config, the server gives out this error when a player joins: https://pastebin.com/isxuWuaE

### Steps to reproduce

1. create a glyph
2. add tabcomplete: true after chat:
3. start the server
4. player joins the server
5. error in the console pops up

### Plugin Version

1.150.4

### ProtocolLib Version

5.0.0-SNAPSHOT-b602

### Server Software & Version

Minecraft 1.19.2
paper-1.19.2-307

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by jackboi03** [comment]
This bug still exists in version 1.152.0
https://pastebin.com/ZdcWHzxy
Minecraft 1.19.3
paper-1.19.3-442
ProtocolLib version 5.0.0-SNAPSHOT-b614

**Comment by Boy0000** [comment]
@jackboi03 1.152.0 is ancient
update to latest + update ProtocolLib to latesdt 5.0
