### ISSUE TITLE
[BUG] InventoryClickEvent error

### ISSUE THREAD

**Issue by ItsSynchro** [oraxen/oraxen#697]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Error occurs randomly 

https://paste.gg/p/anonymous/aaed7ebc2fb04aa9b767f6e24386c465

### Steps to reproduce

N/A

### Plugin Version

1.151.0

### ProtocolLib Version

5.0.0-SNAPSHOT-b608

### Server Software & Version

git-Paper-300 (MC: 1.19.2)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
this will be fixed in 1.151.1 coming hopefully tomorrow @ItsSynchro
