### ISSUE TITLE
[SUGGESTION] Custom Mobs and Entity

### ISSUE THREAD

**Issue by t3pmd** [oraxen/oraxen#698]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Possible to add Custom Mobs and Entities for a full custom plugin?

### Reason

Would be great to have a way to add custom mobs and entities to the Plugin to give it alot of potential? Would be great to see this happen. As a dev that hasn't touched Java before would it also be something to learn how to do?

**Comment by Boy0000** [comment]
this wont be done, mythicmobs is free
