### ISSUE TITLE
[BUG] Furniture that can't be placed on walls still aligns to wall if floor is present

### ISSUE THREAD

**Issue by repeater64** [oraxen/oraxen#705]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

I have a furniture item, which I have restricted to being placed on the floor only, with the following config:
```      limited_placing:
        roof: false
        wall: false
        floor: true
```
However if I set up a situation where the block I right click to place the furniture is on a wall, but there is a floor just below, the furniture does place, as it sees it will be attached to the floor.
However, it aligns to the wall.
I believe that if wall is set to false and floor is set to true, then in any situation where it is ambiguous if the furniture should rotate to be sitting on the wall or on the floor, it should always sit on the floor. The same should probably be true the other way around.
These two screenshots show the result of me right clicking on the floor vs me right clicking on the side of a block. I believe it should always place like how it does when I click on the floor.
![2023-02-10_19 20 09](https://user-images.githubusercontent.com/62812170/218179991-e00892bc-e55d-426d-926f-d552105c6618.png)
![2023-02-10_19 20 16](https://user-images.githubusercontent.com/62812170/218180000-1086946a-54d1-4a93-9d4e-7da8d0348f74.png)

### Steps to reproduce

Create a furniture block that is restricted to placing on the floor only, and try and place it on a wall, but at the bottom of the wall where there is a floor to support it.

### Plugin Version

1.151.1

### ProtocolLib Version

5.0.0-SNAPSHOT-b612

### Server Software & Version

This server is running Paper version git-Paper-386 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 4da844f)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
This is intended as this is how similar vanilla features work.
If the block below is solid, it will attempt to place the furniture even if a wall was rightclicked
