### ISSUE TITLE
[BUG] Armor Texture Error 

### ISSUE THREAD

**Issue by Haz1234** [oraxen/oraxen#710]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

No item matching <armor>_<part> found. Unable to use <armor>_armor_layer_1.png/<armor>_armor_layer_2.png

### Steps to reproduce

Creating custom textured armor using leather armor and a certain color and then using textures 

### Plugin Version

1.149.1

### ProtocolLib Version

5.0.0-SNAPSHOT-b608

### Server Software & Version

bloom.host

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
u have a misconfigured config is all. use discord for support and read over [docs](https://docs.oraxen.com/configuration/custom-armors)
