### ISSUE TITLE
[SUGGESTION] Add a json parser for pack.mcmeta.

### ISSUE THREAD

**Issue by ItsLaivy** [oraxen/oraxen#716]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Verify the pack.mcmeta, check for json errors and send to the user though console.

### Reason

If some error happens on the pack.mcmeta, the texture doesn't loads and doesn't send any error, its confusing.

**Comment by Boy0000** [comment]
this is a rather minute feature which seems to just be another case of user error
If one reworks the mcmeta file i think it shouldn't require oraxen to parse it and make sure
Closing
