### ISSUE TITLE
[BUG] color code unusable on signs

### ISSUE THREAD

**Issue by JeremyDarbellay** [oraxen/oraxen#720]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When I enter : "&fCoucou" on a sign, 
This sign translate this to "<white>Coucou", instead of coloring it to white.
This feature comes from CMI, i've tried with and without oraxen, it happens only with oraxen.

CMI ver : 9.3.1.5 + CMILib 1.2.4.5

### Steps to reproduce

1. have CMI CMILib Oraxen and protocollib (latest)
2. place a sign
3. write "&f your message"

### Plugin Version

${projectVersion} is this output, but i suppose it's a bug, so 1.151.3

### ProtocolLib Version

5.0 b612

### Server Software & Version

paper #420 (latest)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
disable sign formatting in settings.yml @JeremyDarbellay
