### ISSUE TITLE
[BUG] Noteblock mechanic doesn't work on Spigot

### ISSUE THREAD

**Issue by NeotenySS** [oraxen/oraxen#721]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Using the plugin on the Spigot server. Blocks cannot be placed if they use the noteblock mechinck.

### Steps to reproduce

Just install Spigot 1.19.2 and the plugin version 1.152.1, try to put the amethyst ore and the block will not be placed.
P.S.: Don't forget install ProtocolLib (dev from 1.19.2).

### Plugin Version

[08:16:45] [Server thread/INFO]: Oraxen version 1.152.1
[08:16:45] [Server thread/INFO]: Author: Th0rgal

### ProtocolLib Version

[08:20:41] [Server thread/INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b606
[08:20:41] [Server thread/INFO]: Provides read/write access to the Minecraft protocol.
[08:20:41] [Server thread/INFO]: Authors: dmulloy2 and comphenix

### Server Software & Version

[08:25:17] [Server thread/INFO]: This server is running CraftBukkit version 3599-Spigot-CloseUuidServer (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) 
[08:25:17] [Server thread/INFO]: Checking version, please wait... 
[08:25:17] [Thread-249/INFO]: You are 33 version(s) behind

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by NeotenySS** [comment]
But noteblock mechanic work fine to Paper

**Comment by Boy0000** [comment]
Unable to reproduce this at all on my local spigot Server @NeotenySS 
Do you have any other plugins that might interfere with this?

**Comment by NeotenySS** [comment]
Вот список плагинов на моём сервере:
@Boy0000 
Plugins (36): [0;32;1mLuckPerms[0;37;1m, [0;32;1mPlaceholderAPI[0;37;1m, [0;32;1mLoneLibs[0;37;1m, [0;32;1mProtocolLib[0;37;1m, [0;32;1mLibsDisguises[0;37;1m, [0;32;1mSkinsRestorer[0;37;1m, [0;32;1mRPGBank[0;37;1m, [0;32;1mPl-Hide-Pro[0;37;1m, [0;32;1mVault[0;37;1m, [0;32;1mWorldEdit[0;37;1m, [0;32;1mAdvancedPets[0;37;1m, [0;32;1mFastAsyncWorldEdit (WorldEdit)[0;37;1m, [0;32;1mRPGInventory[0;37;1m, [0;32;1mTAB[0;37;1m, [0;32;1mWorldGuard[0;37;1m, [0;32;1mCitizens[0;37;1m, [0;32;1mRacesOfThana[0;37;1m, [0;32;1mCMILib[0;37;1m, [0;32;1mTowny[0;37;1m, [0;32;1mTownyCombat[0;37;1m, [0;32;1mDungeons[0;37;1m, [0;32;1mTownyChat[0;37;1m, [0;32;1mDiscordSRV[0;37;1m, [0;32;1mCMI[0;37;1m, [0;32;1mAuctionHouse[0;37;1m, [0;32;1mMythicMobs[0;37;1m, [0;32;1mMythicLib[0;37;1m, [0;32;1mBeautyQuests[0;37;1m, [0;32;1mMMOCore[0;37;1m, [0;32;1mBeautyQuests-Expansion[0;37;1m, [0;32;1mMMOItems[0;37;1m, [0;32;1mCommandPanels[0;37;1m, [0;32;1mOraxen[0;37;1m, [0;32;1mBeautyQuestsAddon[0;37;1m, [0;32;1mTownyResources[0;37;1m, [0;32;1mSiegeWar[m

**Comment by NeotenySS** [comment]
w

**Comment by Boy0000** [comment]
Yeah I cannot replicate this at all
If literally everything is default in terms of configs etc, you got the latest version from spigot or polymart and there are no errors in your console I cannot really help here.
Noone else running spigot seems to have this issue, neither can i reproduce it so

**Comment by Boy0000** [comment]
Able to replicate this and aim to have it fixed for 1.153.0 next week @NeotenySS
