### ISSUE TITLE
[BUG] <name for bug>

### ISSUE THREAD

**Issue by ImDarkLaw** [oraxen/oraxen#727]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Oraxen failes to load and enable on server restart due to _WorldGuard version compatibility_ issues. However, i'm using latest WorldGuard version that being the **WorldGuard version 7.0.8-beta-01+cbb2ba7**. 

I've pasted below the **console errors** printed that have to do it when the above issue.

06.03 15:25:03 [Server] ERROR Error occurred while enabling oraxen v1.152.3 (Is it up to date?)
06.03 15:25:03 [Server] INFO java.lang.NullPointerException: WorldGuard is not enabled, unable to access the platform.
06.03 15:25:03 [Server] INFO at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[guava-31.1-jre.jar:?]
06.03 15:25:03 [Server] INFO at com.sk89q.worldguard.WorldGuard.getPlatform(WorldGuard.java:101) ~[worldguard-bukkit-7.0.8-beta-01-dist.jar:?]
06.03 15:25:03 [Server] INFO at io.th0rgal.protectionlib.compatibilities.WorldGuardCompat.<init>(WorldGuardCompat.java:23) ~[oraxen-1.152.3.jar:?]
06.03 15:25:03 [Server] INFO at io.th0rgal.protectionlib.ProtectionLib.handleCompatibility(ProtectionLib.java:45) ~[oraxen-1.152.3.jar:?]
06.03 15:25:03 [Server] INFO at io.th0rgal.protectionlib.ProtectionLib.init(ProtectionLib.java:18) ~[oraxen-1.152.3.jar:?]
06.03 15:25:03 [Server] INFO at io.th0rgal.oraxen.OraxenPlugin.onEnable(OraxenPlugin.java:72) ~[oraxen-1.152.3.jar:?]
06.03 15:25:03 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
06.03 15:25:03 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[purpur-1.19.3.jar:git-Purpur-1920]
06.03 15:25:03 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.3.jar:git-Purpur-1920]
06.03 15:25:03 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
06.03 15:25:03 [Server] INFO at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:575) ~[purpur-1.19.3.jar:git-Purpur-1920]
06.03 15:25:03 [Server] INFO at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:486) ~[purpur-1.19.3.jar:git-Purpur-1920]
06.03 15:25:03 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.19.3.jar:git-Purpur-1920]
06.03 15:25:03 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1920]
06.03 15:25:03 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1920]
06.03 15:25:03 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
06.03 15:25:03 [Server] ERROR Error occurred (in the plugin loader) while disabling oraxen v1.152.3 (Is it up to date?)
06.03 15:25:03 [Server] INFO java.lang.NullPointerException: Cannot invoke "io.th0rgal.oraxen.font.FontManager.unregisterEvents()" because "this.fontManager" is null
06.03 15:25:03 [Server] INFO at io.th0rgal.oraxen.OraxenPlugin.unregisterListeners(OraxenPlugin.java:133) ~[oraxen-1.152.3.jar:?]
06.03 15:25:03 [Server] INFO at io.th0rgal.oraxen.OraxenPlugin.onDisable(OraxenPlugin.java:127) ~[oraxen-1.152.3.jar:?]
06.03 15:25:03 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
06.03 15:25:03 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:227) ~[purpur-1.19.3.jar:git-Purpur-1920]
06.03 15:25:03 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.19.3.jar:git-Purpur-1920]
06.03 15:25:03 [Server] INFO at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
06.03 15:25:03 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:196) ~[purpur-1.19.3.jar:git-Purpur-1920]
06.03 15:25:03 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.3.jar:git-Purpur-1920]
06.03 15:25:03 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
06.03 15:25:03 [Server] INFO at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:575) ~[purpur-1.19.3.jar:git-Purpur-1920]
06.03 15:25:03 [Server] INFO at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:486) ~[purpur-1.19.3.jar:git-Purpur-1920]
06.03 15:25:03 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.19.3.jar:git-Purpur-1920]
06.03 15:25:03 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1920]
06.03 15:25:03 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1920]
06.03 15:25:03 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Steps to reproduce

I assume you could replicate this issue by using the latest WorldGuard version a PurPur or Paper server as well as the Oraxen 1.152.3 version. 

### Plugin Version

**Version 1.152.3**

### ProtocolLib Version

**Version 5.0.0-SNAPSHOT-b612**

### Server Software & Version

**Current: git-Purpur-1920 (MC: 1.19.3)***

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
fixed in hotfix 1.152.4
