### ISSUE TITLE
[SUGGESTION] oxidize mechanic 

### ISSUE THREAD

**Issue by magicelk235** [oraxen/oraxen#734]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

This mechanic will be use for making blocks changes to another blocks by (whatever time you want) time just like copper block
Config:
   Mechanics:
      Oxidize:
        Oxidize_block: #the block you want change to
        Oxidize_time: #the time that takes to Oxidize

### Reason

Can be use for making custom oxidize metals

**Comment by Boy0000** [comment]
not gonna implement this
