### ISSUE TITLE
[SUGGESTION] Better ResourcePack path

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#740]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

an option for a better way to organize the resourcepack folder and path in general to look like a normal resourcepack folder
idk if its jsut me, but i get really confused in the way it works now... ((i have adhd so i really dont know if it really is confusing for other people or if its just this shitty disorder, so... anyways i think this still a good suggestion)

### Reason

it is really confusing and bad for me to organize my textures, models and stuff when instead of
pack/assets/minecraft/ models-textures-blockstates 
or stuff like that, i have to use the direct folder for some things like the models,textures and stuff but in other cases i have to create and use the folder assets/minecraft like the blockstates, atlases and stuff

it really annoys me and make me kinda sad cause it breaks some stuff i make and i have to spent a lot of time rearranging the files...
![image](https://user-images.githubusercontent.com/47507632/224451699-b510dfe4-74c7-449e-aa81-ef5a4685291e.png)

so please, consider making it to look more like a normal resource pack folder like this
![image](https://user-images.githubusercontent.com/47507632/224451756-2252b31e-53b3-459e-9946-0357dbfb38aa.png)
![image](https://user-images.githubusercontent.com/47507632/224451766-1f25490b-3950-4ed2-903b-da49d00db20e.png)
![image](https://user-images.githubusercontent.com/47507632/224451775-99dc7463-dfc5-49d9-9888-5843224895a1.png)

PLEASE, I BEG

**Comment by Boy0000** [comment]
you can just use the assets folder @MarkinhosMLP ?
the models and textures folders are just there to make it as simple as possible
the assets folder is just the same

so `Oraxen/pack/models`  = `Oraxen/pack/assets/minecraft/models`
not sure what ur struggling with here  but yeah, not gonna change this

It is essentially gonna break everyones resourcepacks because some find it slightly confusing. Closing

**Comment by Boy0000** [comment]
it regenerates it when there is no textures/models folder and you havent disabled default_assets in settings.yml
sorry but this is to much of a change for something i see no benefit with what so ever

You are free to open a PR but it is much simpler to just disable default assets. The folders need to exist as it contains some required stuff.

If you are confused on what is urs and what isnt, just use the assets/minecarft folder for your stuff over the models and textures one in the root
