### ISSUE TITLE
[BUG] Sound of breaking a block plays forever

### ISSUE THREAD

**Issue by Nolex01** [oraxen/oraxen#746]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

This bug works too if you have a timber plugin installed.
Sound of breaking playing forever at the location.

If you are using this mechanic:

  Mechanics:
    efficiency:
      amount: 2
      
you get haste effect while mining a block but somehow the sound of breaking a block gets stuck and playing forever at the specific location with this efficiency mechanic.

### Steps to reproduce

Create a pickaxe with efficiency mechanic.

  Mechanics:
    efficiency:
      amount: 2

### Plugin Version

1.153.0

### ProtocolLib Version

5.0.0

### Server Software & Version

1.19 paper

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
@Nolex01 is this when breaking a custom block or normal wood/stone type block?
