### ISSUE TITLE
[SUGGESTION] Text effects

### ISSUE THREAD

**Issue by Nolex01** [oraxen/oraxen#752]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Add text effects like:

- rainbow texts
- jumping texts
- etc...

![image](https://user-images.githubusercontent.com/88859676/225723719-784c7936-ef86-44dd-b7ef-3b82a26db77b.png)

### Reason

- fun for the community
- good eula friendly feature

+New feature always good O.o

**Comment by Boy0000** [comment]
buy https://ko-fi.com/s/fa30d0ee95 @Nolex01
