### ISSUE TITLE
[BUG] Furniture with Storage Can be griefed on lands

### ISSUE THREAD

**Issue by RenardFarceur** [oraxen/oraxen#756]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Hi,
The furnitures blocks with a storage mecanic aren't protected by Lands plugin (they Can be opened by nobody no matter what Lands they came from).

### Steps to reproduce

Use a Oraxen furniture with Storage Mecanic
Create a Lands using Land plugin, and place the furniture. Check with another account who isn't in the Land, it Can be opened 

### Plugin Version

1.153.0

### ProtocolLib Version

5.0.0

### Server Software & Version

Paper 1.19.3 425

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
this should be fixed, forgot to close it. lmk if it isnt fixed in latest version
