### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by Victor2411-hub** [oraxen/Oraxen#77]
I have been trying to compile it to add modifications, obviously these will not be distributed

**Comment by Victor2411-hub** [comment]
I have been trying to compile the source code, but it has been difficult
for me I want to do some personal integrations, but I have not been able to
compile it.

Do I have to have the license to do this?

**Comment by Victor2411-hub** [comment]
I have not purchased the plugin, but I am thinking of doing so due to
its excellent performance

[image: image.png]

**Comment by Th0rgal** [comment]
amazing!

**Comment by Victor2411-hub** [comment]
Your work its Wonderfull, thanks

**Comment by Th0rgal** [comment]
I'm not alone! 
![image](https://user-images.githubusercontent.com/41830259/93631206-7a238380-f9eb-11ea-8bce-17539d37b686.png)

**Comment by Victor2411-hub** [comment]
well its work
