### ISSUE TITLE
[BUG] noteblocks turn to custom blocks when placing on every wood type slab

### ISSUE THREAD

**Issue by magicelk235** [oraxen/oraxen#775]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

note blocks turn to custom blocks when placing on every wood-type slab

### Steps to reproduce

place noteblock on a wooden slab

### Plugin Version

1.154.2

### ProtocolLib Version

5.0.0-SNAPSHOT-b624

### Server Software & Version

Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
@magicelk235 again record a clip and show this
the more bugreports you open for stuff i cannot replicate, the more i believe the issue isnt with oraxen
I heavily recommendd updating your server from 1.19 to 1.19.3 or even 1.19.4
No reason to remain on such an outdated version
