### ISSUE TITLE
[SUGGESTION] automatically_set_block_state and /o highest_blockstate

### ISSUE THREAD

**Issue by magicelk235** [oraxen/oraxen#779]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

automatically_set_block_state:
just like automatically_set_model_data and automatically_set_glyph_code it will automatically set block state for noteblocks and strings
/o highest_blockstate:
just like /o highest_modeldata it will tell you what the highest block state of noteblocks and strings

### Reason

automatically_set_block_state:
it will be easier to create custom blocks
/o highest_blockstate:
if you have a lot of custom blocks in a batch of different files and you want to make a custom block but you don't know if the blockstate use or not

**Comment by Boy0000** [comment]
unlike cmd there are significant side effects to bugs with this
items can easily be updated, blocks placed can not
i will not add an automatic assigning of custom variation
