### ISSUE TITLE
[BUG] WEIRD HEADS ON TREES (SLIMEFUN)

### ISSUE THREAD

**Issue by HonzasikCZ** [oraxen/oraxen#783]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Hello!

I don't know if this is caused by Oraxen, but with the SlimeFun addon ExoticGarden, different heads appear on the trees than they have and strangely colored (black and green, blue and black and white)

Without the resource pack, the heads display correctly as fruit

### Steps to reproduce

I don't know what to write here

### Plugin Version

1.155.0-hotfix

### ProtocolLib Version

5.0.0-SNAPSHOT-b616

### Server Software & Version

git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
@HonzasikCZ this is due to the Gesture feature, simply disable it in settings.yml and heads will return to normal
