### ISSUE TITLE
[SUGGESTION] Any way to use custom models as an armor (e.q. Chestplate)

### ISSUE THREAD

**Issue by DenkingOfficial** [oraxen/oraxen#787]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Is there any way to edit chestplate/leggings/boots model?

I can create custom helmet using:
```
Mechanics:
  hat:
    enabled: true
```

But I can't find docs on how to change a model of other armor or info if it's even possible

My item yml file:
```
backpack:
  displayname: "<gradient:#00AD43:#056608>Backpack"
  material: LEATHER_CHESTPLATE # without this it isn't wearable
  Mechanics:
    durability:
      value: 400
  AttributeModifiers:
    - { name: "smth", attribute: GENERIC_ARMOR, amount: 4, operation: 0,
        uuid: cafd4cfa-d58a-11ed-afa1-0242ac120002, slot: CHEST }
    - { name: "smth", attribute: GENERIC_ARMOR_TOUGHNESS, amount: 1, operation: 0,
        uuid: cafd4cfa-d58a-11ed-afa1-0242ac120002, slot: CHEST }
  Pack:
    generate_model: true # tried false, not working
    parent_model: "wearings/backpack" # also tried "model" parameter instead, not working
```

Now it looks like this:

![image](https://user-images.githubusercontent.com/38957619/230681415-f31997bb-72b8-4d3a-b8f6-9a2a14630809.png)

Any help much appreciated
Thank you so much for this amazing plugin!!!

### Reason

.

**Comment by Boy0000** [comment]
No there is not. Game doesnt render this. Only headslot can have non-armor/helmets visible @DenkingOfficial @d4shsk
