### ISSUE TITLE
[BUG] oraxen.command.inventory.give: No such permission

### ISSUE THREAD

**Issue by DenkingOfficial** [oraxen/oraxen#788]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

I used a LuckPerms to edit permissions on the server, but setting `oraxen.command.inventory.give` to `false` doesn't do anything. As well as it is not showing in permissions tree:

![image](https://user-images.githubusercontent.com/38957619/230734433-cfec59a8-298b-4f3d-ab08-844d10f7383b.png)

But information about this is on the documentation page:

![image](https://user-images.githubusercontent.com/38957619/230734757-ebc0f718-8f3e-47e0-8f07-8f75c6934c6e.png)

### Steps to reproduce

1. Set permission `oraxen.command.inventory.give` to `false`
2. Join the server
3. See no difference, items are still obtainable using GUI

### Plugin Version

Oraxen version 1.155.0

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b630

### Server Software & Version

This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
If memory serves they also need oraxen.command
It is dumb and ill make it default to true for future update but sideeffect of commandapi @DenkingOfficial

**Comment by DenkingOfficial** [comment]
I can't understand what do you mean

Docs page says that there is a `oraxen.command.inventory.give` permission which allows to get item from the inventory visualizer. But there is no such permission at all. I want players to be able to view items in the GUI but unable to get them using a button.
