### ISSUE TITLE
[BUG] Oraxen and Slimefun player_head textures

### ISSUE THREAD

**Issue by Bunnky** [oraxen/oraxen#789]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When Oraxen and Slimefun are on the server, Oraxen is breaking Slimefun's textures for all `player_head` items after placed. It seems to turn textures either pure white or pure black, and only changes the texture when another head item is placed near it. It is not consistent as to what changes. Sometimes the `player_head` you placed changes, but sometimes its a `player_head` nearby that changes.

Is it possible to integrate with Slimefun? There's some other issues with Oraxen and Slimefun textures, but thats a seperate topic we worked around. Maybe integrating with Slimefun could fix both issues? I have no idea lol :)

Here's some visuals to help explain:

https://streamable.com/z66njq

![image](https://user-images.githubusercontent.com/6545569/230780667-f24e883c-b818-4583-892e-6da52d1dbcc1.png)
Heads that are not a custom textured `player_head` seem unaffected.

### Steps to reproduce

1. Place a Cargo node from Slimefun on the ground
2. Place another cargo node next to it, or on top.

### Plugin Version

[10:51:55 INFO]: Oraxen version 1.155.1
[10:51:55 INFO]: Authors: th0rgal and boy0000

### ProtocolLib Version

[10:52:21 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b616
[10:52:21 INFO]: Provides read/write access to the Minecraft protocol.
[10:52:21 INFO]: Authors: dmulloy2 and comphenix

### Server Software & Version

[10:52:40 INFO]: This server is running Paper version git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36)
You are running the latest version

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
Player Heads are borked when Gestures is not disabled in settings.yml due to shader stuff @Bunnky
