### ISSUE TITLE
[BUG] Linux pack failed to load

### ISSUE THREAD

**Issue by KalebSchmidlkofer** [oraxen/oraxen#790]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

I was testing out my server on linux and whenever I joined when it tried to load the resource pack it would say `Pack Failed to load`, 

### Steps to reproduce

I started minecraft 1.19.4 on my steam deck(and on my laptop just incase it was specific to the system)  no mods just vanilla 19.4 then I launched the server, It askes if you want to download/enable the pack, I say yes, It then loads the pack then quits to title screen

### Plugin Version

1.155.0

### ProtocolLib Version

5.0.0-SNAPSHOT-b630

### Server Software & Version

git-Purpur-1956 (MC: 1.19.4)*

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
Cant say without seeing ur client logs. Those will tell you exactly what happened. I doubt this is anything other than a malformed pack @KalebSchmidlkofer
