### ISSUE TITLE
[BUG] Dupe when using non-stackable backpack 1.19.2

### ISSUE THREAD

**Issue by oOHiyoriOo** [oraxen/oraxen#791]
### I have checked...

- [x] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

there seems to be another dupe, when using non stackable Backpacks. 
https://cdn.discordapp.com/attachments/935933244803788860/1095784937019424939/2023-04-12_20-56-35.mp4

### Steps to reproduce

1. Get Backpack
2. put items in it.
3. Put a sword in your off-hand
4. aim a flower and press right click to open the backpack
5. Flower gets destroyed by the sword + backpack should be open now.
6. Collect all your items from backpack
7. close backpack and open it with aiming at air or without the sword
8. Profit.

### Plugin Version

1.155.0

### ProtocolLib Version

5.0.0-SNAPSHOT-b606

### Server Software & Version

git-Purpur-1838 (MC: 1.19.2)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
im not sure that swords break flowers normally when right clicking?
atleast i am unable to replicate this @oOHiyoriOo

**Comment by oOHiyoriOo** [comment]
Hey, 
You're right, after even more investigation and checking, 
it turns out this issue is caused by a combination of the "DualWield" plugin, 
which allows the usage of the right hand and Oraxen, so this is actually an issue of DualWield doing its Magic
while another item is used.

Sorry I bothered you with this and did not research enough before writing this.
