### ISSUE TITLE
[SUGGESTION] More block possibilites

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#792]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

maybe some custom blocks with player heads as well?
but the main thing in the suggestion is about more block mechanics like

place cocoa (for custom logs)
bone meal it (if you want something which is not saplings) // like adding bone meal to a stripped log to revert it
shearing a block (could transform one block in other)
tiling with hoe or shovel (could transform one block in other)

### Reason

why not

**Comment by Boy0000** [comment]
this is all suggestions that should be for a custom mechanic parameter or something
similar to how MythicCrucible has skills and no inherent stuff for shearing a block
either make clickactions etc but wont be a full mechanic
