### ISSUE TITLE
[BUG] LifeLeech Bypassing WorldGuard Regions

### ISSUE THREAD

**Issue by ItsSynchro** [oraxen/oraxen#796]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Using the Lifeleech mechanic, Citizens NPCs are able to be killed

### Steps to reproduce

Use Citizens and Oraxen, grab a sword using Lifeleech and smack away at the NPCs.

### Plugin Version

Oraxen version 1.155.1

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b616

### Server Software & Version

Paper version git-Paper-445 (MC: 1.19.3)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by abhithedev200** [comment]
fixed this in my pr #798

**Comment by Boy0000** [comment]
I am unable to replicate this. It might bypass worldguard regions for damaging entities
But Citizens NPCs i cannot damage @ItsSynchro @abhithedev200 

https://user-images.githubusercontent.com/62521371/235131301-661123c5-b1b2-4244-a59d-6df710cd84ce.mp4
