### ISSUE TITLE
[BUG] Crafting Recipe

### ISSUE THREAD

**Issue by Zsomi4** [oraxen/oraxen#803]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

The problem with the current one is that I can't create more of the same item in the crafting recipes + I can't set it so that the crafted item doesn't give me more even if I set it.

### Steps to reproduce

1. Create a new recipe! (Which has several items in one crafting slot)
2. Save a recipe
3. Test the recipe

### Plugin Version

1.155.1

### ProtocolLib Version

5.0.0-SNAPSHOT-b636

### Server Software & Version

Purpur-1957

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
you cannot have crafting slots require say 2 of the same item
I believe that is a limitation of minecraft itself
only the output can be more than 1
