### ISSUE TITLE
[BUG] Can't place furnitures on flat side of the stairs

### ISSUE THREAD

**Issue by Taiyou06** [oraxen/oraxen#804]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Basically barrierless furnitures are placeable on normal blocks but they are not on bottom side of the stairs

### Steps to reproduce

1. Try to place a furniture (without barrier) to bottom of a stair
![image](https://user-images.githubusercontent.com/77050201/233843010-7a119981-260d-428c-81c7-be5f9c0699b6.png)

### Plugin Version

1.155.2

### ProtocolLib Version

5.0.0-SNAPSHOT-b615

### Server Software & Version

Current: git-Purpur-1933 (MC: 1.19.3)*
Previous: git-Purpur-1927 (MC: 1.19.3)
* You are running the latest version

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
finally figured this issue out and I blame Spigot, will be fixed in 1.156.0 thanks
