### ISSUE TITLE
JitPack fails bulding Oraxen

### ISSUE THREAD

**Issue by DerFrZocker** [oraxen/Oraxen#81]
I'm trying to integrate Oraxen into one of my plugins, but can't get the dependency, because JitPack cannot find the build artifacts of Oraxen. It seems that JitPack can build Oraxen, but than is unable to find the build jar.
After trying to build it locally on my machine, I get the same results.

I tested it with commit #e11eff0, here is the build log from JitPack: https://jitpack.io/com/github/oraxen/Oraxen/-e11eff09c0-1/build.log

**Comment by Th0rgal** [comment]
Hmm don't you get a .jar when you try to build it on your own computer?

**Comment by DerFrZocker** [comment]
Just tested it a bit more and found my error, when building it locally (forgot to set a task). I have now the jar and will add it manually to my local maven repo. But the error with JitPack still happens, would be nice if you can look into it, since it is very annoying to recompile / updated the jar after a new release.

**Comment by Th0rgal** [comment]
> Just tested it a bit more and found my error, when building it locally (forgot to set a task). I have now the jar and will add it manually to my local maven repo. But the error with JitPack still happens, would be nice if you can look into it, since it is very annoying to recompile / updated the jar after a new release.

for sure, I'll try to understand what is the bug

**Comment by kristianvld** [comment]
I have the same problem. As far as I can see, all jitpack builds have failed. Example log of tag 1.51.1:
https://jitpack.io/com/github/oraxen/Oraxen/1.51.0/build.log

List of all builds:
https://jitpack.io/com/github/oraxen/Oraxen/

My fix also ended up being to use a manually built .jar file, but due to your license, this has made things hard to distribute to other contributors, as they too would have to manually build the dependency for themselves, as distributing a compiled version or any source code is against the license.

**Comment by Th0rgal** [comment]
> I have the same problem. As far as I can see, all jitpack builds have failed. Example log of tag 1.51.1:
> https://jitpack.io/com/github/oraxen/Oraxen/1.51.0/build.log
> 
> List of all builds:
> https://jitpack.io/com/github/oraxen/Oraxen/
> 
> My fix also ended up being to use a manually built .jar file, but due to your license, this has made things hard to distribute to other contributors, as they too would have to manually build the dependency for themselves, as distributing a compiled version or any source code is against the license.

That's right. Any idea what I did wrong with jitpack?

**Comment by kristianvld** [comment]
It seems you have not setup publishing in your `build.gradle` file. Checkout this example gradle project for jitpack as a reference:
https://github.com/jitpack/gradle-simple
especially the build.gradle with the maven plugin and install task.

Here are your build logs from your latest commit:
https://jitpack.io/com/github/oraxen/Oraxen/-a15b05c825-1/build.log

You can see that it builds the project, but just doesn't know where the artefacts are. Compare this to the successful build logs from the example jitpack gradle project:
https://jitpack.io/com/github/jitpack/gradle-simple/1.1/build.log

**Comment by Th0rgal** [comment]
Thanks for your help. Does it work fine now?

**Comment by DerFrZocker** [comment]
For me it works fine now.

**Comment by Th0rgal** [comment]
Awesome!

**Comment by kristianvld** [comment]
Thank you. Seems to work fine now. 👍
