### ISSUE TITLE
[BUG] <Replacement of Nova units>

### ISSUE THREAD

**Issue by Vlad0Crystal** [oraxen/oraxen#818]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When the explosion occurs, replace the Nova blocks with mushrooms.

### Steps to reproduce

It is necessary to establish  https://www.spigotmc.org/resources/nova-modding-framework-1-19-3.93648/
https://www.spigotmc.org/resources/nova-addon-machines.102712/

But this is alpha from discord. For 1.19.4

### Plugin Version

1.155.3

### ProtocolLib Version

5.0.0 snapshot 636

### Server Software & Version

git-Paper-519 (MC: 1.19.4)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Vlad0Crystal** [comment]
https://user-images.githubusercontent.com/47213885/236450633-e8e0b9e4-1353-4ae4-b2d9-ea1d7a4c4141.mp4

**Comment by Boy0000** [comment]
this just seems like a Nova issue idk, sorry for the late response
