### ISSUE TITLE
[SUGGESTION] Tweaks to ItemName/DisplayName

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#820]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

1 - everytime you want a item to be named like vanilla, you have to place "<white>" at the start of the item name (if you dont add it, it will be italic) so... why not remove this and make it happen by default? 
so, instead of "displayname:  <white>Item name here"  it would simply be   "displayname:  Item name here"

2 - MULTILANGUAGE Item Name

In Minecraft, you can get items with a trasnslateable name with commands, like
/give @p stone{display:{Name:'{"translate":"item.my_custom_stone","italic":false}'}

then, in language files you would add

EN-US "item.my_custom_stone": "New Stone"
PT-BR "item.my_custom_stone": "Pedra Nova"
EN-WTF "item.my_custom_stone": "Burger Stone"

 in Oraxen, it could be like **displayname:  <translate:"item.my_custom_stone">**

### Reason

cuz this would be awesome

**Comment by GliczDev** [comment]
Oraxen supports MiniMessage format, so multilanguage item name should work with this format: https://docs.advntr.dev/minimessage/format.html#translatable

**Comment by GliczDev** [comment]
It should look like this: `<lang:*path*>` (*path* is just a placeholder, you need to paste paru here, without *). Everything is explained in MiniMessage docs, even with examples

**Comment by Boy0000** [comment]
there are some parts that is simply off limits due to spigot API using strings.
Cannot simply change to papers api as that will most definetly break some stuff on spigots end i assume
translatable components are just not something that is feasable to support in itemnames using strings so
