### ISSUE TITLE
[BUG] Colored Furniture doesnt drops with the color

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#822]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Self explanatory, when you place a colored furniture and break it again, the color will vanish

### Steps to reproduce

- create a dyeable furniture
- dye it
- break it
- the color vanishes
- cry or dye it again, and again, and again

### Plugin Version

Oraxen version 1.155.2

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b606

### Server Software & Version

Minecraft 1.19.4
Purpur MC

git-Purpur-1967 (MC: 1.19.4)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
unable to rreplicate this at all. whenever a dyable furniture is broken it drops just fine

**Comment by Boy0000** [comment]
ur right nvm, fixed in 1.156.3 though with an overhaul to furniture drops. should indirectly fix alot other issues
