### ISSUE TITLE
[BUG] formatting settings strips tag even disabled

### ISSUE THREAD

**Issue by JeremyDarbellay** [oraxen/oraxen#826]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Hi, 
I've tried to toggle "formatting.anvil" settings, then output is stripped anyway.

In theory, formatting disabled doesn't format right ? But here, it strips legacy tags, even disabled.

I'm using CMI, with cmi internal command "/itemname &6golden sword" it works (name is colored)
with anvil, it doesn't work (name is &6golden sword)
with anvil and without oraxen, it works (name is colored)

Can you please, doesn't strips legacy tags when formatting is disabled ?
Thank you in advance, have a nice day !

### Steps to reproduce

have a compatible plugin which allow legacy color to name items in anvil.
set settings.yml > Plugin.formatting.anvil to false
Put a color tag like &6 on an item with an anvil, 
check the name -> "&6GoldenSword"

### Plugin Version

1.155.4

### ProtocolLib Version

5.0.0 #631

### Server Software & Version

paper 1.19.4 # 522

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
There is some clunkyness to it atm, ill look into it.
In essence the formatting as is right now only applies to result item
Legacy bad though but whatbever

**Comment by JeremyDarbellay** [comment]
Legacy not the real problem, it's not that bad, it's way more intuitive for players who don't speak English, and for old players. Many of my players don't know hex code or what means "purple", Minecraft can be played by everyone, even players that don't speak English.
We have a command that show what legacy code does, it's "simpler" for player to type "/colors" and use that. This feature is pretty common. And many tutorials show how to use legacy color codes, hex and adventure format aren't so well documented for players. 

And this specific feature is used by players, not only admins/dev, but players, that's why, i'm here. 

I know that legacy need to be deprecated etc, but for now, is it not better to be accessible and fair with everyone, event those who don't speak English and need easier features ?
When legacy won't exist anymore, we probably need something else, but, that's our problem, your problem is that your put a toggle "does my plugin need to format strings in anvil ? yes/no", and even if "no" you format strings in anvil. Remove the option and say that you don't support legacy anymore, or do what you say "not formatting".

Have a nice day
