### ISSUE TITLE
[BUG] Some furniture is invisble after placing

### ISSUE THREAD

**Issue by Tomcatchriss** [oraxen/oraxen#828]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Most of the furniture works as intended, but the furniture Coach, Chair and Cart not working correctly. When I place them, they turning invisible. I can see the barrier blocks, but nothing else.

### Steps to reproduce

Place the furniture

### Plugin Version

Oraxen version 1.155.4

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-642

### Server Software & Version

 git-Purpur-1964 (MC: 1.19.4)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
@Tomcatchriss if ur server is on 1.19.4 and ur fuirniture is type: DISPLAY_ENTITY it will only be visible to players on 1.19.4 clients and above.
If your server isnt forcing players to be on 1.19.4 i suggest using ITEM_FRAME as the type

**Comment by Tomcatchriss** [comment]
Thank you. I didn't know, I could change this for the premade items. That works for me. Thank you.
