### ISSUE TITLE
[SUGGESTION] GSIT Integration

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#830]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

so you would be able to use /crawl /lay /gspin and other mechanics together with oraxen furnitures
also, this would be a lot easier for seat mechanic in furnitures 

the GSIT mechanic also moves the seat yaw for wherever youre looking at so,,, your body will always move to where youre looking at as well (i thought of it cause of a error i was having before, which i thought was a bug #821 ) 

### Reason

the gsit plugin offers a lot of cool stuff, imagine a bed furniture in oraxen and when you right click you automatically lay in it?

**Comment by Boy0000** [comment]
suppose i could integrate it so if gsit is on the server it will use that instead
still should spawn seats and everything like normal
