### ISSUE TITLE
[SUGGESTION] new storage-like mechanics

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#831]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

with that, you would be able to create new crafting tables/ furnaces/ smithing table/ anvil or other vanilla gui mechanics to be attached to custom blocks or furnitures

you already can do something that does look like this using essentials or cmi, and setting the block or furniture to execute "/craft <player, /smithing <player" but it would vanish the items when you close the gui

### Reason

i wanted to make a custom vending machine furniture
using a villager gui, imagine
you right click the block and then opens villager trades
(which you would be able to customize the trades )

**Comment by Boy0000** [comment]
plan to add these types to storage mechanic yeah
