### ISSUE TITLE
[SUGGESTION] BeautyQuests support 

### ISSUE THREAD

**Issue by magicelk235** [oraxen/oraxen#833]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

this will add BeautyQuests support so you can create custom quests for custom oraxen blocks/furniture 

### Reason

beautyQuests is easy to use and It will really be helpful if there oraxen support

**Comment by Boy0000** [comment]
i have 0 clue what oraxen would do in this scenario? this seems like something you would ask for on BeatyQuest's end
