### ISSUE TITLE
[BUG] LIGHTAPI unsupported in 1.19.4 (Even the Fork)

### ISSUE THREAD

**Issue by Steven-OS** [oraxen/oraxen#842]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Light API doesn't work for items in 1.19.4
https://www.spigotmc.org/resources/lightapi.4510/
And neither does the fork: https://github.com/IPECTER/LighterAPI/releases/

The results is this: 
https://gyazo.com/f44dfd6092db9fa8691f9aa205888999.mp4

### Steps to reproduce

Install oraxen
Install light api OR the fork (both dont work)
On PaperSpigot 1.19.4
ProtocolLib 5.0.0

Put light 15 on the block

The block will show up as lighted, but not emmit light

### Plugin Version

1.156.0

### ProtocolLib Version

5.0.0

### Server Software & Version

This server is running Paper version git-Paper-538 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: bcd8dc2)
You are running the latest version
Previous version: git-Paper-524 (MC: 1.19.4)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
not an issue I can do much about
Paper changed their chunk system, thus breaking LightAPI
LighterAPI is a fork of LightAPI which fixes this issue
If it still doesn't work not sure it isnt an issue on Oraxens side atleast.
Suggest making an issue on LighterAPI github
