### ISSUE TITLE
[BUG] Models for items not showing?

### ISSUE THREAD

**Issue by Play12mmmmm** [oraxen/oraxen#849]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When trying to use the plugin (This is my first time using it) the models seemed to not appear? i have the resource pack installed and nothing edited!

### Steps to reproduce

im not sure how to explain this, when going to either the crafting table or "/o inv" no models appear. even when i do have the item equip, and its only the models that aren't really showing ( also the legendary and earth hammer are showing everything else no )

### Plugin Version

Authors: th0rgal and boy0000
Oraxen version 1.156.2

### ProtocolLib Version

ProtocolLib version 5.0.0
Provides read/write access to the Minecraft protocol.
Authors: dmulloy2 and comphenix

### Server Software & Version

This server is running Paper version git-Paper-545 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: bacbf86)
You are running the latest version
Previous versiongit-Paper-542 (MC: 1.19.4)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
please visit the discord for support. Probably a malformed config or something.
