### ISSUE TITLE
[SUGGESTION] AUTO-SET Custom Variation for blocks

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#850]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

just as auto set custommodel data but for blocks

### Reason

it would be great and easier to avoid conflicts, and we already have it for custom model data... so.. why not for blocks as well?

**Comment by Boy0000** [comment]
not gonna do this as unlike CMD there is very little logic to update placed blocks
forcing users to understand and manually have control over them is the best way to prevent these issues
