### ISSUE TITLE
[SUGGESTION] Item Folders/Subfolders

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#851]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

make that you could use folders to have multiple type of items inside of it
for example:
![image](https://github.com/oraxen/oraxen/assets/47507632/31f22fe0-5039-4ec4-94f3-ace088a7f1fd)
the folders would have a chest icon
inside of the folders, you could have multiple other yml to items

oraxen/items/furniture  > furniture is a folder
inside of it you could have "common.yml" "rare.yml", when opening the "furniture folder" using /oraxen inventory you would have all the subfolders

### Reason

for example, if you want to add a lot of furnitures or blocks
you could make subfolders for specific types

for example

oraxen/items/furniture  > furniture is a folder
inside of it you could have "common.yml" "rare.yml"

**Comment by Boy0000** [comment]
probably the better idea ive seen for structuring submenus for oraxen inv
thanks, ill probably implement this
