### ISSUE TITLE
[BUG] Item name

### ISSUE THREAD

**Issue by pmgalileo** [oraxen/oraxen#869]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

when I place an item and then pick it up, it renames itself  into "paper".

### Steps to reproduce

place an item and then pick it up :)
[video](https://imgur.com/a/hSL29j8)

### Plugin Version

latest
Oraxen version 1.156.4

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b625

### Server Software & Version

git-Purpur-1980 (MC: 1.19.4)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
duplicate issue, fixed in upcoming release
