### ISSUE TITLE
[SUGGESTION] add more information about customoregenerator plugin

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#871]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

https://docs.oraxen.com/compatibility/world-generators/custom-ore-generator
or maybe make oraxen have its own way to generate custom ores??? 

### Reason

im trying to make it work for hours and hours.... and i cant understand why its not working lol...

**Comment by Boy0000** [comment]
it does not and its up to these plugins to elaborate on how they have compatibvility with oraxen
