### ISSUE TITLE
[BUG] Display Entity light & brightness features not working as it should

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#872]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

both "light: x" (LightAPI)
and   "display_entity_properties brightness, block/sky"
are not working correctly

### Steps to reproduce

place a display entity with light or brightness properties

### Plugin Version

1.156.4

### ProtocolLib Version

5.0.0 b 606

### Server Software & Version

Purpur 1.19.4
Build 1984

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
this isnt a bug with oraxen its a bug with minecraft itself. you should probably open a bugreport on mojira
