### ISSUE TITLE
[BUG] Item frame furniture not working correctly in 1.19.4

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#873]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

they are being replaced for a whole 1x1x1 display entity with hitbox and stuff like that

![image](https://github.com/oraxen/oraxen/assets/47507632/9ef33bf8-0d4d-4165-b21b-ceb3e8021ed1)

### Steps to reproduce

create a itemframe furniture
place it
F3+B to check hitboxes

### Plugin Version

1.156.4

### ProtocolLib Version

5.0.0 b606

### Server Software & Version

Purpur 1.19.4
Build 1984

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
yes im forcing a 1x1x1 hitbox on itemframes if u specify no barrier or specify no hitbox
this isnt a bug this is just a straight up improvement over no hitbox at all
