### ISSUE TITLE
[SUGGESTION for GITHUB] Tweak / Remove the "repeated" options when repoting a bug

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#874]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

![image](https://github.com/oraxen/oraxen/assets/47507632/00b37c94-b449-43c6-bb85-9447ee80235e)
![image](https://github.com/oraxen/oraxen/assets/47507632/e496d9c6-a538-4b07-92c9-ad9577e42aaa)

### Reason

it is kinda confusing and i have to check the versions everytime cuz i have bad memory even tho i know its the latest one Dx

**Comment by Boy0000** [comment]
not gonna happen
