### ISSUE TITLE
[BUG] String blocks can be triggered and become other blocks

### ISSUE THREAD

**Issue by AllayBreeze** [oraxen/oraxen#881]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When player or mobs step on a string block, the "powered" state of string is changed, causing models to change, too. And also the drops are changed when breaking the block.
![image](https://github.com/oraxen/oraxen/assets/108282297/6b0380d8-b354-4235-a7f8-e84513d4f87d)
![image](https://github.com/oraxen/oraxen/assets/108282297/59fd7a0b-617e-432b-828c-60571170dc04)

### Steps to reproduce

1. Create some custom string blocks;
2. Place a string block (vanilla or custom), then step on it or summon a mob on it.

### Plugin Version

Oraxen version 1.157.0

### ProtocolLib Version

ProtocolLib version 5.1.0-SNAPSHOT-649

### Server Software & Version

git-Purpur-1990 (MC: 1.20)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by AllayBreeze** [comment]
It seems that block updates can also change the states of string blocks (such as placing a solid block near a string)
A screenshot:
Uploading 20230614191128.mp4…

**Comment by Boy0000** [comment]
@AllayBreeze the issue is Oraxen currently only checks for Paper not forks of paper
The issue is cuz ur using Purpur which doesnt register the listener. I'll try and fix it for 1.157.1
