### ISSUE TITLE
[SUGGESTION]  add for string "whitelist_blocks"

### ISSUE THREAD

**Issue by magicelk235** [oraxen/oraxen#889]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

add for string "whitelist_blocks" and if it's set to dirt you can only place it on dirt and you can set multiple blocks? (work with oraxen blocks too)

### Reason

make the string more helpful if you want to make a plant for the plains or a plant for the desert

**Comment by Boy0000** [comment]
limited placing mechanic exists
