### ISSUE TITLE
pushes us as we place custom blocks

### ISSUE THREAD

**Issue by bkgktp** [oraxen/oraxen#893]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When I hold down oraxen note blocks and try to stack them, it throws me down a few blocks later and pushes me.

### Steps to reproduce

just take a custom block and try to get out quickly by putting it on top of each other.

### Plugin Version

1.157.1

### ProtocolLib Version

5.0.0

### Server Software & Version

1.19.4-purpur

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
please record a clip and upload here @bkgktp as im not able to replicate this

**Comment by bkgktp** [comment]
https://streamable.com/hw6zpi

@Boy0000 just try and hold it down.

While it should be placed upwards, it constantly falls down and starts again.

**Comment by Boy0000** [comment]
simply comes down to delay oraxen needs to place blocks. Might be able to speed it up but it would never be same as normal blocks ithink

**Comment by Boy0000** [comment]
this should be alot better with the new experimental nms magic used for correcting and placing blocks
might not but best i can get it atm ithink
