### ISSUE TITLE
[BUG] OraxenFurniture#remove() is not working as intended.

### ISSUE THREAD

**Issue by botprzemek** [oraxen/oraxen#894]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Installed fresh Paper server, added in plugin with Oraxen API, Oraxen and necessary dependencies. When running the code, block is placed, but is not removed with API's #remove().

[Video Footage](https://cdn.discordapp.com/attachments/613680450761785344/1120102221208633434/Base_Profile_2023.06.18_-_23.23.07.02.mp4)

### Sample code for test
```java
    @EventHandler
    public void onBlockBreak(BlockBreakEvent event) {
        Player player = event.getPlayer();
        Location location = event.getBlock().getLocation();

        OraxenFurniture.place(location, "plant", Rotation.NONE, BlockFace.UP);
        player.sendMessage("Test 1");

        Bukkit.getScheduler().runTaskLater(DropPlugin.getPlugin(), bukkitTask -> {
            OraxenFurniture.remove(location, player);
            player.sendMessage("Test 2");
        }, 20);
     }
```

### Plugin Version

Oraxen version 1.157.1
Authors: th0rgal and boy0000

### ProtocolLib Version

ProtocolLib version 5.0.0
Provides read/write access to the Minecraft protocol.
Authors: dmulloy2 and comphenix

### Server Software & Version

Current: git-Purpur-1949 (MC: 1.19.4)*

### How breaking is the bug?

Bug - Plugin usable, but makes server unstable.

**Comment by Boy0000** [comment]
this should be fixed in 1.159.0
my guess is its due to location being where a barrier is or something
ur best bet is to actually use the baseEntity
