### ISSUE TITLE
[BUG] Default blocks and plants from oraxen bugged with vanilla note block and string

### ISSUE THREAD

**Issue by iSeitan** [oraxen/oraxen#896]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When a player use a noteblock and strings and break then it often gives the default oraxen custom blocks and plants wich are not suppose to be obtainable

### Steps to reproduce

place strings or noteblock, place any block on the side and break it

### Plugin Version

1.157.1

### ProtocolLib Version

#654

### Server Software & Version

pufferfish-paperclip-1.20.1-R0.1-SNAPSHOT-reobf

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
entirely unable to replicate this. Please record this bug and add it to this issue @iSeitan 

https://github.com/oraxen/oraxen/assets/62521371/54f72901-2789-4d4e-a78c-bc5cc8e6063f

**Comment by iSeitan** [comment]
https://medal.tv/games/minecraft/clips/1eM5xxts4OKbW3/d1337iiPh7w0?invite=cr-MSxzazYsMzUyMzIzMDgs

**Comment by Boy0000** [comment]
still unable to replicate this, please test it on a server with only oraxen and protocollib
use the /oraxen dump_log command and attach it here


https://github.com/oraxen/oraxen/assets/62521371/a012904a-1441-4ce4-894f-708545422544
