### ISSUE TITLE
[BUG] Custom Blocks Revert To Note Blocks

### ISSUE THREAD

**Issue by RogerPlaysMC** [oraxen/oraxen#902]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When you break the block on top of a custom block such as Amethyst Ore, the Ore reverts to a note block. I tested this with both regular blocks and custom blocks on top, the behavior was the same. Video for reference. 

https://github.com/oraxen/oraxen/assets/13864277/9803a2c9-ff72-4934-83ad-ed5d06d258fa

### Steps to reproduce

Place a custom ore block. Place another block on top of it. Break the top block, the bottom one turns into a note block.

### Plugin Version

Oraxen version 1.157.1

### ProtocolLib Version

ProtocolLib version 5.0.0

### Server Software & Version

git-Purpur-1996 (MC: 1.20.1)*

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
@RogerPlaysMC try this on Paper and not Purpur, and try it with only Oraxen and Protocollib on your server
im entirely unable to replicate this issue so my guess is theres something goin on on your end but

**Comment by RogerPlaysMC** [comment]
This seems to be a Purpur issue. Setting `disable-note-block-updates: true` in purpur.yml solved the problem. Client side, the adjacent custom blocks still flash as note blocks when a custom block is broken, but I'm guessing that not much can be done there.
