### ISSUE TITLE
[BUG] string block change when breaking a block nearby, same thing when you bone meal nearby

### ISSUE THREAD

**Issue by magicelk235** [oraxen/oraxen#906]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

1. when you break a block in any direction(every string block has it own) it change to string block or custom string block
2. when you bone meal near a string block sometimes it changes to a string block or custom string block

### Steps to reproduce

1. place a custom string block then place a block nearby then break it
2. place a custom string block then bone meal nearby blocks

### Plugin Version

1.157.1

### ProtocolLib Version

5.1.0-SNAPSHOT-644

### Server Software & Version

Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
please record this happening and show it
im unable to replicate this so gonna need more info

**Comment by magicelk235** [comment]
https://github.com/oraxen/oraxen/assets/120495924/72d9c300-5981-45f2-9e5a-ff9c0643d4ec

**Comment by magicelk235** [comment]
https://github.com/oraxen/oraxen/assets/120495924/b85eb9eb-755a-401e-94e4-f91de44f6004

**Comment by magicelk235** [comment]
@Boy0000
