### ISSUE TITLE
[SUGGESTION] Make a page in the docs for changelogs info

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#914]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

above Getting Started and FAQ, Changelogs would be a great addition, with clickable links and stuff like that (just like in polymart or spigot page)

### Reason

i think this would be helpful to get more information with changelogs to compare stuff in the docs, so i wouldnt need to go back to polymart or spigot to check the changelog and look for informations in the docs everytime, since i could just click

**Comment by Boy0000** [comment]
the changelog is already on polymart, spigot and discord
not gonna add that to the docs aswell
