### ISSUE TITLE
[SUGGESTION] Half-Barrier Furnitures

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#915]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

it would be a little more laggy and tricky cuz it would use invisible invulnerable shulkers with open lid
could also be made using vanilla shaders with petrified oak slab, or even using an specific campfire/soul campfire/sculk sensor/sculk shrieker blockstate

or somehow create a collision box for furnitures

### Reason

![image](https://github.com/oraxen/oraxen/assets/47507632/65951f41-d1c8-43a1-8947-864166bbf9c5)

would be great for small furnitures that you want to have a hitbox that you could walk trough 
worth mentioning it would also allow waterlogged furniture

**Comment by Boy0000** [comment]
the only real solution here is using petrified oak slab
that said this requires a big reword of the current system so it wouldnt come any time soon

**Comment by Boy0000** [comment]
not gonna work due to xray blocks
