### ISSUE TITLE
[BUG] Non-barrier furniture not protected against breaking due to WorldGuard using Interaction Flag

### ISSUE THREAD

**Issue by TheLaoming** [oraxen/oraxen#918]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Hey, so I just recently updated from 1.19.2 to **1.19.4** and noticed a bug, where players without permissions to break/place (or whatever else) are able to break furnitures using type ITEM_FRAME. It's little bit fatal issue for me.

### Steps to reproduce

Since I can't change to display entity, because it will break all of the furnitures around the world, i'm lost at this point.
I need any kind of fix for item frame furnitures then. Furnitures using ITEM_FRAME and barrier are fine, only without is buggy.
These furnitures are also breakable if I click slightly above the actual location and even due to fact, I am not using display entity.

Tested with multiple versions of Worldguard and WE/FaWE.

Can't post files larger than 10MB, so video is [here](https://streamable.com/iaaqax)

### Plugin Version

1.157.2, tested with 1 and 0 too.

### ProtocolLib Version

5.1.0-SNAPSHOT-654

### Server Software & Version

Paper version git-Paper-550 (MC: 1.19.4), but it's buggy with other forks too.

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
Cant seem to replicate this, anything else u might have forgotten to mention?
Please show the WG flags u have set @TheLaoming 

https://github.com/oraxen/oraxen/assets/62521371/cf3c84fd-42ae-4c53-ba18-fb99b4635b8c

**Comment by TheLaoming** [comment]
Hey, so I just found my issue @Boy0000. I have setup 2 regions. One is standard __global__ with same flags as you shown (plus blocked interation and other stuff). Another is just cuboid region with priority 3, and allowed interaction, but block-place and block break was on "**deny**". Strange fact is, that players are able to break in regions with interact allow, which is really odd, because when I was on 1.19.2, I had the same region with same flags and it was all fine. Now on 1.19.4 block-break (which is disabled in default in regions) has no effect at all. Looks like interact flag have been changed.
[My regions](https://imgur.com/a/CTlt5Z5)

**Comment by TheLaoming** [comment]
Well, but I figured out that players are able to break it in other players Residences (plugin Residence).
Unfortunatelly it was all fine until I used 1.19.4, so it's definitely an issue oraxen and really fatal one. Please let me know, if you find a solution, cuz this kind of bug is really stupid and making me think about to switch to IA in this case.

**Comment by TheLaoming** [comment]
Now back to regions again. I'm also limited about sit furnitures like chairs etc., cuz I have to keep interact flag disabled to protect non barrier furnitures, but in the same time furnitures using sit mechanic aren't functional due to that. Some furnitures are completely unusable for me now.
