### ISSUE TITLE
[SUGGESTION] tags

### ISSUE THREAD

**Issue by magicelk235** [oraxen/oraxen#921]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

this feature will add a way to add tags like the give command ![image](https://github.com/oraxen/oraxen/assets/120495924/3fb69f19-755b-45bf-9752-a5cf877a9188)

### Reason

will be useful if you're using a lot of plugins that not always support each other

**Comment by Boy0000** [comment]
PersistentData is a property already for items
