### ISSUE TITLE
[BUG] Multi-Glyphs console spam

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#924]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

![image](https://github.com/oraxen/oraxen/assets/47507632/938726a7-1d57-49e0-8fee-6a5d8f6fd5e2)

Basically, it will look up for a texture even if you already defined it in font.yml
it does works fine, but the console is filled up with the error messages

### Steps to reproduce

- Make multibitmap glyphs
- Define the textures only in font.yml and not in the glyphs itself
- It will work perfectly
- Check your logs, there will be a lot of "ghost/fake errors"

![image](https://github.com/oraxen/oraxen/assets/47507632/f05437c2-359a-4ca3-b888-06cae67b76fd)
![image](https://github.com/oraxen/oraxen/assets/47507632/039b3b59-f1a2-469b-8649-d8123948c53d)

### Plugin Version

1.157.2

### ProtocolLib Version

5.0.0

### Server Software & Version

Purpur 1.19.4

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
texture was kinda still a required property for verification but yes its a "bug"
