### ISSUE TITLE
[SUGGESTION] Furniture position adjustment in bottom-type slabs

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#925]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

![image](https://github.com/oraxen/oraxen/assets/47507632/0402c3f8-6318-44b5-9b47-574297780222)

![image](https://github.com/oraxen/oraxen/assets/47507632/b2dafcfb-455f-4503-b833-49e461c4d72f)

### Reason

since display entitys is now a thing and itemframes is not necessarly needed anymore, maybe we could have this feature

**Comment by Boy0000** [comment]
this would be broken with barrier based furniture, if implemented it would only support non barrier furniture
