### ISSUE TITLE
[SUGGESTION] Option "Enable-Random-Rotation" for custom blocks mechanics

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#929]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

This is the blockstate that Oraxen generates`
"instrument=basedrum,note=11,powered=false": {"model": "custom/block/wood/stripped_palm_wood"},`

We could have an option to enable a random-rotation of the block, like this one
```
"instrument=basedrum,note=11,powered=false": {"model": "custom/block/wood/stripped_palm_wood"},{"model": "custom/block/wood/stripped_palm_wood","y:90"},{"model": "custom/block/wood/stripped_palm_wood","y:180"},{"model": "custom/block/wood/stripped_palm_wood","y:270}
``` 

### Reason

This type of rotation is in the Y axis (sides only) so would be great for blocks with multiple sides textures, like the crafting table, so instead of the front side of the texture always displaying the same side

**Comment by Boy0000** [comment]
you can do this manually by disabling pack gen and sorting it
This seems like a very neach feature so not something im gonna be adding for now
