### ISSUE TITLE
[Request] Support legacy formatting for signs

### ISSUE THREAD

**Issue by Yukylyu** [oraxen/oraxen#931]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Hi,
I have just updated oraxen to fix bugs but it created others for me; my server is in 1.19.2 and I use the version of oraxen (v1.157.3 ) . Since the addition of these lines in the setting file:
 formatting: # This uses MiniMessage formatting, so legacy colors like §c or &c will not work
     inventory_titles: true # Formats all inventory titles made by any plugin
     titles: true # Formats all titles made by any plugin
     subtitles: true # Formats all subtitles made by any plugin
     action_bar: true # Formats all action bars made by any plugin
     anvil: true # Formats the result item based on the Anvil Text made by any plugin
     signs: true # Formats text on signs when placed or edited
     chat: true # Formats text and glyphs in chat. Disable if using a chat-plugin and you are experiencing issues
     books: true # Formats glyphs in books.
The color codes (legacy) no longer work on the signs (I have color tags that appear) but if I deactivate the option on the signs the glyphs no longer work whereas it was not the case for the versions before (where i havethe two,  color and glyphs).
I don't understand the reason for this change in color code for the signs. Is there a solution to fix this problem in 1.19.2 or this problem will  be fixed by upgrading my server to 1.20?
Thank you in adavance for your answer.
Best regards.

### Steps to reproduce

place a sign
write "&f your message"

### Plugin Version

oraxen-1.157.3 

### ProtocolLib Version

v5.0.0

### Server Software & Version

paper 1.19.2

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
because oraxen doesnt support legacy formatting like &c but <red>
and yes glyphs wont work, unless u use the raw unicode, on signs if u disable formatting
This is just how oraxen chooses to handle it, could it support legacy? sure in theory but its called legacy for a reason aswell

**Comment by Yukylyu** [comment]
Thank you, If you could improve this that would be great.
