### ISSUE TITLE
[BUG] <Custom Hud>

### ISSUE THREAD

**Issue by 19047spy** [oraxen/oraxen#933]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

All enabled, but custom hud does not work, it is not displayed

### Steps to reproduce

I have activated all the parameters in the hud.yml, the resourcespack is active, I have given players all the permissions but it just doesn't show up

huds:
  balance:
    permission: "oraxen.hud.balance"
    display_text: "<shift:100><font:balance_hud>%vault_eco_balance%<font:default><glyph:coin>"
    disabled_whilst_in_water: true
    enabled_by_default: true
    enable_for_spectator_mode: false

### Plugin Version

Oraxen version 1.157.3

### ProtocolLib Version

ProtocoloLib version 5.0,0

### Server Software & Version

This server is running Paper version git-Paper-50 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 990be16)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
probably needs to be "toggled" on @19047spy , stop by the support discord if u need more help
ill leave this open for now
