### ISSUE TITLE
[BUG] recipe

### ISSUE THREAD

**Issue by blockwarss** [oraxen/oraxen#934]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Items from /o give or /o inv work for custom crafts, but as soon as they are recovered for example by breaking an amethyst_ore and it gives us amethyst well with the amethyst we can't craft anything. so for the crafts to work they must be given and not found by mining or other...

### Steps to reproduce

make a craft with /o recipes builder shaped or other, use oraxen items in the design and in the given item. Then restart and place the ores on the ground break the recovered survival for example the amethyst and try to craft and there it will not work.

### Plugin Version

 Oraxen version 1.157.3
 Authors: th0rgal and boy0000

### ProtocolLib Version

ProtocolLib version 5.0.0
Provides read/write access to the Minecraft protocol.
Authors: dmulloy2 and comphenix

### Server Software & Version

This server is running Pufferfish version git-Pufferfish-73 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: cadfa71 on HEAD)
You are on the latest version!
Previous version: git-Paper-550 (MC: 1.19.4)

( even with normal paper )

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
I cannot replicate this
Items gotten from /o inv, /o give and when mined all return the same item

**Comment by blockwarss** [comment]
https://github.com/oraxen/oraxen/assets/36086134/0e7b2dad-c2cc-4036-8cdd-2bae6c562eb9

Not for me
