### ISSUE TITLE
[BUG] Can't put Signed books in the Chiseled Bookshelf due to Oraxen Book Formatting

### ISSUE THREAD

**Issue by Steven-OS** [oraxen/oraxen#935]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Right-clicking a Chiseled Bookshelf does not work if Oraxen is installed. 
A/B testing has been done and the issue only shows up when Oraxen is active.

### Steps to reproduce

1. Install Oraxen and ProtocolLib
2. Install latest version of Paperspigot 1.20.1
3. Get a Chiseled Bookshelf
4. Place the bookshelf
5. Get a book & quill
6. Sign it
7. Right-click the Chiseled Bookshelf
8. Result: The player opens the book instead of placing it inside the bookshelf

### Plugin Version

1.157.3

### ProtocolLib Version

5.0.0

### Server Software & Version

1.20.1 build #60

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
i dont think the renamed title describes ur issue better at all, but yeah can see this being the case

**Comment by Boy0000** [comment]
disable book formatting for now and it should work fine
