### ISSUE TITLE
[BUG] Server Crash

### ISSUE THREAD

**Issue by Real6dq** [oraxen/oraxen#938]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

This bug causes the server to crash as there's a method that is being run on the main thread.

The class that causes this: BlockHelpers.java
The fix: Replace the playCustomBlockSound functions with these ones: 
```
public static void playCustomBlockSound(Location location, String sound, float volume, float pitch) {
        Bukkit.getScheduler().runTask(OraxenPlugin.get(), () -> {
            playCustomBlockSound(toCenterLocation(location), sound, SoundCategory.BLOCKS, volume, pitch);
        });
    }

public static void playCustomBlockSound(Location location, String sound, SoundCategory category, float volume, float pitch) {
        if (sound == null || location == null || location.getWorld() == null || category == null) return;
        Bukkit.getScheduler().runTask(OraxenPlugin.get(), () -> {
            location.getWorld().playSound(location, sound, category, volume, pitch);
        });
    }
```

Crash report: https://pastebin.com/raw/jjQTsVmR (Thanks to clx_ aka Micheal from Paper)

### Steps to reproduce

Zero idea how, some blocks must make a sound on an async thread, the server will go boom.

### Plugin Version

[03:04:40 INFO]: Oraxen version 1.157.2 (works on latest as well, the code wasn't modified there)
[03:04:40 INFO]: Authors: th0rgal and boy0000

### ProtocolLib Version

[03:05:09 INFO]: ProtocolLib version 5.0.0

### Server Software & Version

Paper 1.20.1, Paper 1.19.4, and Paper 1.19.3

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
by the looks of it this happens when ur breaking a block
Still that should all be called on the main thread
Whilst the above might work i would rather see first if i cant replicate this.

Seeing as this has been fine for 99% of users for like 6 months I would rather pinpoint the issue 👍

**Comment by Boy0000** [comment]
the temporary fix it to just disable custom block sounds in mechanics.yml, which should fix all the issues ur having
and well I cannot fix something noone reports so it isnt weird it hasnt been fixed yet
If you insist on having custom block sounds, something IA doesnt have, you can always fork oraxen and change the code for that portion
idk what u mean with the bstats link, just shows oraxen is used by x servers? yes oraxen has 2000+ players daily yet not a single person has had this issue, hence i wanna look more into it

either way if u have 200 players or 2, the issue would be from the same source so idk why that matters to much

**Comment by Boy0000** [comment]
Might be the case, but my original comment still stands.
1. this issue im currently unable to reproduce and seemingly only 3/3000 people have it
2. you can easily fix this simply by disabling 2 settings for now
3. your fix might work but that still doesnt explain the problem, thus i wanna look into it

if this was an issue more than 0.1% of users had ofc i would rush out a tempfix, but there is one already and 0.1% have it, so I choose to look into it more properly. But again ur free to fork Oraxen and do this if u dont want to disable those settings for now 👍

**Comment by Boy0000** [comment]
you can leave this open until the problem is reproducable and fixed
