### ISSUE TITLE
[BUG] Oraxen doesn't let other plugins disable craftings.

### ISSUE THREAD

**Issue by ErdemGKSL** [oraxen/oraxen#939]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

[ValhallaMMO](https://www.spigotmc.org/resources/valhallammo-the-most-engaging-free-rpg-skills-plugin-available.94921/) plugin disables vanilla craftings for example to craft iron pickaxe, you have to smelt the iron ingot to get melted iron ingot, so that normal iron ingot can not craft iron pickaxe, the plugin disables it, but when oraxen is in the server, those recipes are enabled again.

If we disable the recipes by external plugin forcefully like [RecipeManager](https://dev.bukkit.org/projects/recipemanager) oraxen dumps the error
`[15:15:47 ERROR]: Could not pass event PrepareItemCraftEvent to Oraxen v1.157.3`
`java.lang.IllegalArgumentException: Recipe must have non-AIR result.`

### Steps to reproduce

Download [ValhallaMMO](https://www.spigotmc.org/resources/valhallammo-the-most-engaging-free-rpg-skills-plugin-available.94921/) and deploy it to plugins folder, download oraxen.
Try crafting, iron pickaxe with iron ingots, which should be disabled, it will be crafted.
Delete Oraxen from plugins folder.
Stop, and start the server.
Then try crafting again, now you can't craft the item. ValhallaMMO works perfectly fine. Now you have to smelt the iron ingots in the furnace to craft iron pickaxe.

### Plugin Version

[15:30:01 INFO]: Oraxen version 1.157.3
[15:30:01 INFO]: Authors: th0rgal and boy0000

### ProtocolLib Version

[15:30:33 INFO]: ProtocolLib version 5.0.0
[15:30:33 INFO]: Provides read/write access to the Minecraft protocol.
[15:30:33 INFO]: Authors: dmulloy2 and comphenix

### Server Software & Version

[15:30:47 INFO]: This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)
You are running the latest version

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by ErdemGKSL** [comment]
According to the developer of the valhallammo, the plugin just deletes the recipe, not replacing with result of air.
So oraxen somehow ignores deleted vanilla recipes.

**Comment by Boy0000** [comment]
I am unable to reproduce this issue. Can you confirm that this happens on 1.158.0 @ErdemGKSL 
The settings.yml setting merely resets Oraxen recipes and shouldnt touch non oraxen recipes

![image](https://github.com/oraxen/oraxen/assets/62521371/d71b3069-5b8b-4be5-b3a8-0c3a76f73237)
