### ISSUE TITLE
Fake CIT optifine

### ISSUE THREAD

**Issue by magicelk235** [oraxen/oraxen#948]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

This feature will add the ability to create custom textures for items(oraxen items too) by they nbt and stack amount
This feature will add the cit mechanic to items like this:
mechanics:
 cit:
  material: STICK/oraxen_item
  stack: 1-64 #isn't needed if nbt is on
  nbt: {enchantment:"something"} #isn't needed if stack is on
  

### Reason

Of think it will be great idea and really useful for people who want to use optifine CIT without making the players downloading optifine

**Comment by Boy0000** [comment]
i dont want to support weird optifine stuff where it isnt needed

**Comment by magicelk235** [comment]
It's fake optifine, so players don't need to download optifine
