### ISSUE TITLE
[BUG] Placing a custom block using noteblock mechanic on top of grass path/tilled dirt

### ISSUE THREAD

**Issue by Bruhhhh10** [oraxen/oraxen#949]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Placing custom block on top of grass path or tilled dirt doesn't turn it into regular dirt
![image](https://github.com/oraxen/oraxen/assets/134551265/7906c632-32a6-439c-82ca-87266cd705cc)

Even if you place a regular noteblock in minecraft on top of tilled dirt or grass path it will not turn into regular dirt
I think the way to go about this is to change that and make sure any custom block that uses noteblock mechanic if you place on top of tilled dirt/grass path it will turn into regular dirt

and if for some reason if people dont want their custom block to do that, add a config option in the custom noteblock mechanic called something like
untill-grasspaths-tilleddirt: false so it will not untill

### Steps to reproduce

Place a custom block that uses noteblock mechanic on top of grass path or tilled dirt, it will not turn into regular dirt as I would like it to

### Plugin Version

Oraxen version 1.157.4

### ProtocolLib Version

ProtocolLib version 5.1.0-SNAPSHOT-660

### Server Software & Version

Paper version git-Paper-65 (MC: 1.20.1)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
Think this issue is similar to alot of the ones in #952 with beds
Oraxen has to fuck a lot with the BlockPhysicsEvent to prevent certain behaviour
I'll eventually look into fixing them all but yeah

**Comment by Bruhhhh10** [comment]
> Think this issue is similar to alot of the ones in #952 with beds Oraxen has to fuck a lot with the BlockPhysicsEvent to prevent certain behaviour I'll eventually look into fixing them all but yeah

There's also some bugs I've found with string block mechanics, if you have 2 different type of oraxen string blocks and place 1 normal string block right next to it, it wont let you but if you use an autoclicker really fast it will place it anyways and it turns the stringblock right next to it to a different string block or just normal string, it's weird and I've also found some duplication glitches with stringblock mechanics and more ways to turn custom blocks into normal noteblocks
