### ISSUE TITLE
[SUGGESTION] add bedrock models entity support

### ISSUE THREAD

**Issue by tbvns25565** [oraxen/oraxen#950]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

I think adding support for Bedrock entity model would be huge. It would allow for bedrock entity like big player or all those kinds of things. It would bring bedrock custom model entity to java.

It is possible, some people have already done it for Minestom right here: [WSEE](https://github.com/AtlasEngineCa/WorldSeedEntityEngine)

I do know that this would be a huge amount of work, and that is why I won't be disappointed if this request is refused.

(I am not native, so sorry if there are some mistakes)

### Reason

I don't think any plugin do that, ModelEngine do similar thing, but they have their own format (I think). It would also be easier for artiste to port their work from bedrock to java.

**Comment by Boy0000** [comment]
oraxen will not support bedrock or geyser
