### ISSUE TITLE
[BUG] List of duplication glitches, flying flowers and other weird bugs.

### ISSUE THREAD

**Issue by Bruhhhh10** [oraxen/oraxen#952]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Do not skimread and watch the videos carefully

The videos below show the following:
Hanging sign dupes when placed on specific directions
Normal sign dupes when placed on specific directions
Bed dupes
Torchflower dupes
Skulk vein dupes
Head dupes (Player head, Dragon head, etc..)
Dragon egg dupes
Flying sunflower, large fern, rose bush etc
Flying flowers like (poppy, wither rose, dandelion etc...)
Particle bug
Weird tripwire hooks when placed on top of custom block
Seagrass spawning water source block, and when placed a block on top of it to try getting rid of it, it does not start getting rid of the water
Blocks turning into noteblocks glitch

These 3 videos showcase all the bugs mentioned above:
https://www.youtube.com/watch?v=LRGc_KDtOpg
https://www.youtube.com/watch?v=5EcFqR5EzF8
https://www.youtube.com/watch?v=g2EUD3panu0

Yes, this does mean that you can mess with:
crimson roots (flying)
doors (half doors & flying)
pressure plates (flying)
rails (flying)
pointed dripstone (flying)
lantern (flying)
Redstone comparator (flying)
Candles (flying)

### Steps to reproduce

**Hanging sign & normal sign dupes happen when:**
you place a hanging sign on the sides of a custom block or the top of the custom block in a specific direction, will not get consumed but place and you can break to get the sign and repeat to get unlimited hanging signs

you place a normal sign on top of the custom block in a specific direction, will not get consumed but place and you can break to get the sign and repeat to get unlimited signs

**Bed dupes happen when:**

place 1 custom block on the ground, stand on it and look bottom, place the bed, it will not consume the bed but place a half layer bed next to it, you can break that half layer bed and GET another bed and repeat to get unlimited beds

**Torchflower dupes when:**
You place it on a side of a custom block, it doesn't consume but places it and you can break it to get another one and repeat and get stacks of them

**Flying sunflower, large fern, rose bush etc:**
Place a 2 block tall flower like mentioned above on a custom block, break it from the bottom layer and the flower from the top will fly, if you stand on the block while doing it, it wont consume the flower, it will just place a half flower but if you break it you get nothing though

**Flying flowers like poppy wither rose etc:**
Place flower on sides of a custom block and it will fly in the air even if you try to update the flower

**Weird particle bugs:**
when placing stuff like Large fern, sunflowers on the side of the custom block and standing on the block you're placing it
Weird tripwire hook placing:

doesn't require you to place tripwire hook on a wall if you just place it on top of a custom block it just places it as if you're placing it on a wall

**Weird seagrass bug:**
If you place a seagrass on a custom block, it will spawn water and seagrass inside the water, when you try to remove the water by placing a block on the water source block, it doesn't start getting rid of the water even after you break the block, and to update the water I tried placing a noteblock instead of any regular block and when right clicking the noteblock when placed on the water source block and playing a tune, it updates the water and starts getting rid of it, pretty weird

Considered a glitch because when placing a seagrass it should not place a water source block, with this you can also place seagrass on a side of a custom block, and make seagrass place on blocks like magma blocks, slabs, air and other blocks that you cant place seagrass on top of in the vanilla game

*Skulk vein dupe:*
Place a skulk vein on the sides of a custom block or bottom side of the custom block, it will place two

*Custom blocks turning into noteblocks:*
Place your custom block on ground, remove the block below it, place shulker on top of the block, open shulker and tadaa!

*Head dupes:*
Placing head on a bottom of a custom block in a specific direction dupes it, similar case with the signs dupe

*Dragon egg dupes:*
Place a dragon egg on the bottom side of a custom block, make sure at least 2 blocks is removed below it, right click and tadaa it places it but doesn't consume it from your inventory, you can do this on the sides of the custom block aswell just make sure theres air below the custom block

Yes, this does mean you can also dupe sand, gravel, concrete powder, anvils, red sand etc.. just by placing a 3 block pillar of any custom block, and placing sand for example at the sides of said custom block.

### Plugin Version

Oraxen version 1.157.5

### ProtocolLib Version

ProtocolLib version 5.1.0-SNAPSHOT-660

### Server Software & Version

git-Paper-69 (MC: 1.20.1)

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by noiverre** [comment]
Maybe related to #937

**Comment by Bruhhhh10** [comment]
> Maybe related to #937

The bugs I've listed are not related to that at all :)

**Comment by Boy0000** [comment]
Beds and Double Plants have the same issue where cancelling the BlockPhysicsEvent will prevent it from breaking normally

Cannot replicate the issue with ferns, wither roses etc

Sculk vein, tripwirehook and some others are fixed in the linked issue

shulkers I can replicate and should be fixed soon

**Comment by Boy0000** [comment]
the issues with bed and shulkers can be fixed by enabling this setting in Paper for new 1.20.1 builds
Might have some visual quirks still but fixes the core issue
![image](https://github.com/oraxen/oraxen/assets/62521371/4520da30-1a0e-4041-95ad-a66e62a10547)

Eventually Oraxen will properly handle this setting and recommend it to be enabled
