### ISSUE TITLE
[SUGGESTION] Option to block oraxen item in vanilla crafting recipes

### ISSUE THREAD

**Issue by lucian929** [oraxen/oraxen#955]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

When adding custom recipes with plugins like CustomCrafting, there are some issues that can prevent vanilla recipes from working properly.

This can be fixed by adding an option to block oraxen items in vanilla crafting recipes.

### Reason

Fix conflict/incompatibility with CustomCrafting

**Comment by Boy0000** [comment]
Seems to already be the case

![image](https://github.com/oraxen/oraxen/assets/62521371/9ac0fc08-9b53-40c3-83a9-c39176c89c38)
