### ISSUE TITLE
[BUG] TNT cause noteblock mechanics to update

### ISSUE THREAD

**Issue by noiverre** [oraxen/oraxen#956]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Note blocks are updating when TNT blown over it

### Steps to reproduce

paper-global.yml:
```
block-updates:
  disable-noteblock-updates: true
  disable-tripwire-updates: false
```

https://github.com/oraxen/oraxen/assets/77881970/036d4722-a072-4c52-a8c8-9c6cf0490208

### Plugin Version

![image](https://github.com/oraxen/oraxen/assets/77881970/dda0ed4c-fb0c-4a00-974b-418097d3ff16)

### ProtocolLib Version

![image](https://github.com/oraxen/oraxen/assets/77881970/27b77efe-1370-4d57-8996-1011947bfa4c)

### Server Software & Version

![image](https://github.com/oraxen/oraxen/assets/77881970/cab70082-8a1e-45cd-9c0c-c6812c0e8e85)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
similar to tripwires this is just an issue of the client "predicting" a blockstate change
Paper only ensures that server side this doesn't happen but atm doesnt resend that info to the client
Might open a PR to fix that I suppose
