### ISSUE TITLE
[SUGGESTION] noteblock sounds

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#960]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

when using oraxen, noteblocks are used for custom blocks
BUT, all the note blocks still works
so why not adding a new mechanic that lets you use custom blocks like a noteblock instrument sound??

for example, planks play the sound "block.note_block.bass"
falling blocks plays "block.note_block.snare"

so i can use custom wood blocks to play "block.note_block.bass"
or maybe a custom block like "chiseled_soul_grimstone_block" to play the sound "block.note_block.custom""

### Reason

custom noteblock instruments would be awesome

**Comment by Boy0000** [comment]
not gonna happen
Cusotm blocks via noteblock mechanic are designed to entirely disable all noteblock functionality
Will not be changing this
You can code an addon that does this for you
