### ISSUE TITLE
[SUGGESTION] Directional mechanic for string blocks

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#965]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

we could have UP-BOTTOM directional mechanic, so we could create things you can place in the ceiling or in the floor

and also MULTI directional mechanic, which would act like the amethyst clusters, you would be able to place it in the floor, ceiling and sides  (acts the same as dropper directional mechanic)

### Reason

in my opinion, the up-bottom is a needed one for custom string blocks that are not flowers, for example, icicles, crystals and even fake lantern/sign blocks, like hanging and non hanging

**Comment by Boy0000** [comment]
Already declined this afaik just due to the annoyance it causes.
Cant place on wall cuz hitbox will be scuffed
