### ISSUE TITLE
[SUGGESTION] Fake string-nlock

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#966]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

fake string block would be just like furniture blocks using barriers, but instead of using barriers, it would be strings

"and why not using stringblock mechanic?"
you cant make dyable string blocks
"but you can make furnitures with no barriers"

thats the thing, what if i want a stringblock+ display entity / itemframe hitbox or only the stringblock hitbox to break it?
it would be a invisible string model with a specific blockstate that spawns together of a itemframe/display entity

### Reason

with this we could have ilimited stringblocks and also would be better and easier to manage double-sized stringblocks like custom tall plant and stuff like this, cuz the main block hitbox would be the string, and you could add a hitbox for the entity display
so instead of using 2 string blocks for one custom tallplant, you would use only ONE + the entity display hitbox

**Comment by Boy0000** [comment]
Insee no point in this...
Interaction entities exist for non-solid hitboxes and are customizable. Stringblocks arent happening
