### ISSUE TITLE
[SUGGESTION] allowed_placing mechanics

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#968]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

allowed_placing would be the opposite of limited_placing, but it is not the same as TYPE:ALLOW
instead of this, you could choose vanilla blocks that you would be able to place in it

for example, lets say i created a custom grass block and i want minecraft flowers/grass/dripleaves or even crops to be placed in this block

### Reason

you can make dripleaves to be placeable in other blocks with datapacks, but only if you add "note_block" to its tag, the only thing is that... every single custom block would be affected by this

so if oraxen added this as a feature you would be able to specify in which custom blocks you would be able to place things like

grass (grass, tallgrass, fern, large fern)
flowers (all vanilla flowers)
deadbush
plants (bamboo, saplings, azalea and flowering azalea)

**Comment by Boy0000** [comment]
i have no clue what this means... what do you mean with "placed in this block"?
