### ISSUE TITLE
[BUG] Glyphs are not replaced in main menu (ESC)

### ISSUE THREAD

**Issue by rglautaro** [oraxen/oraxen#970]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

The glyph replacements in the game main menu (ESC) is not working

![image](https://github.com/oraxen/oraxen/assets/14943102/dd7fa430-b738-44a8-8917-1f4ffc310fe3)

### Steps to reproduce

- Create a lang file matching whatever language you have for the game
- Override any of the menu messages including any glyph
- /o reload all
- Press ESC, see the empty button

Example lang file
```
{
    "menu.disconnect": "<glyph:menu_banner>"
}
```

### Plugin Version

1.158.0

### ProtocolLib Version

5.0.0

### Server Software & Version

Failing in both
- Paper version git-Paper-112 (MC: 1.19.2)
- Paper version git-Paper-18 (MC: 1.20.1)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
you need a negative shift before to offset it back
the glyph is there just off screen basically

**Comment by rglautaro** [comment]
i do have the shifts, this example was simplified. my exact configuration for the message is this:
`"menu.disconnect": "<shift:32>§f⭅  §f¡Esperamos verte pronto!                §f<shift:-256><glyph:menu_banner>",`
