### ISSUE TITLE
[BUG] 1.20.1 Furniture bug

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#974]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When in 1.20, Furnitures models (using entity display FIXED) are being placed upside down
while in 1.19.4 it doesnt happens

https://github.com/oraxen/oraxen/assets/47507632/934d5920-1e38-437f-bc98-3e8a2bbe0b89

### Steps to reproduce

create a furniture set in 1.19.4
place it down, boom, perfect

update the server to 1.20.1
the furniture youve placed will still be the same, perfect as it should be
but every time you place a new one... it will be placed upside down

### Plugin Version

1.158.2

### ProtocolLib Version

5.0.0

### Server Software & Version

Purpur 1.20.1 Build 2017

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
it is all based on your client
if your server is 1.20 itll use 1.20 changes
and if ur server is 1.19.4 itll do 1.19.4 rotation

if ur client isnt the same this will happen. Not a bug, blame mojang
