### ISSUE TITLE
[SUGGESTION] documentation for CustomOreGenerator

### ISSUE THREAD

**Issue by FrozzenRod** [oraxen/oraxen#977]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

I'd like more information about support for the CustomOreGenerator plugin on the https://docs.oraxen.com/ page.

I can't find anything about adding oraxen ores for this plugin in the documentation.

### Reason

this would help people who want to use CustomOreGenerator to generate their ores.

**Comment by Boy0000** [comment]
ask the devs of CustomOreGenerator to improve their documentation
I do not know myself how they work. There is an open issue for it [here](https://github.com/DerFrZocker/Custom-Ore-Generator/issues/18)
