### ISSUE TITLE
[BUG] Weird Redstone behavior when dusts under/over custom Noteblocks are trying to be updated

### ISSUE THREAD

**Issue by noiverre** [oraxen/oraxen#978]
### I have checked...

- [ ] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

![image](https://github.com/oraxen/oraxen/assets/77881970/5927cbce-03cf-48bf-9093-26aa81780406)

### Steps to reproduce

Use ALTERNATE-CURRENT as redstone implementation in paper config, and disabling noteblock updates in paper config, enable noteblock mechanics in oraxen

Build the following redstone contraption
Try to remove the repeater in red box, the redstone dust state doesn't update

Also the redstone dust on top of the blue block in the middle of the screenshot won't update no matter what

### Plugin Version

Oraxen version 1.158.0
Authors: th0rgal and boy0000

### ProtocolLib Version

ProtocolLib v5.1.0-SNAPSHOT-654
Authors: dmulloy2 and Comphenix
Issues: https://github.com/dmulloy2/ProtocolLib/issues

### Server Software & Version

Checking version, please wait...
This server is running Pufferfish version git-Pufferfish-17 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: f6a081a on HEAD)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
why is this an oraxen bug and not a paper bug?
Did you try and replicate this on a normal Paper server, not a fork, and without Oraxen?
Was the behaviour the same or different?
