### ISSUE TITLE
[BUG] Some chars doesnt works for bitmap glyphs

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#981]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description
this is the "default.json" in the pack.zip (generated by the plugin itself) 
![image](https://github.com/oraxen/oraxen/assets/47507632/ad78780b-6bff-421e-8ac7-7172920cf1e1)
some of it are even replacing question mark
![image](https://github.com/oraxen/oraxen/assets/47507632/b7efb1db-c119-4a75-bbb7-d02dece872b5)

### Steps to reproduce

![image](https://github.com/oraxen/oraxen/assets/47507632/b327e6b9-4a24-4ea9-b9e5-b8c87188d5d6)
![image](https://github.com/oraxen/oraxen/assets/47507632/fa1d8f2e-ddd4-4f18-9331-1316d60e69e5)
![image](https://github.com/oraxen/oraxen/assets/47507632/8066fb95-2fff-4a0c-aa7c-b87c217fbb93)

### Plugin Version

1.158.2

### ProtocolLib Version

5.0.0

### Server Software & Version

purpur 1.20.1 b2018

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
helpful if u post the config as actual yml code blocks and not a scrteenshot so i can copy it

**Comment by Boy0000** [comment]
thats just an issue with the unicode u selected
just use another one idk or just let oraxen assign one
