### ISSUE TITLE
[BUG] Badly formatted duplicate file error

### ISSUE THREAD

**Issue by WizkhalifaX** [oraxen/oraxen#982]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

The plugin disabled after doing `/oraxen reload all` [was merging packs and this happen]

```
24.07 06:15:27 [Server] ERROR Error occurred while enabling Oraxen v1.158.2 (Is it up to date?)
24.07 06:15:27 [Server] INFO java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsJsonObject()" because the return value of "com.google.gson.JsonObject.get(String)" is null
24.07 06:15:27 [Server] INFO at io.th0rgal.oraxen.pack.generation.DuplicationHandler.handleBowPulling(DuplicationHandler.java:368) ~[oraxen-1.158.2.jar:?]
24.07 06:15:27 [Server] INFO at io.th0rgal.oraxen.pack.generation.DuplicationHandler.migrateItemJson(DuplicationHandler.java:328) ~[oraxen-1.158.2.jar:?]
24.07 06:15:27 [Server] INFO at io.th0rgal.oraxen.pack.generation.DuplicationHandler.attemptToMigrateDuplicate(DuplicationHandler.java:250) ~[oraxen-1.158.2.jar:?]
24.07 06:15:27 [Server] INFO at io.th0rgal.oraxen.pack.generation.DuplicationHandler.checkForDuplicate(DuplicationHandler.java:228) ~[oraxen-1.158.2.jar:?]
24.07 06:15:27 [Server] INFO at io.th0rgal.oraxen.utils.ZipUtils.addToZip(ZipUtils.java:43) ~[oraxen-1.158.2.jar:?]
24.07 06:15:27 [Server] INFO at io.th0rgal.oraxen.utils.ZipUtils.writeZipFile(ZipUtils.java:32) ~[oraxen-1.158.2.jar:?]
24.07 06:15:27 [Server] INFO at io.th0rgal.oraxen.pack.generation.ResourcePack.generate(ResourcePack.java:185) ~[oraxen-1.158.2.jar:?]
24.07 06:15:27 [Server] INFO at io.th0rgal.oraxen.OraxenPlugin.onEnable(OraxenPlugin.java:124) ~[oraxen-1.158.2.jar:?]
24.07 06:15:27 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20-R0.1-SNAPSHOT.jar:?]
24.07 06:15:27 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.jar:git-Purpur-1990]
24.07 06:15:27 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.jar:git-Purpur-1990]
24.07 06:15:27 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20-R0.1-SNAPSHOT.jar:?]
24.07 06:15:27 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:577) ~[purpur-1.20.jar:git-Purpur-1990]
24.07 06:15:27 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:488) ~[purpur-1.20.jar:git-Purpur-1990]
24.07 06:15:27 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.20.jar:git-Purpur-1990]
24.07 06:15:27 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[purpur-1.20.jar:git-Purpur-1990]
24.07 06:15:27 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:342) ~[purpur-1.20.jar:git-Purpur-1990]
24.07 06:15:27 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.20.jar:git-Purpur-1990]
24.07 06:15:27 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.jar:git-Purpur-1990]
24.07 06:15:27 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
24.07 06:15:27 [Server] INFO [Oraxen] Disabling Oraxen v1.158.2
24.07 06:15:27 [Server] INFO Oraxen | Successfully unloaded
```

### Steps to reproduce

I was retrying to re-merge again since I have this long issue that I make my oraxen broken again, so basically, what I did was delete my "Packs" folder and even my "ModelEngine" folder after deleting, what I did was this steps;

**First Step:** I open all my ZIP FILES (containing my custom mobs that I have bought in McModels).
**Second Step:** then I get all the "McModels" folder on each zip
**Third Step:** After that, I was manually drag n dropping it to my FTP "ModelEngine" folder in plugins
```
But every zip folder that I have successfully uploaded, I keep doing in console "/meg reload" so every zip upload = meg reload

Now after everything was uploaded, I started to upload some Oraxen zip, which is like the "LittleDucks Set" and more, then after that;
```
**Fourth Step:** I was drag n dropping it, then manually opening the "Items" folder since some of the items of my custom packs was the same name so I need to open it 1 by 1 then inputting the items in specific yml such as "hats.yml"
**Next Step:** After that, I just copied my "ModelEngine/resource packs/assets"
**Last Step:** Then pasted it on "Oraxen/pack/" after doing so, I restarted my server and that's what happen, the plugin has been disabled.

OTHER:
I also tried to do `/o rl all` and still the same.

### Plugin Version

latest

### ProtocolLib Version

ProtocolLib version 5.1.0-SNAPSHOT-660
Provides read/write access to the Minecraft protocol.
Authors: dmulloy2 and comphenix

### Server Software & Version

24.07 11:11:12 [Server] INFO ProtocolLib version 5.1.0-SNAPSHOT-660
24.07 11:11:12 [Server] INFO Provides read/write access to the Minecraft protocol.
24.07 11:11:12 [Server] INFO Authors: dmulloy2 and comphenix

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
you imported a pack with a badly formatted json model file
judging by the error it is a bad bow.json file

**Comment by WizkhalifaX** [comment]
> 

It should be "LittleDucks" set or "LittleShark" set?

**Comment by WizkhalifaX** [comment]
> you imported a pack with a badly formatted json model file judging by the error it is a bad bow.json file

It should be "LittleDucks" set or "LittleShark" set?

**Comment by Boy0000** [comment]
i have no clue and I dont own whatever that is to check.
ill add more fail safes iguess in a future update

**Comment by WizkhalifaX** [comment]
> i have no clue and I dont own whatever that is to check. ill add more fail safes iguess in a future update

Ahh okay so I should wait for the latest update to fix that issue?
