### ISSUE TITLE
[BUG] List of duplication glitches and other weird bugs v2 :)

### ISSUE THREAD

**Issue by Bruhhhh10** [oraxen/oraxen#983]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

This bug report consists of the following bugs:
Half piston glitch
Stringblock dupe glitch and other weird glitches regarding stringblocks
Custom blocks that use noteblock mechanic being able to turn into normal noteblocks
Lava & Water duplication glitch
Flying redstone & redstone being activated even though no redstone power nearby
Hand swing animation doesn't occur when placing a block on stuff like grass, fern, snow, and the hand swing animation doesn't occur when you also shift right click next to another custom block that uses noteblock mechanic

These two videos show off all the bugs listed above:
https://www.youtube.com/watch?v=umqBimWFSz4
https://www.youtube.com/watch?v=Oo7t6Zs0QTY

### Steps to reproduce

Half piston glitch:
Not sure how to explain this glitch, it's pretty weird so just go watch one of the videos.

Stringblock dupe glitch and other weird glitches regarding stringblocks:
If you try placing a vanilla minecraft string next to something that uses custom stringblock mechanic, it wont let you place the vanilla string right next to it, but if you click fast enough like for example using an autoclicker setting it to 0ms and something like 50 clicks per second on right click, it places it anyways and sometimes it bugs out and turns the custom string block mechanic next to it another custom string block you might have in oraxen, and you can also duplicate custom string blocks by just placing the custom string block into something thats updating, like for example if you get a redstone compactor and have it so it turns on and off really fast and place the stringblock right next to it, if you break it, it sometimes will not actually break when you break it but will drop the item therefore duplicating

Custom blocks that use noteblock mechanic being able to turn into normal noteblocks:
get 1 sticky piston and make sure you place it one block above the custom block and two blocks to the left/right, place block next to sticky piston, activate and then deactivate and it should turn into a noteblock

Lava & Water duplication glitch:
Just place lava/water on the ground, put your custom block and then right click on the side of it, even if the lava/water isn't a full source block next to the custom block that uses the noteblock mechanic, it will still put the lava/water in your bucket, therefore duplicating and you can repeat over and over

Flying redstone & redstone being activated even though no redstone power nearby:
Place a piece of redstone down, activate it with torch, put a vanilla minecraft noteblock or a custom block that uses noteblock mechanic on top of the redstone, remove whatever is powering the redstone (e.g redstone torch) and it will stay powered without anything powering the redstone, and you can break the block below it to make the redstone fly and place redstone around it, although the flying redstone will be removed if you break the noteblock/customblock on top of the redstone, oh and also if you try to place a piece of redstone on top of a custom block that uses noteblock mechanic, it wont let you but if you use an autoclicker it will place it anyways.

Hand swing animation doesn't occur when placing a block on stuff like grass, fern, snow, and the hand swing animation doesn't occur when you also shift right click next to another custom block that uses noteblock mechanic:
Just place a custom block on top of snow, fern, grass, large grass or sneak and place a custom block next to another custom block, it will not play the hand swing animation like it would usually do

### Plugin Version

Oraxen version 1.158.0
Authors: th0rgal and boy0000

### ProtocolLib Version

ProtocolLib version 5.1.0-SNAPSHOT-660
Provides read/write access to the Minecraft protocol
Authors: dmulloy2 and comphenix

### Server Software & Version

git-Paper-82 (1.20.1)

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
Several of these bugs are so impossible for me to fix due to how I need to handle BlockPhysicsEvent
Come 1.159.2 all of these should be fixed by toggling Papers disable-noteblock-updates

I dont think it is a better way than saying "these bugs will happen if you are on spigot or you refuse to enable the setting"
