### ISSUE TITLE
[SUGGESTION] Collidable Furnitures with entity display

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#987]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

adds an option furniture to make its hitbox to have collision with entities or players

### Reason

idk exactly why or how but it is possible to make entity display collidable somehow, ive seen some people do it and i think would be great for some type of furnitures

**Comment by Boy0000** [comment]
not possible ask mojang to add this
