### ISSUE TITLE
Stonecutter Recipes [BUG]

### ISSUE THREAD

**Issue by Chiefink5** [oraxen/oraxen#992]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

There is a major bug with the stonecutter recipe builder. the list is as follows:

1. Inserting an item into the "cut block" slot, or final result spot, makes the item invisible. The item is still there to be clicked and picked up again though.
2. Saving the recipe with `/o recipe save (name)` saves it to the correct place, just without the input value configured, even though the input item was inserted into the custom recipe.

### Steps to reproduce

1. Collect your items you wish to create a custom `Stonecutter Recipe` with.
2. Open the `/o recipe builder stonecutter` menu.
3. Insert your items into the corresponding slots.
4. *Notice that the far right slot is empty once an item is inserted into it.*
5. Save the recipe using `/o recipe save test`
6. Restart server
7. Open config section: `Oraxen/recipes/stonecutting` 
8. Notice that the recipe for `test` has no input value

### Plugin Version

[04:33:48 INFO]: Oraxen version 1.158.2
[04:33:48 INFO]: Authors: th0rgal and boy0000

### ProtocolLib Version

[04:34:32 INFO]: ProtocolLib version 5.1.0-SNAPSHOT-645
[04:34:32 INFO]: Provides read/write access to the Minecraft protocol.
[04:34:32 INFO]: Authors: dmulloy2 and comphenix

### Server Software & Version

[04:34:45 INFO]: Checking version, please wait...
[04:34:45 INFO]: This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)
You are running the latest version

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
the builder seems to be kinda broken, probably because it is using a normal stonecutting ui
Editing it in the yml file itself seems to work fine
