### ISSUE TITLE
glyphs "tabcomplete" is not work

### ISSUE THREAD

**Issue by bkgktp** [oraxen/oraxen#993]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

<img width="227" alt="image" src="https://github.com/oraxen/oraxen/assets/101702786/b2f39119-fc6c-4eea-859d-664ef3b7c880">

When I type an expression like :alarm in-game, it doesn't complete

<img width="222" alt="image" src="https://github.com/oraxen/oraxen/assets/101702786/2bcecbf4-0b1f-4b0c-8724-60fcb21a5e1c">

<img width="213" alt="image" src="https://github.com/oraxen/oraxen/assets/101702786/ad07254f-4fde-452d-830a-a1b8ae5f860b">

### Steps to reproduce

<img width="267" alt="image" src="https://github.com/oraxen/oraxen/assets/101702786/f2af0d69-ea22-493f-a3e0-51b7c26bc681">

I couldn't get the tab complete to work even though I've given the op or emoji.use permission to myself.

### Plugin Version

<img width="391" alt="image" src="https://github.com/oraxen/oraxen/assets/101702786/8acbf29a-4de7-4773-842a-47dd654dae39">

### ProtocolLib Version

<img width="700" alt="image" src="https://github.com/oraxen/oraxen/assets/101702786/84e2e59e-b154-45cc-a08a-965999da1c3b">

### Server Software & Version

<img width="465" alt="image" src="https://github.com/oraxen/oraxen/assets/101702786/99a51feb-8201-42c8-b5d3-fb756ace3148">

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
by defaulty it tabcompletes the unicode not placeholder
u can change it in settings.yml

**Comment by bkgktp** [comment]
I'm sorry I didn't notice this, I must have skipped this detail on the wiki. It would be nice if "unicode_completions" was set to false by default.
