### ISSUE TITLE
[SUGGESTION] Misc Noteblock Mechanics

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#997]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

new misc mechanics like
cactus-placeable
deadbush-placeable
flower-placeable
grass-placeable
sapling-placeable
berry-bush-placeable

and others

### Reason

basically, i wanted to make a fake sand block where you would be able to place cactus, deadbush in it.
and also a custom grass block which you can place plants and flowers

**Comment by Boy0000** [comment]
this can be done in an addon relatively easily and prevents clutter in oraxen
