### ISSUE TITLE
Furniture's barriers sometimes don't break

### ISSUE THREAD

**Issue by bkgktp** [oraxen/oraxen#999]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

The barrier on the right does not disappear from the double-barrier furniture [placed.[](url)](url)

### Steps to reproduce

> magic_store_oakfench:
>   displayname: OakPlank Fence
>   material: PAPER
>   Pack:
>     generate_model: false
>     model: furnitures/summer_001/oakfench
>     custom_model_data: 1092
>   Mechanics:
>     furniture:
>       facing: UP
>       barriers:
>       - x: 0
>         y: 0
>         z: 0
>       - x: 1
>         y: 0
>         z: 0
>       drop:
>         silktouch: false
>         loots:
>         - oraxen_item: magic_store_oakfench
>           probability: 1.0
>       limited_placing:
>         floor: true
>         roof: false
>         wall: false
>       block_sounds:
>         place_sound: block.wood.place
>         break_sound: block.wood.break
>         hit_sound: block.wood.hit
>         step:
>           sound: block.wood.step
>           volume: 0.25
>         fall:
>           sound: block.wood.fall
>           volume: 0.25

If I break the furniture on the left, the barrier on the right does not disappear.

https://github.com/oraxen/oraxen/assets/101702786/6e674d91-8543-40b5-bea3-23b57683f84b

If you break the furniture from the right, the barrier on the left disappears and works smoothly.

### Plugin Version

<img width="400" alt="resim" src="https://github.com/oraxen/oraxen/assets/101702786/df29bfd5-4264-47d8-954c-fb7beb63b740">

### ProtocolLib Version

<img width="672" alt="resim" src="https://github.com/oraxen/oraxen/assets/101702786/8614ee3b-b276-4778-88be-c4f8b5a526c4">

### Server Software & Version

<img width="467" alt="resim" src="https://github.com/oraxen/oraxen/assets/101702786/8757fd35-8270-40fe-81e2-be96f39911a6">

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by bkgktp** [comment]
and we can't click where the barrier isn't broken and place a block, I guess the entity there isn't deleted. You can see it in the video.

**Comment by Boy0000** [comment]
replicate this on a paper server, same configs, only oraxen and protocollib
I am entirely unable to replicate this on such a server
